### ISSUE TITLE
REFACTOR - Make use of the .yml file for pattern data

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#1]
At the moment most, if not all, patterns have 'hard coded' content/data into the patterns `.hbs` file. 

To make it easier for developers using the visual framework it would be better to move any of this content/data to the .yml file that each component has. 

- [x] remove all 'hard coded' content/data from patterns and put it into data
- [x] make use of `{{> '@component'}}` rather than `{{render '@component'}}` 
- [ ] add documentation about how to add content/data for a pattern within a pattern

questions: 

do we want to start making use of any handlebars sugar for `{{each}}` for anything like lists?

**Comment by sturobson** [comment]
I have added the fractal handlebars helpers dependency.

Along with this I have added a simple `{{#each}}` handlebars helper to loop through `key: value` pairs

**Comment by khawkins98** [comment]
Where do we stand on this one? I think we've started putting some data into the `.yml`s, I guess this one is more of a chore/cleanup now? Or do we still have architecture work to do?

**Comment by sturobson** [comment]
Yes, I had a branch for this (I might have committed it, if not it's lost in the MacBook move). 

This could be one for me to pick up when it's trains, planes, and automobiles when I travel back to the UK on Friday

**Comment by sturobson** [comment]
I'm closing this one as it's moved to #316 for the Beta release

**Comment by khawkins98** [comment]
315 issues later 😭 🙃
