### ISSUE TITLE
Sass includePaths ignored after switch to Dart Sass

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#1019]
In #990 we moved to Dart Sass, but it's not using the `includePaths`.

(note: this isn't a big deal for vf-core, but will be a big issue for things like vf-eleventy)

Docs suggest [includePaths should work with Dart](https://sass-lang.com/documentation/js-api#includepaths), so either gulp-sass isn't passing the option or something else has gone off. 

I have seen other issues about Dart Sass having issues with includePaths and gulp, investigation.

**Comment by sturobson** [comment]
Ah - I thought I had this fixed. When I looked at Dart-Sass last year(?) the `includePaths` issue had me stumped - but this time around I thought I had it fixed - hence the PR :-/

**Comment by sturobson** [comment]
Ah - so I must have fixed the issues with `vf-core` -- now to investigate what I did 😭

**Comment by sturobson** [comment]
The other thing here - is if we can get as much information in the Sass as possible - rather than relying on `includePaths` then `vf-core` would be more portable into other task managers that teams wanting to use it might prefer.

**Comment by khawkins98** [comment]
This isn't the error that I thought it was, rather that vf-rollup uses `@import 'vf-sass-config/index.scss';` and we've typically excluded index.scss from being imported. 

1. Not sure why this wasn't breaking before
2. Not sure if we need to ignore these

**Comment by sturobson** [comment]
The thing with Dart-Sass is we can move towards using `index.scss` as the file to include by making use of `@use` and `@forward` to avoid any duplication of styles created.

**Comment by khawkins98** [comment]
Yeah, so if we can not-ignore index.scss files it's a step in a good direction.

**Comment by khawkins98** [comment]
Under the current approach, only the Sass file name gets stored in the component index:

```json
availableComponents {
  'ebi-header-footer--embl-selector.scss': true,
  'ebi-header-footer--footer.scss': true,
  'ebi-header-footer--form.scss': true,
  'ebi-header-footer--header.scss': true,
  'ebi-header-footer--layout.scss': true,
  'ebi-header-footer--utility.scss': true,
  'ebi-header-footer.scss': true,
  'ebi-header-footer.variables.scss': true,
  'index.scss': true,
  'package.variables.scss': true,
```

This is _okish_, but it means index.scss is too generic, I think we can move to keys like `vf-sass-config/index.scss` as a non-breaking change and a general improvement.

**Comment by khawkins98** [comment]
Making progress on this. 

Bad news: there are some issues between gulp-sass and dart sass when it comes to working with include paths.

Good news: we don't really need gulp-sass and can use dart sass natively which should have some performance wins, drop the node-sass/LibSass dependency and allow us to get the cutting-edge dart sass features faster.

**Comment by sturobson** [comment]
ok, I'll stop working on this :D 

I think we should move away from includePaths as much as possible - as mentioned [above](https://github.com/visual-framework/vf-core/issues/1019#issuecomment-661701934)
