### ISSUE TITLE
Subtitle on pages is not displayed

### ISSUE THREAD

**Issue by filipe-dias** [visual-framework/vf-core#1031]
Same as title, no subtitle shown. Possibly because of the recent update to vf-intro?

yarn.lock:
`"@visual-framework/vf-intro@^1.0.2":
  version "1.1.1"
  resolved "https://registry.yarnpkg.com/@visual-framework/vf-intro/-/vf-intro-1.1.1.tgz#9b3cfe671a9afe2d7a540113129fe0326ce8a86a"
  integrity sha512-T4TSCREOiA6JmgDQkLqA01/MkI9wnFmoX5Daik4l4qLVUTENb4CrMZGn2rFDIIGB8TqdZXFcJKMUS2W0g2YHvQ==`

**Comment by sturobson** [comment]
Hey Filipe! 

Can you give the example `.yml` content you are trying to use to get this to work.

As mentioned there's no 'subtitle' but there is a `vf-lede`…

Do you know if `vf-lede` is installed in the repo you are using (it should be listed in the `package.json`)?

**Comment by sturobson** [comment]
fixed with #1034
