### ISSUE TITLE
Component: nearest EMBL site (embl-location-nearest)

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#1051]
There are use cases where we want to know which EMBL site a user is closest to (for example: intranet).

Rough overview of a/c:

1. [x] 1. Try to auto-detect lat/lon in browser using the Geolocation_API
    - https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API/Using_the_Geolocation_API
    - https://developers.google.com/web/fundamentals/native-hardware/user-location#dont_keep_the_user_waiting_set_a_timeout
2. [x] 2. Calculate the closest site
    - https://stackoverflow.com/a/21297385
3. [ ] 3. Store the location as a cookie and refresh every 30 minutes or so
4. [x] 4. Fallback+customisation to manually set a location
    - some kind of drop-down list
5. [x] 5. Set the location as a data-prop `embl-location-nearest="barcelona"`  
6. [x] 6. Use this in other components
    - exactly how is TBC, but it's a pre-request for any location-specific highlights (such as activating a tab with location-specific information)

For speed, we could skip steps 1 through 3 and start at 4.

**Comment by sturobson** [comment]
Is this effected by GDPR?

**Comment by khawkins98** [comment]
> Is this effected by GDPR?

We have a legitimate use for it and it's only temporarily stored on the user's browser. It probably falls more onto the "cookie side" of GDPR. In any other org I'd say we should update our GDPR statement to include it, but EMBL and GDPR, [ya know](https://www.embl.de/aboutus/administration/legal-services/data-protection/IP68-Data-Protection-EN-18052018.pdf).

**Comment by sturobson** [comment]
Thinking about my initial question - I'm assuming that the cookie won't be set until they've accepted the GDPR banner notice anyway?

**Comment by khawkins98** [comment]
This has been mostly addressed by #1069, but does not add a cookie as:

1. It's more code
2. Privacy questions
3. It's still an early conceptual component and we can grow as needed
