### ISSUE TITLE
CDN: Document stable releases to assets.emblstatic.net

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#1074]
While we recommend that users use their own local builds, we do also offer the CDN. We need to better explain its configuration in the docs.

## Dev vs prod

- `dev.assets.emblstatic.net` vs `assets.emblstatic.net` dev has lower TTL, iirc 5 mins vs 1 hour

## Available thing

https://`{dev}`.assets.emblstatic.net/vf/`{version}`/css/styles.css

- droping `{dev}` will serve production
- `{version}` can be `develop` or a tag, i.e. `v2.0.0-beta.2` `v2.0.0` `v2.1.0``v2.2.0`

Example: https://assets.emblstatic.net/vf/v2.2.0/css/styles.css

## Bonus

- [ ] Readout of all tagged versions available

**Comment by sturobson** [comment]
> While we recommend that users use their own local builds

This point should be laboured on the documentation page for static assets. 

Which means we could probably do with looking at the documentation on making your own `.css` file too. 

I think a video tutorial could be good for that‽

**Comment by khawkins98** [comment]
We now show the latest version on the homepage: https://visual-framework.github.io/vf-core/

![image](https://user-images.githubusercontent.com/928100/96414879-01803480-11ee-11eb-9bbe-79e497fae369.png)

And we list out various version on the `/updates` page. 

The homepage also does a bit better job restructuring on npm versus CDN. 

More could always be done, but being bold and closing.

@sturobson if you think we should pursue some of the (good) ideas you've mentioned as a priority could you make a ticket?
