### ISSUE TITLE
Further enhance boilerplates

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#1105]
In #1093 we added some new boilerplates, but of course, we need to do more. 

- [ ] Error pages (404, 403, 500) Example 404: https://wwwdev.embl.org/kdjafljdls
- [x] Further examples to the search page
    - https://visual-framework.github.io/vf-core/patterns/search-results/
    - [x] summary list results
    - [x] table results
    - [x] card results
    - [ ] mobile versions of the above

**Comment by khawkins98** [comment]
A conceptual example of search results for courses from @nikiforosk 

![course snippets - v2 - 08Sep20](https://user-images.githubusercontent.com/928100/92706023-78efb800-f354-11ea-8836-54bfe62db2d7.jpg)

**Comment by gabsie** [comment]
HI, I also am attaching some explorations from the Covid-19 portal, but wouldn't stand by any of them too much - they have been done quickly and trying to put out a fire.. I can probably spend more time thinking about this and also about some search result scenarios relevant to HCA.

![Nucleotide Sequences - search results in tables](https://user-images.githubusercontent.com/19713125/92739499-dc89dd80-f374-11ea-90a3-03cab4bb2dba.png)
![Related Resources - filtering and tagging](https://user-images.githubusercontent.com/19713125/92739509-e01d6480-f374-11ea-9841-289e56062d86.png)

**Comment by nikiforosk** [comment]
Below are links to more complete examples which show all six type of courses and the kinds of summaries that we have been considering for each search result:
- [First ~200 characters of the overview without the keyword highlighted
](https://invis.io/2NYEWTQEURS#/431380347_Course_Snippets_-_V2_-_First_200_Chars_-_11Sep20)
- [Fragments with keywords highlighted](https://invis.io/2NYEWTQEURS#/431380348_Course_Snippets_-_V2_-_Highlighted_Keywords_-_11Sep20)

It looks like we'll go with the first option because the context surrounding the keyword in the fragments doesn't always seem to be very informative.
 
@khawkins98 As I mentioned yesterday, I'd appreciate any suggestions on how we can make certain types of courses (e.g. virtual course) stand out using existing elements of the visual framework.

**Comment by khawkins98** [comment]
The closest existing example  is https://wwwdev.embl.org/events page which has many similar semantic fields

![image](https://user-images.githubusercontent.com/928100/93081067-f423d780-f68e-11ea-9325-0436125b1b17.png)

Obviously the exact structure of the result and visual emphasis will vary by content. 

But there are probably three "generic" types of result listing:

1. Summary list (most common?)
1. Table (less common and highly specific as it begins to become application like?) 
1. Cards (for very visual content with a stronger emotional connection, think: Airbnb)

And then a mobile remix for each of the above. 

My thought is to begin by making an example of the first type (summary list) as it's probably the most reusable, and perhaps later to make an example table and card based results for "spiritual" guidance.

**Comment by khawkins98** [comment]
And although not entirely visually up-to-date, there is some good thinking in the EBI Search result format — and it provides a wide range of result sample content to accommodate: https://www.ebi.ac.uk/ebisearch/search.ebi?db=allebi&query=keratin

![image](https://user-images.githubusercontent.com/928100/93081611-d014c600-f68f-11ea-804b-9e5bf747f6db.png)

**Comment by khawkins98** [comment]
In #1112 I've added some more content the Search example https://visual-framework.github.io/vf-core/patterns/search-results/

That work has prompted something thinking about making the `vf-summary` default pattern more flexible.

This will likely get picked back up after I'm back on the 28th.

**Comment by gabsie** [comment]
Hi, everyone

I am attaching here some faceting for dates on the left hand side... 
Can we please discuss it some time?
I think with big search results with data, we need some options like these.
Once again - does this need another ticket?
Gabs

![Display updates - v1](https://user-images.githubusercontent.com/19713125/99735103-e853f780-2abb-11eb-99ee-ee4ce29e1ef4.png)


![Display updates - v1, release date](https://user-images.githubusercontent.com/19713125/99735095-e4c07080-2abb-11eb-9880-3e6afe1e4543.png)

**Comment by khawkins98** [comment]
Thanks @gabsie  

- Layout: I've been doing some work at https://github.com/visual-framework/vf-core/issues/878#issuecomment-724748526 that would get closer to this
- Pagination: I've not seen that particular flavour before, but it looks nice. related work in #233
- FIlters/facets: Some work occurring in #1229

We have some priority work for EMBL.org in the next week, but would really like to spend some time on this the week of 30 Nov.

**Comment by khawkins98** [comment]
This has been accomplished and/or covered in other issues. Closing.
