### ISSUE TITLE
💄 making the `vf-card` a bit more like a card, visually.

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#1114]
There are currently quite a few places where the basic `vf-card` component is being used (with no theming and no design variant). 

These get absorbed into the page some what because there's (usually) no distinction from the page background colour and the background colour of the text on the card.

There are two options I think we can go with to make them look a little more 'card-like'.

One is to add a border around all four sides of the card.

![Screenshot 2020-09-14 at 11 35 39](https://user-images.githubusercontent.com/925197/93076217-ec5c3700-f67e-11ea-8cc5-a2a3ed388a10.png)

This works quite well on cards with no theming or design variant but will breakdown a little if added. It would also require additional CSS for when to add or not add the styling.

The other way, and my preferred way, would be to add a slight box-shadow to the cards. This gives them the 'feel' that they are placed 'on top' of the page. This would also work if the cards do have theming and design variants attached. And if the card does have a link (the generally do) it makes more sense when hovered that the shadow increases a little. 

![Screenshot 2020-09-14 at 11 34 48](https://user-images.githubusercontent.com/925197/93076430-3c3afe00-f67f-11ea-8b39-b754dcf02b5b.png)

Thoughts?

**Comment by gabsie** [comment]
Hi, Stu and everyone

I am with @sturobson on this one - prefer the highlighted variant. 
It would probably be good to also see this within the page - see how it sits .. in different contexts (whether it makes it very 'netty')

Gabs

**Comment by sturobson** [comment]
Thanks for the input @gabsie. I think the most prevalent page that would benefit is [embl.org news home page](https://www.embl.org/news/).

live, as it currently is:

![Screen Shot 2020-09-14 at 12 14 00](https://user-images.githubusercontent.com/925197/93079362-e87ee380-f683-11ea-9e7a-24198238288f.png)

with the updated box-shadow elevation:

![Screen Shot 2020-09-14 at 12 14 37](https://user-images.githubusercontent.com/925197/93079399-f896c300-f683-11ea-9d41-8dc862919e93.png)

**Comment by sturobson** [comment]
@filipe-dias asked (via Slack)

> would it work when there's a fullbleed grey background, which is common with cards?

![Screenshot 2020-09-17 at 10 11 13](https://user-images.githubusercontent.com/925197/93450756-3e46cc00-f8ce-11ea-90fd-5319533432f6.png)

**Comment by sturobson** [comment]
via Slack @filipe-dias then asked:

> did you try with the other one that has those design spirals or whatever they are? I think it's a darker gray

This threw up an issue with the lightness of the grey, where it can make the card 'glow': 

![Screenshot 2020-09-17 at 10 30 31](https://user-images.githubusercontent.com/925197/93452949-f2495680-f8d0-11ea-97e9-305da1ed3f27.png)

I switched out the initial `-grey--lightest` with `-grey--dark`, which blends into the bg (this is ok here - because the theming and image make it look like a 'card' already:

![Screenshot 2020-09-17 at 10 30 07](https://user-images.githubusercontent.com/925197/93453018-0b520780-f8d1-11ea-8961-f27b06239d12.png)

I've checked this on the news page (the original example) and I think it's ok:

![Screenshot 2020-09-17 at 10 29 45](https://user-images.githubusercontent.com/925197/93453119-2b81c680-f8d1-11ea-8a5c-beb367cc3f09.png)

**Comment by sturobson** [comment]
There's now a PR open to merge these changes in #1124

**Comment by sturobson** [comment]
As #1124 has been merged - we can close this.
