### ISSUE TITLE
Do we need all of the `max-width` rules in components that we know would/should be inside `vf-body`?

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#1115]

**Comment by khawkins98** [comment]
Hrm, I also don't the "extra" max-width provides much benefit.

**Comment by khawkins98** [comment]
Can be closed?

**Comment by sturobson** [comment]
Maybe for the backlog list?

Looks like we've got it in 28 files from a quick search. 

Some of those I think will have to stay (EBI header/footer and of course `vf-body) but the rest can probably go

**Comment by khawkins98** [comment]
I think we're in a better shape on this one. Can be closed?
