### ISSUE TITLE
GA event tracking: on SPA permit to avoid `ga('send', 'pageview')`

### ISSUE THREAD

**Issue by nbuso** [visual-framework/vf-core#1116]
Give the possibility not to have "ga('send', 'pageview')", it can cause false counting of page navigations in cases of SPA

**Comment by khawkins98** [comment]
Adding this link from slack for background: https://medium.com/techiediaries-com/integrating-google-analytics-with-angular-10-9-6157629d75dc

**Comment by khawkins98** [comment]
Would something like this work? `<body data-vf-google-analytics-autosend="false">`

---

Docs: https://visual-framework.github.io/vf-core//components/vf-analytics-google/

**Comment by khawkins98** [comment]
A new method has been added in #1157 to not automatically send a pageview.

```js
import { vfGaIndicateLoaded } from 'vf-analytics-google/vf-analytics-google';
let vfGaTrackOptions = {
  vfGaTrackPageLoad: false
};
vfGaIndicateLoaded(vfGaTrackOptions);
```

Closing this one, please reopen if you need any further help/support.

CC @sandykadam as this might be of use to you.
