### ISSUE TITLE
GA event tracking on complex components

### ISSUE THREAD

**Issue by nbuso** [visual-framework/vf-core#1117]
On complex components marking the component with 'data-vf-google-analytics-region' can be not ideal. If I have a component that is composed of several html elements the GA tracker will issue an event also if I click on part of the component that is not triggering any real event for the application.
Suppose you have a component that handle the pagination, it may take a large width of the page, also white spaces: placing 'data-vf-google-analytics-region' the tracker will generate events also if clicking on the white part of the component.
This problem is obviously more evident if you are using external components libraries; in such cases the internal html component that is triggering the event you are interested in is not accessible from your project sources.

Provide an API to trigger manually such event instead to solve these cases.

**Comment by khawkins98** [comment]
Would using the `analyticsTrackInteraction()` function meet your needs?

From vf-analytics-google.js at line 198: 

```js
 * Analytics tracking
 * ---
 * This code tracks the user's clicks in various parts of the site and logs them as GA events.<br/>
 *
 * Dev note:
 * add class verbose-analytics to your body for a readout to console on clicks.
 *
 * @param {element} actedOnItem
 * @param {string} customEventName Event action
 * @example
 * jQuery(".analytics-content-footer").on('mousedown', 'a, button', function(e) {
 *   analyticsTrackInteraction(e.target,'Content footer');
 * });
 */
function analyticsTrackInteraction(actedOnItem, customEventName) {
```

**Comment by khawkins98** [comment]
Cipying a slack comment in:

>  check what is the source of the event. If it's a <a, <input, ... you trigger the event otherwise no. If you add some defaults and the possibility of configuring it with a data-xxx attribute it may solve most situations (edited)

**Comment by khawkins98** [comment]
The above function has now been namespaced and available for use as `vfGaTrackInteraction()`

**Comment by khawkins98** [comment]
I think this has now been resolved by elevating and [documenting `vfGaTrackInteraction()`](https://visual-framework.github.io/vf-core//components/vf-analytics-google/).

Closing, please reopen if needed.
