### ISSUE TITLE
'on localhost' banner is a tad annoying in window previews. 

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#1119]
When visiting any page of `vf-core` when running locally both the 'page' you visit and the iframe 'page' of the component that is nested inside have a little fixed banner telling us we're on local. 

This gets a little annoying and makes developing certain components in the details view unworkable.

![Screenshot 2020-09-15 at 09 05 13](https://user-images.githubusercontent.com/925197/93183473-f0499100-f732-11ea-84b4-22b215fa3517.png)

**Comment by khawkins98** [comment]
We could disable loading vfBanner of iframes with something like:

```js
if(node.ownerDocument !== document) {
  // is iframe
} else {
  vfBanner();
}
```

But that would break the vf-banner component preview too.

As a partial fix+feature I've been meaning to add for a while we can make `vfBanner()` add appropriate padding to the bottom of the page so it doesn't block content. 

![image](https://user-images.githubusercontent.com/928100/94659140-1e6acb80-0304-11eb-8490-371fc9358e88.png)


Have a PR in progress.

**Comment by sturobson** [comment]
e can make vfBanner() add appropriate padding to the bottom of the page so it doesn't block content.

can we do this within a `_preview.njk` file?

**Comment by khawkins98** [comment]
I'm going to turn off the "You're on your local development environment" banners. In general, they seem to be annoying. 

If coders do wind up getting confused without them, we could easily reactivate.

Closing. Please reopen if you think we need to.
