### ISSUE TITLE
vf-search - clickable area around the 'clear search' pseudo button on the search bar

### ISSUE THREAD

**Issue by peter-walter** [visual-framework/vf-core#1120]
It has been noted by the training team that the target area around the 'clear search' pseudo element of the search bar is very small - is it possible to add any clickable padding around this?

![image](https://user-images.githubusercontent.com/13538087/93188808-5a653480-f739-11ea-9a10-a3a05e73eb6a.png)

**Comment by khawkins98** [comment]
This uses the browser-native "clear" element, though I'm sure (hope?) it's possible to override. Any experience here @sturobson ?

**Comment by peter-walter** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-search-cancel-button ?

**Comment by peter-walter** [comment]
https://developer.mozilla.org/en-US/docs/Archive/Web/CSS/::-ms-clear ?

**Comment by sturobson** [comment]
I don't think I've ever seen a clear button in a text input before. Is it something better put as an actionable button rather than inline? Perhaps we need some UX insight on this?

**Comment by peter-walter** [comment]
It’s unique to the type=“search”

See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search#Differences_between_search_and_text_types

**Comment by khawkins98** [comment]
It's a frequent ask as well as "Google does it"

![image](https://user-images.githubusercontent.com/928100/93202536-21d25480-f753-11ea-8166-c0598d62ee09.png)

**Comment by sturobson** [comment]
I mean, Google also thought the 'floating label' was the way to make form inputs until recently when they actually did some user research to show it was not.

Do we really want to add more CSS for something browsers provide by default? 

Aside: the HTML for that is absolutely horrendous - but it's good to see they've finally gone past using tables for the search home page :sob:

**Comment by sturobson** [comment]
![Screenshot 2020-11-06 at 11 52 40](https://user-images.githubusercontent.com/925197/98363274-9bd1dc00-2026-11eb-9e98-65a3ae29af43.png)


Closing this now.
