### ISSUE TITLE
vf-search: Rendering error in Safari

### ISSUE THREAD

**Issue by peter-walter** [visual-framework/vf-core#1121]
Input box is not styled

![image](https://user-images.githubusercontent.com/13538087/93190928-db253000-f73b-11ea-8a2d-9bd397de8556.png)

**Comment by sturobson** [comment]
There's an issue in our build w/ autoprefixer that has stopped it from adding `-webkit-appearance: none` - waiting on #1113

**Comment by khawkins98** [comment]
Missed #1113, now approved.

**Comment by sturobson** [comment]
@pwalter-ebi do you know if this is occurring from a pre-compiled `.css` file and if it's versioned or the `dev` one?

If it's `dev` it should show up soon - if not it'll be a little longer as we'd need to create the versioned copy and update npm.

Let's keep this open until:

- [x] it's live on `dev/styles.css`
- [x] the components that relate to #1113 are updated on `npm`
- [ ] a new version of the precompiled `.css` version has been released.

**Comment by peter-walter** [comment]
However training appear to be using https://dev.assets.emblstatic.net/vf/v2.0.0-rc.3/css/styles.css which I guess is a few steps behind.

**Comment by khawkins98** [comment]
Yeah, I've raised this with Prakash. Hopefully, those get updated soon, but there will be a few CSS class substitutions needed as quite a lot has changed since rc.3 

https://gitlab.ebi.ac.uk/ebiwd/ebi-academy/ebi-academy-catalogue/-/issues/2

**Comment by khawkins98** [comment]
Can be closed?

**Comment by sturobson** [comment]
![Screenshot 2020-11-06 at 11 49 07](https://user-images.githubusercontent.com/925197/98363047-3bdb3580-2026-11eb-93f0-4ed9f047a066.png)
![Screenshot 2020-11-06 at 11 48 53](https://user-images.githubusercontent.com/925197/98363049-3d0c6280-2026-11eb-8a9e-d6779a7a30bd.png)
![Screenshot 2020-11-06 at 11 48 45](https://user-images.githubusercontent.com/925197/98363052-3d0c6280-2026-11eb-8842-3a5dd01b4f9a.png)

**Comment by sturobson** [comment]
These screenshots were taken today in Safari.

And we are now at `2.3.1rc1` so I'm closing this. 

https://visual-framework.github.io/vf-core/updates/2020-10-29-component-updates/
