### ISSUE TITLE
GA - Dynamic/multiple category option for events

### ISSUE THREAD

**Issue by sandykadam** [visual-framework/vf-core#1132]
Can we have multiple category option in GA, right now we are not able to track Outbound links, Downloads events.

![Screenshot 2020-09-28 at 11 18 38](https://user-images.githubusercontent.com/1227241/94420677-64952300-017c-11eb-8cac-b30bf59136e1.png)

Update - 

Download was not working in Covid19 because angular is generating download file based on checkbox selection and the code we have in VF component is it will check with any download urls format having xml|ppt|txt etc which is not in case of covid19
so is there way we can create GA send event public function from another components

e.g 
```
// in VF Component
function vfGaAddEvent(eventCat, eventAction, eventLabel) {
ga && ga('send', 'event', eventCat, eventAction, eventLabel);
}
// in external download component code
gaSrv = GaEventsTrackerService();
gaSrv.VfGaAddEvent('Download', 'Type / XML',  'some file path');
```
Ken suggestion to use `vfGaTrackInteraction()` to do this, but this will only log Event i.e "Download" but we also need to track what kind of file user download e.g XML, FASTA, EMBL, TXT etc

**Comment by khawkins98** [comment]
Hi @sandykadam. Reviewing the code, it looks like I "forgot" about the features that were added. In ` 1.0.0-rc.1` the "Download" and "Email" categories were added.

https://github.com/visual-framework/vf-core/blob/140a20e6f1e9a32c14958bb5b26358d480a349cc/components/vf-analytics-google/vf-analytics-google.js#L275-L283

I suspect the component code you're using is out of date, would be good if we can track down why you can't use the JS from https://www.npmjs.com/package/@visual-framework/vf-analytics-google directly.

**Comment by khawkins98** [comment]
This one's done. Closing. Some related work in #1161
