### ISSUE TITLE
BUG: `vf-tabs` nested tabs confusion

### ISSUE THREAD

**Issue by dbushell** [visual-framework/vf-core#1136]
When nesting the `vf-tabs` pattern, the JavaScript gets confused switching tabs.

Example can be seen in the documentation:
https://visual-framework.github.io/vf-core/components/vf-tabs/

Switch between the first 4 tabs you'll see "Section 1" to "4" as expected. Then try to use the nested tabs and "Section 3" gets stuck permanently and the nested tabs don't appear to switch. 

Myself and @kasprzyk-sz have both experienced the issue with different implementations.

<img width="626" alt="Screenshot 2020-09-30 at 09 13 30" src="https://user-images.githubusercontent.com/998922/94660202-e9a34800-02f4-11eb-9d2a-ec41b030f22d.png">

**Comment by sturobson** [comment]
I've not been a fan of nesting tabs inside of tabs -- doesn't look like the best way to display content. I'd rather not have this option available, alas here we are.

**Comment by khawkins98** [comment]
Going to set the priority on this one to "low" because, as @sturobson notes, we really shouldn't have occurrences of nested patterns in the wild. This was more of a theoretical "will to go". 

But we should track down what's wrong here, but, again, as long as we don't have a real need for nested tabs ...

**Comment by sturobson** [comment]
perhaps we should hide the variant (although I'm not sure how possible that is with the live documentation site)

**Comment by gabsie** [comment]
I am a little bit for not including this/hiding etc :) if we're not happy with it.
