### ISSUE TITLE
GA - Refactor verbose logging with customised function

### ISSUE THREAD

**Issue by sandykadam** [visual-framework/vf-core#1140]
Currently we have verbose logging of GA events irrespective of event category, we cannot log different event category as we have one common verbose log.

So we need to have a single function which we can call at multiple places to log different event category like mail/download etc.

**Comment by khawkins98** [comment]
Hey Sandeep. Do you mean the logging to console.log, or what gets logged in Google Analytics Events?

**Comment by sandykadam** [comment]
Yes console log when event is triggered, I some fix I will raise PR
