### ISSUE TITLE
GA - Track form interactions

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#1161]
In [`vf-analytics-google`](https://visual-framework.github.io/vf-core/components/vf-analytics-google/) there is currently not a method track when a user has clicked on a form element.

## Example use case

https://www.covid19dataportal.org/sequences?db=embl

![image](https://user-images.githubusercontent.com/928100/96243502-1f0e8d80-0fa5-11eb-988c-e09e7b00da27.png)

## a/c

- [x] Track clicks on `label` and `input`
- [x] Derive a label
  - 1. Use `data-vf-ga-label`
  - 2. Use string value of wrapping `label` 
  - 3. User string value of associated `label`
  - 4. Fallback to `id` `value` `name` attributes

**Comment by khawkins98** [comment]
@sandykadam Once rc.6 is live on npm this will work. 

For your particular use case, you'll need to add `data-vf-analytics-label="A special label"` to your input checkboxes.

**Comment by sandykadam** [comment]
Thanks @khawkins98 thats great, I will check and will let you know

**Comment by khawkins98** [comment]
Links for posterity:

- https://www.npmjs.com/package/@visual-framework/vf-analytics-google
- https://unpkg.com/@visual-framework/vf-analytics-google@1.0.0-rc.6/CHANGELOG.md

**Comment by sandykadam** [comment]
Hi Ken,

Issue 1 - Can we give first priority to "data-vf-analytics-label" if present else it should look for ID, currently it is giving preference to "id" even though "data-vf-analytics-label" is present.

Please check this PR code - https://gitlab.ebi.ac.uk/c19portal/cv19-frontend/-/merge_requests/185

![Screenshot 2020-10-28 at 16 06 39](https://user-images.githubusercontent.com/1227241/97463389-9cd48080-1937-11eb-8f62-24af619bdb0b.png)

![Screenshot 2020-10-28 at 16 07 09](https://user-images.githubusercontent.com/1227241/97463623-dad1a480-1937-11eb-9f2b-e78196c426a0.png)

Issue 2 - Facets tracking only works first time, when we select another new facet option tracking doesn't work.

**Comment by khawkins98** [comment]
I think the issue is that the `data-vf-analytics-label` is on the `mat-checkbox` element, and the DOM event is on the the further nested `input` element.

Can you add the `data-vf-analytics-label` to `input`?

This might also relate to issue 2.

**Comment by oss6** [comment]
Hi @khawkins98 , I am Ossama Edbali from EBI, working with @sandykadam.

We tried putting the `data-vf-analytics-label` attribute on `input`, however the latter is hidden (internal styling from `mat-checkbox`).
So I tried putting the analytics attribute on `label`, however the `target` element is the child of `label` (in this case `span` or the `div`, see the above image). In `vf-analytics-google.js` there currently isn't a way to get a `label` from a child element, although this functionality is present for `a` elements (see https://github.com/visual-framework/vf-core/blob/develop/components/vf-analytics-google/vf-analytics-google.js#L221 for context).

Can I go ahead and raise an issue for this functionality (and possibly a PR following that)?

Thank you!

**Comment by khawkins98** [comment]
Thanks for your research. Yes PRs are very welcome. 

Alternatively we could also observe `mat-checkbox` for the data attribute.

**Comment by oss6** [comment]
I'm happy with either, adding it to `mat-checkbox` would be great, it depends on how generic `vf` wants to be (or if it's known to be used with Angular material).
I think that adding the functionality to `findParent` for elements inside `label` would still be a good thing.

**Comment by khawkins98** [comment]
I think this one can be closed. Proceeding.
