### ISSUE TITLE
REFACTOR: Typography

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#1167]
Currently the typography feels a little 'disjointed' and doesn't tie nicely with the 8px layout system that we're slowly introducing.

Things to do:

1. Agree on the font sizes for headings and text for desktop
2. Agree on the font sizes for headings and text for desktop 
3. Introduce #865 for components
4. Have separate 'content' and 'component' Sass mixin (making use of #865)
5. Start implementing this 'side by side' if needed.

Here's a quick CodePen of what would change https://codepen.io/sturobson/full/7a5d07586e6dd5ccf2fc7fbb425d9a74

This is based on 18px being the 'base font size' (which we use for body copy) and based on a 'minor third' (1.125) increase in type-scale

**Comment by khawkins98** [comment]
Worth waiting for the dust to settle on EMBL.org first?

**Comment by khawkins98** [comment]
Related  #607 (REFACTOR / QUESTION -- component and content typography)

**Comment by khawkins98** [comment]
Also adding @cindyebi to this one.

**Comment by cindyebi** [comment]
Typography token updates:

- Change from the “T-shirt sizing” naming convention e.g. Extra Small, Small, Medium, etc. to H1, H2, …
- 16pt minimum font size using a Major Third type-scale of 1.250
- Bold and Semibold Heading font weight variants for a better visual hierarchy

Link to the **Design Library on Figma**: https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?node-id=5%3A39

**Comment by khawkins98** [comment]
Thanks Cindy.

Also attaching an export as a PDF for future reference: [typography.pdf](https://github.com/visual-framework/vf-core/files/5813775/typography.pdf)

The values would map to this file and a quick look suggest no major issues technically: https://github.com/visual-framework/vf-core/blob/develop/components/vf-design-tokens/src/typographic-scales/vf-font--sans.yml (Though I'm sure @sturobson will have a more nuanced view, particularly on how we export the Figma values to the file)

Once we have an approach to go from Figma to code, this might be a good candidate for an 4.0.0-alpha.1 release to test the sizes; some particular things to watch for:

- the heading sizes are larger with the minimum going from 19px to 26px so we'll need to see how that affects the news summary and section headers, in particular:
![image](https://user-images.githubusercontent.com/928100/104578890-8e0a8980-565b-11eb-8d2a-1fa1348dd236.png)
(also as content authors are already verrrry long headlines)
- similarly the smallest paragraph size is bigger, but the only odd one out is probably figure captions and perhaps author information (but these area probably smaller than they should be)

We'll also need to come up with a strategy around rollout as we'll probably have many components that were using heading-3 switching to heading-4 or heading-5, but I think that's just going to have to be a chore.

So a blog post is probably in order. Perhaps co-authored by @cindyebi and @sturobson ?
