### ISSUE TITLE
Discussion/notes: improving the component library browser

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#1175]
The component library remains an ongoing work in progress.

One of the big outstanding things that has been discussed a few times is how to handle "in context" component navigation ... that is, the left column:

![image](https://user-images.githubusercontent.com/928100/96611005-878aa100-12fc-11eb-9f1b-97f8049e2413.png)

## The problem

The left column works well from a UX approach, but as a simple grid it can disrupt the preview of some things that are intended to be used as full width.

[vf-u-fullbleed](https://visual-framework.github.io/vf-core/components/vf-u-fullbleed/)

![image](https://user-images.githubusercontent.com/928100/96611114-aab55080-12fc-11eb-91b2-7fb62b7061b7.png)

And even less obvious ones like [vf-intro](https://visual-framework.github.io/vf-core/components/embl-grid), where they're intended to be used in a full-width container:

![image](https://user-images.githubusercontent.com/928100/96611755-4b0b7500-12fd-11eb-8d8b-0a038e580a74.png)

---

## Soooo... 

how do other component libraries/systems handle component browsers?

### Orbit

Uses a tree-like left sidebar. It avoids layout breaks by not showing previews for these components on the page and instead of linking to an external page for previews.

https://orbit.kiwi/components/navigationbar/

![image](https://user-images.githubusercontent.com/928100/96612989-ba359900-12fe-11eb-8911-ad83a52d73b1.png)

### Patternfly

Uses a left-side tree and — where a component can't be shown in-context — shows a screenshot that opens in a new tab.

https://www.patternfly.org/v4/components/login-page

![image](https://user-images.githubusercontent.com/928100/96613472-4ba50b00-12ff-11eb-8fba-447383357ef7.png)

### USWDS

Also left side and uses a screenshot (like Patternfly)

https://designsystem.digital.gov/page-templates/#documentation-page

![image](https://user-images.githubusercontent.com/928100/96613670-873fd500-12ff-11eb-968b-59a8469aa556.png)

### Duet 

Uses resizeable iframes and requires that you make your browser sufficiently large to show "desktop in a desktop"

https://www.duetds.com/templates/hero-area-light/

![image](https://user-images.githubusercontent.com/928100/96613935-d6860580-12ff-11eb-8328-e869d980dee0.png)

### More?

I'm sure I've overlooked some.

---

## Do we already have a partial solution?

It's conceivable to adapt `vf-tree`

![image](https://user-images.githubusercontent.com/928100/96612101-a9385800-12fd-11eb-9261-320130184994.png)

---

## Conclusion

- All use some kind of left-hand navigation or tree.
- Options for too-wide components
  - Show in an iframe
  - Open in a tab

--- 

## a/c

- [ ] Prefer no JS
- [ ] Some good mobile approach
- [ ] Same method for elements/blocks/containers

(We also need to otherwise improve the content flow of the component documentation, but that's a slightly separate issue)

**Comment by khawkins98** [comment]
I'll probably make an "exploratory branch" over the next couple of days.

**Comment by sturobson** [comment]
<img width="1279" alt="Screenshot 2020-08-30 at 18 33 39" src="https://user-images.githubusercontent.com/925197/96617544-ad637600-12fb-11eb-93cb-55d16dc80f35.png">

There's also this old idea I had which I wanted to dig into at some point…

But, I think, there would (at least) need to be a uniform way of denoting variants and themes -- which we currently do not have.

**Comment by khawkins98** [comment]
Yeah this is part of a "bunch of things". 

- component navigation
- page hierarchy
- component previews

Which may not be able to be solved individually.

**Comment by khawkins98** [comment]
Adding a couple more (I should have thought to add these sooner).

### The omnipresent Gov.uk design system

![image](https://user-images.githubusercontent.com/928100/96838186-d002a580-1447-11eb-8332-50dff689cbd5.png)

https://design-system.service.gov.uk/components/accordion/

### Co-op

![image](https://user-images.githubusercontent.com/928100/96838248-ec064700-1447-11eb-8822-2822a8b440e0.png)

https://coop-design-system.herokuapp.com/pattern-library/foundations/page-layout.html

Most interesting as it has no "in-context" component list and instead uses the breadcrumbs to direct you to the component overview (very container-y and VF-y)

## Musings

I think these two (and USWDS) are probably the best inspiration to where we want to go, as:

1. They're not JS based 
2. The other examples aren't just component lists, they're full left-hand site navigations -- a pattern we don't recommend for VF sites and services

Maybe we can have a quick chat after standup

**Comment by khawkins98** [comment]
Dropping @sturobson 's mockup here so it doesn't disappear again. 

![Screen Recording 2020-08-19 at 11 16 01](https://user-images.githubusercontent.com/928100/96864436-b02fa980-1468-11eb-91aa-6b8d73814822.gif)

**Comment by khawkins98** [comment]
☝️  Noting the obvious that to fully achieve the above we'll have to be much more structured in our approach to the README.md, however we can still make some progress towards it.

**Comment by khawkins98** [comment]
Some work was also done on this in #1341

**Comment by khawkins98** [comment]
Also: having a grid that shows component status in code and Figma ... like https://design.gitlab.com/components/status/

![image](https://user-images.githubusercontent.com/928100/115414184-1e75de80-a1f6-11eb-9c6a-122dcb6c0de5.png)

**Comment by khawkins98** [comment]
Work done on this in #1689
