### ISSUE TITLE
🐛 fractal previews no longer picking up the local CSS

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#1176]
From the recent changes I've noticed that the CSS isn't loading in Fractal when running `gulp dev` when inside `tools/vf-component-library`.

the `path` doesn't appear to be resolving, or the CSS file is no longer there as replacing 

```
<link rel="stylesheet" href="{{ '/css/styles.css' | path }}">
```

with 

```
<link rel="stylesheet" href="http://localhost:3003/vf-core/css/styles.css">
```

works as expected, but is obviously not a viable solution.

**Comment by khawkins98** [comment]
Might be from the move from fractal 1.2.1 to 1.3.0

**Comment by khawkins98** [comment]
I've been meaning to add this option to https://visual-framework.github.io/vf-core//troubleshooting

`git clean -f -X`

Which deletes all ignored and untracked files. So it will delete all the node_modules and any dynamic things.

Then reinstalled:

`yarn install && cd tools/vf-core/ && yarn install && gulp vf-dev`

I've done that and the local fractal seems to be fine.

Also my versions:

```bash
mac:vf-core khawkins$ npm -v
6.13.4
mac:vf-core khawkins$ node -v
v12.16.1
```

![image](https://user-images.githubusercontent.com/928100/97470434-cd241b00-1947-11eb-932b-e6f793e80a80.png)

**Comment by sturobson** [comment]
doing the `git clean` and re-instsalling everything worked. 

I think we can close this as it's been added to the documentation?

**Comment by khawkins98** [comment]
![drop it in the ocean](https://media.tenor.co/images/36423c60a761ba8c4d2325d08d1062c9/tenor.gif)
