### ISSUE TITLE
Refactor deployment, default branches

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#118]
Now that we're planning regular release we should:

- [ ] Switch the default branch back to `master`
- [ ] Deploy all commits on `develop` to `dev.assets.emblstatic.net/vf/`
- [ ] Deploy all commits on `master` to `assets.emblstatic.net/vf/`
- [ ] Deploy all tags on `master` to `assets.emblstatic.net/vf/{tag}`
     - e.g. `assets.emblstatic.net/vf/v2.0.0-alpha.1`

This was already partly discussed in #28

**Comment by khawkins98** [comment]
I need to rope Peter into this one, so we won't get here until `alpha.3`

**Comment by sturobson** [comment]
We could have an NPM package of the versioned compiled CSS … and use unpkg for the urls that people use?

**Comment by khawkins98** [comment]
I've pinged Peter on this earlier in the week, him and Sandeep should hopefully be tackling soonish.

**Comment by pwalter-ebi** [comment]
Do we want the tags so granular?
assets.emblstatic.net/vf/v2.0.0-alpha.1
or
assets.emblstatic.net/vf/v2.0

**Comment by khawkins98** [comment]
I think we need some way for, say, WP to opt in to changes. So it might be running on `alpha.1` but not be ready yet for `alpha.2`

**Comment by pwalter-ebi** [comment]
Discussion outcomes
https://docs.google.com/document/d/1ZtTR8V28orNgqsOwuKpAGfFOgtlBPQn3dOgh22GhM3c/edit

Pull request
https://github.com/visual-framework/vf-core/pull/304

**Comment by khawkins98** [comment]
Now sorted by #304:

- https://dev.assets.emblstatic.net/vf/develop/
- https://dev.assets.emblstatic.net/vf/{tag}/ (eg v2.1.2)
- https://dev.assets.emblstatic.net/vf/{minor}/ (eg v2.1)
- https://dev.assets.emblstatic.net/vf/{major}/ (eg v2)

Won't be available until we merge to `master`, leaving this issue open until we have confirmation,

**Comment by khawkins98** [comment]
Looks like this is now working with @pwalter-ebi 's most recent edit (#309). 

Tagged releases will be added as they're made (so no alpha.1/2/3). 

Leaving open as a documentation task.

**Comment by khawkins98** [comment]
It works 🎉

https://dev.assets.emblstatic.net/vf/v2.0.0-alpha.4/css/styles.css
