### ISSUE TITLE
Redirect to visual-framework.dev

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#1200]
With the visual-framework.dev domain registered (#720) and live (#1199) we now need to redirect the old URLs from https://visual-framework.github.io/vf-core

## PR 1 #1205
1. [x] Update component library to not have a directory (🚫  https://latest.visual-framework.dev/vf-core/components)
1. [x] Update all the links in the vf-core repo
1. [x] Drop the travis deployment to gh-pages
1. [x] Tag a release to avoid lerna publishing all the components

## PR 2
1. [x] Drop pages from gh-pages
1. [x] Add a 404 JS-based redirect to the new domain

## Chore

1. [x] Update links to the new URL in other places (slack, presentations, etc)

**Comment by khawkins98** [comment]
We should be all set here; some test redirects:

- https://visual-framework.github.io/vf-core/components
- https://visual-framework.github.io/vf-core/search/?search_query=intro
- https://visual-framework.github.io/vf-core/feed.xml

@sandykadam one thing missing is a 404 page, is it easy to map this page https://latest.visual-framework.dev/404.html ?

**Comment by sandykadam** [comment]
Does it have same setup like we had "info/error-pages/404/index.html" or create custom one.

**Comment by khawkins98** [comment]
This 404 has some special things, it currently deploys to /404.html, but I can easily move it under `info/error-pages/404/index.html` if that's better?

**Comment by sandykadam** [comment]
Sorry my bad I fail to notice you already have actual "404.html" and I thought there is no 404 and need to have rules in place.
Please ignore my previous comments, I got it now will have rules in place for 404.html.

**Comment by sandykadam** [comment]
Fixed now applied to both latest & stable.

**Comment by khawkins98** [comment]
👍  thanks!

https://stable.visual-framework.dev/dasfs
