### ISSUE TITLE
GA - Feature to track outbound/external links

### ISSUE THREAD

**Issue by sandykadam** [visual-framework/vf-core#1210]
Currently VF2.0 is not able to track external outbound/outgoing links in GA. So we need to add this feature in current component.

**Comment by khawkins98** [comment]
We could borrow the approach from the drupal google analytics module:

https://git.drupalcode.org/project/google_analytics/-/blob/8.x-2.x/js/google_analytics.js#L67

```js
          else if (drupalSettings.google_analytics.trackOutbound && this.href.match(/^\w+:\/\//i)) {
            if (drupalSettings.google_analytics.trackDomainMode !== 2 || (drupalSettings.google_analytics.trackDomainMode === 2 && !Drupal.google_analytics.isCrossDomain(this.hostname, drupalSettings.google_analytics.trackCrossDomains))) {
              // External link clicked / No top-level cross domain clicked.
              ga('send', {
                hitType: 'event',
                eventCategory: 'Outbound links',
                eventAction: 'Click',
                eventLabel: this.href,
                transport: 'beacon'
              });
            }
          }
```

We'd need to:

1. Add a new category "external links"
2. Add a way to detect the current domain (if on www.EBI.ac.uk/EBI, everything in `*.ebi.ac.uk/*` would be considered internal)
3. Optional: Add a way to pass external domains considered internal (if on EMBL.org, don't consider EBI.ac.uk as external)

**Comment by khawkins98** [comment]
Aside: I noticed the drupal module uses `ga('set', 'transport', 'beacon');`, which might be good for us to use as it offers more robust tracking:

https://developers.google.com/analytics/devguides/collection/analyticsjs/sending-hits

**Comment by sturobson** [comment]
With #1216 merged - can this be closed now? 

@sandykadam + @khawkins98

**Comment by sandykadam** [comment]
Works great on local but I found new bug when you click on footer logos European commission or any logo link, there is error

`
ERROR TypeError: Cannot read property 'split' of undefined
    at vfGaTrackInteraction (vf-analytics-google.js:328)
    at HTMLBodyElement.<anonymous> (vf-analytics-google.js:233)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41645)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:480)
    at invokeTask (zone-evergreen.js:1621)
    at HTMLBodyElement.globalZoneAwareCallback (zone-evergreen.js:1647)

`

**Comment by khawkins98** [comment]
This looks like it might be a separate issue with a missing `getElementsByTagName("img")[0]` in 

```js
    // is there an inner image?
    if (linkName.length == 0 && actedOnItem.getElementsByTagName("img")) {
      if (actedOnItem.getElementsByTagName("img")[0]) {
        if (actedOnItem.getElementsByTagName("img")[0].hasAttribute("src")) {
          linkName = actedOnItem.src.split("/").vfGaLinkLast();
        }
      }
    }
```

**Comment by khawkins98** [comment]
Have moved the above to a new issue. Closing this one.
