### ISSUE TITLE
vf-cluster spacing variation margins

### ISSUE THREAD

**Issue by dbushell** [visual-framework/vf-core#1212]
Issue can be seen with the [Cluster](https://visual-framework.github.io/vf-core/components/vf-cluster/) examples.

I've noticed for the `medium` and `large` spacing variations the margin is set with this selector:

```css
.vf-cluster--600 > * > * {
  --vf-cluster-margin: #{map-get($vf-spacing-map, vf-spacing--600)};
}
```

So the child items get the `--vf-cluster-margin` change.

However the parent which has a negative margin remains the `small` default.

```css
.vf-cluster > * {
  margin: calc(var(--vf-cluster-margin) / 2 * -1) !important;
}
```

The `--vf-cluster-margin` never updates on the parent. So the variations get slightly more inset and don't align properly.

![vf-cluster-margin](https://user-images.githubusercontent.com/998922/97887551-fc5cd280-1d21-11eb-8498-85243ec7f7b7.png)

Seems to me the CSS prop only needs to be updated on the `.vf-cluster` class rather than the child selectors? Like how the custom spacing works.

**Comment by sturobson** [comment]
@dbushell just confirming with another persons eye … this is what is expected:

![Screenshot 2020-11-04 at 14 57 09](https://user-images.githubusercontent.com/925197/98127487-ac5f4680-1eae-11eb-8c98-8f847839d088.png)
