### ISSUE TITLE
📒 Documentation: write reference on image handling best practice

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#1230]
In short: it's best to not let CSS do the image cropping. Resize your images or have your CMS or image proxy do the cropping.

**Comment by sturobson** [comment]
Some thoughts:

- we should still make use of CSS for cropping as the 'fallback' for when content creators don't follow the size guidelines*
- * we need to make the size guidelines
- we should investigate the reintroduction of using width and height to help the [layout engine in browsers](https://www.smashingmagazine.com/2020/03/setting-height-width-images-important-again/).

- more to follow, I'm sure.

**Comment by khawkins98** [comment]
Stub documentation at https://latest.visual-framework.dev/guidance/image-handling/
