### ISSUE TITLE
📒 Documentation: clarify component interoperability

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#1231]
Many developers expect that VF components should all share the same version, that is: it feels weird to use `vf-button@1.2.3` with `vf-card@2.2.2`.

From a developer:

> it's also difficult to know which version of the vf package to use. I started updating the versions to the latest but some are at version 3xx and other are at 1xx then it's not clear if they are compatible with each other

We should make the versioning practice clearer.

We have already have these pages, which aren't so easy to find:

- https://stable.visual-framework.dev/developing/components/updating-a-component/
- https://stable.visual-framework.dev/developing/guidelines/versioning/

**Comment by sturobson** [comment]
I know Fractal shows the components used in a component.

- Is this possible with our new layout? 
- Is it possible to find the version number and attach it?

**Comment by khawkins98** [comment]
Some documentation at https://latest.visual-framework.dev/guidance/versioning-and-component-interoperability/

By my view, this can now be closed.
