### ISSUE TITLE
🤔 should `vf-footer` be sticky to the bottom of the viewport?

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#1246]
On pages with little content - the footer just 'flows' which can leave whitespace below it, if the browser viewport is large.

Should we look at making it 'sticky' 

![Screenshot 2020-11-18 at 08 31 58](https://user-images.githubusercontent.com/925197/99505448-c140dd00-2978-11eb-9b8d-4c53f65657dd.png)

**Comment by khawkins98** [comment]
I gave this a quick try using a method (not necessarily the best method):

```css
.vf-footer {
  position: sticky;
  top: 100%;
}
.vf-body {
  min-height: 100vh;
}
```

That works but it makes an aliasing artefact (on Chrome) with how the full-bleed green line is drawn:

![image](https://user-images.githubusercontent.com/928100/102222536-d3645b80-3ee3-11eb-92d9-9f5882169d90.png)

Adding a `will-change: transform;` sorts it.

But it makes me wonder if this is a "content issue" and we'll make more issues than we might fix?
