### ISSUE TITLE
Enhancement: export vfGaTrackInteraction for ESM

### ISSUE THREAD

**Issue by oss6** [visual-framework/vf-core#1248]
## Summary

Add the `vfGaTrackInteraction` function to the exported members of `vf-analytics-google`.

## Use case

In an Angular project we want to programmatically track an event and it would be useful to have something like this:

```
import { vfGaTrackInteraction } from '@visual-framework/vf-analytics-google/vf-analytics-google.js'
...
vfGaTrackInteraction(...);
```

**Comment by oss6** [comment]
As discussed in Slack I'm happy to raise a PR for this :+1:

**Comment by khawkins98** [comment]
I'll plan to do a component release tomorrow with the new feature.

**Comment by oss6** [comment]
Thank you very much Ken

**Comment by khawkins98** [comment]
This is now finally on npm. Had a few things pop up. 

https://stable.visual-framework.dev/updates/2020-11-24-component-updates/
