### ISSUE TITLE
FEATURE - Show pattern version in web interface

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#125]
As the version of a pattern can be important, we should show it in the web interface.

I know this is set/incremented by lerna in `pacakge.json` and I believe Fractal would need a version number stated in the `pattern.config.yml`...

Options:
- We could manually add version to `pattern.config.yml` ... tedious and error prone!
- Maybe lerna can update the yml?
- Some sort of post-commit magic?

**Comment by khawkins98** [comment]
Have just realised that this shows up in the badge (see image), it'd be nice to have it in a more flexible real-data format (for things like a future search result or on overview pages), but not sure that's practical?

![image](https://user-images.githubusercontent.com/928100/50636908-2ee7e980-0f58-11e9-8d68-b87a3f8f8969.png)

**Comment by sturobson** [comment]
In a previous contract I edited the Fractal `.nunj` files, adding some JS, to search the `package.json` and printing it out with the rest of the "File Information".

We could do that? But I'm not sure there's _real_ need for it at the moment. 

Adding 'on hold' as a label

**Comment by khawkins98** [comment]
Added to backlog.
