### ISSUE TITLE
DOCS - Add a "filesystem" tree map

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#128]
This should help with onboarding and just be useful in general. Probably for the README.md.

Probably we'd want to use `tree`, here's a command I got to in a few minutes: 
- ` tree  -L 2 . -I 'node_modules|cache|test_*|.git|.github|bin' -a`

Which gives (+some manual annotation)

## Filesystem notes

```
├── .editorconfig
├── CHANGELOG.md
├── CONTRIBUTING.md
├── README.md
├── SETTINGUP.md
├── assets  (your global Sass assembly file)
│   └── scss 
├── build  (dynamic folder used for rendering of static pattern library)
├── components  (all the components you wish to use)
│   ├── _previews (templates for the web pattern browser)
│   ├── vf-activity-group
...
│   └── vf-video-teaser
├── docs (documentation files for the web interface)
│   ├── changelog
│   └── guidelines
├── fractal.js (configuration for the web pattern library)
├── gulpfile.js
├── lerna.json 
├── package.json
├── public  (dynamic folder used for rendering of global CSS, JS, pattern assets)
└── tools 
    ├── component-generator (make new components)
    ├── css-generator (build requirement)
    ├── frctl-mandelbrot-embl-subtheme  (embl web interface)
    └── frctl-mandelbrot-vf-subtheme ( vanilla web interface)
```

☝️ this is probably less important for the `vf-core` and more so for the child theme template.

**Comment by khawkins98** [comment]
Adding to backlog.

**Comment by khawkins98** [comment]
Actually this exists already at https://github.com/visual-framework/vf-core/blob/develop/docs/contributing/file-structure.njk

Removing from backlog.

**Comment by sturobson** [comment]
aside: I wonder if we can move `_previews` outside of `vf-component` and if we did what performance hit it would or would not create.

**Comment by khawkins98** [comment]
Seems they're "just another component" so that means:

- They've go to go in `./components` ... but
- As they're a component we could call it `vf-previews` or
- Call it `vf-boilerplates`, which might be useful as a collection of generic page layouts

All that said, we've got 5 preview templates, I think we really only need 3, or maybe even 2. Potentially we don't even need any. Related: https://github.com/visual-framework/vf-core/issues/213

**Comment by sturobson** [comment]
should we amend what we call 'a component' and decide it to mean:

> A component is something that is used to create web pages and products for EMBL

which would mitigate `_previews` from being a 'true' component?

I agree we need to cut them down to less than 5.

I think `vf-boilerplate` would be something 'other' within BigZing! that can show templated pages as examples. In the larger design system, not something that comes in with the Fractal install.

**Comment by khawkins98** [comment]
Yeah, this all ties in with that outstanding question of what role does the `vf-core` website play ... I know you've previously expressed how it might make sense if it just becomes more of a raw component library, which it feels like we're headed towards.
