### ISSUE TITLE
Enhancement: making all the components 'stack' nicely across pages and sites.

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#1284]
We are running into issues with how the components 'stack' on top of each other because of the vast potential difference across sites and pages.

We can make things better by improving things across `vf-core`, `vf-wp`, and `vf-eleventy` (static-html-pagess). By intruding the `vf-stack` component more globally and letting the components dictate any custom margin sizes between each other in the components using the CSS custom property. This means IE11 will get consistent spacing - but more modern browsers will get the spacing required per component to let content 'breath'.

- [x] add `vf-stack vf-stack--400` to the `<body>` element where needed (in `vf-wp`).
- [ ] add `vf-stack vf-stack--400` to the `<body>` element where needed (in `vf-elventy`).
- [x] add `vf-stack vf-stack--400` to the `<body>` element where needed (in `vf-core`).
- [x] add `vf-stack vf-stack--400` to the `<body>` element where needed (in `static-html-pages`).
- [ ] remove all bottom margins from components in `vf-core`
- [ ] update components in `vf-eleventy`, `vf-wp`, `static-html-pages` as needed
- [ ] update component spacing 'as needed' using the 'real content' from embl.org testing
- [ ] add css custom properties as needed to components in `vf-core`
- [ ] update components to npm
- [ ] pull them into projects
- [ ] test again
- [ ] deploy

**Comment by sturobson** [comment]
> add vf-stack vf-stack--400 to the <body> element where needed (in static-html-pages).

https://gitlab.ebi.ac.uk/emblorg/embl-org-static-html-pages/-/merge_requests/642

**Comment by khawkins98** [comment]
Looking through the components this seems to have been largely accomplished, and where it hasn't it's on components that are in need of other updates (vf-details) and we can remove the custom margins as we refactor.
