### ISSUE TITLE
COMPONENT: we need a vf-skip-content component

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#1303]
Add a one sentence summary of what it is you need it to do.

Now that Firefox has a developer tool to show the tab order for screen readers I think we need to add a 'skip to content' component so that people can get past quite a few tabs to get to the content.

Here's how many tabs they need to get to before they get to a news article:

![Screenshot 2020-12-16 at 10 28 22](https://user-images.githubusercontent.com/925197/102336987-d0bc4180-3f89-11eb-98b0-fa9ca0ee70be.png)

---

- In a few words, what does this component look like?

It would be a small set of text links that are only 'invoked' when a site visitor presses the tab key when visiting a page.

- In a few words, what does this component do?

It allows a site visitors to skip items that appear on every page (header, navigation, breadcrumbs) quickly

- Would a rebrand change the structure or layout of this component?

No

- Can other websites use this component? Or is it only useful in your organisation or website?

Yes, and they probably should.

- Do you have any designs or concepts?

Nope, but it's quite a simple thing, more function over form.

- Have you done any user testing already?

Nope.

- How often do you expect to make use of this component?

Almost every page of the site(s).

- Can you list out major elements in this component?

A heading, some links

- Will all elements of this component be used every time?

Yep

- Does this component contain other components?

Only from existing Sass mixins, maybe the grid for appearance

- Do you already have a component?

Nope

**Comment by khawkins98** [comment]
This is "invisible" right?

Here's one that we've used at EBI in that past:

```html
<div id="skip-to">
 <ul>
 <li><a href="#content">Skip to main content</a></li>
 <li><a href="#local-nav">Skip to local navigation</a></li>
 <li><a href="#global-nav">Skip to EBI global navigation menu</a></li>
 <li><a href="#global-nav-expanded">Skip to expanded EBI global navigation menu (includes all sub-sections)</a></li>
 </ul>
</div>
```

**Comment by sturobson** [comment]
> This is "invisible" right?

More or less - I think it depends how it's done. 

I have seen some that are exposed when I scroll 'up the page'. We don't want that.

This also means we need to add and 'enforce' some semantic things as well I think - like having the page 'content' wrapped in a `<main>` element.

**Comment by khawkins98** [comment]
We don't have the capacity to action this, it is being moved to the backlog #446
