### ISSUE TITLE
Checkbox to disable the SVG in a link-list easy variant

### ISSUE THREAD

**Issue by filipe-dias** [visual-framework/vf-core#1338]
Hi @kasprzyk-sz 

As you requested, this issue is for adding the ability to not show the V-shaped SVG in the [easy variant of the link list](https://stable.visual-framework.dev/components/vf-link-list/#vf-link-list--easy). Nunjucks code uses `"svg": false,`

Thanks

**Comment by sturobson** [comment]
Hi @filipe-dias this needs to be raised [in the `vf-wp` repo](https://github.com/visual-framework/vf-wp/issues/new/choose).
