### ISSUE TITLE
In search form, making the input mandatory turns borders red

### ISSUE THREAD

**Issue by prakashebi** [visual-framework/vf-core#1345]
![Screenshot 2021-02-03 at 11 02 28](https://user-images.githubusercontent.com/45974822/106703321-0982a980-6610-11eb-8f16-9165960409ab.png)

It adds the following class to the input element which sets the border color to red even without interacting with the search form.
```
.vf-form__input:invalid {
    border-color: #d32f2f;
}

```
Is it the expected behavior or borders should stay in default color until user submits the form without giving any input!

**Comment by khawkins98** [comment]
Hey Prakash,  in this case you have:

```html
<input 
  id="textbox-filter" type="search" class="vf-form__input | vf-search__input" autocomplete="off" 
  maxlength="50" minlength="3" required="" 
  value="">
```

You don't need the `required=""` portion. Without it the native HTML will still turn it red for less 3 or more than 50.

## Empty

![image](https://user-images.githubusercontent.com/928100/106716224-78ef9d80-65fe-11eb-8e7c-c929ae56edfc.png)

## 2 chars (fails)

![image](https://user-images.githubusercontent.com/928100/106716243-7f7e1500-65fe-11eb-82fc-f7dc03275726.png)

## 3 chars (pass)

![image](https://user-images.githubusercontent.com/928100/106716260-84db5f80-65fe-11eb-8498-c730599340d2.png)

**Comment by sturobson** [comment]
aside: We should document when where to use this -- I think realistically the only place required needs to be is on login forms, everything else could be a barrier. This would be easier if/when we split out the `vf-forms` to show each component separately

**Comment by prakashebi** [comment]
Hi Ken,

The input in the search form should be required as system can't search if it doesn't know what to search. If we submit a search form without search term the logic breaks.

`minlength` attribute triggers validation only if we enter at least one character, if the input is empty `minlength` doesn't validate at all and in this case we need `required` also.

I will try to make the input mandatory in the form submission logic without `required` attribute.

**Comment by sturobson** [comment]
I don't think I've ever seen a search input that's been required. Google, Amazon, eBay, Bing etc etc don't require a search term.

**Comment by prakashebi** [comment]
Yeah that's true, I am trying to do the same now.
I also haven't seen an input turns invalid only by adding a `required` attribute and without interacting with the form at all.

**Comment by sturobson** [comment]
Ah, that would require some JavaScript. 

We haven't added that to `vf-core` (yet) as from previous experience in things like this - I've had issues with including vanilla JS in form validation as part of the component breaking when used inside other JS frameworks.
