### ISSUE TITLE
Component: vf-card to button? how?

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#1346]
There's been recurring feedback from stakeholders that linked vf-card's aren't obvious that they are "interact-able". So they've had links and buttons shoehorned in.

1. Do we agree that they need to be more "obvious" as links?
2. Is there a way we can achieve this without adding additional "click here" elements?
3. If we do need an element, what should we use?

## Default vf-card links

![image](https://user-images.githubusercontent.com/928100/106730712-f3c0b480-660e-11eb-8fcf-b1e7ea06c3c6.png)

![image](https://user-images.githubusercontent.com/928100/106730827-1521a080-660f-11eb-9743-31258a691d9c.png)

## With text links

EMBL.org/news

![image](https://user-images.githubusercontent.com/928100/106730549-cd9b1480-660e-11eb-8df9-c3b671cbf409.png)

www.EBI.ac.uk

![image](https://user-images.githubusercontent.com/928100/106730601-d986d680-660e-11eb-9c2a-ca59a3c0c3b7.png)

## With buttons

![image](https://user-images.githubusercontent.com/928100/106730472-b8be8100-660e-11eb-8ae1-722ddf625315.png)

www.ebi.ac.uk/about/our-impact/covid-19

![image](https://user-images.githubusercontent.com/928100/106730645-e277a800-660e-11eb-8281-ab453114861a.png)

Probably some other ones out there too...

I'll also add this to the UX consultation agenda.

**Comment by khawkins98** [comment]
Related: Consistency: "read more" links #1287

**Comment by sturobson** [comment]
I think it makes sense to integrate what we do with the section header, this would keep things [simple](https://latest.visual-framework.dev/design-principles/#Simple), [ingrained](https://latest.visual-framework.dev/design-principles/#Ingrained), and [unified](https://latest.visual-framework.dev/design-principles/#Unified) within the system.

https://user-images.githubusercontent.com/925197/107145003-b2921280-6936-11eb-94bc-6e841053c07e.mov

**Comment by khawkins98** [comment]
There's an issue with EBI gitlab's deployment mirroring, so adding a static snapshot of the latest look for linked cards with images: 

![image](https://user-images.githubusercontent.com/928100/107411685-1f600500-6b0f-11eb-8520-dc48f625c82b.png)

![image](https://user-images.githubusercontent.com/928100/107411717-2850d680-6b0f-11eb-82aa-245be4dd8967.png)

**Comment by khawkins98** [comment]
With new arrows and how we note you shouldn't use buttons on cards ("read more" links at #1287), we can close this.
