### ISSUE TITLE
BUG: layout of design principles 'ingrained' explanation is 'off'.

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#1350]
A quick five minutes in the code and I cannot see why we're getting a single column in the last bit of content -- it probably is some errant HTML element somewhere.

**Comment by khawkins98** [comment]
This bit should be inside the adjacent `div.vf-content`:

https://github.com/visual-framework/vf-core/blob/fee43ea0c9e8ceda402034347c031e3b8ac5343e/tools/vf-component-library/src/site/design-principles/index.njk#L141-L143

**Comment by khawkins98** [comment]
Actually, I think for what you want it shouldn't be nested inside that `section.embl-grid`

**Comment by khawkins98** [comment]
Made a quick PR: https://github.com/visual-framework/vf-core/pull/1351

aside: do we have docs on when to use vf-divider between sections?

I didn't see anything at https://stable.visual-framework.dev/components/vf-divider/
