### ISSUE TITLE
Bug: vf-card vertically centres content

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#1395]
When several vf-card have `vf-card__content` of differing heights, the grid vertically centres.

As seen at https://stable.visual-framework.dev/

![image](https://user-images.githubusercontent.com/928100/109184416-45cca400-778f-11eb-9f49-895676232e72.png)

This is currently the probable solution, but needs testing (lest it introduce its own bugs):

```css
.vf-card {
    align-content: start;

```

**Comment by sturobson** [comment]
Historically we used `grid` to define the image height (first row in the grid). Now we are doing this with `aspect-ratio` we do not need to do this -- and removing `display: grid` actually gives us the same layout as adding `align-content: start`. 

I wonder if we can get by with this by removing `display: grid` completely (which would mean the it defaults to `display: block` from the vendor CSS).

**Comment by khawkins98** [comment]
The fix in #1396 used `align-items: start;` and not `align-content: start;` so this one is still happening. 

https://latest.visual-framework.dev/

![image](https://user-images.githubusercontent.com/928100/111503758-56958780-8747-11eb-8633-9dd967affd2b.png)
