### ISSUE TITLE
proposal: strip back `vf-box` to more of a layout component.

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#1397]
Now that `vf-card` takes up some of the work that we currently use for `vf-box` I think we can strip back some of the functionality 

I propose we can:

- remove any CSS that determines what text can do
- reduces the design variants (not sure on this one - I guess if you want a bordered item, you probably need a `vf-card`.
- remove padding by default and make it an 'additive' thing with `--800` style variants
- increase the variants and introduce '--inline` and `--block` so we can apply padding accordingly.
- reduce the background colour options - and make use of the newer natural colour stack. 

This should help us reduce the reliance on utility classes in our codebase for spacing and colours and push people to use the `vf-card` or `vf-summary` as needed.

**Comment by khawkins98** [comment]
Liking the sound of this. If i'm following we should also:

- Move vf-box from a "block" to "layout" component type

![image](https://user-images.githubusercontent.com/928100/109292487-bbd21900-782a-11eb-82af-9f20da588f21.png)

**Comment by sturobson** [comment]
As we are moving this to more of a layout component I want to include the ability to choose where you want to add the padding.

I think the options could be:

- top
- bottom
- left
- right
- top and bottom
- left and right

We will be using CSS logical properties here so `inline` and `block` as needed (`inline` is left and right, `block` is top and bottom).

The question is how do we want to expose this in the nunjucks?

We can simply have the key/value of:

```
box_spacing_position: inline
```

and using a `for` loop we can allow for:

```
box_spacing_position: ['inline', 'block']
```

but I worry that we're relying on users to type this out correctly. 

Im leaning towards:

```
box__spacing_inlline: true
box__spacing_block: true
```

but this will lead to more key/value pairs needed to be written in the `.yml` as well as more `if` statements in the nunjucls.

I guess as the nunjucks isn't the end result of HTML this doesn't matter so much.

Thoughts?

Brevity or Clarity.

**Comment by khawkins98** [comment]
so to enable both the yaml would be like:

```
- block
   - inline
   - block
```

or for top right only

```
- block
  - top
  - right
```
If so, that seems ok

**Comment by sturobson** [comment]
hmmm, perhaps we could do

```
- spacing_position
  - all
  - top
  - left
  - bottom
  - right
```

and get the nunjucks to work it all out.

I was thinking:

```
spacing_position_inline_start: true
```

etc, but that's quite verbose for a user to typ.

**Comment by khawkins98** [comment]
We don't have the capacity to action this, it is being moved to the backlog #446
