### ISSUE TITLE
Enhancement: vf-content should handle images better

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#1412]
Currently `vf-content` doesn't do a great job dealing with random images, just showing them at their full width. I bumped into this when writing [today's VF update](https://stable.visual-framework.dev/updates/2021-03-05-component-updates/) and needed to add a vf-figure class as a workaround (which meant I couldn't use markdown for that item)

Example:

https://codepen.io/khawkins98/pen/eYBjaLg?editors=1100

![image](https://user-images.githubusercontent.com/928100/110140285-39ba9500-7dd4-11eb-8a37-0da85c26fac0.png)

Simple fix for plain images and figure could be:

```css
.vf-content img {
  max-width: 100%;
}
```

with simple fix

![image](https://user-images.githubusercontent.com/928100/110140323-4343fd00-7dd4-11eb-8b4f-b1d0a314dad8.png)

**Comment by sturobson** [comment]
Would it be wise to add `height: auto` which matches the original responsive images styles of RWD?

```
vf-content img {
  height: auto
  max-width: 100%;
}
```

This might also stop the over reliance of `vf-figure` for images a little - a path we've accidentally gone down.

**Comment by khawkins98** [comment]
Sounds good 👍
