### ISSUE TITLE
vf-details component doesn't appear clickable

### ISSUE THREAD

**Issue by peter-walter** [visual-framework/vf-core#1417]
Maybe adding the following CSS would help by adding the pointer when hovering over the summary line.
```
.vf-details--summary:hover {
  cursor: pointer;
}
```

**Comment by sturobson** [comment]
Hi @pwalter-ebi.

I've just checked the spec to see that this the default browser behaviour. 

However, as we add the `pointer` for buttons I don't see why we cannot add this to other interactive elements to help guide the site visitor to see that it's 'clickable'.

👍

**Comment by peter-walter** [comment]
Useful information: https://css-tricks.com/two-issues-styling-the-details-element-and-how-to-solve-them/
