### ISSUE TITLE
Enhancement: support Google Analytics gtag tracking

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#1428]
Google Analytics is now strongly pushing users to switch from `ga` (analytics.js) to `gtag` (gtag.js). This means many VF sites will start switching. 

![image](https://user-images.githubusercontent.com/928100/111670162-d25f0500-8817-11eb-825a-ff0b3c4dbfb5.png)

If you don't want to use gtag you have to read the small print and find the "additional tracking methods." and then read [a mess of technical docs](https://support.google.com/analytics/answer/7538414).

![image](https://user-images.githubusercontent.com/928100/111670203-dd199a00-8817-11eb-9ac3-3a8ce15baca4.png)

## Impacts

The syntax is similar but not the same: https://developers.google.com/analytics/devguides/collection/upgrade/analyticsjs

```js
ga('create', 'GA_MEASUREMENT_ID', 'auto', 'trackerName');
ga('trackerName.send', 'event', [eventCategory], [eventAction], [eventLabel], [eventValue], [fieldsObject]);
```

```js
gtag('event', eventName, {
  'send_to': 'GA_MEASUREMENT_ID',
  'parameter1': 'value1',
  'parameter2': 'value2',
  // ...
});
```

### Example

analytics.js:

```js
// Creates the default tracker.
ga('create', 'GA_MEASUREMENT_ID', 'auto');

// Uses the default tracker to send the event to the
// Google Analytics property with tracking ID GA_MEASUREMENT_ID.
ga('send', 'event', 'Videos', 'play', 'Fall Campaign');
```

gtag.js:

```js
// Sends the event to the Google Analytics property with
// tracking ID GA_MEASUREMENT_ID set by the config command in
// the global tracking snippet.
gtag('event', 'play', {
  'event_category': 'Videos',
  'event_label': 'Fall Campaign'
});
```

### So...

This 

```js
      ga && ga("send", "event", "UI", "UI Element / " + parentContainer, linkName);
```

Would become:

```js
      gtag && gtag("event", "UI Element / " + parentContainer, {
          "event_category": "UI", 
          "event_label": linkName
       });
```
## We'll need to ...

1. A way to detect if a site is on `ga` or `gtag`
2. Some way to support event tracking without a mess of if/else statements
3. Some way to eventually deprecate and remove `ga` (probably a few years off)

For now priority is low, but we'll soon get many requests.

**Comment by nikiforosk** [comment]
@sandykadam to follow up on this.

**Comment by nikiforosk** [comment]
@sandykadam please update this issue with the latest developments.

**Comment by sandykadam** [comment]
We need to include changes for this request in current sprint and test the component in one of the website, most of the testing is done by Ken and Ossama and so far looks good. Ken has given PR for this change request.

**Comment by nikiforosk** [comment]
As we just discussed in the scrum, these changes are now in latest:
https://latest.visual-framework.dev/components/vf-analytics-google/index.html

**Comment by sandykadam** [comment]
Hi @khawkins98 

We were testing GA on Covidportal local and did random tests, we could see the GA event getting logged in console. But on new GA4 dashboard we could not see events there. Can you please let us know if we missing any settings? We added the required custom definitions.

![Screenshot 2022-11-23 at 14 23 24](https://user-images.githubusercontent.com/1227241/203571313-50cc9112-2bc4-492c-925c-29171bfae7a4.png)

I was expecting something like this as we see in old version:

![Screenshot 2022-11-23 at 15 45 31](https://user-images.githubusercontent.com/1227241/203589496-fc507ad6-f204-451b-af93-27f6e4b3b1e6.png)

**Comment by khawkins98** [comment]
Hey Sandeep. I suspect you've not added the GA4 "custom definitions"; there's a mini guide in the readme:

![grafik](https://user-images.githubusercontent.com/928100/203610247-9ee1d673-b806-4715-a196-1c82dcec65ea.png)

https://latest.visual-framework.dev/components/vf-analytics-google/#usage

**Comment by khawkins98** [comment]
Missed at first that you had added the custom definitions. 

I've noticed in GA4 that it takes a lot longer to see the events. If the events are being logged on the 22nd, you won't be able to see them in the reports until the next day (or at least many hours later).

However, if you want to see if GA4 is correctly receiving the events there is a debug view (Configure -> Debug View).

To get this to work you need to get the browser to send the correct events -- the easiest way I've found is to use this extension in Chrome: https://chrome.google.com/webstore/detail/google-analytics-debugger/jnkmfdileelhofjcijamephohjechhna

![grafik](https://user-images.githubusercontent.com/928100/203611451-9177795b-cf7a-4cd8-8c93-c443643eab70.png)

**Comment by sandykadam** [comment]
Thanks @khawkins98 it is working fine, it is indeed very slow to update. We were able to see in debug & Real time view but  "Events" section still shows their inbuilt events but not the events which we created e.g "UI" or "External links". So wondering is it the way it will work or we still have to wait to have them appear in this section.

![Screenshot 2022-11-24 at 10 31 50](https://user-images.githubusercontent.com/1227241/203762292-5d652f29-4ac9-4363-baf5-a2f969a2428d.png)

**Comment by khawkins98** [comment]
That should be working .. judging by @pacope92's  commit, did it turn out that `vfGaIndicateLoaded()` was not being run?

**Comment by sandykadam** [comment]
Yay finally it is showing the events in GA portal.

![Screenshot 2022-11-24 at 14 10 27](https://user-images.githubusercontent.com/1227241/203804740-029dc9fa-a463-4fae-9ff7-5b5a7d4ee196.png)

Also changes these [G4 changes are released now](https://stable.visual-framework.dev/components/vf-analytics-google/), so we can close this ticket now. Will create new tickets if there is any issue reported by users.

Thanks a lot @khawkins98 @oss6 @pacope92 for working and testing this.
