### ISSUE TITLE
Bug: vf-content requires non-existant version of vf-form

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#1452]
Somehow vf-content wound up requiring `@visual-framework/form@^2.0.0` when an alpha of 2.0.0 is the latest.

https://github.com/visual-framework/vf-wp/pull/747/checks?check_run_id=2199452835

```
+ gulp@4.0.2
added 323 packages from 220 contributors in 11.382s
yarn install v1.22.10
[1/4] Resolving packages...
error Couldn't find package "@visual-framework/form@^2.0.0" required by "@visual-framework/vf-content@1.5.0" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: The operation was canceled.
```

This is causing updates to vf-content to fail.

**Comment by sturobson** [comment]
looks like Github doesn't recognise anything after the first 'closes' in a PR. Closing this 'the old way' - by pressing a button.
