### ISSUE TITLE
Display icon for external link/outgoing links

### ISSUE THREAD

**Issue by sandykadam** [visual-framework/vf-core#1507]
Are there any plans to implement icon next to links which are external?

![Screenshot 2021-04-27 at 22 17 28](https://user-images.githubusercontent.com/1227241/116314032-7f795580-a7a6-11eb-80e4-83fc7de164c9.png)

**Comment by stefangutnick** [comment]
We use this pattern on the COVID-19 portal here, in the cross-references column: 

https://www.covid19dataportal.org/sequences?crossReferencesOption=all&db=embl-covid19

In this case, I think it's a useful pattern as you may have spent time filtering/sorting the table and don't want to leave the site. But this is pretty much just assumptions and I have no evidence for this. 

Interestingly, it looks like Gov.uk is moving away from the icons, as they didn't find them to be widely understood, so just added ambiguity to their websites: 

https://designnotes.blog.gov.uk/2016/11/28/removing-the-external-link-icon-from-gov-uk/


So I'm not really sure if there is a definitive answer to this, we will just have to pick. I think I will continue to use it in contexts where it could prevent user error, but not where it's clearly an external link anyways.

**Comment by khawkins98** [comment]
I think we have a pair of questions here:

1. Is it helpful to users to visually distinguish external or outgoing links?
2. If so, is text or an icon better?
3. Bonus: if an icon is best, what do we use? Do we use the same icon for both external and outgoing?

Note: I'll add this to the VF-UX consultation agenda.

**Comment by sandykadam** [comment]
Yeh icon will be good and should be same for external or outgoing. @khawkins98 I'm curious to see what you mean by text?

**Comment by khawkins98** [comment]
> I'm curious to see what you mean by text

I can't remember where. But there was a group that evaluated the external icons and found they were poor and suggested something along the lines of: "Don't use an icon, and if you _really_ need to indicate an external or new window link it's best to use parentheticals"

Like:

- [I'm a link](#) (opens in a new tab)

**Comment by stefangutnick** [comment]
@khawkins98 

This is the article from Gov.uk that Niki shared earlier, which advocates for abandoning icons. 

https://designnotes.blog.gov.uk/2016/11/28/removing-the-external-link-icon-from-gov-uk/

I largely agree with the reasoning - the icons don't seem to be universally understood and don't necessarily add any value to users

**Comment by khawkins98** [comment]
Hey @sandykadam. We caught up about this at the VF-UX consultation today, here is the collective thinking: The UX research and thinking is dubious about the need and helpfulness of these icons. 

As such we don't think we'll implement this from a core VF perspective. However, if there's a spot where they really do seem needed, please do flag it and we can revisit the discussion.

**Comment by sandykadam** [comment]
Cool thanks for the update 👍

**Comment by khawkins98** [comment]
Closing this one, we can reopen/revisit as needed.

**Comment by khawkins98** [comment]
Saw this today where gov.uk spells out `(opens in a new tab)`

![image](https://user-images.githubusercontent.com/928100/122405343-424c6b00-cf80-11eb-9223-d66bdda191d8.png)
