### ISSUE TITLE
DOCS: Deprecation process

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#152]
1. [ ] What does it mean for pattern "deprecation" 
1. [ ] How to deprecate a pattern
1. [ ] Put that documentation somewhere

**Comment by khawkins98** [comment]
Draft text:

# Deprecating patterns

Inevitably, code will be replaced and improved and patterns will need to be marked as deprecated so:

1. Developers know to stop using the pattern; and
1. Aren't removed so existing sites continue to function

## How to deprecate

In the pattern folder:

1. In `pattern-name.config.yml` add:
     - `status: deprecated`
1. In `pattern-name.scss` wrapp the sass with:
    - `html:not(.vf-disable-deprecated) {`
1. Update `README.md` with:
    - why the pattern has been deprecated
    - what pattern(s) developers should instead use

## Need to deprecate just one variant in a pattern

The exact process by which to do this is still being decided, but for now:

1. Add a note to the `--variant.hbs`
1. Wrap the relevant css in `html:not(.vf-disable-deprecated) {`
1. Hide the variant tab in `.config.yml`:
```
variants:
  - name: deprecated-variant
    hidden: true
```

**Comment by khawkins98** [comment]
This documentation was added in #347. 

Still be good to have a gulp task for this, but that one's a bit lower priority. I don't think we'll forget about the need to automate, but @sturobson if you think we might, maybe make a seperate ticket and we can backlog?

Closing this.

**Comment by sturobson** [comment]
let's raise the ticket when we've got the time to work on it 😎
