### ISSUE TITLE
vf-card nunjucks template contains a potential error

### ISSUE THREAD

**Issue by nitinja** [visual-framework/vf-core#1523]
![image](https://user-images.githubusercontent.com/3931042/118501950-dbe8e880-b746-11eb-8eec-dd8f657353ed.png)

This template takes variable `modifiers` from content but uses as `modifier`

**Comment by khawkins98** [comment]
Thanks for the bug report, up for making a simple PR for this one?

**Comment by nitinja** [comment]
sure, will do
