### ISSUE TITLE
VF tree update

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1525]
Trying to summarise the discussion on the vf tree so far in order to create an issue:

Best practices to apply to the update of the VF tree (which could be basis for the documentation of this component):

1. Use downward arrow when closed (to open) and upward arrow when open (to close) as recommended by NN: https://www.nngroup.com/articles/accordion-icons/

2. Do not have icons and text labels do different actions (e.g. label linking to page, icon opening an accordion). This is also known as a "split button" and should be avoided according to the same NN article: https://www.nngroup.com/articles/accordion-icons/

Ideally, the top level element should be a grouping folder and not a link [as suggested by @khawkins98](https://github.com/visual-framework/vf-core/discussions/1498#discussioncomment-659909).

3. Increase text size from 14px to 16px and remove grey background for better readability.

4. Underline links on mouseover (based on the recommendations and design of navigation links in https://www.nngroup.com/articles/guidelines-for-visualizing-links/)

5. When it serves as a navigator (as is the case on the Training site), place it close to the page content [as suggested by @cindyebi](https://github.com/visual-framework/vf-core/discussions/1498#discussioncomment-648725) and shown in this mockup:
https://user-images.githubusercontent.com/75834903/115848835-35961580-a41c-11eb-8ed9-e4c28c063e7a.png 
 
The latest mockup of the Vf tree is this:
https://user-images.githubusercontent.com/75834903/116059297-97eb5200-a678-11eb-97ef-b82c44649967.png

The latest version of the online tutorial (with wrapped text and updated masthead) is in dev:
https://wwwdev.ebi.ac.uk/training/online/courses/functional-genomics-ii-common-technologies-and-data-analysis-methods/rna-sequencing/performing-a-rna-seq-experiment/laboratory-performance/ 

Comments:

1. [By Stu](https://github.com/visual-framework/vf-core/discussions/1498#discussioncomment-724373)

> The text becoming bold, having a background and being indented is a bit weird?
> I'm not sure creating a layout shift of the text is good.

I'm not sure why the label is indented in active state. Also, I'd start without the blue background (just use bold) and only add it if needed.

2. For the EBI Training site the top level element needs to be a link so we'll propose the behaviour  in the image below:

https://user-images.githubusercontent.com/928100/116085976-a7ca5c80-a69f-11eb-9467-55b195c203e1.png

3. In the future we could consider showing unvisited links in blue and visited links in purple as in https://stable.visual-framework.dev//components/vf-link/index.html 

This could be helpful for the navigator of the training site.

This is an example from NN: https://www.nngroup.com/articles/guidelines-for-visualizing-links/

![Screenshot 2021-05-12 at 16 26 36](https://user-images.githubusercontent.com/20280139/118002609-b1aabb80-b33f-11eb-9402-4c6f943951ad.png)

_Originally posted by @nikiforosk in https://github.com/visual-framework/vf-core/discussions/1498#discussioncomment-729796_

**Comment by khawkins98** [comment]
Link to the discussion: https://github.com/visual-framework/vf-core/discussions/1498

**Comment by khawkins98** [comment]
An alpha has been shipped for this https://stable.visual-framework.dev/components/vf-tree/

I'm not fully up to speed on what work still needs to be done. I think the biggest is addressing the split button?

**Comment by nikiforosk** [comment]
Prakash added a comment about an issue with the first arrow to the development thread:

https://github.com/visual-framework/vf-core/pull/1534#issuecomment-851988780

Regarding other work to be done, we'd probably want to have a default version without the split button and without links at the top level (although for the Training the latter is necessary and the split button seems to be less of an issue with the current implementation, in which the whitespace also acts as a link like the label next to it). 

I think that it will also be useful to show unvisited links in blue and visited links in purple as we do with [other textual links](https://stable.visual-framework.dev//components/vf-link/index.html). [The Topics in the sidebar of NN](https://user-images.githubusercontent.com/20280139/118002609-b1aabb80-b33f-11eb-9402-4c6f943951ad.png) is an example of that.

**Comment by nikiforosk** [comment]
Vf-tree has been gone live for over a year now in the online tutorials of the training site. It seems to work well and we haven't had any issues from the Training team, participants in feedback sessions or other feedback by learners.

I mentioned above that it will also be useful to show unvisited links in blue and visited links in purple as we do with [other textual links](https://stable.visual-framework.dev//components/vf-link/index.html). [The Topics in the sidebar of NN](https://user-images.githubusercontent.com/20280139/118002609-b1aabb80-b33f-11eb-9402-4c6f943951ad.png) is an example of that.

**Comment by nikiforosk** [comment]
I mentioned above that it will also be useful to show unvisited links in blue and visited links in purple as we do with [other textual links](https://stable.visual-framework.dev//components/vf-link/index.html). [The Topics in the sidebar of NN](https://user-images.githubusercontent.com/20280139/118002609-b1aabb80-b33f-11eb-9402-4c6f943951ad.png) is an example of that.

However, most other issues mentioned in this ticket have been addressed and  [vf-tree](https://stable.visual-framework.dev/components/vf-tree/) has been gone live for over a year now in [the online tutorials of the training site](https://www.ebi.ac.uk/training/online/courses/biocuration-collection/what-is-biocuration/). 

It seems to work well and we haven't had any issues from the Training team, participants in feedback sessions or other feedback by learners. So I'm closing this ticket.
