### ISSUE TITLE
Hint text on search box remains when cursor is placed on the box

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1580]
The hint text on the search box of the vf-search component remains in place when the cursor is placed on the box. It disappears after you type the first character of the keyword. See e.g. the search box in https://www.embl.org/search/

In other sites such as [gov.uk](https://www.gov.uk/) or even google (if you open a new tab in Chrome) the hint text disappears when the cursor is placed on the box. Should we adopt the same behaviour?

**Comment by nitinja** [comment]
It's possible using this code https://stackoverflow.com/a/12250084/741251, should we choose to implement

**Comment by khawkins98** [comment]
Is there a consensus that:

1. This hiding placeholder text on focus is the best choice?
2. We should implement it?

If so, it should be a fairly easy change.

**Comment by khawkins98** [comment]
@nikiforosk are you still interested in this change? If not, I'll close the issue to make the backlog more concise. You could always reopen in  the future.

**Comment by nikiforosk** [comment]
I think it will be a small improvement but I understand if there are more urgent things to do at the moment.

**Comment by nikiforosk** [comment]
We haven't observed or received any negative feedback on this issue so I'm closing it.
