### ISSUE TITLE
Figure caption: use darker text, larger size and normal type (not italics)

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1582]
We received the following feedback from the training team:

> The figure legends are now in light grey italics which are quite hard to read. Can we make the grey darker and make sure it is not in italics?

An example of this is on this page*:
https://wwwdev.ebi.ac.uk/training/online/courses/bioinformatics-terrified/what-makes-a-good-bioinformatics-database/controlled-vocabularies/taxonomy/

The default specification for the `figcaption` text [in 'vf-figure'](https://stable.visual-framework.dev//components/vf-figure/) is 14px, #707372 colour and italics. 

Although this is doesn't fail [the WAVE accessibility test](https://wave.webaim.org/report#/https://wwwdev.ebi.ac.uk/training/online/courses/bioinformatics-terrified/what-makes-a-good-bioinformatics-database/controlled-vocabularies/taxonomy/) it does contradict several other guidance that we use for VF and general recommendations about text:

- 14px is the smallest acceptable font size in the VF. This should be normally reserved for text that is not important. In scientific writing (particularly in our online courses, and presumably also in scientific news articles) Figure captions convey important text. Readers sometimes skip the main text and just read the captions.

- The recommended secondary colour for text in the VF is #373A36 (which is slightly darker than #707372).

- The text should be normal and not italics. Using italics (as well as underlying words and writing in capitals) [is not recommended](https://accessibility.blog.gov.uk/2016/09/02/dos-and-donts-on-designing-for-accessibility/).

Therefore I suggest:

- Increase the font size of the caption to 19px (or at least 16px).

- Change the colour of the caption text to #373A36 (the VF secondary colour).

- Use normal type instead of italics.

Notice that positioning the text under the figure and within the 'vf-figure' component should be enough for sighted readers and assistive technologies to identify it as a caption so extra stylistic variations aren't really necessary.

*Note that the figure on [the example page of the online tutorial](https://wwwdev.ebi.ac.uk/training/online/courses/bioinformatics-terrified/what-makes-a-good-bioinformatics-database/controlled-vocabularies/taxonomy/) isn't centered aligned and the legend doesn't span across the width of the page (I believe that Prakash has gotten in touch about this independently).

**Comment by cindyebi** [comment]
The rationale for the secondary VF text color in #373A36 is because we want to limit the usage of black text on a white background since high contrast text can cause problems to users who have sensitive eyes:

https://dm-ed.com/info/contrast-sensitivity/

https://uxmovement.com/content/why-you-should-never-use-pure-black-for-text-or-backgrounds/#:~:text=High%20color%20contrast%20is%20useful,safe%20for%20the%20user's%20eyes.

**Comment by nikiforosk** [comment]
I agree with @cindyebi that #373A36 could be better than pure black for the main text but this look like a topic for another discussion. 

The issue that I'd like to raise here is that the caption text is suboptimal so would like to recommend the following changes (repeated from above):

- Increase the font size of the caption to 19px (or at least 16px).

- Change the colour of the caption text to #373A36 (the VF secondary colour).

- Use normal type instead of italics.

**Comment by khawkins98** [comment]
We'll need to split the work on integrating the typography colours into a more foundational bit of code. However the major vf-figure issues we can start to address here. 

A fairly straightforward fix is to:

- 16px
- no italic
- darker grey (making this the vf secondary text colour once available in code)

Here's what that looks like (not the improved colour contrast)

![image](https://user-images.githubusercontent.com/928100/121863552-45cfc000-ccfc-11eb-90af-339152d9e6ef.png)

Current 

![image](https://user-images.githubusercontent.com/928100/121863641-5aac5380-ccfc-11eb-8b77-64915e72b2e8.png)

## Notes:

We'll want to be sure that this text is obviously attached to the image and not the flow of the body text. The above changes (staged in #1586) seem to preserve that:

![image](https://user-images.githubusercontent.com/928100/121863811-83344d80-ccfc-11eb-9cc8-7f2944482091.png)

There is some other (more technical) figure treatment discussion at #1583

**Comment by khawkins98** [comment]
New issue for the functional colours: https://github.com/visual-framework/vf-core/issues/1587
