### ISSUE TITLE
Tokens: bring in functional colours, deprecate theming, grey body text

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#1587]
With the ongoing design work to the VF by @cindyebi, we're:

- [x] Moving away from theming: https://stable.visual-framework.dev/design-tokens/theming/
- [x] Adding "functional" colours: https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?node-id=0%3A1
- [ ] Swapping a black `#000` body text for a more accessible off-black

We should:

- [x] Deprecate [theme.palette.alias.yml](https://github.com/visual-framework/vf-core/blob/develop/components/vf-design-tokens/src/theme.palette.alias.yml)
- [x] Create functional.palette.alias.yml and add the corresponding colours:

![image](https://user-images.githubusercontent.com/928100/121878914-89cac100-cd0c-11eb-81e0-3b53f5e3e919.png)

**Comment by khawkins98** [comment]
Also: 

- add some notes on when to use which functional colour
  - solid black to only be used for small text (less than 14px)
- @cindyebi to swap the secondary and primary typography colours

**Comment by cindyebi** [comment]
Done swapping the typography colour labels on Figma @khawkins98

**Comment by khawkins98** [comment]
Partly addressed (and much conversation) in #1597.

---

Copying some of @nikiforosk comments from Slack here:

> I haven't been able to find out why gov.uk ended up using #0B0C0C for text instead of some other shading of black (or dark grey) but this article suggests they've been using it since 2012: https://designnotes.blog.gov.uk/2019/07/29/weve-updated-the-gov-uk-colours-and-font/
> 
> Especially given that we don't have black defined in the EMBL colours so it doesn't really contradict our design system per se: https://wwwdev.embl.org/guidelines/design/page/design-guidelines/colours/
>
> My concern about #373A36 is that it was originally introduced as a secondary neutral colour but not specifically for text, and as you mentioned in github various other sites (which have hopefully explored this already) use darker tints.

--- 

I caught up with @cindyebi based on the above conversation and others and we have a planned way forward:

1. @cindyebi to pick an "almost black" that is near the gov.uk black (but not the same as to not encroach on their identity) and is also, perhaps, a touch warm like the other embl neutral colours
2. we'll use this new black in place of the current `neutral 900` (as embl does not specify an absolute black) as the new secondary text colour
3. we'll feed this into dev code for the VF to test out which text should be grey (primary) and near-black (secondary). Most likely we'll keep the body text (19px) as secondary (black) and headers at or below 24px as secondary. 

More testing, discussion and a new PR to come.
