### ISSUE TITLE
PATTERN - Data Protection Banner

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#16]
We need to create/replicate the GDPR data protection banner for use across all EMBL sites.

Currently the pattern can [be found here](https://www.ebi.ac.uk/style-lab/websites/patterns/banner-data-protection.html).

the existing pattern uses data attributes for the recreating the content using the CSS `content` selector.

This does not get read by screen readers (VO on MacOS tested), so we need to use 'actual content' moving forward. I don't see this as a problem? A WP plugin(?) could be created for just this thing? For example.

Also from an accessibility (a11y) viewpoint it needs to be near the top of the DOM on page load, so this is something we would need to add to documentation for people who would be implementing this.

**Comment by sturobson** [comment]
Ah, wait a minute -- I'm making use of `content` in CSS to put the `data-message` in place.

Are you saying/thinking that we get JS to inject it where it needs to be? 

(Yes, I've not looked to deeply at the current implementation, and when straight to `content`).

**Comment by sturobson** [comment]
![screenshot 2018-11-08 at 10 57 32](https://user-images.githubusercontent.com/925197/48194524-3074a700-e345-11e8-8c2d-00cf0f88d232.png)

**Comment by sturobson** [comment]
1. do inline links in text that has a background colour stick with the blue or match the text colour and make use of the underline to denote a link?
2. is this a good place to use the green/blue CTA?
3. Is the dark gray better than the black?

(note: that width of text has been increased to a max-width of 60em, so it doesn't look too far away from the button (unless you're on a massive monitor).
4. Should the text just run up to the button regardless of monitor size?
5. Would it be better to have a 'floating' notice that has a max-width so the text is editable?

**Comment by khawkins98** [comment]
Had a look at this, I think it's good and plenty for now (any design comments from Mark aside). I'll make a new issue to write out some user stories around what the banner needs to do (some of these are special to our fragmented developer scenario).

**Comment by khawkins98** [comment]
There's a couple little rough things here I'll make a PR for:
- Banner is `absolute` and not `fixed`
- Banner content area spills out to the whole screen

I think we can also leverage `vf-body` and `vf-grid` for some reusability. 

Currently:

![image](https://user-images.githubusercontent.com/928100/48254557-a42cb780-e40a-11e8-8167-82dc751a6c37.png)



Updated:

![image](https://user-images.githubusercontent.com/928100/48254362-249ee880-e40a-11e8-94f0-1e88aa1dde9f.png)
