### ISSUE TITLE
Box component has low contrast 

### ISSUE THREAD

**Issue by stefangutnick** [visual-framework/vf-core#1619]
[vf-box ](https://stable.visual-framework.dev/components/vf-box/)has low contrast in several of the configurations. Seems due to using black rather than #fff

![Screenshot 2021-07-08 at 10 50 59 am](https://user-images.githubusercontent.com/82038328/124906698-41d34d00-dfdf-11eb-98c6-790cd1cc637d.png)

**Comment by khawkins98** [comment]
Thanks for this. It's a bug after introducing the off-black for text. Fix is pending at https://github.com/visual-framework/vf-core/pull/1620
