### ISSUE TITLE
Navigation: global navigation

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#1621]
- How can we make best use of the vf-global-navigation?
- Is it's scope hierarchal, lateral or both?
- How might we handle EBI's "black bar"?
    -  Considerations for legacy VF 1.x sites?
- Mobile functionality?

a/c

- [ ] mockups
- [ ] user journeys
- [ ] summary slides for stakeholders
- [ ] action plan

**Comment by nitinja** [comment]
Is this the tracking issue for Megamenu? think so.

**Comment by khawkins98** [comment]
Hey @nitinja it  also relates to #1622. 

I think it may be best to just make a new issue — I'll do that now and cross-link to this one.
