### ISSUE TITLE
Navigation: in-page navigation

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#1623]
How can we better facilitate linking within pages? Currently the `vf-links-list` does not scale well:

https://www.embl.org/sites/hamburg/
![image](https://user-images.githubusercontent.com/928100/125067240-46b60080-e0b4-11eb-8a59-b015c7049f9e.png)

Vertical and sticky menus may be an option
- https://www.covid19dataportal.org/submit-data
- https://experienceleague.adobe.com/docs/experience-manager-core-components/using/components/navigation.html?lang=en
- https://www.audi.de/de/brand/de/beratung-kauf/geschaeftskunden.html
  - https://www.audi.com/ci/en/guides/user-interface/components/navigation.html

It could be made horizontal and sticky, but risks being conflated with page-to-page vf-navigation.

a/c

- [ ] mockups
- [ ] user journeys
- [ ] summary slides for stakeholders
- [ ] action plan

**Comment by sturobson** [comment]
Ahoy hoy! 

Just popping up to mention that I was planning on integrating `vf-cluster` as part of the 'on this page' navigation so that it doesn't rely on the 3 column grid and makes use of space where available. 

Spilios had made use of this somewhere by changing some classes here and there (from a copy/paste snippet I provided). 

That would at least - make better use of the space for text nodes to wrap as the space shrinks or get larger. 

aside - if the page is long enough that you have lots of 'on this page' links -- is the page _too_ long‽

**Comment by khawkins98** [comment]
👋  hey Stu!

**Comment by khawkins98** [comment]
We're testing a prototype evolution of the on-this-page navigation (perhaps to become `vf-navigation--on-page` as `vf-links-list` is probable to be deprecated #1649). 

![image](https://user-images.githubusercontent.com/928100/132357685-0b660400-84c1-4bcf-aac8-b659f98f7370.png)

https://www.embl.org/directory/

Stylistically this has some concerns due to the potential confusion with `vf-tabs` however we're hoping to get some real-world insights into usage (or lack of).

**Comment by khawkins98** [comment]
It's been a month and I had a quick look at the metrics. 

The "on this page" does draw a number of clicks (about 10%). Most clicked were "About EMBL" "Sites" and "Find", which makes sense as:

- "Research" is already at the top 
- "Services" and "Training" are already heavily linked from across EMBL.org

So it does seem that users use it — as for satisfaction I can only say there have been no complaints and requests to use it. 

Seems it's worth further investigation/refinement as a `vf-navigation--on-page` (or similar)

**Comment by khawkins98** [comment]
(The /directory page itself is the 35th most popular page for EMBL.org)

**Comment by cindyebi** [comment]
I have some visual styling suggestions for this coming up next week :)

**Comment by khawkins98** [comment]
@cindyebi did you get to spend any time making visuals for this? 

Spilios was asking me about it the other day.

**Comment by cindyebi** [comment]
@khawkins98 I think visually this in-page navigation component can be made similar to the vf-tabs as they have similar attributes:
<img width="1539" alt="Screenshot 2021-10-22 at 13 51 43" src="https://user-images.githubusercontent.com/75834903/138456788-dce2ae32-d0f1-4e39-b8f6-0bcbb90e647a.png">

[Carbon Design](http://carbon-for-ibm-dotcom.mybluemix.net/patterns/in-page-navigation/) categorises this as a "_Jump to section_" component variant.

**Comment by khawkins98** [comment]
The worry/question is: "will making in-page navigation look like tabs confuse users?"

Part of me thinks yes, but part of me thinks "no, tabs and navigation serve similar roles in that they change the page content"

perhaps we need to:

1. Make it
2. Test it

**Comment by cindyebi** [comment]
Perhaps to differentiate it from the vf-tabs, we could add the "**On this page**" text label to the left of the navigation menus, listed as one of the component's _mandatory_ attributes. @khawkins98
