### ISSUE TITLE
Documentation for creating hero images for new VF2 sites

### ISSUE THREAD

**Issue by sandykadam** [visual-framework/vf-core#1641]
As some of the teams started using new VF2 structure using HTML or WordPress sites, they finding it difficult to understand what should be the correct hero banner image size/dimensions. So can we please have some documentation around creation of graphics for hero images. Information like safe area, with text, without text, graphic alignment etc.

https://stable.visual-framework.dev/components/vf-hero/index.html?q=hero

Following is example of how Amazon store give guideline on how to use hero image on store.

![Screenshot 2021-08-04 at 12 47 48](https://user-images.githubusercontent.com/1227241/128176021-2d20e278-b1ea-4870-b0fd-47a37eb028b6.png)

**Comment by khawkins98** [comment]
Thanks for this issue. We currently have some limited guidance:

> The default variant is equivalent to vf-hero--1200 and the recommended image size is 3000 by 1000 pixels.

However we can expand on this with some further points ... draft text:

```md

### Hero background images

You can bring your own image to use with the vf-hero. 

- Size: recommended is 3000 by 1000 pixels.
- Positioning: people and other important imagery should be placed on the right side. The image will, by default, vertically centre and align to the right side.
- Imagery: most of the image should be abstract as to not visually compete with the text in the hero box.
- Text: do not use raster text as part of the image.
- Consult design: the image should be made in consultation with your organisation's design team for brand alignment and input on how best to create it.

```





```
