### ISSUE TITLE
Accesibility: vf-card--striped fails contrast test

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1657]
This is about contrast between the white subheader and the light green background in the stripped heading:
https://stable.visual-framework.dev/components/vf-card/#vf-card--striped-only-headings

I tried a couple of tools but all of them report that the contrast of 3.77 is not sufficient. It should be at least 4.5:1 for text of this size.

Inspect contrast tool:
![Screenshot 2021-09-06 at 11 24 15](https://user-images.githubusercontent.com/20280139/132670843-8ce2eb4f-a02d-4cf4-9eb9-142c8eb960ee.png)

WAVE contrast checker:
https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=18974C

WAVE test on actual pages:
https://wave.webaim.org/report#/https://wwwdev.ebi.ac.uk/sample/about/our-impact
![Screenshot 2021-09-06 at 11 27 52](https://user-images.githubusercontent.com/20280139/132670932-3e7d93cd-8a86-4109-abfb-2c528c6dc541.png)

https://stable.visual-framework.dev/components/vf-card/#vf-card--striped-only-headings
![Screenshot 2021-09-06 at 11 29 00](https://user-images.githubusercontent.com/20280139/132670965-6e7cd2d4-8bde-4332-a2bc-8a9b1afdfceb.png)

Note from @khawkins98: 
It seems to me the subheading was placed in the wrong “region” and mainly considered in the non-striped variant (white background). Here’s how I believe it should have been done:

@khawkins98 Can you please add your screenshot here from [the VF clinic google document](https://docs.google.com/document/d/1200GecXZZbIzHJ3HQ2ygY5NIYwQDyRVhfP21iscP7Y8/edit?usp=sharing)?

**Comment by khawkins98** [comment]
👍 

Here's that screenshot on how I believe it should (and must) appear:

![image](https://user-images.githubusercontent.com/928100/132813740-6ed3002e-ea6a-4e9a-8c5f-054a4e3d9872.png)

@cindyebi any concerns on this?

**Comment by nikiforosk** [comment]
> 👍
> 
> Here's that screenshot on how I believe it should (and must) appear:
> 
> ![image](https://user-images.githubusercontent.com/928100/132813740-6ed3002e-ea6a-4e9a-8c5f-054a4e3d9872.png)
> 
> @cindyebi any concerns on this?

Thanks @khawkins98!

We need to make sure that it passes the WAVE test now. It looks like it does (albeit not for normal text at AAA level) just by testing the colours but it will be good to test the card itself in context too:
https://webaim.org/resources/contrastchecker/?fcolor=FFFFFF&bcolor=007b53

It also looks like this change will push the subtext a bit closer to the main text in the bordered card:
https://stable.visual-framework.dev/components/vf-card/#vf-card--bordered

This is probably not very disruptive but it's so worth keeping an eye on it too (again by looking at the pages that use this component).

**Comment by cindyebi** [comment]
Thank you @khawkins98 it seems like it's more of an implementation issue rather than contrast issue. I believe it is in accordance with the AA standard, and as we discussed in one of the VF Clinic awhile ago, we are not going to accommodate the AAA standard at the moment but possibly in the future.

**Comment by khawkins98** [comment]
@cindyebi the current implementation fails the AA standard. maybe easiest to chat about this at the VF meeting today.

**Comment by khawkins98** [comment]
Adding a side-by-side screenshot 

![image](https://user-images.githubusercontent.com/928100/132833740-48ba42a9-ee51-485c-9395-86a46ed01860.png)

**Comment by khawkins98** [comment]
Also worth noting that the subheading is not currently used for most implementations of the card.

**Comment by cindyebi** [comment]
I just updated the Figma component variant:

![Screenshot 2021-09-22 at 14 02 35](https://user-images.githubusercontent.com/75834903/134348430-bb09dbe2-aa58-4a16-bb2a-d71cf5960ffe.png)
