### ISSUE TITLE
Accesibility: vf-summary__date should not be all caps

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1673]
This came up in the context of the current Industry redesign sprint but is probably relevant to other projects too.

The stakeholders suggested that vf-summary__date should be presented in sentence case (instead of small caps) and we think that this will probably improve the readability of the dates. Days of the week and months should remain capitalised (e.g. "Monday 03 June", etc).

I noticed that the text size is 14px and thought that it may be helpful to increase it to 16px. 

I'm also tagging @cindyebi as we may need advice from her too.

**Comment by sandykadam** [comment]
Can we have some approx delivery date for this, so I can inform the Industry team.

**Comment by cindyebi** [comment]
@nikiforosk I need to understand what the actual problem is because it's not very clear. Could you please rephrase the problem so we could think of possible solutions? I think changing it to be not all caps is one solution, but there are other ways to make these accessible: increase the size, change the colour, etc., but we need to understand the actual problem first.

**Comment by khawkins98** [comment]
@nikiforosk @sandykadam is there clarity if we still need this? 

If so I can get it ready today/tomorrow. 

It would look like:

![image](https://user-images.githubusercontent.com/928100/145020883-a0d7c9e7-5de2-4cd5-a40d-d01a1acb3a04.png)

**Comment by khawkins98** [comment]
@nikiforosk as long as we're on the topic, is there clarity from an accessibility perspective if cardinal or ordinal dates are better; that is:

- `4th September 2021`
- `4 September 2021`

The first example seems odd.

**Comment by sandykadam** [comment]
Yeah the main issue was, date display is in capital letters, if we can make it small letter that should be great. Or we can have one extra class to make it caps if there is need on any other projects.

Below is the industry page where this discussion started. Accessible in VPN https://wwwdev.ebi.ac.uk/industry/private/members-area/

![Screenshot 2021-12-07 at 11 29 37](https://user-images.githubusercontent.com/1227241/145021665-59f46940-9ea1-439c-a054-f2502ece0ae2.png)

**Comment by nikiforosk** [comment]
> @nikiforosk as long as we're on the topic, is there clarity from an accessibility perspective if cardinal or ordinal dates are better; that is:
> 
> * `4th September 2021`
> * `4 September 2021`
> 
> The first example seems odd.

I'm not aware of any accessibility-related guidance for this but gov.uk seems to suggest using "4 September" instead of "4th September": https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#dates

**Comment by nikiforosk** [comment]
> Yeah the main issue was, date display is in capital letters, if we can make it small letter that should be great. Or we can have one extra class to make it caps if there is need on any other projects.
> 
> Below is the industry page where this discussion started. Accessible in VPN https://wwwdev.ebi.ac.uk/industry/private/members-area/
> 
> ![Screenshot 2021-12-07 at 11 29 37](https://user-images.githubusercontent.com/1227241/145021665-59f46940-9ea1-439c-a054-f2502ece0ae2.png)

@khawkins98 Also please notice that in the screenshot above the date appears below the title and there is no other additional information to describe the event. 

I suspect they'd like to keep that order and simply change the day and month into Sentence case (i.e. "Monday 6 June to Tuesday 7 June 2022").

**Comment by khawkins98** [comment]
Thanks, both, I'll proceed with these as I think they're fairly logical and non-disruptive changes. 

PR to follow for review.
