### ISSUE TITLE
Accessibility: Hyperlinked section headers don’t count as h2 headings in WAVE tests

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1683]
See e.g. “Our COVID-19” response vs “Our achievements” in the new impact page:
https://wave.webaim.org/report#/https://wwwdev.ebi.ac.uk/sample/about/our-impact

This causes “skipped header” alerts when authors add subsections within a hyperlinked section header.

![section-header-no-h2-Screenshot 2021-09-06 at 11 10 55](https://user-images.githubusercontent.com/20280139/135108970-ce36e98b-8a3c-402b-904c-e3e5540f5c43.png)

**Comment by khawkins98** [comment]
@nikiforosk thank you for making this issue. It should be resolved in #1685 

In the following days it will be released to npm and made available to various integrating projects (like the Microsites)
