### ISSUE TITLE
Bookmark component's label isn't aligned centre vertically

### ISSUE THREAD

**Issue by cindyebi** [visual-framework/vf-core#1687]
@khawkins98 Bookmark component's label isn't aligned centre vertically on Google Chrome:

<img width="482" alt="Screenshot 2021-10-01 at 11 45 39" src="https://user-images.githubusercontent.com/75834903/135607550-8cfb1a0f-3c0f-4831-81d9-de397cb13883.png">

Secondly, it would be great to know how the Inline variant behaves before being clicked (currently there's only the "after" state on the site):
<img width="299" alt="Screenshot 2021-10-01 at 11 46 08" src="https://user-images.githubusercontent.com/75834903/135607605-70b3319b-79ac-40de-b00b-ad6e8983b865.png">

**Comment by khawkins98** [comment]
This is an issue with  FF vs Chrome's vertical spacing. We dealt with something similar in vf-section-header:

https://github.com/visual-framework/vf-core/blob/5384ab31a5f48656ee87cdf3353e4d096df3f0f2/components/vf-section-header/vf-section-header.scss#L30
