### ISSUE TITLE
Create a standardise interactive color token

### ISSUE THREAD

**Issue by cindyebi** [visual-framework/vf-core#1688]
@khawkins98 As per the last VF Clinic discussion, we want to standardise the interactive color token for all components. Currently we have yellow and different shades of blue as our interactive color(s):

![Screenshot 2021-09-28 at 14 55 01](https://user-images.githubusercontent.com/75834903/135646628-977bb48c-89f0-4a49-a84b-8b657f9061fe.png)

![Screenshot 2021-09-28 at 14 49 13](https://user-images.githubusercontent.com/75834903/135646648-de64d7e6-afb5-46ed-992b-0e19293bc74d.png)

<img width="1229" alt="Screenshot 2021-10-01 at 16 28 18" src="https://user-images.githubusercontent.com/75834903/135646754-54d919b9-9dfb-42b2-8f8d-a0883a1ffed4.png">

<img width="222" alt="Screenshot 2021-10-01 at 16 29 52" src="https://user-images.githubusercontent.com/75834903/135646970-51a52ed9-eb79-4e74-bd57-1a311a6eae2b.png">

Actions:
• add the blue #50 (#D1E3F6) as “interactive hover colour” (name subjective to improvement)
• update table select colour (search and dropdown as well)
• table hover row switch to a slightly darker grey

**Comment by khawkins98** [comment]
Thanks @cindyebi

I'll make this new token and update the components. I'll also make a screen recording of how that is done for @nitinja and any other future persons needing to know about token integration in the VF
