### ISSUE TITLE
Issue with geolocation component when used twice on one page

### ISSUE THREAD

**Issue by kasprzyk-sz** [visual-framework/vf-core#1694]
The geolocation component is used twice (two sets of tabs) on https://www.embl.org/internal-information/

First case: `vf-tabs` in Quick links section

https://github.com/visual-framework/vf-wp/blob/master/wp-content/themes/vf-wp-intranet/partials/popular-container.php

Second case: `vf-tabs` in Community blog section

https://github.com/visual-framework/vf-wp/blob/master/wp-content/themes/vf-wp-intranet/partials/community-blog-container.php

When you open/refresh https://www.embl.org/internal-information/ a browser shows the middle of the page (community-blog)
![Screenshot 2021-10-12 at 12 25 55](https://user-images.githubusercontent.com/54020899/136939288-49929cf5-1e17-447e-84aa-e99a30b75540.png)

**Comment by khawkins98** [comment]
This doesn't occur in FF, but does happen in Chrome (and I suppose other webkit browsers). It's the engine trying to be clever by scrolling to the "clicked" content. 

https://github.com/visual-framework/vf-core/blob/558ace3e5cc8dad97c687c5c44f52e2df8b85f91/components/vf-location-nearest/vf-location-nearest.js#L247-L249

There are two possible workarounds that could be tried:

## Easy

`e.preventDefault();` 

we need  to be sure it doesn't stop vfTabs from functioning

## Aggressive

Preserve the current position to override scroll, like

```js
function disableScrolling(){
    var x=window.scrollX;
    var y=window.scrollY;
    window.onscroll=function(){window.scrollTo(x, y);};
}

function enableScrolling(){
    window.onscroll=function(){};
}
```

I'll try some on my local.
