### ISSUE TITLE
Should we change the components folder to modules

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#170]
With more 'things' being put into the `components` folder of `vf-core` that are not really 'components' in the visual sense - should we move to change the folder name?

Originally lerna.js calls the folder `packages` as it's going on NPM (getting) … 

I think `modules` might work?

Adding this issue today whilst opening #169 in my browser.

---

I've also ideas about what we should / could do with EMBL specific patterns/code in the vf-core UI

**Comment by khawkins98** [comment]
So, currently:

```
.
├── components
│   ├── _previews
│   ├── vf-core
│   ├── vf-core-patterns -> ../node_modules/@visual-framework
│   ├── vf-design-tokens
│   ├── vf-logo
│   ├── vf-masthead
│   ├── vf-pattern-1-2-3
│   ├── vf-sass-config
│   └── vf-sass-utilities
├── LCOAL CONFIG STUFF
└── tools
    ├── component-generator
    ├── css-generator
    └── frctl-mandelbrot-vf-subtheme
```

What if we (riffing off you suggestion):

```
.
├── modules
│   ├── _previews
│   ├── vf-core
│   │   ├── component-generator
│   │   ├── css-generator
│   │   ├── vf-design-tokens
│   │   ├── vf-sass-config
│   │   └── vf-sass-utilities
│   ├── vf-core-patterns -> ../node_modules/@visual-framework
│   ├── vf-logo
│   ├── vf-masthead
│   └── vf-pattern-1-2-3
├── LCOAL CONFIG STUFF
└── vf-pattern-library-theme
```

To summarise:
1. Call the folder `modules`
2. Put all the core logic/variable/mixin/tooling stuff under `vf-core`
    - Makes it a little clearer that the stuff in `vf-core` is used in a lot of places
    - If you're using a child framework it makes it a little easier to update by replacing the stuff in `vf-core`
3. Maybe `vf-design-tokens` should go directly under `/modules`

**Comment by khawkins98** [comment]
Added to backlog.
