### ISSUE TITLE
Tabs: add a possibility to link to a particular tab

### ISSUE THREAD

**Issue by kasprzyk-sz** [visual-framework/vf-core#1700]
Example: 

I'd like to link directly to the Password management tab on: 

https://www.embl.org/internal-information/it-services/embl-user-accounts-heidelberg/

Each tab has it's unique ID but adding it as an anchor to the URL, opens the first tab anyway.

![Screenshot 2021-10-22 at 10 40 17](https://user-images.githubusercontent.com/54020899/138422720-8fe7cc9e-839d-4560-bfba-c854e11550a6.png)

https://www.embl.org/internal-information/it-services/embl-user-accounts-heidelberg/#vf-tabs__section-73a123e3-b312-425a-aeb7-9d3e38c5f693

**Comment by khawkins98** [comment]
This should be a fairly straightforward bit of JS to look for a `#vf-tabs__section` in the URL on pageload.

**Comment by khawkins98** [comment]
Implemented in #1708

https://stable.visual-framework.dev/components/vf-tabs/
