### ISSUE TITLE
Autogenerated Banners needs GA tracking region

### ISSUE THREAD

**Issue by nitinja** [visual-framework/vf-core#1751]
Banners that are autogenerated using `embl-notifications` component, needs a GA tracking region. Can be made configurable in future updates.

**Comment by nikiforosk** [comment]
@nitinja Can you please explain this in more detail? 

Also who will be able to follow up on this?

**Comment by nitinja** [comment]
the component "embl-notifications" can be used to insert new banners on page like this one 
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/3931042/177169765-f65d26b3-ceb6-43dd-9963-a945791dba66.png">
These inserted banners do not have google analytics tags on them. Those tags are required to precisely target and track clicks on those banners to answer questions like "how many people bothered to actually click this thing?"
We have to add this mechanism. cc @nikiforosk

**Comment by nikiforosk** [comment]
Thanks @nitinja!

I'm adding a link to the component: https://stable.visual-framework.dev/components/embl-notifications/

@MGS-sails worked on notifications recently so hopefully we will be able to follow up. Please co-ordinate any additional knowledge transfer that might be required.

#1428 is also about GA tracking.

**Comment by sandykadam** [comment]
@nikiforosk this is good to have option. This ticket was just to have GA region/label around banner code. Region is nothing but a name under which that event will be tracked and easy to find in GA interface. This change will be common across any project.

By default GA is tracking all links of the pages, so if there is banner and if it has a link it will automatically get tracked in GA.
