### ISSUE TITLE
Make the vf-dropdown component accessible using the tab button

### ISSUE THREAD

**Issue by MGS-sails** [visual-framework/vf-core#1754]
For accessibility reasons, the vf-dropdown component should work when a user tabs over it and presses the enter button.

**Comment by nikiforosk** [comment]
More specifically you should be able to access [vf-dropdown](https://stable.visual-framework.dev/components/vf-dropdown/) by pressing the tab key (like other links and buttons on a page), access the menu options with the arrows and expand it with enter (optionally) as mentioned in [the keyboard testing guide](https://webaim.org/techniques/keyboard/#testing):
 
![Screenshot 2022-02-01 at 10 36 52](https://user-images.githubusercontent.com/20280139/151954449-6a2b5d16-6881-4eb8-bceb-407edb89da87.png)

This component appears in a couple of pages at the moment (both require login):
- My learning: https://wwwdev.ebi.ac.uk/training/user 
- Online tutorial: https://wwwdev.ebi.ac.uk/training/online/courses/bioinformatics-terrified

**Comment by nikiforosk** [comment]
Add ARIA labels and tab indexing 

@pacope92 Add the link to your prototype here

**Comment by nikiforosk** [comment]
@pacope92 I tried this in latest and I can now access the dropdown with the keyboard (which wasn't possible before):

https://latest.visual-framework.dev/components/vf-dropdown/

I can also move through the menu items with the up/down arrow as suggested in the guide above. However, I noticed that the links within the similar menu in gov.uk are accessed via the tab (which is also [how it is on stable](https://stable.visual-framework.dev/components/vf-dropdown/)): https://www.gov.uk/

**Comment by nikiforosk** [comment]
@pacope92 I looked into this a bit more and found the following example:

**[ARIA Example Disclosure Navigation Menu](https://www.w3.org/WAI/ARIA/apg/example-index/disclosure/disclosure-navigation.html#ex_label)**

- Menu opens with Space or Enter (as it is taken to be a button)
- When the menu is open you can use the tab key to move to the links
- You can also use the up/down arrow keys to move to the links but this is marked as optional

See [the keyboard support section](https://www.w3.org/WAI/ARIA/apg/example-index/disclosure/disclosure-navigation.html#kbd_label) for full description.

The navigation menu in gov.uk works like this but doesn't have support for the arrow keys: 
- Menu opens with Space or Enter (as it is taken to be a button)
- When the menu is open you can use the tab key to move to the links
- If you click on the arrow key when the menu is open then it scrolls down the page

I think we should do it like gov.uk (also keeping in mind that the version in stable uses the tab key to move to the links and the arrows to scroll up/down the page). So we only need to add a way to access the menu with the tab key and open it with Space or Enter to the version in stable.

**Comment by nikiforosk** [comment]
I can see the changes in latest, thank you @pacope92: https://latest.visual-framework.dev/components/vf-dropdown/

**Comment by nikiforosk** [comment]
The changes have now been released: https://stable.visual-framework.dev/components/vf-dropdown/
