### ISSUE TITLE
Bug: "On this page" vf-navigation

### ISSUE THREAD

**Issue by spivass81** [visual-framework/vf-core#1755]
<img width="1179" alt="Screenshot 2022-02-08 at 12 23 34" src="https://user-images.githubusercontent.com/50863581/152978094-57c0aa14-0af0-4133-b1af-2ea56f117ed3.png">

https://wwwdev.embl.org/limbo/annual-report/#services

The vf-navigation component overlaps the hero and the container components.

We will be using this component for the new annual report page, the dev version of which is going to be presented to the DG for feedback, so it would be great if we could sort this out with priority.

**Comment by nitinja** [comment]
This issue has been fixed now.
