### ISSUE TITLE
Low contrast error for text of vf-social-links

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1760]
WAVE shows low contrast errors for the text that appears behind the icons of [vf-social-links](https://stable.visual-framework.dev/components/vf-social-links/index.html) (this text becomes visible when the styles are turned off):
![social-low-contrast-errors-Screenshot 2022-02-14 at 12 06 57](https://user-images.githubusercontent.com/20280139/153862640-115c1d1d-5cc1-43ae-8270-055a9e11df60.png)

This is from the WAVE report of the EBI news pages but we came across it on other pages which use this component (see below):
https://wave.webaim.org/report#/https://www.ebi.ac.uk/about/news

According to the corresponding guidelines:
> When text is presented over a background image, the text must have a background color defined (typically in CSS) that provides adequate text contrast when the background image is disabled or unavailable. 

![social-low-contrast-reference-Screenshot 2022-02-14 at 12 09 46](https://user-images.githubusercontent.com/20280139/153862672-20e21a61-fbfc-47ec-9d24-1ca6effdfcd6.png)

Other pages with [vf-social-links](https://stable.visual-framework.dev/components/vf-social-links/index.html) that show the same error:

- Online tutorial book cover:
https://wave.webaim.org/report#/https://www.ebi.ac.uk/training/online/courses/bioinformatics-terrified/

- Personal profile: 
https://wave.webaim.org/report#/https://www.ebi.ac.uk/about/jobs/career-profiles/alegria-aclan-software-developer

Note that on the Personal profile page we're using the Wordpress widget of this component.

**Comment by nikiforosk** [comment]
A similar thing is happening with the Pagination component e.g. in https://wave.webaim.org/report#/https://www.ebi.ac.uk/services/data-resources-and-tools

@nikiforosk to test this with lighthouse and do a bit of research to understand if it is a real issue.

**Comment by nikiforosk** [comment]
A few tools to test this with:

- [ ] Google lighthouse
- [ ] [Color Contrast Accessibility Validator](https://color.a11y.com/?wc3)
- [ ] www.accessibilitychecker.org

**Comment by nikiforosk** [comment]
@pacope92 Could you please add a brief explanation of what you changed?

We get a similar alert with the pagination component e.g. in https://wave.webaim.org/report#/https://www.ebi.ac.uk/services/data-resources-and-tools

**Comment by francisco-ebi** [comment]
Hi @nikiforosk, previously we had this hidden text in each link:
<img width="627" alt="Screenshot 2022-11-21 at 09 58 53" src="https://user-images.githubusercontent.com/5340971/203028229-ead3b371-e8f0-4a42-af2f-69be045e392b.png">
This text had a class to make it visible only to screen readers and it had the black default color that clashed with the black background.
To avoid this issue I made the following change: 
<img width="837" alt="Screenshot 2022-11-21 at 10 08 27" src="https://user-images.githubusercontent.com/5340971/203029763-fbc8bf37-3bfb-4d5f-9216-8a5836ecf8e2.png">
I replaced the hidden text with the aria-label attribute which will serve the same purpose.

**Comment by nikiforosk** [comment]
These changes have now been released: https://stable.visual-framework.dev/components/vf-social-links/index.html
