### ISSUE TITLE
Focus indicator of arrow on vf-tree is hard to spot

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1761]
When I navigate [the vf-tree component](https://stable.visual-framework.dev/components/vf-tree/) with the keyboard, each menu item has an outline as expected:
![vf-tree-selected-menu-Screenshot 2022-02-14 at 13 29 14](https://user-images.githubusercontent.com/20280139/153873935-122b5564-2ab7-40b3-a8de-7c826dcc4c65.png)

However when the arrow next to "What is bioinformatics" is selected the outline disappears and the arrow becomes bold instead:
![vf-tree-arrrow-bold-Screenshot 2022-02-14 at 13 29 23](https://user-images.githubusercontent.com/20280139/153874184-faddf6bb-aa8d-4155-891b-b9b5f9c2dba7.png)

This is quite hard to spot, especially when the arrow is part of an expanded menu because in that case the label and the arrow of this menu, e.g. **What makes a good bioinformatics database? ^** below, are already bold before they receive keyboard focus:
![vf-tree-active-menu-arrrow-bold-Screenshot 2022-02-14 at 13 30 02](https://user-images.githubusercontent.com/20280139/153874696-0cb8b803-c8e9-4891-a753-32538cba94aa.png)

It will be good to show an outline around the arrow too to assist keyboard navigation.

We came across this issue while we were testing keyboard navigation on the content pages of an EBI training online tutorial:
https://www.ebi.ac.uk/training/online/courses/bioinformatics-terrified/what-makes-a-good-bioinformatics-database/

**Comment by kasprzyk-sz** [comment]
Hey @pacope92 I can pick this up if it's ok for you

**Comment by nikiforosk** [comment]
I can see the outline now around the arrow in latest:
https://latest.visual-framework.dev/components/vf-tree/ 

I noticed that sometimes the outline of a link doesn't always show as a full rectangle. I created a separate issue for this: https://github.com/visual-framework/vf-core/issues/1816

**Comment by nikiforosk** [comment]
The changes have now been released: https://stable.visual-framework.dev/components/vf-tree/
