### ISSUE TITLE
Header of vf-hero is h2 instead of h1

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1762]
The header of the vf-hero component is h2 instead of h1.

This means that most pages with a vf-hero get a “Missing first level heading” alert. 

This is the case for the EBI home page:
https://wave.webaim.org/report#/https://www.ebi.ac.uk/

![missing-h1-Screenshot 2022-01-31 at 13 30 38](https://user-images.githubusercontent.com/20280139/153883111-5245b54d-2f2f-45f8-b027-ceabfb54e538.png)

and the EMBL home page:
https://wave.webaim.org/report#/https://www.embl.org/

and most other pages that have a hero within the EBI and the EMBL site.

As the reference of this alert mentions: 
> A first level heading (`<h1>`) should be present on nearly all pages. It should contain the most important heading on the page (generally the document title).

Also note that the font size of `vf-hero__heading` is 42px, which is the same as h1 in WP as previously commented in https://github.com/visual-framework/vf-core/issues/1727#issuecomment-983572880

**Comment by nitinja** [comment]
@nikiforosk 
<img width="511" alt="image" src="https://user-images.githubusercontent.com/3931042/163180208-402a1fc0-a2ca-4c91-a5cc-c431bfb025ad.png">

There is also a related issue that subheading appears to be a heading but it's not a heading (it's a paragraph instead). Should we fix this as well?

**Comment by nikiforosk** [comment]
> @nikiforosk <img alt="image" width="511" src="https://user-images.githubusercontent.com/3931042/163180208-402a1fc0-a2ca-4c91-a5cc-c431bfb025ad.png">
> 
> There is also a related issue that subheading appears to be a heading but it's not a heading (it's a paragraph instead). Should we fix this as well?

This is more of a tagline than a header and sometimes it can be quite long, as in the people's page: https://wave.webaim.org/report#/https://www.ebi.ac.uk/people

I'd leave it like this for now and change the actual header of the hero from h2 to h1.

**Comment by nitinja** [comment]
@nikiforosk ok, thanks
