### ISSUE TITLE
Change link variant of VF button to be a button element rather than a link

### ISSUE THREAD

**Issue by MGS-sails** [visual-framework/vf-core#1774]
https://stable.visual-framework.dev/components/vf-button/#variants
the sample HTML given on this page (see link above) uses an anchor tag with the href set to JS void

`<a href="JavaScript:Void(0);" class="vf-button vf-button--link">a link variant</a>`

the problem with this is that, some of our pipelines fail when a proper href is not provided to anchor tags, such as on the academy project

I have found that using an actual button tag and adding the vf-button vf-button--link classes still works perfectly.
So I think it’s better to use an actual button tag in the example rather than an anchor tag.
Also I feel that having a button tag is more in line with the concept of it being a “variant” of the vf button, as an anchor tag is not a variant, rather it is a different element entirely

**Comment by nitinja** [comment]
Thanks @MGS-sails some discussion here: https://github.com/visual-framework/vf-core/pull/1540

**Comment by nikiforosk** [comment]
From a quick look at [carbon design](https://carbondesignsystem.com/components/button/usage/) that has an equivalent "ghost" button, I see that they also use the button element:

![Screenshot 2022-05-11 at 11 12 54](https://user-images.githubusercontent.com/20280139/168297948-65815d43-5446-44ef-96aa-f1317ea04a03.png)

`<Button kind='ghost'>Button</Button>`

So this proposal makes sense to me.

**Comment by nikiforosk** [comment]
As Nitin mentioned, an example of using  button-as-link is "Select all locations" in the sign up form:
https://www.embl.org/jobs/alerts

@nitinja please provide any additional information that we may need to be able to follow up on this.

NB: As discussed in #1779 in the Training site we use a similar component called [#vf-bookmark--inline](https://stable.visual-framework.dev/components/vf-bookmark/#vf-bookmark--inline) (which also functions as a button-as-link preceded by an icon) to mark a page as favourite or complete, see e.g.: https://www.ebi.ac.uk/training/events/guide-ebi-search/
 (You need to create an account and login to see how this works)

**Comment by sandykadam** [comment]
Output should like this:

```
<button class="vf-button vf-button--link">a link variant</button>
```

Instead of a href

```
<a href="JavaScript:Void(0);" class="vf-button vf-button--link">a link variant</a>

```

**Comment by nikiforosk** [comment]
This is done in latest so I'm moving it to Done for this sprint: https://latest.visual-framework.dev/components/vf-button/index.html#vf-button--link 

I'll close the issue once the change is released in stable.

**Comment by nikiforosk** [comment]
on stable: https://stable.visual-framework.dev/components/vf-button/#vf-button--link
