### ISSUE TITLE
Navigation element overflow behavior

### ISSUE THREAD

**Issue by prakashebi** [visual-framework/vf-core#1775]
When we zoom in a page having Navigation component the text is trimmed from the top of the navigation and this is happening in Google chrome specifically.

In the [navigation](https://stable.visual-framework.dev/components/vf-navigation/) component there is class `vf-cluster` which has **overflow** property set to **hidden**. Removing this property fixes this issue.

**Comment by prakashebi** [comment]
Screenshot
![nav-component](https://user-images.githubusercontent.com/45974822/170669097-18a1eda3-e77b-4752-a3f9-88b7a23d88e6.png)

**Comment by nikiforosk** [comment]
Note that this is also an accessibility issue as the content on the page should be displayed correctly when people zoom in up to 200%

**Comment by nikiforosk** [comment]
@sandykadam This seems to work on microsites up to 200% zoom in as required. Might be an issue with the implementation of the component in the training site. Sandeep will follow up with Prakash on that.

**Comment by sandykadam** [comment]
Hi @nikiforosk 

This issue is not reproducible anymore on training website, I verified with @prakashebi. 
Also it was referring to the DEV css so we corrected it to point to LIVE css of VF, that could have been issue which could have resolve this.

So we are good to close this ticket.

Thanks

**Comment by nikiforosk** [comment]
Thanks I'll close this ticket then and remove it from the backlog.
