### ISSUE TITLE
Badge component variant: solid light blue background

### ISSUE THREAD

**Issue by nitinja** [visual-framework/vf-core#1778]
Add a one sentence summary of what it is you need it to do.
We are using a badge variant on EBI website services section, so UX people thought we may want to add it to the variants of [vf-badge](https://stable.visual-framework.dev/components/vf-badge/).

<img width="186" alt="image" src="https://user-images.githubusercontent.com/3931042/173047275-b535b284-959f-4afb-888a-31361f9814dc.png">

---

- In a few words, what does this component look like?
Badge Variant

- In a few words, what does this component do?
acts as a badge

**Comment by bhushan-ebi** [comment]
@Adedoyinebi to review and close this and create a new one to identify the requirements for a standard VF Badge component.

**Comment by bhushan-ebi** [comment]
#1914 issue already created for identifying the requirements for VF Badge.
