### ISSUE TITLE
Update documentation and default option of vf-bookmark

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1779]
The documentation of [vf-bookmark](https://stable.visual-framework.dev/components/vf-bookmark/) mentions that the default icon is the star. 

But on the training site (where this component has been applied so far), we are using the heart, see:

https://www.ebi.ac.uk/training/events/pride-database-proteomics-data-submission-access-and-visualisation/
and
https://www.ebi.ac.uk/training/online/courses/a-guide-to/

The actual button variants on the component's page also show the heart (but [#vf-bookmark--inline](https://stable.visual-framework.dev/components/vf-bookmark/#vf-bookmark--inline) uses the star).

We also use this variant for other purposes such as Marking a page as complete, see e.g.:
https://www.ebi.ac.uk/training/online/courses/a-guide-to/molecular-sequence-features-and-analysis/
and
https://www.ebi.ac.uk/training/events/guide-ebi-search/

This uses a checkmark icon instead of the heart.

Suggested improvements:

- [x] Change the documentation of the component so that the default icon is the heart.
- [x] Change [#vf-bookmark--inline](https://stable.visual-framework.dev/components/vf-bookmark/#vf-bookmark--inline) so that it also uses the heart.
- [x] Add links to pages that use this component:
- https://www.ebi.ac.uk/training/events/pride-database-proteomics-data-submission-access-and-visualisation/
- https://www.ebi.ac.uk/training/online/courses/a-guide-to/molecular-sequence-features-and-analysis/

Related tasks:
-  #1843
-  #1844

@prakashebi has lead the implementation of this components for the Training site so could provide advice.

**Comment by sandykadam** [comment]
This will be code change https://github.com/visual-framework/vf-core/issues/1774#issuecomment-1384179276

**Comment by nikiforosk** [comment]
on stable: https://stable.visual-framework.dev/components/vf-bookmark/
