### ISSUE TITLE
QUESTION: How to deprecate a variant

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#178]
When one variant in a pattern is no longer to be used/deprecated, how should we do that?

We can achieve this in part by:

1. Adding a note to the `--variant.hbs`
1. Wrapping the relevant css in `html:not(.vf-disable-deprecated) {`
1. Hiding the variant tab in `.config.yml`:
```
variants:
  - name: deprecated-variant
    hidden: true
```

Is that sufficient? Can/should we do anything more? 

Related to: `DOCS: Deprecation process` #152

**Comment by khawkins98** [comment]
I think we're close on this one, but we need to have a think before we close. Bumping to alpha.4.

**Comment by sturobson** [comment]
We might want to circle back and see what other things could possibly be deprecated - design tokens for one.

**Comment by khawkins98** [comment]
Added to the backlog.
