### ISSUE TITLE
Deep links on VF tabs not working

### ISSUE THREAD

**Issue by MGS-sails** [visual-framework/vf-core#1781]
Clicking on a tab that has a deep link, does not cause the URL to change. i.e, the tab ID does not get added in the URL as suggested in the documentation. 
For example on the code below, when you click on the "Section" tab, the url does not get changed to "https://stable.visual-framework.dev/components/vf-tabs/#vf-tabs__section--1" 
It just remains as it is
```html
<div class="vf-tabs">
  <ul class="vf-tabs__list" data-vf-js-tabs>
    <li class="vf-tabs__item">
      <a class="vf-tabs__link" href="#vf-tabs__section--1">Section</a>
    </li>
    <li class="vf-tabs__item">
      <a class="vf-tabs__link" href="#vf-tabs__section--2">A Short Section</a>
    </li>
  </ul>
</div>

<div class="vf-tabs-content" data-vf-js-tabs-content>
  <section class="vf-tabs__section" id="vf-tabs__section--1">
    <h2>Section 1</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam euismod, tortor nec pharetra ultricies, ante erat imperdiet velit, nec laoreet enim lacus a velit. <a class="vf-link" href="#">Nam luctus</a>, enim in interdum condimentum, nisl diam iaculis lorem, vel volutpat mi leo sit amet lectus. Praesent non odio bibendum magna bibendum accumsan.</p>
  </section>
  <section class="vf-tabs__section" id="vf-tabs__section--2">
    <h2>Section 2</h2>
    <p>Nullam at diam nec arcu suscipit auctor non a erat. Sed et magna semper, eleifend magna non, facilisis nisl. Proin et est et lorem dictum finibus ut nec turpis. Aenean nisi tortor, euismod a mauris a, mattis scelerisque tortor. Sed dolor risus, varius a nibh id, condimentum lacinia est. In lacinia cursus odio a aliquam. Curabitur tortor magna, laoreet ut rhoncus at, sodales consequat tellus.</p>
  </section>
</div>
```

**Comment by nikiforosk** [comment]
@nitinja As you're working on this please keep in mind that opening the deep link in a new tab should also actually open this page on this tab. 

This isn't currently working on our workaround for the Training site e.g. in https://www.ebi.ac.uk/training/online/courses/biocuration-collection/#vf-tabs__section--gettingstarted

**Comment by nikiforosk** [comment]
@nitinja please update this issue for @MrSpockB to follow up.

**Comment by geetikamalhotra** [comment]
@nikiforosk this seems to be working on the training website. Is there a workaround implemented there?
https://www.ebi.ac.uk/training/online/courses/biocuration-collection/#vf-tabs__section--gettingstarted

**Comment by nikiforosk** [comment]
> @nikiforosk this seems to be working on the training website. Is there a workaround implemented there? https://www.ebi.ac.uk/training/online/courses/biocuration-collection/#vf-tabs__section--gettingstarted

Yes, they have applied a workaround on the Training site but this isn't working fully either: If you click on the link below for the second tab (or try to open it in another tab from the actual page) it doesn't point to the right part of the page:
https://www.ebi.ac.uk/training/online/courses/biocuration-collection/#vf-tabs__section--contents

**Comment by kasprzyk-sz** [comment]
Hey @nikiforosk I can look into this during our current sprint. Is it ok for you?

**Comment by nikiforosk** [comment]
Yes that's fine but might need to talk to Mahfouz for clarifications.

**Comment by MGS-sails** [comment]
Hi @nikiforosk @kasprzyk-sz @pacope92 I will be happy to go on a call to demonstrate this.

**Comment by nikiforosk** [comment]
This seems to be working on latest:

https://latest.visual-framework.dev/components/vf-tabs/#vf-tabs__section--621211

I'll write a small summary of what we fixed and the behaviour of the component on the training site.

**Comment by nikiforosk** [comment]
A quick update of the status on tabs:

- [x] The URL of tabs in stable didn't update (as Mahfouz originally reported). This has now been fixed in latest (see e.g. https://latest.visual-framework.dev/components/vf-tabs/#vf-tabs__section--1).

- [x] Clicking on a tab link from another page or opening a this link on a new tab seems to work both in stable & in latest (There is a small issue with ["On the page" vf-navigation](https://stable.visual-framework.dev/components/vf-navigation/#vf-navigation--on-this-page) component which appears a bit too close to the tab when a tab is clicked on these pages).

@MGS-sails Please note opening a tab on a new page on the Training site doesn't work as expected, see e.g. https://www.ebi.ac.uk/training/online/courses/biocuration-collection/#vf-tabs__section--contents

But since this works with the actual component, it should be an issue with the implementation of the component in the Training site.

**Comment by nikiforosk** [comment]
The changes have now been released: https://stable.visual-framework.dev/components/vf-tabs/
