### ISSUE TITLE
Fix for 1771 (make vf-navigation--on-this-page more dynamic, responsive)

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1784]
@pacope92 reviewed [the commit](https://github.com/visual-framework/vf-core/commit/be6d68aaf1aaf30a2db62f85e4c9d9198c252879) for #1771 and identified some fixes.

@sandykadam is currently testing these fixes in a couple of scenarios.

We believe that this may also address #1757

**Comment by francisco-ebi** [comment]
Fix has been deployed to production, closing this.
