### ISSUE TITLE
separation of patterns by 'ownership'

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#179]
I think it might be cleaner to move `EMBL specific` patterns to their own 'space' in the layout of patterns?

I think the best way to do this in the UI is to duplicate the layout with blocks/containers/pages/deprecated 

We cannot do this in the folder structure as it'd be a pain for lerna etc.

I think we should be able to do this with the way you have created the lists in the Fractal UI.

Next step is for me to try this - if it works - I'll raise a PR.

**Comment by khawkins98** [comment]
Copying a comment over from the above PR:

> ties in with the need to document our user types/need (#127)
>
> That is:
> 1. We have EMBL site builders that won't much care if a pattern is "VF block" or "EMBL block"
> 2. We have distinctly non-EMBL users that want to avoid all EMBL specific stuff
> 
> Ideally we could do something like:
> 1. If building for EMBL (dev.beta.embl.org/../dev-docs/), then show EMBL patterns
> 2. If building generic VF (visual-framework.github.io/vf-core/), then hide EMBL patterns
> 
> But that has implications beyond just showing the patterns but also which patterns are used and > what's in `vf-core/index.scss`

As a mid-term step, thought is to use the above PR (splitting out patterns by type) for alpha.2 and then revisit a more holistic solution for alpha.3

**Comment by khawkins98** [comment]
I think this has been largely addressed and it's a general thing we're working on. Being bold and closing.
