### ISSUE TITLE
EBI corporate website - footer redesign

### ISSUE THREAD

**Issue by sandykadam** [visual-framework/vf-core#1795]
Currently, there are a number of inconsistencies between main navigation and the footer:

language and names used
grouping of categories and the use of "&"
mentioning categories which are not present in the main nav (Industry)

The review of the footer requires coordination with the work done on developing the megamenu and in consultation with colleagues from EMBL where the footer is used very differently.

Originally reported in - [ECWR-5](https://www.ebi.ac.uk/panda/jira/browse/ECWR-5)

**Comment by nikiforosk** [comment]
We'll track this in #1796
