### ISSUE TITLE
Update EBI footer

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1796]
Update the [EBI footer](https://stable.visual-framework.dev/components/ebi-header-footer/index.html?q=EBI%20footer#ebi-header-footer--footer) to mirror the changes in [ECWR-526](https://www.ebi.ac.uk/panda/jira/browse/ECWR-526):

- Remove "By topic" link 
- Rename  "By name (A-Z)" to "Data resources and tools" and link to https://www.ebi.ac.uk/services/data-resources-and-tools
- Add "Data submission" below "Data resources and tools" and link to https://www.ebi.ac.uk/submission/ 

We may also replace & with "and" to conform with the EBI styleguide. 

Mockup by Carla in Figma:

https://www.figma.com/file/lftJKEvKQ0v4zXDyYYCyVC/EBI-Corporate-Site?node-id=2420%3A8162

**Comment by nikiforosk** [comment]
We could work on it together with the megamenu #1794 in a VF sprint about issues that have to do with the EBI website.

**Comment by sandykadam** [comment]
@nikiforosk I had already created footer ticket in core https://github.com/visual-framework/vf-core/issues/1795. Upto you to keep separate or merge in it.
Rodica wanted to redesign footer completely with more information.

**Comment by nikiforosk** [comment]
@sandykadam I'll add your text from #1795 as a comment here and close it:

Currently, there are a number of inconsistencies between main navigation and the footer:

language and names used
grouping of categories and the use of "&"
mentioning categories which are not present in the main nav (Industry)

The review of the footer requires coordination with the work done on developing the megamenu and in consultation with colleagues from EMBL where the footer is used very differently.

Originally reported in - [ECWR-5](https://www.ebi.ac.uk/panda/jira/browse/ECWR-5)

**Comment by nikiforosk** [comment]
This will also address the "Redundant link" alert on the footer (e.g. on [the EBI homepage](https://wave.webaim.org/report#/https://www.ebi.ac.uk/)):

![Screenshot 2022-09-27 at 11 56 12](https://user-images.githubusercontent.com/20280139/192507890-8e92774c-b95e-467a-a95c-0d812ae64a1d.png)

**Comment by sandykadam** [comment]
> This will also address the "Redundant link" alert on the footer (e.g. on [the EBI homepage](https://wave.webaim.org/report#/https://www.ebi.ac.uk/)):
> 
> ![Screenshot 2022-09-27 at 11 56 12](https://user-images.githubusercontent.com/20280139/192507890-8e92774c-b95e-467a-a95c-0d812ae64a1d.png)

@nikiforosk this link will anyway get removed once we done with this fix [ECWR-526](https://www.ebi.ac.uk/panda/jira/browse/ECWR-526)

**Comment by nikiforosk** [comment]
@sandykadam It looks like that [the EBI footer component](https://stable.visual-framework.dev/components/ebi-header-footer/#ebi-header-footer--footer) has been updated to mirror the changes in [ECWR-526](https://www.ebi.ac.uk/panda/jira/browse/ECWR-526). So I'll close this issue.
