### ISSUE TITLE
Update EBI header component 

### ISSUE THREAD

**Issue by sandykadam** [visual-framework/vf-core#1797]
Originally from https://www.ebi.ac.uk/panda/jira/browse/ECWR-525

**Problem**

Based on UX team feedback on corporate website in header section when we click on search icon we get search field along with "x" link to close popup but that "x" is coming above Search button on black bar.

@nikiforosk I verified training site for why it is working there and found that VF is outdated in training pages and it doesn't use `vf-body` class in `<body>` tag on their pages which is required to show the standard VF grid centered content, if we use `vf-body` 'x' button will break on training pages as well. 

EBI corporate website 
![image](https://user-images.githubusercontent.com/1227241/189697650-3cc3e0d2-9d83-4660-ad60-43b75f34a23d.png)

Training pages
![image](https://user-images.githubusercontent.com/1227241/189697706-1cca3230-85c0-424e-aa2e-498bc85469d3.png)

**Solution:**

Need to update https://stable.visual-framework.dev/components/ebi-header-footer component to fix some css issues.
Following is some basic  initial css fix need to apply.

![Screenshot 2022-09-12 at 16 38 54](https://user-images.githubusercontent.com/1227241/189698116-fb4abbd5-20fc-4c83-9332-e2481c8af6f4.png)

cc: @prakashebi

**Comment by nikiforosk** [comment]
I added this to the group of issues about the EBI site in the backlog. 

We need to think whether it should be addressed before the mega-menu (see #1794) which will presumably include a search function and will eventually replace the black bar.

**Comment by sandykadam** [comment]
This issue will be fixed with my current fix in https://github.com/ebiwd/EBI-Framework/pull/203
Ideally this fix needs to be added in vf-core but right now we focusing on fixing accessibility issues of only EBI corporate site

**Comment by nikiforosk** [comment]
I've added this issue to the sprint backlog of Sprint 02 as my understanding is that the fixes for [the EBI header](https://stable.visual-framework.dev/components/ebi-header-footer/#ebi-header-footer--header) will include [the various accessibility issues](https://docs.google.com/presentation/d/13QfRjFJtjRkaXVXrlfKPafrjhLvH7-lNgM7EF02VxMc/edit#slide=id.g14114ca1e7d_0_1579) on the black bar that are currently being addressed on dev.

**Comment by nikiforosk** [comment]
Includes various changes on black bar on corporate site:

- [ ] Accessibility fixes
- [ ] fixed the [x] button

**Comment by sandykadam** [comment]
This change needs to get approval from WCC so we will not include in current release. On EBI corporate website we have added a hack fix so we can check on wwwdev site. 


Actual vf-core fix will look like this.

![Image](https://user-images.githubusercontent.com/1227241/203019769-52d2137f-d071-4d6c-a0d3-2d59a36b5e36.png)
