### ISSUE TITLE
Generic descriptive text being displayed on component search 

### ISSUE THREAD

**Issue by MGS-sails** [visual-framework/vf-core#1834]
When you search for a component on this page:
https://stable.visual-framework.dev/search/?search_query=form

You will notice that the descriptive text present on each of the search results, is a repeated generic text.
It would be better if the descriptive text actually describes the individual components in the search results.

**Comment by sandykadam** [comment]
Good catch @MGS-sails not sure if this was recent issue or its there since launch :) 
@pacope92 lets take this for next sprint, if its quick fix we can release because for ebi-header-footer anyway we need to create new tag soon.

**Comment by bhushan-ebi** [comment]
I've made changes to the tools/vf-component-library/node_modules/@visual-framework/vf-extensions/gulp-tasks/gulp-build-search-index.js to reflect the summary of results on search. Please see attached .xlsx file showing results from each index.html file indexed. Result for each index.html file in the sheet is in the immediate row below, blanks mean there's no result for that file.

Please suggest if we can move ahead with this result. Also note that this requires change in vf-core component as per my understanding.

[SearchIndexResults.xlsx](https://github.com/visual-framework/vf-core/files/10550967/SearchIndexResults.xlsx)

**Comment by sandykadam** [comment]
@bhushan-ebi  lets discuss this offline, we might have to expand further to get proper search results

**Comment by bhushan-ebi** [comment]
Pasting the attachment on correct ticket this time.

![Image](https://user-images.githubusercontent.com/122287459/216943350-8aa89999-3877-4e9d-8ef0-dbbd8e451a7e.png)

**Comment by nikiforosk** [comment]
I'm moving this to Done too but let's remember to do a final check after releasing to latest and close the issue then.

**Comment by nikiforosk** [comment]
on stable: https://stable.visual-framework.dev/search/?search_query=cards
