### ISSUE TITLE
Review of VF components by PD

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1838]
When the new PD joins, they should review the existing VF components on the design library in Figma.

The objectives are to:

- [ ] Familiarise themselves with the VF
- [ ] Identify components in Figma which are out of sync with the live components
- [ ] Identify gaps in documentation

Related links:

- [ ] [VF components](https://stable.visual-framework.dev/components/)
- [ ] [Components in Figma](https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?node-id=373%3A2&t=oxHKS5SrIV66DG2Z-1)
- [ ] [Component status list](https://docs.google.com/spreadsheets/d/1jan7jnM_Bdhr5HStoGnfytx_izNNBoPeyth0-009VcQ/edit#gid=0)

Next steps:

- [ ] #1880 (Sprint 04)
- [x] https://github.com/visual-framework/vf-core/issues/1926
- [ ] [Review WP components](https://stable.visual-framework.dev/wordpress/blocks/)
- [ ]  #1837

**Comment by nikiforosk** [comment]
In the next sprint, start with reviewing the Elements and Layout first (which are the simplest components).

**Comment by bhushan-ebi** [comment]
@Adedoyinebi  to close this issue and then create additional independent tasks for reviewing blocks, containers and patterns.

**Comment by Adedoyinebi** [comment]
The vf Layouts, Elements and Design tokens have been reviewed and the findings documented. The required follow ups tasks were also created. Find the full summary in the task https://github.com/visual-framework/vf-core/issues/1922

New tasks have been created for the review of:

- Patterns - https://github.com/visual-framework/vf-core/issues/2049
- Containers - https://github.com/visual-framework/vf-core/issues/2050
- Blocks - https://github.com/visual-framework/vf-core/issues/2051

Closing this task
