### ISSUE TITLE
Update the documentation of vf-card-container

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1841]
Update the documentation of [vf-card-container](https://stable.visual-framework.dev/components/vf-card-container/) to mention:

**Section header**
- [ ] Use one card container for all cards that belong to the same section.
- [ ] Always include [a vf-section header](https://stable.visual-framework.dev/components/vf-section-header/index.html) to the card container. This ensures that your page will not have [skipped headings](https://www.w3.org/WAI/tutorials/page-structure/headings/#heading-ranks) between the cards and the preceding content outside the container.
- [ ] If you do not want the section header to be visible, you can hide it using the class `vf-u-sr-only` (for screen reader only). See the [example with a hidden header below](URL).

Also see #1840 

**Card container background**
- [ ] Use a white background for both [striped (green) cards](https://stable.visual-framework.dev/components/vf-card/#vf-card--striped) and [bordered (white) cards](https://stable.visual-framework.dev/components/vf-card/#vf-card--bordered).
- [ ] `vf-u-background-color-ui--grey--light`: `#f3f3f3` (called 'Gray lightest' in [the equivalent WP block](https://stable.visual-framework.dev/wordpress/blocks/container-block/)) may be used as an alternative background of bordered (white) cards, especially when the section header is hidden and there is no text between the section header and the cards. 
- [ ] [The Meet our people page](https://www.ebi.ac.uk/about/jobs/meet-our-people) at the EMBL-EBI site includes examples of using the card container that [pass the basic contrast tests for accessibility](https://wave.webaim.org/report#/https://www.ebi.ac.uk/about/jobs/meet-our-people#).

 Also see #1842

**Comment by nikiforosk** [comment]
Contrast checks between "Light gray" background (`vf-u-background-color--grey--lightest`: `#D0D0CE`) and:

- [Link Colour `#3b6fb6`](https://webaim.org/resources/contrastchecker/?fcolor=3B6FB6&bcolor=D0D0CE): 3.28:1
- [x] Pass at AA for large text (24px)
- [ ] **Fail for normal text** (19px or smaller but not bold)
This means that we can use [vf-section-header-is-a-link](https://stable.visual-framework.dev/components/vf-section-header/#vf-section-header--is-a-link) on this background but **we cannot have links** in the text between the section header and the cards.

- [Link Hover Colour `#193f90`](https://webaim.org/resources/contrastchecker/?fcolor=193F90&bcolor=D0D0CE): 6.3:1
- [x] Pass at AA & AAA large text (24px)
- [x] Pass at AA for normal text (19px or smaller but not bold)

- [Primary Text Colour `#1a1c1a`](https://webaim.org/resources/contrastchecker/?fcolor=1A1C1A&bcolor=D0D0CE): 11.09:1
- [x] Pass at AA & AAA large text (24px)
- [x] Pass at AA for normal text (19px or smaller but not bold)
This means that we can have a section header (that isn't a link) in the container and text between the header and the cards.

**Comment by nikiforosk** [comment]
**This isn't an option for the WP container**
Contrast checks between light gray background (`vf-u-background-color--grey--light`: `#a8a99e`) and:

- [Link Colour `#3b6fb6`](https://webaim.org/resources/contrastchecker/?fcolor=3B6FB6&bcolor=A8A99E): 2.13:1
- [ ] **Fail for large text** (24px)
- [ ] **Fail for normal text** (19px or smaller but not bold)
This means that **we cannot use** [vf-section-header-is-a-link](https://stable.visual-framework.dev/components/vf-section-header/#vf-section-header--is-a-link) on this background and **we cannot have links** in the text between the section header and the cards.

- [Link Hover Colour `#193f90`](https://webaim.org/resources/contrastchecker/?fcolor=193F90&bcolor=A8A99E): 4.09:1
- [x] Pass at AA for large text (24px)
- [ ] **Fail for normal text** (19px or smaller but not bold)

- [Primary Text Colour `#1a1c1a`](https://webaim.org/resources/contrastchecker/?fcolor=1A1C1A&bcolor=A8A99E): 7.21:1
- [x] Pass at AA & AAA large text (24px)
- [x] Pass at AA for normal text (19px or smaller but not bold)
Note that there are some questions about [how accurate this contrast value is](https://medium.com/@think_ui/why-color-contrast-is-not-as-black-and-white-as-it-seems-94197a72b005). The actual perceived contrast might be lower...

@kasprzyk-sz In general, I'd recommend avoiding this background in card containers (including the version in WP) because it fails the contrast checks for [vf-section-header-is-a-link](https://stable.visual-framework.dev/components/vf-section-header/#vf-section-header--is-a-link) as well as links in the text between the section header and the cards.

**Comment by nikiforosk** [comment]
We also use the following two background colours in the vf-card-container. Both pass the contrast checks:

**Grey lightest**: `vf-u-background-color-ui--grey--light` `#f3f3f3` (e.g. in the "How to work with us" container of [the EBI Research page](https://www.ebi.ac.uk/research)):

- [Link Colour `#3b6fb6`](https://webaim.org/resources/contrastchecker/?fcolor=3B6FB6&bcolor=F3F3F3): 4.57:1
- [x] Pass at AA & AAA for large text (24px)
- [x] Pass at AA for normal text (19px or smaller but not bold)

- [Link Hover Colour `#193f90`](https://webaim.org/resources/contrastchecker/?fcolor=193F90&bcolor=A8A99E): 8.78:1
- [x] Pass at AA & AAA for large text (24px)
- [x] Pass at AA for normal text (19px or smaller but not bold)

- [Primary Text Colour `#1a1c1a`](https://webaim.org/resources/contrastchecker/?fcolor=1A1C1A&bcolor=F3F3F3): 15.45:1
- [x] Pass at AA & AAA large text (24px)
- [x] Pass at AA for normal text (19px or smaller but not bold)

**White**: `vf-u-background-color-ui--off-white` `#fafafa` (e.g. in the featured news container on the top of [the EMBL News page](https://www.embl.org/news/)):

- [Link Colour `#3b6fb6`](https://webaim.org/resources/contrastchecker/?fcolor=3B6FB6&bcolor=FAFAFA): 4.86:1
- [x] Pass at AA & AAA for large text (24px)
- [x] Pass at AA for normal text (19px or smaller but not bold)

- [Link Hover Colour `#193f90`](https://webaim.org/resources/contrastchecker/?fcolor=193F90&bcolor=FAFAFA): 9.33:1
- [x] Pass at AA & AAA for large text (24px)
- [x] Pass at AA for normal text (19px or smaller but not bold)

- [Primary Text Colour `#1a1c1a`](https://webaim.org/resources/contrastchecker/?fcolor=1A1C1A&bcolor=FAFAFA): 16.42:1
- [x] Pass at AA & AAA large text (24px)
- [x] Pass at AA for normal text (19px or smaller but not bold)

**Comment by nikiforosk** [comment]
@kasprzyk-sz The documentation of [the WP (card) container block](https://stable.visual-framework.dev/wordpress/blocks/container-block/) mentions:

> Select the background color for the container. You can use White, Grey light, and Grey lightest as pre-determined colors. If you need an image, select Image and paste the URL in the field that appeared below.

However, light gray (`vf-u-background-color--grey--light`: `#a8a99e`) [fails the contrast checks](https://github.com/visual-framework/vf-core/issues/1841#issuecomment-1396862295) for vf-section-header-is-a-link as well as links in the text between the section header and the cards.

Can you change the documentation to be more consistent with [the suggestions above](https://github.com/visual-framework/vf-core/issues/1841#issue-1530566256):
- [ ] Use the white background for both [striped (green) cards](https://stable.visual-framework.dev/components/vf-card/#vf-card--striped) and [bordered (white) cards](https://stable.visual-framework.dev/components/vf-card/#vf-card--bordered).
- [ ] The lightest gray background (`#D0D0CE`) may be used as an alternative background of bordered (white) cards, especially when the section header is hidden and there is no text between the section header and the cards. 
  - [ ] Please **do not include links in the text** between the section header and the cards with this background as the Link Colour `#3b6fb6` [fails the contrast check for normal text with this background (3.28:1)](https://webaim.org/resources/contrastchecker/?fcolor=3B6FB6&bcolor=D0D0CE).

It may be useful to remove light gray (`vf-u-background-color--grey--light`: `#a8a99e`) as an option for the background of this block to prevent contrast errors.

**Comment by kasprzyk-sz** [comment]
Thank you @nikiforosk. I updated the block documentation accordingly.

Just to clarify, in Wordpress we use the following background colors:

Grey light: `.vf-u-background-color--grey--lightest`
Grey lightest: `.vf-u-background-color-ui--grey--light`

**Comment by nikiforosk** [comment]
@kasprzyk-sz Suggestions to update the documentation of [the WP container block](https://stable.visual-framework.dev/wordpress/blocks/container-block/) following our discussion this morning:

**Point 4:**

4. The container defaults to three columns (which is the recommended number of image-based cards per row). However if text-only cards are being used you can use 4 columns. See the examples below for adding cards with different columns.

**Point 5:**

5. Select the desired type of Header and add text for your Header:
- The container needs to have a Header. This ensures that your page will not have [skipped headings](https://www.w3.org/WAI/tutorials/page-structure/headings/#heading-ranks) between the cards and the preceding content outside the container.
- If you do not want the section header to be visible, you can hide it by changing the "Show Header" option to "No".

**Point 6:**

6. Select the background color for the container. Use the White background for both striped (green) cards and bordered (white) cards.
- The "Gray lightest" and "Gray light" backgrounds or an image may be used as an alternative background of bordered (white) cards, especially when the section header is hidden and there is no text between the section header and the cards.
- **Do not include links** in the text between the section header and the cards with the "Gray light" background as the link colour [fails the contrast check for normal text with this background ](https://webaim.org/resources/contrastchecker/?fcolor=3B6FB6&bcolor=D0D0CE).

**Point 8:**
8. Click on the block in the editor and a blue border will appear. Within the block border add [cards](https://stable.visual-framework.dev/wordpress/card-block/).
- Use one card container for all cards that belong to the same section.

NB: I removed the boxes from the last point as we have retired them.

Point 5 about the Header and point 6 about the background colour should also be added to the instructions about Other content further down on the same page.

**Comment by nikiforosk** [comment]
These are now on stable: https://stable.visual-framework.dev/components/vf-card-container/
