### ISSUE TITLE
Change variant and examples for vf-card-container

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1842]
Make the following changes to [vf-card-container](https://stable.visual-framework.dev/components/vf-card-container/):

- [x] Add an example with a hidden header (See #1840) 
- [x] Use white background for both examples
- [x] Use [striped (green) cards](https://stable.visual-framework.dev/components/vf-card/#vf-card--striped) for the example with the hidden header (See #1841)

**Comment by bhushan-ebi** [comment]
https://visual-framework.slack.com/archives/C03SMU5N6RK/p1675434375832759



![Image](https://user-images.githubusercontent.com/122287459/216664180-2c1e4f58-d7a9-4171-89ae-6a502244e9d5.png)

**Comment by nikiforosk** [comment]
I can see these changes in latest so I'm moving this issue to Done: https://latest.visual-framework.dev/components/vf-card-container/

**Comment by nikiforosk** [comment]
These are now on stable: https://stable.visual-framework.dev/components/vf-card-container/
