### ISSUE TITLE
No descriptive text in the search results of certain pages

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1854]
While working on #1835 we noticed that some pages do not have a descriptive text in the search results of the VF site. 

This spreadsheet contains the search index results (requires permission to view):
https://docs.google.com/spreadsheets/d/1Bdke2QVWPJ47TNvd0rqPLznyvNUUx_-d/edit?usp=sharing&ouid=115682926722519271452&rtpof=true&sd=true

- [x] #1883
- [x] #1885 

Related tasks:
- [x] #1900 
- [x] #1901 
- [x] #1904 
- [x] #1911 
- [x] #1920 

Will not do:
- [x] #1902
- [x] #1903

**Comment by nikiforosk** [comment]
In the next sprint we'll add the descriptions for "components" in the spreadsheet.

**Comment by nikiforosk** [comment]
@bhushan-ebi Please close this tasks when the subtasks are completed.

**Comment by bhushan-ebi** [comment]
Closing this ticket as all the tasks in this one are completed now.
