### ISSUE TITLE
Update vf-card-container documentation to include 'hidden' flag for section header

### ISSUE THREAD

**Issue by bhushan-ebi** [visual-framework/vf-core#1873]
This is a follow up of #1841 

@bhushan-ebi What exactly should we add to the documentation of the documentation of [vf-card-container](https://stable.visual-framework.dev/components/vf-card-container/)?

**Comment by nikiforosk** [comment]
This comment is dealt by #1884:

By looking at the code of [the example with the hidden cards](https://stable.visual-framework.dev/components/vf-card-container/#vf-card-container--section-header-hidden) I also noticed that the hidden header is a link:

`<h2 class="vf-section-header__heading **vf-section-header__heading--is-link** vf-u-sr-only"><a href="JavaScript:Void(0);">Missions</a><svg aria-hidden="true" class="vf-section-header__icon | vf-icon vf-icon-arrow--inline-end" width="1em" height="1em" xmlns="http://www.w3.org/2000/svg"><path d="M0 12c0 6.627 5.373 12 12 12s12-5.373 12-12S18.627 0 12 0C5.376.008.008 5.376 0 12zm13.707-5.209l4.5 4.5a1 1 0 010 1.414l-4.5 4.5a1 1 0 01-1.414-1.414l2.366-2.367a.25.25 0 00-.177-.424H6a1 1 0 010-2h8.482a.25.25 0 00.177-.427l-2.366-2.368a1 1 0 011.414-1.414z" fill="" fill-rule="nonzero"></path></svg></h2>`

I'm not sure this is best practice, maybe a hidden header should be a headers without a link (i.e. [the default variant](https://stable.visual-framework.dev/components/vf-section-header/index.html#vf-section-header--default))? We should also check with @kasprzyk-sz on whether this is the case in the corresponding WordPress block.

**Comment by bhushan-ebi** [comment]
@nikiforosk 
Following -
"If you do not want the section header to be visible, you can hide it using the class vf-u-sr-only (for screen reader only)"

should read something like -

"If you do not want the section header to be visible, you can hide it by passing 'hidden' as true (hidden: true) inside the 'container_section__header' section in card container config.yml setting. This value (true) applies the class vf-u-sr-only (for screen reader only) to the section header and hides it."

**Comment by bhushan-ebi** [comment]
Hi @nikiforosk when you are updating the document can please also change the below line (32):

* moves the `default` context data in the `.yml` file to a `variant` to allow easier use of `{% include %}`.

to

* moves the `default` context data in the `.yml` file to a `variant` to allow easier use of `{#{% include %}#}`.

in  the file components/vf-card-container/CHANGELOG.md ?

**Comment by bhushan-ebi** [comment]
@nikiforosk also please change below (line  29):

To set the `aspect-ratio` you will need to set the `card_custom_aspect_ratio` key/value pair in the `.yml` or the `&#x7B;&#x25;&#x20; render &#x20;&#x25;&#x7D;` api of the `vf-card-container as needed.

to

To set the `aspect-ratio` you will need to set the `card_custom_aspect_ratio` key/value pair in the `.yml` or the `{% render %}` api of the `vf-card-container as needed.

in components/vf-card-container/README.md

**Comment by nikiforosk** [comment]
I have a updated the documentation as described in this issue (and in #1884). This is the pull request: https://github.com/visual-framework/vf-core/pull/1890

**Comment by nikiforosk** [comment]
This is now in latest: https://latest.visual-framework.dev/components/vf-card-container

**Comment by nikiforosk** [comment]
Pushed to stable with the latest release: https://stable.visual-framework.dev/components/vf-card-container/
