### ISSUE TITLE
BUG - Identical changelogs in all component's changelog section

### ISSUE THREAD

**Issue by MGS-sails** [visual-framework/vf-core#1874]
The changes logs for a lot of the components, seem to be identical. And they also do not match the versions as stated on the NPM registry. However, the changelog.md files appear to match what is on NPM. See the change logs of the example components below, also when you compare them to the latest versions as stated on NPM, you will see that they do not match up:

https://stable.visual-framework.dev/components/embl-grid/index.html?q=@visual-framework/embl-grid
https://stable.visual-framework.dev/components/vf-pagination/index.html?q=pagination
https://stable.visual-framework.dev/components/vf-button/index.html?q=button

**Comment by bhushan-ebi** [comment]
@MGS-sails can  you please review the bug fix on https://latest.visual-framework.dev/  and share your findings?

**Comment by MGS-sails** [comment]
@bhushan-ebi @nikiforosk thanks for looking into this. 
I can see that the changelog is no longer identical for individual components. 
However, I noticed that for the vf-pagination component, there is a slight mismatch between the changelog and the version history on the NPM registry. 
Observe the 2 images attached:
On the changelog, the version after 1.0.1, is 1.0.1-rc.2 where as on the NPM registry, its 1.0.1-rc.3. 
This is just an example. There seem to also be other mismatches between the 2. 

I'm not sure if this is necessarily a big deal.  More importantly I can see that the changelogs are no longer identical.

**Comment by nikiforosk** [comment]
@bhushan-ebi can you please create a follow-up task to address @MGS-sails comment above?

**Comment by bhushan-ebi** [comment]
@MGS-sails thanks for your  review and for the findings about changelog mismatch. I've created #1898 to take care of this in coming sprints.
CC : @nikiforosk
