### ISSUE TITLE
Upgrade 11ty version

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1875]
This ticket is to upgade the 11ty v2 version, PR is already given by Ken https://github.com/visual-framework/vf-core/pull/1848
We need to test and verify and accordingly include in release

- [x] Merge the pull request of Ken and test the VF website if everything working
- [x] Make the same changes of upgrade on EBI corporate website see https://github.com/visual-framework/vf-core/issues/1886
- [ ] Make the same changes of upgrade on EMBL corporate website see https://github.com/visual-framework/vf-core/issues/1887

**Comment by bhushan-ebi** [comment]
Ken's pull request was closed and a similar request was opened (which had additional changes) to take care  of the upgrade.
