### ISSUE TITLE
React compatibility support for vf-hero component

### ISSUE THREAD

**Issue by sandykadam** [visual-framework/vf-core#1876]
Currently, we only have Nunjucks and HTML support for each component. This ticket is created to make [vf-hero](https://stable.visual-framework.dev/components/vf-hero/index.html) component with [React js](https://reactjs.org/) support format.

This should support all variants of `vf-hero` and other supporting parameters as given in the documentation.

**Comment by bhushan-ebi** [comment]
Changes are ready and should be available on dev site (https://latest.visual-framework.dev/) for testing after next deployment. 
PR - https://github.com/visual-framework/vf-core/pull/2004

**Comment by sandykadam** [comment]
All is fine, Good to close this ticket
