### ISSUE TITLE
React compatibility support for vf-banner component

### ISSUE THREAD

**Issue by sandykadam** [visual-framework/vf-core#1878]
Currently, we only have Nunjucks and HTML support for each component. This ticket is created to make [vf-banner](https://stable.visual-framework.dev/components/vf-banner/) component with [React js](https://reactjs.org/) support format.

This should support all variants of `vf-banner` and other supporting parameters as given in the documentation.

**Comment by bhushan-ebi** [comment]
Changes are ready and should be available on dev site (https://latest.visual-framework.dev/) for testing after next deployment. 
PR - https://github.com/visual-framework/vf-core/pull/2005

**Comment by sandykadam** [comment]
All is fine, good to close the ticket.
