### ISSUE TITLE
Angular compatibility support for vf-banner component

### ISSUE THREAD

**Issue by sandykadam** [visual-framework/vf-core#1879]
Currently, we only have Nunjucks and HTML support for each component. This ticket is created to make [vf-banner](https://stable.visual-framework.dev/components/vf-banner/index.html) component with [Angular](https://angular.io/) support format.

This should support all variants of `vf-banner` and other supporting parameters as given in the documentation.

- [x] Make sure it will work for Angular projects and update the document to which angular version it will support
- [ ] Make sure it supports all varients and parameters as it is working now in HTML & Nunjucks version
- [x] Test these angular changes in a plain angular project locally and see if everything works

**Comment by bhushan-ebi** [comment]
vf-banner currently supports 'basic' and 'inline' variant. #1925  created to support 'fixed' and 'top' variant as it has dependency on vf-button component, which is not updated yet to latest Angular.
