### ISSUE TITLE
Review Elements and Layout components

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1880]
See the description of #1838 for objectives and related links. 

This is the first step in the review focusing on 

- [x] Elements
- [x] Layout
- [x] [Design tokens](https://stable.visual-framework.dev/design-tokens/)

**Comment by Adedoyinebi** [comment]
Elements - Effort: 15
Layout - Effort: 5
Tokens - Effort: 4

**Comment by nikiforosk** [comment]
@Adedoyinebi has [completed the review of Elements](https://docs.google.com/spreadsheets/d/1jan7jnM_Bdhr5HStoGnfytx_izNNBoPeyth0-009VcQ/edit#gid=0&fvid=1389102366) and has started looking at Layout and Design tokens.

We added various tasks on the product backlog based on the review so far and created issue #1922 to finish the review.
