### ISSUE TITLE
Add missing descriptions for components

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1883]
Add missing descriptions for components in the spreadsheet with the search index results (requires permission to view):
https://docs.google.com/spreadsheets/d/1Bdke2QVWPJ47TNvd0rqPLznyvNUUx_-d/edit?usp=sharing&ouid=115682926722519271452&rtpof=true&sd=true

Part of #1854

**Comment by nikiforosk** [comment]
Estimate: 13 components to review x 2 hours each: 26hs

Revised estimate: 2 days -> 16hs

**Comment by nikiforosk** [comment]
I've added descriptions to pages in /component and noticed the following odd ones:

**Empty pages** (which should be retired?):
- https://stable.visual-framework.dev/components/previews/index.html
- https://stable.visual-framework.dev/components/preview/preview/index.html
- https://stable.visual-framework.dev/components/dist/dist/index.html

Pages that (should) **redirect** to other pages:
-  https://stable.visual-framework.dev/components/vf-design-tokens/index.html has a link to https://stable.visual-framework.dev/design-tokens/
- https://stable.visual-framework.dev/developing/components/creating-new-components/index.html 
currently gives a 404 but should redirect to https://stable.visual-framework.dev/guidance/creating-components/
- https://stable.visual-framework.dev/developing/components/updating-a-component/index.html redirect to https://stable.visual-framework.dev/guidance/versioning-and-component-interoperability/
- https://stable.visual-framework.dev/developing/components/deprecating-components/index.html redirect to https://stable.visual-framework.dev/guidance/deprecating-components/

**Video teaser**
- https://stable.visual-framework.dev/components/vf-video-teaser
I'm not sure what this component is meant to do (compared to vf-video-container)

I also noticed that when [I search for "component"](https://stable.visual-framework.dev/search/?search_query=component) I get a lot of older component updates with the repeated but not informative snippet "Component updates" (which is the same as the title of the document).

Similarly, [when I search for release](https://stable.visual-framework.dev/search/?search_query=release), the snippet is the same as the link in the search results. E.g. for "Rollup release 2.5.0" the snippet is "Rollup release 2.5.0" whereas it would be better to use the first few lines of the first paragraph, i.e. "We're excited to release rollup version 2.5.0. It's our first stable rollup in two months..."

**Comment by sandykadam** [comment]
> **Empty pages** (which should be retired?):
> 
> * https://stable.visual-framework.dev/components/previews/index.html
> * https://stable.visual-framework.dev/components/preview/preview/index.html
> * https://stable.visual-framework.dev/components/dist/dist/index.html

Yes above pages we can have a ticket to remove it from build process. Technically they are not public pages but they are required as part of building 11ty pages.


> Pages that (should) **redirect** to other pages:
> 
> * https://stable.visual-framework.dev/components/vf-design-tokens/index.html has a link to https://stable.visual-framework.dev/design-tokens/
> * https://stable.visual-framework.dev/developing/components/creating-new-components/index.html
>   currently gives a 404 but should redirect to https://stable.visual-framework.dev/guidance/creating-components/
> * https://stable.visual-framework.dev/developing/components/updating-a-component/index.html redirect to https://stable.visual-framework.dev/guidance/versioning-and-component-interoperability/
> * https://stable.visual-framework.dev/developing/components/deprecating-components/index.html redirect to https://stable.visual-framework.dev/guidance/deprecating-components/

For redirects, again we can have a ticket and can setup redirects for relevant pages.



> **Video teaser**
> 
> * https://stable.visual-framework.dev/components/vf-video-teaser
>   I'm not sure what this component is meant to do (compared to vf-video-container)

I guess this is not used anywhere but we can do scan on both corporate site and accordingly take decision to upgrade this component or deprecate it. A container is a collection of its small components and hence needed some extra changes to accommodate those collection displays.



> I also noticed that when [I search for "component"](https://stable.visual-framework.dev/search/?search_query=component) I get a lot of older component updates with the repeated but not informative snippet "Component updates" (which is the same as the title of the document).
> 
> Similarly, [when I search for release](https://stable.visual-framework.dev/search/?search_query=release), the snippet is the same as the link in the search results. E.g. for "Rollup release 2.5.0" the snippet is "Rollup release 2.5.0" whereas it would be better to use the first few lines of the first paragraph, i.e. "We're excited to release rollup version 2.5.0. It's our first stable rollup in two months..."

These are release notes for each release and we have fix template which has a fixed title, for some releases we changed it, for some of them we kept it as it is, hence you might see similarities but in reality, they are unique releases and as a search functionality we scan all pages so users can search release documents.

**Comment by nikiforosk** [comment]
I created follow-up tasks as suggested by Sandeep above:

- #1900 
- #1901 
- #1902 
- #1903
