### ISSUE TITLE
Hidden header in vf-card container shouldn't be a link

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1884]
By looking at the code of [the example with the hidden cards](https://stable.visual-framework.dev/components/vf-card-container/#vf-card-container--section-header-hidden), I noticed that the hidden header is a link:

`<h2 class="vf-section-header__heading vf-section-header__heading--is-link vf-u-sr-only"><a href="JavaScript:Void(0);">Missions</a><svg aria-hidden="true" class="vf-section-header__icon | vf-icon vf-icon-arrow--inline-end" width="1em" height="1em" xmlns="http://www.w3.org/2000/svg"><path d="M0 12c0 6.627 5.373 12 12 12s12-5.373 12-12S18.627 0 12 0C5.376.008.008 5.376 0 12zm13.707-5.209l4.5 4.5a1 1 0 010 1.414l-4.5 4.5a1 1 0 01-1.414-1.414l2.366-2.367a.25.25 0 00-.177-.424H6a1 1 0 010-2h8.482a.25.25 0 00.177-.427l-2.366-2.368a1 1 0 011.414-1.414z" fill="" fill-rule="nonzero"></path></svg></h2>`

This isn't best practice because when you navigate with the keyboard the header is selected as a link but it isn't visible to the user.  

- [x] Change the hidden header to a header without a link (i.e. [the default variant](https://stable.visual-framework.dev/components/vf-section-header/index.html#vf-section-header--default))
- [x] We should also check with @kasprzyk-sz on whether the hidden header in the corresponding WordPress block is the default variant.
- [x] Update the documentation to mention that the hidden header should be a header without a link (this should be part of #1873)

_Originally posted by @nikiforosk in https://github.com/visual-framework/vf-core/issues/1873#issuecomment-1447991851_

**Comment by bhushan-ebi** [comment]
Hi @kasprzyk-sz, can you please provide your comment on 2nd bullet point  above?

**Comment by bhushan-ebi** [comment]
Hi @nikiforosk, can you please confirm if you  are taking care of the 3rd bullet point above when working  on the ticket #1873

**Comment by nikiforosk** [comment]
@bhushan-ebi Yes I'll take care of the 3rd bullet point as part of #1873.

Regarding the 2nd point, I think @sandykadam mentioned during the sprint planning meeting that the option to hide the section header in the WordPress Container block is available only if the header isn't a link, which is how we'd like it to be. But it would be useful if @kasprzyk-sz can confirm this.

**Comment by bhushan-ebi** [comment]
Thanks @nikiforosk . Yes @sandykadam confirmed about the 2nd point that it's taken care of already.

**Comment by kasprzyk-sz** [comment]
Sorry for coming late to this. In WordPress block it depends what kind of `section header` variant the user selects.


![Image](https://user-images.githubusercontent.com/54020899/223959894-c6fda87f-67c9-4013-9ad4-8f560c620866.png)


 By default, however, only the `<h2>` tag is outputed.

**Comment by nikiforosk** [comment]
> - [x] Update the documentation to mention that the hidden header should be a header without a link (this should be part of #1873)

I updated the documentation to address this bullet point and the suggestions in #1873. This is the pull request: https://github.com/visual-framework/vf-core/pull/1890

**Comment by nikiforosk** [comment]
This is now in latest: https://latest.visual-framework.dev/components/vf-card-container

**Comment by nikiforosk** [comment]
> Sorry for coming late to this. In WordPress block it depends what kind of `section header` variant the user selects.
> 
> ![Image](https://user-images.githubusercontent.com/54020899/223959894-c6fda87f-67c9-4013-9ad4-8f560c620866.png)
> 
> By default, however, only the `<h2>` tag is outputed.

I had a quick look at the WordPress editor and I noticed that I can hide a `section header` that is a link:

![Screenshot 2023-03-16 at 09 50 24](https://user-images.githubusercontent.com/20280139/225580506-7a46217e-a99e-43e5-acbb-105b4099f097.png)

Ideally, we'd like the "Show header" option to be available only for the section headers that are **not** links. 

@kasprzyk-sz I created an issue in the wp repo about this: https://github.com/visual-framework/vf-wp/issues/1236

**Comment by sandykadam** [comment]
@nikiforosk if that is the case then we should update the example on card-container page as well, because there we have subheading and text as well.

This fix was generic to any heading type right and not just fixed to link
