### ISSUE TITLE
Add updated descriptions to components

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1885]
Update the component documentation with the descriptions from #1883.

- [ ] Need to add an `##About` section and add the descriptions in the spreadsheet below.
- [ ] The descriptions to be added are marked with a blue cell background [in the sheet called "issue 1885" in this spreadsheet (requires access)](https://docs.google.com/spreadsheets/d/1Bdke2QVWPJ47TNvd0rqPLznyvNUUx_-d/edit#gid=813966481).

Read [How to update component documentation in git (Jun 2023)](https://docs.google.com/document/d/1z449Qten640oFZzL3ayTVZ9A7u58vm0CNOl5jDsbgww/edit#heading=h.5w1vqtsurxbx).

Tracked by #1854

**Comment by bhushan-ebi** [comment]
Changes are deployed on dev site (https://latest.visual-framework.dev/) for testing and will be pushed to live site in next deployment. 
PR - https://github.com/visual-framework/vf-core/pull/2001

**Comment by sandykadam** [comment]
CHanges looks ok, good to close ticket
