### ISSUE TITLE
FEATURE - Add z-index map and function

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#19]
So far we have used z-index in three places:

[vf-form__input](https://github.com/visual-framework/vf-core/blob/develop/components/elements/vf-form/vf-form__input/vf-form__input.scss#L32)
[vf-masthead](https://github.com/visual-framework/vf-core/blob/develop/components/blocks/vf-masthead/vf-masthead.scss#L84)
[vf-data-protecion-banner](https://github.com/visual-framework/vf-core/blob/pattern/data-protection/components/blocks/vf-data-protection-banner/vf-data-protection-banner.scss#L27)

These are based on [my novel way of using z-index](http://www.alwaystwisted.com/articles/2014-07-22-talkin-bout-z-index) but I think we should move towards something that makes use of Sass, it's variables, functions, and maps.

Something [like this](https://www.sitepoint.com/better-solution-managing-z-index-sass/)

So that we call the z-index with a function that references the map of variables.

I guess for now, we only need to look at the ones we currently have, and we can add and adapt as the component library fills out a little more.

Thoughts?

**Comment by khawkins98** [comment]
Might be worth revisiting this in the next few weeks, noticed a first z-index issue on the microsites:

https://wwwdev.ebi.ac.uk/about/teams/protein-function-development/

![zindex](https://user-images.githubusercontent.com/928100/60335452-43082300-999e-11e9-9c14-d44fdb6a2a10.gif)

**Comment by sturobson** [comment]
Cool - it can be something that is a 'design token' - even though this only really effects web things. I could get that into this weeks 'design tokens sprint'.

**Comment by sturobson** [comment]
… although in this css I would suggest that the z-index of the banner needs bumping up - which can be a `hack.scss` addition to `vf-wp`.

**Comment by sturobson** [comment]
regarding [your comment](https://github.com/visual-framework/vf-core/issues/19#issuecomment-506682724) I think this should be something that's added to the 'hack' file for `vf-wp` rather than something that's added in `vf-core` to fix

**Comment by khawkins98** [comment]
This one close-able now?
