### ISSUE TITLE
Remove empty pages from build process

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1900]
> **Empty pages** (which should be retired?):
> 
> * https://stable.visual-framework.dev/components/previews/index.html
> * https://stable.visual-framework.dev/components/preview/preview/index.html
> * https://stable.visual-framework.dev/components/dist/dist/index.html
> * https://stable.visual-framework.dev/components/src/src/index.html

Yes above pages we can have a ticket to remove it from build process. Technically they are not public pages but they are required as part of building 11ty pages.

_Originally posted by @sandykadam in https://github.com/visual-framework/vf-core/issues/1883#issuecomment-1460496971_

Tracked by #1854

**Comment by bhushan-ebi** [comment]
Changes should be available on dev site (https://latest.visual-framework.dev/) for testing after next deployment. 
PR - https://github.com/visual-framework/vf-core/pull/2006

**Comment by sandykadam** [comment]
Tested and working as expected pages now showing 404. Good to close ticket.
