### ISSUE TITLE
Set up redirects to other pages

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1901]
> Pages that (should) **redirect** to other pages:
> 
> * https://stable.visual-framework.dev/components/vf-design-tokens/index.html has a link to https://stable.visual-framework.dev/design-tokens/
> * https://stable.visual-framework.dev/developing/components/creating-new-components/index.html
>   currently gives a 404 but should redirect to https://stable.visual-framework.dev/guidance/creating-components/
> * https://stable.visual-framework.dev/developing/components/updating-a-component/index.html redirect to https://stable.visual-framework.dev/guidance/versioning-and-component-interoperability/
> * https://stable.visual-framework.dev/developing/components/deprecating-components/index.html redirect to https://stable.visual-framework.dev/guidance/deprecating-components/

For redirects, again we can have a ticket and can setup redirects for relevant pages.

_Originally posted by @sandykadam in https://github.com/visual-framework/vf-core/issues/1883#issuecomment-1460496971_

**Comment by bhushan-ebi** [comment]
Changes should be available on dev site (https://latest.visual-framework.dev/) for testing after next deployment. 
PR - https://github.com/visual-framework/vf-core/pull/2006

**Comment by sandykadam** [comment]
Tested all redirects on latest site, all working as expected. Good to close the ticket.
