### ISSUE TITLE
Add missing descriptions for release document pages (component updates)

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1903]
Add missing descriptions to component updates in the spreadsheet ([row 315 onwards](https://docs.google.com/spreadsheets/d/1Bdke2QVWPJ47TNvd0rqPLznyvNUUx_-d/edit#gid=1453097999&range=A315)).

----

> I also noticed that when [I search for "component"](https://stable.visual-framework.dev/search/?search_query=component) I get a lot of older component updates with the repeated but not informative snippet "Component updates" (which is the same as the title of the document).
> 
> Similarly, [when I search for release](https://stable.visual-framework.dev/search/?search_query=release), the snippet is the same as the link in the search results. E.g. for "Rollup release 2.5.0" the snippet is "Rollup release 2.5.0" whereas it would be better to use the first few lines of the first paragraph, i.e. "We're excited to release rollup version 2.5.0. It's our first stable rollup in two months..."

These are release notes for each release and we have fix template which has a fixed title, for some releases we changed it, for some of them we kept it as it is, hence you might see similarities but in reality, they are unique releases and as a search functionality we scan all pages so users can search release documents.

_Originally posted by @sandykadam in https://github.com/visual-framework/vf-core/issues/1883#issuecomment-1460496971_

**Comment by nikiforosk** [comment]
@sandykadam I'm a bit unclear on what I need to do for this task.

Each release already has a paragraph under the title, e.g. for [Rollup release 2.5.0](https://stable.visual-framework.dev/updates/2021-07-29-component-updates/) the text is:

> We're excited to release rollup version 2.5.0. It's our first stable rollup in two months and brings a level of maturation of existing components.

However, this text doesn't show up in the snippet [when I search for "release"](https://stable.visual-framework.dev/search/?search_query=release):

![Image](https://user-images.githubusercontent.com/20280139/227922354-4494f98b-fad0-41fc-828f-6a0a1a366194.png)

I think that we discussed adding this text to the spreadsheet but I'm not sure how this will help given that it's already there on the page. I think it's more of a question of making sure that the text is shown in the search results?

**Comment by sandykadam** [comment]
@nikiforosk we decided to have the release description for these release pages, which will be covered in your exercise of adding descriptions in an excel sheet for all pages so it will display on search results.
