### ISSUE TITLE
Update documentation of vf-form components

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1904]
Update the documentation of [the vf-form components](https://stable.visual-framework.dev/components/#form) so that they are cross linked to [the vf-form example](https://stable.visual-framework.dev/components/vf-form/) and vice versa:

- [ ] The descriptions to be added are marked with a blue cell background [in the sheet called "forms 1904" in this spreadsheet (requires access)](https://docs.google.com/spreadsheets/d/1Bdke2QVWPJ47TNvd0rqPLznyvNUUx_-d/edit#gid=441654993).

Read [How to update component documentation in git (Jun 2023)](https://docs.google.com/document/d/1z449Qten640oFZzL3ayTVZ9A7u58vm0CNOl5jDsbgww/edit#heading=h.5w1vqtsurxbx).

Follow-up from #1854

**Comment by Adedoyinebi** [comment]
As discussed in the standup today

- To show cross linkage between [the vf-form components](https://stable.visual-framework.dev/components/#form) and [the vf-form example](https://stable.visual-framework.dev/components/vf-form/) and vice versa. Link will be added to the vf-form component’s intro text **“The vf-form is the wrapping component for [all form elements](https://stable.visual-framework.dev/components/#form)”** which directs to the section showing the [form elements](https://stable.visual-framework.dev/components/#form).
- The documentation of [vf-form__legend](https://stable.visual-framework.dev/components/vf-form__legend/) will be updated as shown in the [excel sheet prepared by Niki](https://docs.google.com/spreadsheets/d/1Bdke2QVWPJ47TNvd0rqPLznyvNUUx_-d/edit#gid=441654993).

**Comment by Adedoyinebi** [comment]
This change will be taken care of in the task Add updated descriptions to components #1885 by @bhushan-ebi

**Comment by bhushan-ebi** [comment]
Changes are deployed on dev site (https://latest.visual-framework.dev/) for testing and will be pushed to live site in next deployment. 
PR - https://github.com/visual-framework/vf-core/pull/2002

**Comment by sandykadam** [comment]
Document changes looks fine, good to close the ticket.
