### ISSUE TITLE
Retire collapse component

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1911]
[The vf-collapse component](https://stable.visual-framework.dev/components/vf-collapse/) hasn't been fully implemented and [vf-details](https://stable.visual-framework.dev/components/vf-details/) can be used instead.

- [ ] Justification text: This component hasn't been fully implemented and [vf-details](https://stable.visual-framework.dev/components/vf-details/) can be used instead. 
- [ ] Use the red banner and the Deprecated badge as [we do for vf-box](https://stable.visual-framework.dev/components/vf-box/index.html).
- [ ] Remove from the list of Elements on the [Components page](https://stable.visual-framework.dev/components/) and the VF megamenu.
- [ ] Read [the instructions on Deprecating components](https://stable.visual-framework.dev/guidance/deprecating-components/)

**Comment by bhushan-ebi** [comment]
PR - https://github.com/visual-framework/vf-core/pull/2039
