### ISSUE TITLE
Improve vf-blockquote

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1915]
Based on feedback from the comms team, [the vf-blockquote variant](https://stable.visual-framework.dev/components/vf-blockquote/) can be improved.

- [ ] Come up with improved designs for vf-blockquote to address the feedback
- [x] visual-framework/vf-wp#1237

Docs to review:
- [ ] [Discussion document](https://docs.google.com/document/d/1AEL4XU2UM7Dz03DVt21q6aIAmnB4ENAh4IOksN4GBJQ/edit#heading=h.am2vybcg3sol)
- [ ] News items guidelines: [see comments about blockquote](https://docs.google.com/document/d/1R6mrKSUobsxgB3UunLVrHkja02iyKfGkeqK__FCTEus/edit#bookmark=id.catywzw1b9eb) 

Similar components
- [ ] [Inset text in gov.uk](https://design-system.service.gov.uk/components/inset-text/) (Also see [Cost of living payment page](https://www.gov.uk/guidance/cost-of-living-payment) that uses inset text and warning text):
> Some users do not notice inset text if it’s used on complex pages or near to other visually prominent elements. For this reason, avoid using inset text as a way of highlighting very important information that users need to see.

**Comment by Adedoyinebi** [comment]
Updated design for the vf-blockquote
- Slides showing the [overview of the updated design](https://docs.google.com/presentation/d/16l51KsJJ7lDMcEGlHJtNUYccevamNj_Aae3Y60aXDsU/edit#slide=id.p)
- [vf-blockquote in the figma design library](https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?node-id=4060%3A2284&t=iB5xccykP2VHDFYY-1)
- [Figma mockups](https://www.figma.com/file/xOI3wE6Z1SdG2smyu71myL/test-page?node-id=433%3A824&t=x0ZWirKeQGRI3PW5-1) of the updated vf-blockquote design

**Comment by nikiforosk** [comment]
Implementation task: #1945
