### ISSUE TITLE
Use primary text colour for vf-list

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1916]
[The variants of vf-list](https://stable.visual-framework.dev/components/vf-list/index.html?q=list) that have a 16px font size also use the secondary text colour `#373a36`. We should change the colour of these variants to the primary text colour `#1A1C1A`

**Comment by Adedoyinebi** [comment]
On inspection of the [vf-list](https://stable.visual-framework.dev/components/vf-list/index.html?q=list) variants, the affected examples have been listed below. 

List of examples affected in the vf-list:

- [Default variant](https://stable.visual-framework.dev/components/vf-list/index.html?q=list#:~:text=Variants-,Default%20variant,-a%20list%20item)
- [Tight variant](https://stable.visual-framework.dev/components/vf-list/index.html?q=list#:~:text=Tight%20variant,-a%20list%20item)
- [Inline variant](https://stable.visual-framework.dev/components/vf-list/index.html?q=list#:~:text=Inline%20variant,-a%20list%20item)
- [Ordered variant](https://stable.visual-framework.dev/components/vf-list/index.html?q=list#:~:text=Ordered%20variant,-a%20list%20item)
- [Unordered variant](https://stable.visual-framework.dev/components/vf-list/index.html?q=list#:~:text=Unordered%20variant,-a%20list%20item)

@bhushan-ebi **Dev Tasks**

- Investigate if the colour inconsistency affects just the [vf-list](https://stable.visual-framework.dev/components/vf-list/index.html?q=list) examples or the cases where it has be used on services and sites
- Update the colour of the listed variants from the **secondary text colour #373A36** to the **primary text colour #1A1C1A** to ensure consistency

@Adedoyinebi **Documentation Task**
- Create a follow up task to create documentation to the [vf-list](https://stable.visual-framework.dev/components/vf-list/index.html?q=list) as there is no documentation on this component

**Comment by Adedoyinebi** [comment]
Follow up task has been created to add documentation to the [Vf-list](https://stable.visual-framework.dev/components/vf-list/)

**Link to follow up task**
- [Add documentation for VF-list](https://github.com/visual-framework/vf-core/issues/1997) #1997

**Comment by bhushan-ebi** [comment]
On further investigation in this task it was found that changing the colour from secondary to primary would have widespread impact on other components. 
Finding:
The _typography.scss file has a mixin named set-type() which returns the secondary colour #373A36 for text-body--3, text-body--4, text-body--5. This mixin is being called from multiple component SCSS files and so changing the mixin to return primary colour #1A1C1A would affect all these components.
Since both the colours are nearly similar we can still do this change but further discussion is needed among team members before we go ahead.

**Comment by bhushan-ebi** [comment]
Other similar issue which needs to be reviewed - https://github.com/visual-framework/vf-core/issues/1949

**Comment by Adedoyinebi** [comment]
The best practice from patterns observed in other design systems showed a consistent use of colours in the defined list items, some examples are:

[Gov.uk’s design system (Lists)](https://design-system.service.gov.uk/styles/lists/#numbered-lists)

- All list types and defined texts use the same primary text colour from the [colour token](https://design-system.service.gov.uk/styles/colour/).



![Image](https://github.com/visual-framework/vf-core/assets/126486114/24cb16a3-26ba-4f70-a5b7-b7035cd3f159)



[Polaris - by Shopify (Lists)](https://polaris.shopify.com/components/lists/list?example=list-numbered)

- All the list variants use the same default text colour **#303030 (**RGBA: 48,48, 48,1**).** " —p-colour-text"



![Image](https://github.com/visual-framework/vf-core/assets/126486114/cac79a6a-fce9-4e57-9d9d-549f99eaa4dc)

To ensure consistency of the design of vf list items I would recommend that the variants be updated to the **primary text colour #1A1C1A**

@bhushan-ebi  Next steps:

Update the following list items colour to the primary text colour **#1A1C1A:**

- [Default variant](https://stable.visual-framework.dev/components/vf-list/index.html?q=list#:~:text=Variants-,Default%20variant,-a%20list%20item)
- [Tight variant](https://stable.visual-framework.dev/components/vf-list/index.html?q=list#:~:text=Tight%20variant,-a%20list%20item)
- [Inline variant](https://stable.visual-framework.dev/components/vf-list/index.html?q=list#:~:text=Inline%20variant,-a%20list%20item)
- [Ordered variant](https://stable.visual-framework.dev/components/vf-list/index.html?q=list#:~:text=Ordered%20variant,-a%20list%20item)
- [Unordered variant](https://stable.visual-framework.dev/components/vf-list/index.html?q=list#:~:text=Unordered%20variant,-a%20list%20item)

**Comment by Adedoyinebi** [comment]
Follow up task has been created for the implementation of this update https://github.com/visual-framework/vf-core/issues/2041. Closing this task.
