### ISSUE TITLE
Add vf-figure component to Figma library

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1919]
The vf-figure component isn't in the Figma library:

- [ ] Check with Oana from comms on if they have any suggestions for improving this component
- [ ] Check where the component and its variants are used in our sites

- [ ] Create a mockup of (the revised component) in Figma
- [ ] Decide if we'll include the different variants in Figma

**Comment by bhushan-ebi** [comment]
Create a version in figma that is in sync with what we have on the HTML. In future we can update based on additional requirements.

**Comment by Adedoyinebi** [comment]
The [vf-figure ](https://stable.visual-framework.dev/components/vf-figure/) has been [created in figma](https://www.figma.com/design/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?node-id=5621-904&t=WWGvfBya2t4DwAAI-1) based on the current design on the [html](https://stable.visual-framework.dev/components/vf-figure/) site as discussed.

However, alignment options such as:

- [Align Inline Start variant](https://stable.visual-framework.dev/components/vf-figure/#:~:text=Align%20Inline%20Start%20variant)
- [Align Inline End variant](https://stable.visual-framework.dev/components/vf-figure/#:~:text=Align%20Inline%20End%20variant)
- [Align Centered variant](https://stable.visual-framework.dev/components/vf-figure/#:~:text=Align%20Centered%20variant)

Have not been added in figma as this functionality depends on the container and layout used in figma, hence it is more applicable in dev as it could be obstructive if added to the component in figma

**Useful links**

- [Vf-figure in figma](https://www.figma.com/design/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?node-id=5621-904&t=WWGvfBya2t4DwAAI-1)

@OliveiraCs  Kindly review the component before it is published to the figma design library

**Comment by OliveiraCs** [comment]
Review conducted on the vf-figure in Figma. I have not identified any further actions required for this component.

**Comment by Adedoyinebi** [comment]
The vf-figure has been published in the [figma library.](https://www.figma.com/design/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?node-id=5621-904&t=f2QH7na4dymX0d6D-1) Closing this task
