### ISSUE TITLE
Retire vf-explainer component

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1920]
The implementation of [the vf-explainer](https://stable.visual-framework.dev/components/vf-explainer/index.html?q=explainer) component hasn't been completed. 

The basic use case for providing details is supported by [vf-details](https://stable.visual-framework.dev/components/vf-details/). For highlighting explanations we suggested that the Comms team uses [vf-card](https://stable.visual-framework.dev/components/vf-card/).

- [ ] Justification text: This component hasn't been implemented. The basic use case for providing details is supported by [vf-details](https://stable.visual-framework.dev/components/vf-details/). For highlighting explanations we suggested that the Comms team uses [vf-card](https://stable.visual-framework.dev/components/vf-card/).
- [ ] Use the red banner and the Deprecated badge as [we do for vf-banner](https://stable.visual-framework.dev/components/vf-box/index.html).
- [ ] Remove from the list of Elements on the [Components page](https://stable.visual-framework.dev/components/) and the VF megamenu.
- [ ] Read [the instructions on Deprecating components](https://stable.visual-framework.dev/guidance/deprecating-components/)

**Comment by sandykadam** [comment]
As of now, this component is not used anywhere in any website. This was just an experimental component added.

**Comment by bhushan-ebi** [comment]
PR - https://github.com/visual-framework/vf-core/pull/2040
