### ISSUE TITLE
Finish review of Layout components and Design tokens

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1922]
@Adedoyinebi to finish the review of the following:

- [x] Layout components
- [x] [Design tokens](https://stable.visual-framework.dev/design-tokens/) 

See the description of #1838 for objectives and related links. 

This is a follow up task from #1880

**Comment by Adedoyinebi** [comment]
**Layouts** 

- The layout guidelines have been reviewed and documented in the [excel sheet](https://docs.google.com/spreadsheets/d/1jan7jnM_Bdhr5HStoGnfytx_izNNBoPeyth0-009VcQ/edit?usp=sharing). Layouts in HTML which do not have use cases in figma as they already have be catered for by [grids](https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?type=design&node-id=367%3A217&mode=design&t=fzMB2HUCQSgjXuVv-1) and [spacing tokens](https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?type=design&node-id=65%3A1141&mode=design&t=fzMB2HUCQSgjXuVv-1) do not need to be added in the figma library. Examples of such layout components are: [Body](https://stable.visual-framework.dev/components/vf-body/), [Cluster](https://stable.visual-framework.dev/components/vf-cluster/), [Sidebar layout](https://stable.visual-framework.dev/components/vf-sidebar/) and [Stack](https://stable.visual-framework.dev/components/vf-stack/) as these layout guides are more applicable in the development phase.

**Design Tokens**

-  Spacing and size 

Has been reviewed and the observations documented in the excel sheet. All [Spacing tokens](https://stable.visual-framework.dev/design-tokens/spacing/#:~:text=Breakpoints-,Spacing,-Spacing%200) and [breaking points](https://stable.visual-framework.dev/design-tokens/spacing/#:~:text=vf%2Dspacing%2D%2D1600-,Breakpoint%20widths,-Extra%20Small%20Breakpoint) in the visual framework are available and consistent in figma and the vf site with the exception of the [Spacing 0](https://stable.visual-framework.dev/design-tokens/spacing/#:~:text=Breakpoints-,Spacing,-Spacing%200) --vf-spacing--0 which is [not in figma](https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?type=design&node-id=65%3A1141&mode=design&t=3Jb7meX9YQPdjSH7-1) but also not required.

- Colours

Have been reviewed and documented in the [excel sheet](https://docs.google.com/spreadsheets/d/1jan7jnM_Bdhr5HStoGnfytx_izNNBoPeyth0-009VcQ/edit?usp=sharing). New issue has been created to address the inconsistency observed in figma ([Update the definition of the token for "link colour" in figma](https://github.com/visual-framework/vf-core/issues/1998) #1998 ).

- Typography

Typography tokens have been reviewed and the findings documented in the [excel sheet](https://docs.google.com/spreadsheets/d/1jan7jnM_Bdhr5HStoGnfytx_izNNBoPeyth0-009VcQ/edit?usp=sharing), subsequently a [proposal was created](https://www.figma.com/file/6OfOhIu5zq4OBW2HaS7UEe/Typography-Proposal?type=design&node-id=4%3A2&mode=design&t=AiA9f8fKPOtEDSLz-1) to address the issues observed and [simplify the description of typography](https://github.com/visual-framework/vf-core/issues/1926) and typography tokens, see issue #1926 for details.

@geetikamalhotra please review

**Comment by Adedoyinebi** [comment]
@stefangutnick please review this task

**Comment by stefangutnick** [comment]
@Adedoyinebi I did some spot-checking on the excel sheet and it all looks good to me. Big task. I suppose this is something that needs to be continuously updated to stay correct.
