### ISSUE TITLE
Simplify description of typography and headings

### ISSUE THREAD

**Issue by nikiforosk** [visual-framework/vf-core#1926]
During [the review of Elements](https://github.com/visual-framework/vf-core/issues/1880) we noticed that the descriptions of typography and headings in Figma and the VF site are too complicated. The purpose of this task is to make these descriptions simpler to understand and use:

- [ ] Simpler description of typography and heading Elements

Related descriptions of components:

**Typography**

- [ ] [VF Text](https://stable.visual-framework.dev/components/vf-text/)
- [ ] [Design tokens: Typography](https://stable.visual-framework.dev/design-tokens/typography/)
- [ ] [Figma: Typography](https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?node-id=6%3A0&t=Mbjv3CfcrfQyTBB5-1)
- [ ] We also need to check how typography is defined in WordPress

**Headings**

- [ ] [VF Headings](https://stable.visual-framework.dev/components/vf-heading/)
- [ ] [Design tokens: Typography](https://stable.visual-framework.dev/design-tokens/typography/)
- [ ] [Figma: Typography](https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?node-id=6%3A0&t=Mbjv3CfcrfQyTBB5-1)
- [ ] We also need to check how headings are defined in WordPress

Related documents:

- [ ] [Utility classes](https://stable.visual-framework.dev/components/vf-utility-classes/)
- [ ] [Component status (2023): Typography review](https://docs.google.com/spreadsheets/d/1jan7jnM_Bdhr5HStoGnfytx_izNNBoPeyth0-009VcQ/edit#gid=1954575919)
- [ ] [Typography presentation](https://docs.google.com/presentation/d/1rrEerrbV2iyfuqLQRFZ1JQN7PBPSw5WqLMVZjX4zB20/edit#slide=id.g1f99f728c79_0_0)

Related tasks:

- [ ] https://github.com/visual-framework/vf-core/issues/1880
- [x] https://github.com/visual-framework/vf-core/issues/1838
- [ ] https://github.com/visual-framework/vf-core/issues/1727

@Adedoyinebi please review this issue and add any related document and the link to your proposal to it.

**Comment by Adedoyinebi** [comment]
The VF-typography proposal to help simplify the usage and understanding of Typography elements and tokens:

- [Overview of changes](https://docs.google.com/presentation/d/1al2rZvFwbtvmOjhwZsgzCew5nrwfxbt1NBnpKz2jmfs/edit#slide=id.p)
- [Simplifying Typography- Headers & Texts](https://docs.google.com/document/d/1xHLYrcJjGQ7_nU2CJ-YOv8R90zNk_8kwuztcuqHIsbc/edit#)
- [Simplifying Typography tokens](https://docs.google.com/document/d/1OvKEAunsfWjk-WYSmnPecDbGnOjFrKUOd08dXLyjpQ0/edit#heading=h.24iihicfouju)

**Comment by Adedoyinebi** [comment]
[VF typography proposal mockups in figma](https://www.figma.com/file/6OfOhIu5zq4OBW2HaS7UEe/Typography-Proposal?node-id=4%3A2&t=8YvuAi8wEfhectgt-1) for the:
- Headings page
- Texts page
- Typography tokens page

**Comment by nikiforosk** [comment]
Implementation task: #1946
