### ISSUE TITLE
Identify lint errors/warnings for existing components and prepare strategy to fix and release them

### ISSUE THREAD

**Issue by sandykadam** [visual-framework/vf-core#1935]

**Comment by bhushan-ebi** [comment]
Changes are deployed on dev site (https://latest.visual-framework.dev/) for testing and will be pushed to live site in next deployment. 
PR - https://github.com/visual-framework/vf-core/pull/1999

**Comment by bhushan-ebi** [comment]
Please see status of the fixes at https://docs.google.com/spreadsheets/d/1QH3jh3S9vczEIcn4jblSs0EnRUA3DO2H52rqMVEq4kI/edit?usp=sharing

**Comment by sandykadam** [comment]
Same as #1936 The majority of the warnings/issues are fixed with this change, but we need to keep monitoring and proactively fix them with an ongoing process. Good to close this ticket
