### ISSUE TITLE
The links for the VF-tab angular version are not working as expected. 

### ISSUE THREAD

**Issue by francisco-ebi** [visual-framework/vf-core#1937]
Hello,
I have discovered a bug with the vf-tabs component.
In the Pathogen portal we have this page:
<img width="721" alt="Screenshot 2023-04-14 at 14 54 19" src="https://user-images.githubusercontent.com/5340971/232064079-92c7b3b9-2219-4cbe-9d77-60380083b8d1.png">

And if the 'ENA result' link is clicked, it doesn't preserve the 'monkeypox' path, as you can see:
<img width="1440" alt="Screenshot 2023-04-14 at 14 56 31" src="https://user-images.githubusercontent.com/5340971/232064552-1a0de459-3f6f-4d9f-aa72-66b7db2eeb6d.png">
In the VF stable site that doesn't happen so I'm assuming there is a clash between how the component updates the url and how Angular handles the routing.
Regards

**Comment by nikiforosk** [comment]
@bhushan-ebi This looks related to #1845

**Comment by bhushan-ebi** [comment]
With further follow up on this ticket and after discussion with @francisco-ebi , it's observed that this issue doesn't seem to present on the site anymore. #2037 has been created to further create Angular version of VF Tabs where this issue will be revisited.
