### ISSUE TITLE
Vf-blockquote implementation

### ISSUE THREAD

**Issue by Adedoyinebi** [visual-framework/vf-core#1945]
- The [current Vf-blockquote](https://stable.visual-framework.dev/components/vf-blockquote/)'s design has been updated to improve consistency and meet the [requirements discussed with the stakeholders](https://docs.google.com/document/d/1AEL4XU2UM7Dz03DVt21q6aIAmnB4ENAh4IOksN4GBJQ/edit#heading=h.fhl7dnnaxblq)

- The task is to implement the [updated vf-blockquote](https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?node-id=4060%3A2284&t=9u4Pt9TumowhOENS-1) design in the visual framework

Useful links
- [Discussion document](https://docs.google.com/document/d/1AEL4XU2UM7Dz03DVt21q6aIAmnB4ENAh4IOksN4GBJQ/edit#heading=h.fhl7dnnaxblq)
- [Updated vf-blockquote design ](https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?node-id=4060%3A2284&t=9u4Pt9TumowhOENS-1)
- [Mockup of the vf-blockquote](https://www.figma.com/proto/xOI3wE6Z1SdG2smyu71myL/test-page?page-id=433%3A823&node-id=433-824&viewport=301%2C849%2C0.36&scaling=min-zoom) on an article
- [Presentation on the design update](https://docs.google.com/presentation/d/16l51KsJJ7lDMcEGlHJtNUYccevamNj_Aae3Y60aXDsU/edit?usp=sharing)

Related issue 
- [Improve vf-blockquote#1915](https://github.com/visual-framework/vf-core/issues/1915)

**Comment by Adedoyinebi** [comment]
@kasprzyk-sz please look at the updates to the blockquote design to check how it would affect the Visual framework in wordpress

**Comment by kasprzyk-sz** [comment]
Hi @Adedoyinebi, looks good. Now we need to update the component and then I'll be able to implement it in WordPress

**Comment by nikiforosk** [comment]
@bhushan-ebi to implement these changes when he has time and to follow-up with @kasprzyk-sz.

**Comment by Adedoyinebi** [comment]
@bhushan-ebi Here's the updated [documentation](https://docs.google.com/document/d/1xczbGYQ9zBpHX8pkkwG8cX5ARnq6qaHJETmKeezjc0Y/edit#heading=h.8ckbh3nl2q5g) for the [vf-blockquote](https://stable.visual-framework.dev/components/vf-blockquote/index.html?q=blockquote)

**Comment by bhushan-ebi** [comment]
This change has been done and pushed to live. Please see the release log at https://stable.visual-framework.dev/updates/2023-10-09-component-updates/
