### ISSUE TITLE
Simplifying Vf-typography implementation

### ISSUE THREAD

**Issue by Adedoyinebi** [visual-framework/vf-core#1946]
From the review of the elements of the [Visual framework](https://stable.visual-framework.dev/) discrepancies were spotted between the visual framework in HTML, Figma and in the [typography tokens](https://stable.visual-framework.dev/design-tokens/spacing/) which made it difficult to understand, reference and use typography elements in the Visual framework. 

[A proposal has been created](https://docs.google.com/presentation/d/1al2rZvFwbtvmOjhwZsgzCew5nrwfxbt1NBnpKz2jmfs/edit#slide=id.g23a8dcfd639_0_87) that addresses the issues found during the review and helps to simplify typography for the users.

The task is to implement the updates to the typography pages based on the proposal.
The updates have been [mocked up in figma](https://www.figma.com/proto/6OfOhIu5zq4OBW2HaS7UEe/Typography-Proposal?page-id=0%3A1&node-id=4-2&viewport=369%2C153%2C0.17&scaling=min-zoom) for the:

- [Headings page](https://www.figma.com/file/6OfOhIu5zq4OBW2HaS7UEe/Typography-Proposal?node-id=4%3A2&t=JzakqKmtutadldaN-1)
- [Text page](https://www.figma.com/file/6OfOhIu5zq4OBW2HaS7UEe/Typography-Proposal?node-id=41%3A574&t=JzakqKmtutadldaN-1)
- [Tokens page](https://www.figma.com/file/6OfOhIu5zq4OBW2HaS7UEe/Typography-Proposal?node-id=41%3A1066&t=JzakqKmtutadldaN-1)

Related issue
- [Simplify description of typography and headings#1926](https://github.com/visual-framework/vf-core/issues/1926)
- [Review of VF components by PD#1838](https://github.com/visual-framework/vf-core/issues/1838)

**Comment by Adedoyinebi** [comment]
Related issue

- [Update colours of VF typography#1949](https://github.com/visual-framework/vf-core/issues/1949)

**Comment by bhushan-ebi** [comment]
@bhushan-ebi to work on #2043 for implementation.
