### ISSUE TITLE
Update colours of VF typography

### ISSUE THREAD

**Issue by Adedoyinebi** [visual-framework/vf-core#1949]
From the [typography review](https://docs.google.com/spreadsheets/d/1jan7jnM_Bdhr5HStoGnfytx_izNNBoPeyth0-009VcQ/edit#gid=1954575919), some VF typography elements were found to have different colours in the HTML examples from how it should be defined.

Task

- [ ] Remove the inverted colour on [1 Display variant](https://stable.visual-framework.dev/components/vf-heading/#vf-heading--1-display)
- [ ] Update the colour of "[3 Regular variant](https://stable.visual-framework.dev/components/vf-text/#vf-text--3-regular)", "[4 Small variant](https://stable.visual-framework.dev/components/vf-text/#vf-text--4-small)", and "[5 Extra Small variant](https://stable.visual-framework.dev/components/vf-text/#vf-text--5-extra-small)" of texts,  from #373A36 to the primary text colour #1a1c1a

**Comment by nikiforosk** [comment]
@Adedoyinebi to check if these are still valid after implementing the changes in #1946

**Comment by stefangutnick** [comment]
1.Removing inverted heading - are we sure we want to remove it? We are still using it on the VF site. But it does seem like it should be renamed and moved to a seperate variant.
2. Correcting variant colours: Bhushan has helped me find the correct file, however changing it will impact several other components. Not exactly sure how to proceed on this one

**Comment by stefangutnick** [comment]
![Image](https://github.com/visual-framework/vf-core/assets/82038328/98d08c99-8b3d-4710-84d6-055de90e4ac5)

**Comment by Adedoyinebi** [comment]
- Based on the discussion in the Typography proposal review meeting on Monday 13th May and after investigating best practices, we agreed to update the colour of text variants from the secondary text colour **#373A36** to the primary text colour **#1A1C1A** to ensure consistency of the typography examples.
- The  [inverted vf-heading (1 Display variant)](https://stable.visual-framework.dev/components/vf-heading/#:~:text=Variants-,1%20Display%20variant,-This%20heading%20size) should be removed and replaced with the “[Heading level 1](https://www.figma.com/design/6OfOhIu5zq4OBW2HaS7UEe/Typography-Proposal?node-id=575%3A555&t=yhK9hO765BVqVBht-1)” based on the typography proposal for headings

**Useful links:**

- Simplifying Typography in the Visual framework - [Presentation slides](https://docs.google.com/presentation/d/1BeThFyB7QuvFmDztKN5HMF3y2H31A1zNYy0Cnl4T_5o/edit?usp=sharing)
- Mockups showing updated design and documentation of:
    - [Vf-headings](https://www.figma.com/design/6OfOhIu5zq4OBW2HaS7UEe/Typography-Proposal?node-id=575%3A555&t=3T45KjfevzFfcGta-1)
    - [VF-texts](https://www.figma.com/design/6OfOhIu5zq4OBW2HaS7UEe/Typography-Proposal?node-id=575%3A995&t=3T45KjfevzFfcGta-1)
    - [VF typography tokens](https://www.figma.com/design/6OfOhIu5zq4OBW2HaS7UEe/Typography-Proposal?node-id=575%3A679&t=3T45KjfevzFfcGta-1)

@bhushan-ebi A follow up task has been created for the implementation of the proposed updates - [Implementation of updated vf-typography colours in the examples #2042](https://github.com/visual-framework/vf-core/issues/2042)
