### ISSUE TITLE
In mobile view, clicking on About leads to a 404 page 

### ISSUE THREAD

**Issue by stefangutnick** [visual-framework/vf-core#1953]
The "About" megamenu transforms to a link when the VF site is viewed on mobile. 

The link points to a non-existing page:

https://stable.visual-framework.dev/topics

It should instead point to:

https://stable.visual-framework.dev/about/

**Comment by stefangutnick** [comment]
See this line 

https://github.com/visual-framework/vf-core/blob/b2f0e918b7572b385ec32e28a138d52677df992d/tools/vf-component-library/src/site/_includes/layouts/base.njk#L64

**Comment by bhushan-ebi** [comment]
Changes should be available on dev site (https://latest.visual-framework.dev/) for testing after next deployment. 
PR - https://github.com/visual-framework/vf-core/pull/2006

**Comment by sandykadam** [comment]
Tested this url https://latest.visual-framework.dev/topics but it doesn't redirect

**Comment by bhushan-ebi** [comment]
@sandykadam, /topics is nonexistent and is not the intended link. If you change the viewport to mobile view and then click on 'about' link, it used to go to /topics. Now it's fixed to go to /about.

**Comment by sandykadam** [comment]
ah ok, got it. Working as expected then good to close this ticket.
