### ISSUE TITLE
Add auto-layout to vf-link in Figma

### ISSUE THREAD

**Issue by Adedoyinebi** [visual-framework/vf-core#1954]
Add auto layout functionality to the [vf-link component in figma](https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?type=design&node-id=983%3A108&mode=design&t=yHqmYXNYN06gSApS-1)

**Current state**

![Image](https://github.com/visual-framework/vf-core/assets/126486114/9fd6fbfa-6144-4811-8784-1031b82ea8ea)

The VF link in figma is created using frames and does not:

- Adjust the frame’s size (Height and length) when the text is updated. This has to be done manually and could lead to inconsistent designs.
- Wrap the text to the next line when the frame is adjusted, this has to be done by creating a new paragraph, which modifies the text’s content in a case where it is copied directly for development or other use cases. 

**Desired state**

Add auto layout to the link component in figma to enable:

- Frame to resize when the text is updated
- Text wrapping to the next line when the frame is adjusted

Cautionary note should be added when publishing that explains that the update could alter the layout of existing designs.

**Comment by Adedoyinebi** [comment]
Updates have been made to the [VF-link component in figma,](https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?type=design&node-id=983%3A108&mode=design&t=lkBHs8kjWsBhJAfZ-1) this changes affect the use of the component only in figma, to help create more consistent designs easily. The UI element and states of the [VF-link component](https://stable.visual-framework.dev/components/vf-link/) remain unchanged with the current update.

**Updates made**

Auto layout added to the vf-link component in figma to allow:
- Frame to resize when the text is updated
- Text wrapping to the next line when the frame is adjusted

﻿
**How to wrap texts**

- Highlight the links text
- Change the “Text resizing” setting from “Auto width” to “Auto height”

![Image](https://github.com/visual-framework/vf-core/assets/126486114/33f68a74-348f-42a7-8889-3ddc8499cec0)
- Update text’s frame’s layout from “Fixed” to “Fill container”
![Image](https://github.com/visual-framework/vf-core/assets/126486114/4a817bed-04af-43ea-a059-5bac3c2c34bf)
- Adjust the link component's frame’s width as needed. 
- Text wraps to the next line!

**Limitations**

- Text does not wrap by default.
- The layout of existing designs might be altered in some cases by the update. To reduce possibility of changes to existing design layout, the component is set to not wrap by default (Similar to how the component worked initially). Check instances in which the vf-link component has been used in your designs to address any change in the layout.

**Comment by geetikamalhotra** [comment]
- [ ] task 1 converting task to issue
- [ ] task 2 testing
- [ ] task 3 linking the tasks together

**Comment by geetikamalhotra** [comment]
- [ ] task 2 testing
- [ ] task 3 linking the tasks together
