### ISSUE TITLE
VF Twitter social icon update

### ISSUE THREAD

**Issue by Adedoyinebi** [visual-framework/vf-core#1955]
X has now updated its official [brand guidelines page](https://about.twitter.com/en/who-we-are/brand-toolkit), the social media brand icon formally known as twitter should be updated in the [visual framework](https://stable.visual-framework.dev/components/vf-social-links/index.html?q=social).

- Icon should be updated in the [figma library](https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?type=design&node-id=983%3A278&mode=design&t=2tpgWkm9a5rGvK3x-1)
- Icon should be updated in the [VF site](https://stable.visual-framework.dev/components/vf-social-links/index.html?q=social)

**Comment by Adedoyinebi** [comment]
@bhushan-ebi @geetikamalhotra Based on the updated official [brand guidelines page](https://about.twitter.com/en/who-we-are/brand-toolkit) for X(Twitter), the VF social media icon has been [updated in the figma design system](https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?type=design&node-id=983%3A278&mode=design&t=qpKDKDLyYwIkPRH1-1) to match the design format of [our social icons.](https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?type=design&node-id=983%3A278&mode=design&t=qpKDKDLyYwIkPRH1-1)

**Comment by sandykadam** [comment]
Comments from Oana (Comms team) to update sequence of social icons.
It would be LinkedIn, Twitter/X, YouTube, Facebook

cc: @kasprzyk-sz to update in vf-wp

**Comment by bhushan-ebi** [comment]
This change has been done and pushed to live. Please see the release log at https://stable.visual-framework.dev/updates/2023-10-09-component-updates/

vf-wp commits:
https://github.com/visual-framework/vf-wp/commit/64c1fe1a96804fe08363fa6c5534d5827eb92de8
https://github.com/visual-framework/vf-wp/commit/00ddf36cc9d5faa72b6bf87005c77b3f2ee7983b
