### ISSUE TITLE
Back to top button

### ISSUE THREAD

**Issue by Adedoyinebi** [visual-framework/vf-core#1956]
**Current state**

[The back to top button in the visual framework](https://stable.visual-framework.dev/components/vf-back-to-top/index.html?q=back%20to%20top) is designed to be a [primary button](https://stable.visual-framework.dev/components/vf-button/index.html?q=button#:~:text=Variants-,Primary%20variant,-Primary%20button), the action of scrolling back to the top is a secondary action for a user reading or exploring content on an article.

**Desired state**

The back to top button should be a [secondary button](https://stable.visual-framework.dev/components/vf-button/index.html?q=button#:~:text=HTML-,Secondary%20variant,-Secondary%20button) to reduce distraction from the primary goal of the user.

- Update arrow for[ back to top in Figma](https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?type=design&node-id=1601%3A1886&mode=design&t=2tpgWkm9a5rGvK3x-1).
- Update [back to top button in VF site](https://stable.visual-framework.dev/components/vf-back-to-top/index.html?q=back%20to%20top) to a [secondary button](https://stable.visual-framework.dev/components/vf-button/index.html?q=button#:~:text=HTML-,Secondary%20variant,-Secondary%20button).

**Comment by Adedoyinebi** [comment]
@bhushan-ebi The arrow on the [VF back to top button in figma ](https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?type=design&node-id=1601%3A1886&mode=design&t=Psq0ntnnRIkmgsxw-1)has been updated to align with the version on the [live environment](https://stable.visual-framework.dev/components/vf-back-to-top/index.html?q=back%20to%20top)

**Comment by bhushan-ebi** [comment]
This change has been done and pushed to live. Please see the release log at https://stable.visual-framework.dev/updates/2023-10-09-component-updates/
