### ISSUE TITLE
Update vf-breadcrumb's documentation

### ISSUE THREAD

**Issue by Adedoyinebi** [visual-framework/vf-core#1957]
The [current vf-breadcrumb documentation](https://stable.visual-framework.dev/components/vf-breadcrumbs/index.html?q=breadcrumb) recommends that the page should only show three nodes. From [the research done](https://docs.google.com/presentation/d/1ZsYfYUnkRtGG_-15Awfck65g5voC2meSVvA_qoecn5U/edit#slide=id.g25aaad0ca41_0_571), the breadcrumbs should show the full path on desktop, this should be reflected in[ the updated documentation](https://docs.google.com/document/d/1UWYZ5vcGSdESsMY6gIUfPaTLx99rjUurtqUcsWeTKEw/edit?usp=sharing).

**Comment by Adedoyinebi** [comment]
@bhushan-ebi  @sandykadam @geetikamalhotra Here’s the [file containing the updated documentation](https://docs.google.com/document/d/1UWYZ5vcGSdESsMY6gIUfPaTLx99rjUurtqUcsWeTKEw/edit?usp=sharing) for the breadcrumbs, the texts to be added are highlighted in green, the texts to be removed are strikethrough.

Based on the[ research on the breadcrumbs](https://docs.google.com/presentation/d/1ZsYfYUnkRtGG_-15Awfck65g5voC2meSVvA_qoecn5U/edit#slide=id.g25aaad0ca41_0_571) the documentation has been updated to recommend showing the full navigation path for the breadcrumb on desktop.

**Comment by bhushan-ebi** [comment]
This change has been done and pushed to live. Please see the release log at https://stable.visual-framework.dev/updates/2023-10-09-component-updates/
