### ISSUE TITLE
Update build process document with missing step

### ISSUE THREAD

**Issue by sandykadam** [visual-framework/vf-core#1966]
Once production release is done we need to revert back the `vfVersion` value to `develop` in this file [siteConfig.js](https://github.com/visual-framework/vf-core/blob/develop/tools/vf-component-library/src/site/_data/siteConfig.js#L18) so https://latest.visual-framework.dev/ (which is our DEV website) site will pick up development changes of css & js. This change needs to push back to develop branch.

This step needs to be documented in [PUBLISHING.md](https://github.com/visual-framework/vf-core/blob/develop/PUBLISHING.md) file under "Post release" section

**Comment by bhushan-ebi** [comment]
Changes for this issue are completed in last release and confirmed with @sandykadam as no further changes are needed. Closing as Done.
