### ISSUE TITLE
Bug: Vf-dropdown - Cannot click links on dropdown in Safari

### ISSUE THREAD

**Issue by francisco-ebi** [visual-framework/vf-core#1973]
@lilim-ebi from ENA discovered a bug for the Vf-dropdown. If you open https://www.covid19dataportal.org/ or https://www.pathogensportal.org/ and try to click a link on one of the dropdown's (like About or Tools), it works in Chrome and Firefox except in Safari.

The links in any vf-dropdown should be clickable in Safari.

**Comment by geetikamalhotra** [comment]
- [ ] Draft task

**Comment by geetikamalhotra** [comment]
- [ ] Accessibility testing

- [ ] Responsive solution implementation

- [ ] Comms and go live

**Comment by bhushan-ebi** [comment]
As per latest comment here https://github.com/visual-framework/vf-core/pull/1972#issuecomment-2059257275 the issue is resolved and good to be closed.
