### ISSUE TITLE
Vf-bookmark small button variant

### ISSUE THREAD

**Issue by Adedoyinebi** [visual-framework/vf-core#1974]
Based on the [request from the Training team](https://embl.service-now.com/nav_to.do?uri=sc_task.do%3Fsys_id=11b8c3081bc271503182bb35464bcb6f%26sysparm_stack=sc_task_list.do%3Fsysparm_query=active=true) a [small button variant](https://stable.visual-framework.dev/components/vf-button/) of the [vf-bookmark button](https://stable.visual-framework.dev/components/vf-bookmark/#vf-bookmark--button) is needed on some pages e.g [The course page](https://www.ebi.ac.uk/training/online/courses/a-guide-to/introduction/)

The current vf-bookmark only has the [large button variant ](https://stable.visual-framework.dev/components/vf-button/#:~:text=HTML-,Secondary%20variant,-Secondary%20button) and the [link variant ](https://stable.visual-framework.dev/components/vf-button/#vf-button--link).

The task is to add a small button variant of the bookmark component in VF

**Comment by bhushan-ebi** [comment]
Changes are deployed on dev site (https://latest.visual-framework.dev/) for testing and will be pushed to live site in next deployment. 
PR - https://github.com/visual-framework/vf-core/pull/2003

**Comment by Adedoyinebi** [comment]
The small button variant has been added to the [vf-bookmark in figma](https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?type=design&node-id=1776%3A1934&mode=design&t=U65qkQdCSUQEIOB7-1). This change has been tested and published in the [figma library](https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?type=design&node-id=1776%3A1934&mode=design&t=U65qkQdCSUQEIOB7-1).

**Comment by sandykadam** [comment]
Tested the changes and looks great, good to close this ticket.
