### ISSUE TITLE
Update blog link in about page

### ISSUE THREAD

**Issue by sandykadam** [visual-framework/vf-core#1975]
On https://stable.visual-framework.dev/about/ page there is link introduction para which needs to replace with new link.

old - https://blogs.embl.org/communications/2018/09/12/faster-scientific-websites-through-reusability

replace with -  https://www.embl.org/about/info/communications/blog/2018/09/faster-scientific-websites-through-reusability/

**Comment by bhushan-ebi** [comment]
Changes should be available on dev site (https://latest.visual-framework.dev/) for testing after next deployment. 
PR - https://github.com/visual-framework/vf-core/pull/2006

**Comment by sandykadam** [comment]
Tested and working as expected, good to close the ticket.
