### ISSUE TITLE
Retire H6 in wordpress

### ISSUE THREAD

**Issue by bhushan-ebi** [visual-framework/vf-core#1979]
This comes from Ux teams findings about typography. H6 is not needed in Wordpress and so it needs to be removed from options

**Comment by bhushan-ebi** [comment]
H6 has been removed from Wordpress and no longer available.

**Comment by sandykadam** [comment]
@bhushan-ebi can you please share examples of this which are coming from WP

**Comment by bhushan-ebi** [comment]
@sandykadam please see attached.
![image](https://github.com/user-attachments/assets/6e17bcdc-73ac-4235-a438-1207d6fdd115)

**Comment by sandykadam** [comment]
ok, these are WP inbuilt and not added by us.

**Comment by bhushan-ebi** [comment]
Yes correct. We can hide it using WP hook and JS but that's not a practical solution. I'll leave it as it is.

**Comment by bhushan-ebi** [comment]
As the options coming in the block editor are inbuilt in WordPress, we'll keep this as it is. It's not advisable to change or override the core functionality for such cases.
