### ISSUE TITLE
Documentation update for multiple components

### ISSUE THREAD

**Issue by bhushan-ebi** [visual-framework/vf-core#1983]
Add proper /detailed documentation to[ following components (and others too if needed) ]: 

- https://stable.visual-framework.dev/components/ebi-vf1-integration/
- https://stable.visual-framework.dev/components/embl-content-meta-properties/

**Comment by Adedoyinebi** [comment]
As discussed during previous sprint planning meetings. The checks for documentation gaps will be done as part of the review tasks which have been created:

- https://github.com/visual-framework/vf-core/issues/2049
- https://github.com/visual-framework/vf-core/issues/2050
- https://github.com/visual-framework/vf-core/issues/2051

For other elements such as [vf-blockquote](https://docs.google.com/document/d/1xczbGYQ9zBpHX8pkkwG8cX5ARnq6qaHJETmKeezjc0Y/edit#heading=h.swzzac6vnja0), [vf-breadcrumbs](https://github.com/visual-framework/vf-core/issues/2010) and [vf-list](https://github.com/visual-framework/vf-core/issues/1997) documentation has been updated based on previous reviews.

Closing this task.
