### ISSUE TITLE
Update VF typography names in figma

### ISSUE THREAD

**Issue by bhushan-ebi** [visual-framework/vf-core#1986]
Naming conventions for VF Typography seems incorrect as per Ux team's analysis. This naming needs to be corrected and updated in line with widely acceptable standards.

**Comment by geetikamalhotra** [comment]
- [ ] converting it into an issue

**Comment by geetikamalhotra** [comment]
- [ ] test 1
- [ ] test 2
- [ ] test 3

**Comment by Adedoyinebi** [comment]
Following the[ Typography proposal review](https://docs.google.com/presentation/d/1BeThFyB7QuvFmDztKN5HMF3y2H31A1zNYy0Cnl4T_5o/edit?usp=sharing) meeting on Monday 13th May, the discussed updates to the Typography names have been [updated in the defined names in Figma](https://www.figma.com/design/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?node-id=6%3A0&t=ZcvWpiwYjh3KK3m6-1) to better align with the naming in HTML vf-headings, vf-texts and Typography tokens.

@bhushan-ebi As a follow up to other related issues addressed in the typography proposal. A follow up task has been created for the implementation https://github.com/visual-framework/vf-core/issues/2043

**Comment by Adedoyinebi** [comment]
Update has been published in the [figma library](https://www.figma.com/design/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?node-id=6%3A0&t=ZcvWpiwYjh3KK3m6-1). Closing this task.
