### ISSUE TITLE
Add documentation for VF-list

### ISSUE THREAD

**Issue by Adedoyinebi** [visual-framework/vf-core#1997]
The [vf-list component](https://stable.visual-framework.dev/components/vf-list/) currently has no documentation providing guidance on how to use the component or the variants available. The task here is to add documentation for this component on the [vf-site](https://stable.visual-framework.dev/components/vf-list/).

**Comment by Adedoyinebi** [comment]
Consider if there are cases that require different colour (Primary and secondary text colours) and document guidance for such cases

**Comment by stefangutnick** [comment]
I have written a first draft of the documentation here to be reviewed. 
@Adedoyinebi In what cases might someone need to have different colours in a list? We should discuss to see if that's a use case, hopefully would like to avoid it if possible? 

https://docs.google.com/document/d/1UXtYqySvCKG9WtnraUy6mgTr1aZ9-NNZDPtmiwhHFXY/edit?usp=sharing

**Comment by Adedoyinebi** [comment]
Documentation has been created by @stefangutnick  for the Vf-list component. Accessibility checks have also been done by Carla. 

Next steps 

Issue has been added to follow up on the code issue found, and to update the document on the vf site

- [ ] [Update documentation and resolve code issue for VF-list](https://github.com/visual-framework/vf-core/issues/2007)
