### ISSUE TITLE
Update the definition of the token for "link colour" in figma

### ISSUE THREAD

**Issue by Adedoyinebi** [visual-framework/vf-core#1998]
From the review done there were inconsistencies observed in the definition of link colours and in the naming of the states [in figma](https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?type=design&node-id=65%3A646&mode=design&t=3Jb7meX9YQPdjSH7-1) and HTML. Link colour defined differently **#2A57A3** in figma,  **#3B6fB6**[ in HTML](https://stable.visual-framework.dev/design-tokens/theming/#:~:text=vf%2Dcolor__brand%2D%2Ddark-,Text,-Primary%20Text%20Colour). 

**Task**

Update the [link colour tokens in figma](https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?type=design&node-id=65%3A646&mode=design&t=VA2DqXzUFCxNy1Bn-1) to match with the description and colours in the vf site.

Add [focused state](https://stable.visual-framework.dev/design-tokens/theming/#:~:text=vf%2Dcolor__brand%2D%2Ddark-,Text,-Primary%20Text%20Colour) for the link to the tokens described in the figma tokens

**Comment by stefangutnick** [comment]
I have updated the following in figma: 

1. Design token for links, corrected to #3b6fb6 (aka Blue 600)
2. Updated the link colour tokens to have Hover and Focus as #193f90 (aka Blue 900) 
3. Added a Focus link variant on the Link component

**Comment by Adedoyinebi** [comment]
@stefangutnick I have reviewed the updates, no issues spotted. Moving this task to done.
