### ISSUE TITLE
DOCS - Branch naming convention

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#2]
We will be adopting the branch naming convention previously used:

```
type/good-name
```

but we should clarify the `type` a little better. In the aim to have this documented somewhere.

1. `feature` - to be used when working on a new component. Is `feature` the right word here, maybe `new-item` or something?
2. `fix` - to be used for ... fixes. Do we want to split this and add `hot-fix` for things for the `master` branch?  
3. `docs` - for anything to do with documentation. Content or code.
4. `updates` - when we update anything - is this a good enough term? What about `refactor` as that is mainly that `updates` have been used for. 

Are there any more we can think of?

**Comment by khawkins98** [comment]
If we're making/editing a pattern, how about `pattern/pattern-name--any-extra-info`

i.e. `pattern/vf-button--tweak-widths`

**Comment by sturobson** [comment]
Yes. Let’s also have `pattern` for just pattern things.
