### ISSUE TITLE
Styling `embl-group-page`

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#200]
Follow-on from #199

> 1. How should we set the background colour?
>  We need something generic I guess - as would `vf-body__embl-group` be a little redundant where this could be used else where?
>  `vf-body--bg-alt`?
>
> 2\. How do we control the in/out of the background colour as you scroll down?
> I 'think' once it goes fully white it stays that way.
>David's turned the `vf-inlay` into a separate 'container` effectively for each vertical strip of content I think
>
>I think we need to work out how to employ `grid-column` a little better. As we can ID parts of the grid `[main-start] [main-end]` etc - I'm wonder if we can set 'most things' to `grid-column: main` which would fit a) within `vf-inlay` and b) `vf-body`.

>As there's no sub grid there's no conflict (I'm not sure if there would be with sub grid) - so there's no clash of which `main` to use.

_Originally posted by @sturobson in https://github.com/visual-framework/vf-core/pull/199#issuecomment-460616588_

**Comment by sturobson** [comment]
This can having bigger naming convention considerations. 

dark on white and white on dark background/foreground colours

options

- `--alt` - I'm not entire convinced with this name.
- `--contrast` - I'm not sure this makes 'sense'.

**Comment by khawkins98** [comment]
Maybe it's a question of "intent" ... are we:

- A. Adding a class that adds a background to `vf-body`?
- B. Adding a class that helps style the contents of `vf-body` as a "group"?

Right now I think it's mostly A, but could see it becoming B ... "for group pages `vf-list` should have more padding", or would that be covered by `vf-list--group_page`?

**Comment by sturobson** [comment]
It's mainly A.

I don't think it would be good to have a body class effecting things like list padding and we should do something with the `--modifier` class. I'll try and write these 'rules' down so we've got something to fall back on and improve in future.

**Comment by khawkins98** [comment]
Cool. To me I'd think we should mark it as `vf-body--bg-group` (or to that effect) as the group background could change over time.

**Comment by sturobson** [comment]
options

- 'vf-body vf-body--bg-group`
- `vf-body vf-body--group-bg-color`
- `vf-body vf-group--bg-color`

**Comment by khawkins98** [comment]
No. 3 `vf-body vf-group--bg-color` is appealing as it suggest it could be used in other places that might be needed.

**Comment by khawkins98** [comment]
Think we've addressed this PRs #221 and #222, closing.
