### ISSUE TITLE
Update documentation and resolve code issue for VF-list

### ISSUE THREAD

**Issue by Adedoyinebi** [visual-framework/vf-core#2007]
[Documentation has been created](https://docs.google.com/document/d/1UXtYqySvCKG9WtnraUy6mgTr1aZ9-NNZDPtmiwhHFXY/edit?usp=sharing) to provide usage guidelines for the vf-list component. The task is to update the documentation on the [vf-site](https://stable.visual-framework.dev/components/vf-list/).

While reviewing the accessibility, it was observed that the ordered list is not defined properly. It is currently defined as \<ul\> instead of \<ol\>.  @bhushan-ebi kindly review the code and update this to \<ol\> as discussed.

**Summary of tasks**

- [x] #2011
- [x] #2012

**Useful articles**
[design system - lists](https://design.homeoffice.gov.uk/accessibility/lists), [W3C- Lists](https://www.w3.org/MarkUp/html3/lists.html)

**Resources**
- [Link to vf-link documentation](https://docs.google.com/document/d/1UXtYqySvCKG9WtnraUy6mgTr1aZ9-NNZDPtmiwhHFXY/edit?usp=sharing)

**Comment by bhushan-ebi** [comment]
PR for this change  - [2053](https://github.com/visual-framework/vf-core/pull/2053)
