### ISSUE TITLE
Develop responsive vf-breadcrumbs

### ISSUE THREAD

**Issue by Adedoyinebi** [visual-framework/vf-core#2008]
The current [vf-breadcrumbs](https://stable.visual-framework.dev/components/vf-breadcrumbs/) component does not have a responsive variant for mobile interfaces. From the [intranet project](https://docs.google.com/presentation/d/1ZsYfYUnkRtGG_-15Awfck65g5voC2meSVvA_qoecn5U/edit?usp=sharing), we learnt that it is best practice to limit the number of nodes shown on mobile interfaces which have limited screen real estate. 

A mobile version of the breadcrumbs should be created with the following specifications:

- Improve the target area for the [vf-breadcrumbs](https://stable.visual-framework.dev/components/vf-breadcrumbs/)
On mobile where a larger touch are is required 8px padding should be added above and below the breadcrumb to achieve a height of 44px which is [recommended for mobile devices](https://www.w3.org/WAI/WCAG22/Understanding/target-size-enhanced#benefits).

- Shorten breadcrumb trail on mobile to show only the parent page in the site architecture ([Design of the breadcrumb trail showing the previous page](https://www.figma.com/file/LIIgoNnuREnUcNf2WCU6ZF/Intranet?type=design&node-id=2080%3A27040&mode=design&t=lhop5tY3QkWQ6lAy-1))

**Tasks**

- @bhushan-ebi create a responsive version of the breadcrumb as discussed for [the vf-site](https://stable.visual-framework.dev/components/vf-breadcrumbs/)
- @Adedoyinebi Add the responsive design in [figma](https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?type=design&node-id=983%3A137&mode=design&t=fe5GCiQWRjTfOaTP-1)

**Design links for reference - Intranet project**

[Breadcrumb for desktop](https://www.figma.com/file/LIIgoNnuREnUcNf2WCU6ZF/Intranet?type=design&node-id=2080%3A26758&mode=design&t=lhop5tY3QkWQ6lAy-1)
[Mobile responsive breadcrumb design](https://www.figma.com/file/LIIgoNnuREnUcNf2WCU6ZF/Intranet?type=design&node-id=2080%3A27040&mode=design&t=lhop5tY3QkWQ6lAy-1)

**Comment by Adedoyinebi** [comment]
Responsive [vf-breadcrumb](https://stable.visual-framework.dev/components/vf-breadcrumbs/) has also been [added in figma](https://www.figma.com/design/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?node-id=983%3A137&t=ZcvWpiwYjh3KK3m6-1) to be used on designs of mobile interfaces, recommended breaking point: width below 768px.

The mobile version shows only the parent node in the hierarchy. 

**Useful links**:

- [Mobile responsive variant of the vf-breadcrumb in figma](https://www.figma.com/design/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?node-id=983%3A137&t=ZcvWpiwYjh3KK3m6-1)

**Comment by bhushan-ebi** [comment]
These changes are done as part of the parent ticket #1976
