### ISSUE TITLE
Update design of the vf-breadcrumbs in figma and on the vf-site

### ISSUE THREAD

**Issue by Adedoyinebi** [visual-framework/vf-core#2009]
From the review of the breadcrumbs design during the Intranet project. The Vf-breadcrumbs component's enhancement on desktop are as follows:

**Improve the target area for the breadcrumb**
Increase the spacing after the “>” symbol from 4px to 8px to avoid [overlap of touch target areas](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum#target-spacing-toolbar) for small words in the breadcrumb

**Task**

- [ ]  @Adedoyinebi Update the design of the [vf-breadcrumb component in figma](https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?type=design&node-id=983%3A137&mode=design&t=fe5GCiQWRjTfOaTP-1)

- [ ]  @bhushan-ebi Update the [vf-breadcrumb in html](https://stable.visual-framework.dev/components/vf-breadcrumbs/) as specified above

**Comment by Adedoyinebi** [comment]
The desktop variants of the [vf-breadcrumbs](https://stable.visual-framework.dev/components/vf-breadcrumbs/) has been [updated in figma](https://www.figma.com/file/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?type=design&node-id=983%3A137&mode=design&t=rNgn9EN5mGnNHWPq-1)

- Spacing after the separator “>” increased form 4px to 8px to avoid [overlap of touch target areas](https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum#target-spacing-toolbar) for small words in the breadcrumb.

@stefangutnick kindly review this update

**Comment by stefangutnick** [comment]
@Adedoyinebi The padding now appears to be 4+4 px which is correct, looks good

**Comment by Adedoyinebi** [comment]
Based on the discussion with @bhushan-ebi  yesterday, We agreed to use a padding of 8px on the left and right of the of the ">" Chevron for a uniform padding on both ends. 

The padding on the top and bottom of each node has also been updated to 8px to achieve a target touch size of 44px for touch based interactions matching [AAA accessibility standard on target touch area](https://www.w3.org/WAI/WCAG22/Understanding/target-size-enhanced.html)

Design of the [Vf-breadcrumb](https://stable.visual-framework.dev/components/vf-breadcrumbs/) has been [updated in figma](https://www.figma.com/design/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?node-id=983%3A137&t=ZcvWpiwYjh3KK3m6-1) based on this.

@stefangutnick please review

Image below showing desired target touch area without overlap on other elements


![Image](https://github.com/visual-framework/vf-core/assets/126486114/b6e292cf-e7c4-49ef-98ea-ec022a21eb7c)

**Comment by bhushan-ebi** [comment]
Figma changes are done as per comment above https://github.com/visual-framework/vf-core/issues/2009#issuecomment-2104274387.
Dev changes are done as part of parent ticket #1976
