### ISSUE TITLE
Add documentation for responsive vf-breadcrumb

### ISSUE THREAD

**Issue by Adedoyinebi** [visual-framework/vf-core#2010]
Following the development of the responsive [vf-breadcrumb](https://stable.visual-framework.dev/components/vf-breadcrumbs/) (From issue #2008 ), Guidelines for the usage should be updated for using the responsive breadcrumbs.

**Task**

@Adedoyinebi Update the documentation for vf-breadcrumbs with guidelines for the responsive breadcrumbs

**Comment by Adedoyinebi** [comment]
An [updated documentation has been created](https://docs.google.com/document/d/1l3eafOcxq1NnSZCvRtElJpwYCBYA4aP4R-XM0G6H0wc/edit?usp=sharing) for [vf-breadcrumbs](https://stable.visual-framework.dev/components/vf-breadcrumbs/) providing guidelines on how to use the responsive breadcrumb. The parts to be added are highlighted in green.

@stefangutnick kindly help with reviewing this documentation

[Link to updated documentation for vf breadcrumb](https://docs.google.com/document/d/1l3eafOcxq1NnSZCvRtElJpwYCBYA4aP4R-XM0G6H0wc/edit?usp=sharing)

**Comment by bhushan-ebi** [comment]
@Adedoyinebi , I've made the changes to the document as discussed today. I'll commit the code along with other changes for breadcrumb.

**Comment by bhushan-ebi** [comment]
These changes are done as part of the parent ticket #1976
