### ISSUE TITLE
Implementation of improved vf-link examples

### ISSUE THREAD

**Issue by Adedoyinebi** [visual-framework/vf-core#2030]
In order to improve the [examples of the vf-link](https://stable.visual-framework.dev/components/vf-link/#:~:text=Examples-,Example,-A%20text%20link)] in the visual framework, areas with inconsistencies were addressed in issue: Improvements on examples of vf-link [#1912](https://github.com/visual-framework/vf-core/issues/1912). 

@bhushan-ebi This task is to implement the changes:

- Remove disabled link from [vf-link examples](https://stable.visual-framework.dev/components/vf-link/#:~:text=Examples-,Example,-A%20text%20link)]
- Add underline to hover example by default
- Update label of examples to provide more clarity:
    - Default (No change)
    - Hover - “A text link on hover”
    - Visited - “A visited text link”
- Visited link example should be updated from #734595 to #563D82

**Useful links**

[See figma link](https://www.figma.com/file/6OfOhIu5zq4OBW2HaS7UEe/Typography-Proposal?type=design&node-id=548%3A9&mode=design&t=7AgSDo8ybIZsnKBz-1)] for mockup of the disabled link examples

![Image](https://github.com/visual-framework/vf-core/assets/126486114/7d2bc944-4958-4ee5-a0f7-67b6a6349bbe)

**Comment by bhushan-ebi** [comment]
PR for this change - [2056](https://github.com/visual-framework/vf-core/pull/2056)
