### ISSUE TITLE
Update colour of vf-list

### ISSUE THREAD

**Issue by Adedoyinebi** [visual-framework/vf-core#2041]
**Current state**

Some variants of the [vf-list ](https://stable.visual-framework.dev/components/vf-list/)use the secondary text colour **#373A36** while others are using the primary text colour **#1A1C1A** 

**Task** 

Based on the investigation done in issue #1916, @bhushan-ebi  update the following variants of vf-list to the primary text colour **#1A1C1A**:

- [Default variant](https://stable.visual-framework.dev/components/vf-list/index.html?q=list#:~:text=Variants-,Default%20variant,-a%20list%20item)
- [Tight variant](https://stable.visual-framework.dev/components/vf-list/index.html?q=list#:~:text=Tight%20variant,-a%20list%20item)
- [Inline variant](https://stable.visual-framework.dev/components/vf-list/index.html?q=list#:~:text=Inline%20variant,-a%20list%20item)
- [Ordered variant](https://stable.visual-framework.dev/components/vf-list/index.html?q=list#:~:text=Ordered%20variant,-a%20list%20item)
- [Unordered variant](https://stable.visual-framework.dev/components/vf-list/index.html?q=list#:~:text=Unordered%20variant,-a%20list%20item)

**Comment by bhushan-ebi** [comment]
PR for this change - [2055](https://github.com/visual-framework/vf-core/pull/2055)
