### ISSUE TITLE
Implementation of updated vf-typography colours in the examples

### ISSUE THREAD

**Issue by Adedoyinebi** [visual-framework/vf-core#2042]
Following up with the investigation on task **[#1949](https://github.com/visual-framework/vf-core/issues/1949)** we agreed that in order to ensure consistency of colours the examples of the [vf-headings](https://stable.visual-framework.dev/components/vf-heading/) and [vf-texts,](https://stable.visual-framework.dev/components/vf-text/#vf-text--3-regular) the colours of the variants should be updated as follows:

- [Vf text](https://stable.visual-framework.dev/components/vf-text/) variants colour should be updated from the secondary text colour **#373A36** to the primary text colour **#1A1C1A** to ensure consistency of the typography examples:
    - [3 Regular variant](https://stable.visual-framework.dev/components/vf-text/#vf-text--3-regular:~:text=3%20Regular%20variant,-This%20text%20is)
    - [4 Small variant](https://stable.visual-framework.dev/components/vf-text/#vf-text--3-regular:~:text=4%20Small%20variant,-This%20text%20is)
    - [5 Extra small variant](https://stable.visual-framework.dev/components/vf-text/#vf-text--3-regular:~:text=5%20Extra%20Small%20variant)

- The [inverted vf-heading (1 Display variant)](https://stable.visual-framework.dev/components/vf-heading/#:~:text=Variants-,1%20Display%20variant,-This%20heading%20size) should be removed and replaced with the “[Heading level 1](https://www.figma.com/design/6OfOhIu5zq4OBW2HaS7UEe/Typography-Proposal?node-id=575%3A555&t=yhK9hO765BVqVBht-1)” based on the typography proposal for headings

**Useful links:**

- Simplifying Typography in the Visual framework - [Presentation slides](https://docs.google.com/presentation/d/1BeThFyB7QuvFmDztKN5HMF3y2H31A1zNYy0Cnl4T_5o/edit?usp=sharing)
- Mockups showing updated design and documentation of:
    - [Vf-headings](https://www.figma.com/design/6OfOhIu5zq4OBW2HaS7UEe/Typography-Proposal?node-id=575%3A555&t=3T45KjfevzFfcGta-1)
    - [VF-texts](https://www.figma.com/design/6OfOhIu5zq4OBW2HaS7UEe/Typography-Proposal?node-id=575%3A995&t=3T45KjfevzFfcGta-1)
    - [VF typography tokens](https://www.figma.com/design/6OfOhIu5zq4OBW2HaS7UEe/Typography-Proposal?node-id=575%3A679&t=3T45KjfevzFfcGta-1)

**Comment by bhushan-ebi** [comment]
PR for this change - [2058](https://github.com/visual-framework/vf-core/pull/2058)
