### ISSUE TITLE
Implementation of simplified typography pages

### ISSUE THREAD

**Issue by Adedoyinebi** [visual-framework/vf-core#2043]
To address discrepancies spotted in the [VF component review](https://docs.google.com/spreadsheets/d/1jan7jnM_Bdhr5HStoGnfytx_izNNBoPeyth0-009VcQ/edit?usp=sharing)  of typography elements. A proposal has been created which improves:

- Naming convention of typography elements
- Documentation of Headings and Texts
- Layout of the Vf-typography tokens

@bhushan-ebi I have created this implementation task for the proposed design updates based on the mockups below

Links to figma mockups in for:
- [Headings](https://www.figma.com/design/6OfOhIu5zq4OBW2HaS7UEe/Typography-Proposal?node-id=575%3A555&t=S9CPyk5yaIqzeU4q-1)
- [Texts](https://www.figma.com/design/6OfOhIu5zq4OBW2HaS7UEe/Typography-Proposal?node-id=575%3A995&t=S9CPyk5yaIqzeU4q-1)
- [Type sizes - Tokens page](https://www.figma.com/design/6OfOhIu5zq4OBW2HaS7UEe/Typography-Proposal?node-id=575%3A679&t=S9CPyk5yaIqzeU4q-1)

**Useful links:**

- [Slides - Simplifying typography in the visual framework](https://docs.google.com/presentation/d/1BeThFyB7QuvFmDztKN5HMF3y2H31A1zNYy0Cnl4T_5o/edit#slide=id.g2b970107330_0_0)

**Comment by bhushan-ebi** [comment]
PR for this change - [2058](https://github.com/visual-framework/vf-core/pull/2058)
