### ISSUE TITLE
Review and update documentation for VF-Table

### ISSUE THREAD

**Issue by bhushan-ebi** [visual-framework/vf-core#2047]

**Comment by Adedoyinebi** [comment]
[Documentation has been created](https://docs.google.com/document/d/1M4AmzZquejjOF5xraOb3jEudNZqUzy-oRk41Vv82d1w/edit?usp=sharing) for the current [vf-table](https://stable.visual-framework.dev/components/vf-table/) component to provide usage guidelines for the variants and best practice recommendation.

Here's the link to the drafted documentation:
https://docs.google.com/document/d/1M4AmzZquejjOF5xraOb3jEudNZqUzy-oRk41Vv82d1w/edit?usp=sharing 

@OliveiraCs Kindly help with reviewing this task



As we have agreed, investigation on any further improvement required for the component is being addressed in the task https://github.com/visual-framework/vf-core/issues/2048

**Comment by OliveiraCs** [comment]
To provide more context for both scenarios, consider adding the following bullet points:

**When to use** 

- To systematically organise and display structured information.
- When users need to access specific data to perform tasks.
- For side-by-side comparisons of multiple data sets.
- When handling large volumes of data that require sorting and management.
- To illustrate relationships and categories within structured data clearly.

**When not to use**

- **For simple data**: avoid using data tables for straightforward or minimal data that can be easily represented without a grid format.
- **For visual content**: do not use tables to present primarily visual content, such as images or videos, where a visual layout is more appropriate.
- **For interactive elements**: avoid using tables for interactive components like forms, sliders, or charts, as they may not offer the best user experience.
- **For complex layouts**: avoid tables for complex layouts or multi-level hierarchical information, as they can become cumbersome and hard to navigate.
- **For limited data context**: avoid tables when the context or relationships between data points are not well defined or necessary for understanding the information.

**Comment by Adedoyinebi** [comment]
The [documentation](https://docs.google.com/document/d/1M4AmzZquejjOF5xraOb3jEudNZqUzy-oRk41Vv82d1w/edit) has been updated based on @OliveiraCs 's recommendations and structured to keep the content concise to ensure the that documentation is easier for the users to read through.

**Links**:

[Updated documentation for vf-table](https://docs.google.com/document/d/1M4AmzZquejjOF5xraOb3jEudNZqUzy-oRk41Vv82d1w/edit)

@bhushan-ebi kindly update the documentation for [vf-table on the html site](https://stable.visual-framework.dev/components/vf-table/)

**Comment by bhushan-ebi** [comment]
PR #2083
