### ISSUE TITLE
Review VF Blocks

### ISSUE THREAD

**Issue by Adedoyinebi** [visual-framework/vf-core#2051]
Review the Block components in the Visual framework and document findings in the [excel sheet](https://docs.google.com/spreadsheets/d/1jan7jnM_Bdhr5HStoGnfytx_izNNBoPeyth0-009VcQ/edit?usp=sharing).

Check for:

- Elements that are out of sync with the live components
- Documentation gaps
- Possible enhancements
- Accessibility

Create follow up task to address these where necessary

**Comment by bhushan-ebi** [comment]
@Adedoyinebi as discussed, putting this in backlog as work can be continued on it.

**Comment by Adedoyinebi** [comment]
The review of the vf blocks has been conducted, the findings we documented in the [excel sheet](https://docs.google.com/spreadsheets/d/1jan7jnM_Bdhr5HStoGnfytx_izNNBoPeyth0-009VcQ/edit?gid=0#gid=0). The issues spotted were subsequently discussed with the team and prioritised through a dot voting exercise [in figjam](https://www.figma.com/board/hshYZbLLQ0bJ8aCkXUu9aJ/Review-of-Vf-blocks?node-id=0-1&t=gSsEYp1FGIb7VKF9-1). 

**Useful links**
- [Component review sheet](https://docs.google.com/spreadsheets/d/1jan7jnM_Bdhr5HStoGnfytx_izNNBoPeyth0-009VcQ/edit?gid=0#gid=0)
- [Vf figma library](https://www.figma.com/design/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?node-id=373-2&t=AVHFLcJcy85BrsAX-1)
- [Vf-blocks review in figjam](https://www.figma.com/board/hshYZbLLQ0bJ8aCkXUu9aJ/Review-of-Vf-blocks?node-id=0-1&t=2TuoIaJxjmAtGU4F-1)
- [Slides: Review of vf blocks](https://docs.google.com/presentation/d/1rhwZS-kcrPqpwDPS6q7oEIik3T1fUkMv132iijEjJTc/edit?usp=sharing)

Next steps as discussed would be:

- Address Navigation issues as an Epic
- Create backlog items for other issues in the prioritised list (Medium priority) Add examples to reference issues. Add all other issues to the backlog’s low priority list
- Backlog review meeting
- Next review will be for containers


The issues have been added in git hub. Closing this task.
