### ISSUE TITLE
Design smaller variant of Vf-blockquote

### ISSUE THREAD

**Issue by Adedoyinebi** [visual-framework/vf-core#2059]
The [last blockquote design update](https://docs.google.com/presentation/d/16l51KsJJ7lDMcEGlHJtNUYccevamNj_Aae3Y60aXDsU/edit#slide=id.g230a4709085_0_0) focused on the use case for Articles in which an external quote needs emphasis in a sea of texts. [Recent discussions](https://docs.google.com/document/d/1jLXlTqUcubGlVdd_9I7tH0m4436CfcGo54FoQQC2q4s/edit) with the comms team has shown that a smaller variant is needed for cases like microsites where emphasis is not required on the quote.

**Examples**
https://wwwdev.ebi.ac.uk/about/our-impact/biodiversity-and-climate-change/
https://www.ebi.ac.uk/research/research-group-leaders-at-embl-ebi
https://www.ebi.ac.uk/about/jobs/tech-careers - This uses cards 
https://www.ebi.ac.uk/about/public-engagement

Consider use case where a blockquote is used close to a section header of 24 px or 21px the current blockquote font size of 28px would overwhelm the section header.

**Task**
- Design a smaller variant of the [vf-blockquote ](https://www.figma.com/design/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?node-id=4060-2284&t=mnbPxQFMxp7eVw4p-1)in figma.

**Useful links**
- [Meeting notes - Blockquote on the Biodiversity page](https://docs.google.com/document/d/1jLXlTqUcubGlVdd_9I7tH0m4436CfcGo54FoQQC2q4s/edit)

**Comment by Adedoyinebi** [comment]
![Image](https://github.com/user-attachments/assets/2302ca03-2d0a-440c-acf1-1bbdf0f545ce)

We discussed the proposed solution with the team on Wednesday **7th August** and agreed to use the small blockquote variant with a font size of 21px as this variant provides a font size which is smaller that the commonly used section headers while also being larger than the default body paragraph font.

**Useful links**

-[ Vf-blockquote - Proposed design for the smaller variant  - Slides](https://docs.google.com/presentation/d/1s4eYOcer-7OhrKSiWuYeoL3TbvsAv3ekfBQanlDDiZU/edit?usp=sharing)

**Next steps**

- Create responsive variant
- Add design in figma library
- Develop the small variant and responsive blockquote variants

**Comment by Adedoyinebi** [comment]
![Image](https://github.com/user-attachments/assets/e7c36744-44d8-4d01-9061-7bbff151299b)


The responsive variant of the [vf-blockquote](https://stable.visual-framework.dev/components/vf-blockquote/) has been designed as discussed.  Here’s the [link to the design in figma](https://www.figma.com/design/xOI3wE6Z1SdG2smyu71myL/test-page?node-id=1244-5680&t=2Nl9N12KPYhVRILn-1).

**Highlights of the responsive design**

- Blockquote design and layout is more compact on mobile placing prominence on the quotation
- Text aligned to the right for good readability
- Related components of the attribution are grouped together. This also reads better for screen readers.
- Small avatar variant (64px by 64px) used on mobile for the both large and small variants of the blockquote
- Recommended breaking point of 768px

**Useful links**

- [Design of the mobile responsive vf-blockquote](https://www.figma.com/design/xOI3wE6Z1SdG2smyu71myL/test-page?node-id=1244-5680&t=2Nl9N12KPYhVRILn-1)
- [Mockup of the blockquote on mobile](https://www.figma.com/design/xOI3wE6Z1SdG2smyu71myL/test-page?node-id=1220-4087&t=2Nl9N12KPYhVRILn-1)

**Next steps**

- Add the [responsive design](https://www.figma.com/design/xOI3wE6Z1SdG2smyu71myL/test-page?node-id=1244-5680&t=2Nl9N12KPYhVRILn-1) & [Small blockquote](https://www.figma.com/design/xOI3wE6Z1SdG2smyu71myL/test-page?node-id=1065-1584&t=2Nl9N12KPYhVRILn-1) to the visual framework library in figma
- Development of the [responsive design](https://www.figma.com/design/xOI3wE6Z1SdG2smyu71myL/test-page?node-id=1244-5680&t=2Nl9N12KPYhVRILn-1) & [Small blockquote](https://www.figma.com/design/xOI3wE6Z1SdG2smyu71myL/test-page?node-id=1065-1584&t=2Nl9N12KPYhVRILn-1)
- Update the [vf-blockquote](https://stable.visual-framework.dev/components/vf-blockquote/) documentation by:
    - Removing the texts saying “This component is not optimised for mobile devices.”
    - Adding notes on when to use the small variant of the blockquote as documented in [the slides](https://docs.google.com/presentation/d/1s4eYOcer-7OhrKSiWuYeoL3TbvsAv3ekfBQanlDDiZU/edit#slide=id.g2f1068d9d80_0_98)

**Comment by Adedoyinebi** [comment]
The responsive and small vf-blockquote has been added to the [visual framework library in figma](https://www.figma.com/design/3bkXbDDIFkIH8fMEdbCGvY/Design-Library?node-id=4060-2284&t=gnlAjNp303JV3ZPl-1). @stefangutnick kindly review the published updates.

**Comment by stefangutnick** [comment]
@Adedoyinebi Looks very well thought out, I don't have any comments. Great work!

**Comment by Adedoyinebi** [comment]
Thank you for reviewing this @stefangutnick 

@bhushan-ebi A follow up task has been created for the development of the enhancements [#2114](https://github.com/visual-framework/vf-core/issues/2114). Closing this task.
