### ISSUE TITLE
ENHANCEMENT - "This page intentionally left blank. See the pattern variants."

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#213]
Before Christmas I was toying w/ creating `vf-pattern__example.hbs` which would be a more 'designed' version of the `collated: true` option.

As it defaults to … the default file we could either 

a) use `collated: true` and just put everything in one 'file' in the UI
b) create a separate `vf-pattern__example.hbs` file 
c) see if we can hide the `default` if empty
d) get rid of the component iframe(?) views and make the `vf-component.md` file the page.

**Comment by khawkins98** [comment]
Adding this one to the backlog.
