### ISSUE TITLE
COMPONENT - vf-table

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#235]
Capturing some notes on how we should approach a `vf-table` pattern:

From slack:

> David Bushell [4:30 PM]
is there a pattern for `<table>`?
ideally a single class that uses selectors like `.vf-table > td` etc :slightly_smiling_face:
> 
> Stuart Robson [4:32 PM]
not yet.
Something, again that could be ‘knocked’ up and informed by existing patterns.
> 
> Ken Hawkins [4:40 PM]
> It’s a good point on how we want to address the use of styling on html elements for tables … given that tables are largely a “functional” thing like `.vf-content`, @David Bushell’s suggestion `.vf-table child-elements` sounds good
> 
> Stuart Robson [4:41 PM]
yep, don’t want to have a class on every table cell… not really :sob:

**Comment by khawkins98** [comment]
And there's probably a few variants that we'll want:

- vf-table
- vf-table__compact (minimal padding)
- vf-table__minimal (no strokes)
- vf-table__stack (stack in responsive mode)

Maybe we could draw code for these from bootstrap or foundation

**Comment by sturobson** [comment]
They should be a double dash rather than an underscore because they’re modifiers?

**Comment by khawkins98** [comment]
Good catch. I always get twisted with `__` and `--` when I'm outside of code land ... well I get twisted in code land, too.

**Comment by khawkins98** [comment]
Added to the backlog
