### ISSUE TITLE
vf-code-example bottom margin

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#245]
@khawkins98 

Is the reason we have this 

```
.vf-code-example {
  display: grid;
  margin-bottom: map-get($vf-spacing-map, vf-spacing-xxl) * 2;
}
```

because of it's use within the component library, rather than in the Visual Frameworks actual patterns?

I'm assuming the only time we would really see this is within `vf-content`?

I ask because, currently, it's part of the EMBL demo pages within `vf-core` and that bottom margin is making the the `vf-banner` pattern on those pages look big, because of that bottom margin creating more vertical white space.

**Comment by khawkins98** [comment]
Not sure why that spacing is so big. Happy to see it made more general and we can tweak locally in the pattern library, if needed.

**Comment by sturobson** [comment]
#246 should 'fix' this for now.

**Comment by sturobson** [comment]
closing because #246 is now merged
