### ISSUE TITLE
changing the markup for `vf-masthead__heading`

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#258]
I was thinking about this over coffee …

In the group pages we have, inside the `vf-inlay`, a `vf-masthead` with a heading, and now a subheading.

The subheading is a description of the group.

I'm wondering if it's a better fit as a `<span>` or similar of `vf-masthead__heading`.

Currently the markup is:

```
<div class="vf-masthead__title">
  <h1 class="vf-masthead__heading">Häring Group</h1>
  <p class="vf-masthead__sub-heading">Chromosome structure and dynamics</p>
</div>
```

I think we could change that to:

```
<div class="vf-masthead__title">
  <h1 class="vf-masthead__heading">Häring Group<span class="vf-sr-only">:</span> <span class="vf-masthead__heading--additional">Chromosome structure and dynamics</span></h1>
</div>
```

This way, a screen reader and a search crawler would read it in one parse. It would also benefit searches (not sure if applicable) as the description is part of the H1 and tells the story a little more.

If there's no objections to this - I'll make this change today.

**Comment by sturobson** [comment]
This is a potential breaking change for: 

the `vf-wp-theme` and/or the content hub

**Comment by khawkins98** [comment]
Conceptually I really like this.
