### ISSUE TITLE
Is Lerna the best option for our mono repo?

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#264]
Lerna has been doing almost what we want for our mono-repo but we'd rather not have a lot of extra tags in the repo (and definitely not 100s of releases).

Right now we `lerna publish --no-git-tag-version`, that gets us halfway, but as there's no history for each sub-package, Lerna can't tell if the package has changed. 

Maybe there's a better tool out there?

**Comment by sturobson** [comment]
here's a list of options - https://github.com/korfuri/awesome-monorepo#build-systems--dependency-management-tools

**Comment by khawkins98** [comment]
Have just pushed to npm for alpha.3 and seen this command, maybe it would help next time:

[--conventional-commits](https://github.com/lerna/lerna/tree/master/commands/version#--conventional-commits)

**Comment by khawkins98** [comment]
This conversation might still have merit, but I don't think we've exhausted Lerna as the option-to-be. 

Closing and backloging.
