### ISSUE TITLE
QUESTION - Do we need to put every component on NPM to start with?

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#27]
The idea is to put all components on npm as their own little npm package. 

This way users of the VF can pick and choose what to install rather than the whole kitchen sink.

To get the ball rolling I am unsure if we really need every component on NPM?

We would need the basics: the Sass variables, maps, functions, mixins as well as Elements as they're needed for blocks and containers...

But do we need all blocks and containers?

What would be a good, small set of components to start adding to test the water of this?

- Sass code
- Elements
- Factoid?
- Data Protection Banner?
- Anything else?

**Comment by khawkins98** [comment]
So if I did a `npm install vf-tabs` on a fresh project, I'd get what?

- `node/modules/@visual-framework/vf-tabs` and
- `node/modules/@visual-framework/vf-core`

Is that right?

**Comment by sturobson** [comment]
Yes.

If you then add `vf-data-protection-banner` which also uses `vf-core` -- unless `vf-core` has changed it won't re-download that package.

We need to determine what goes in the package too -- Sass file, CSS file, JS file, HBS file?

**Comment by khawkins98** [comment]
How about everything in the pattern repo (README.md + uncompiled) AND compiled code?

**Comment by sturobson** [comment]
Oh, we can include everything that's in the folder if needed. 

I'm not sure the READEME.md would be read there (it'll be deep within node_modules to start with).

I think the compiled .css would be good.

We would need to create another task that runs the html compilation part of `fractal build` to also include the `.html` file -- I think that'd be a nice to have too?

Of course, everything will be within a folder (within a folder?), within `node_modules` so we need to document how easy(😛) it is too reference it.

**Comment by khawkins98** [comment]
Yeah, would be good to have a little `vf-npm-sample-site` repo.
