### ISSUE TITLE
REFACTOR - `vf-masthead` pattern

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#273]
In the previous release we tried to refactor the `vf-masthead` pattern whilst adding in the the `--additional` text class for the heading. This managed to blow up the design a little.

There are a few things I want to make simpler, in terms of where the design is now and where the `vf-masthead` original came from.

- deciding what is the `<header>` element
- do we need to specify `embl-group-pages__header`?
- theme-able
- option to have a background image
- less `<div>`s do we need `vf-masthead__inner` and `vf-masthead__title`?
- look to use `grid` just for that component
- responsive

**Comment by khawkins98** [comment]
Sounds about right. 

Questions/thoughts:

- Do you mean "header" in the sense of the masthead pattern? Or in the wider sense of what is the chief header of all the headers? 
- On the themable aspect, we'll probably have to account for a few ways:
    - completely overriding by rolling your own pattern (that should be pretty easy)
    - theming within the VF by setting a toke/variable/property
    - theming outside of the VF by adding a class or custom CSS -- think WP ... I could see supporting a few defaults (`.vf-masthead__background-option-X`) and CSS overrides (`.vf-masthead__background-custom { background: blue; }`)

**Comment by sturobson** [comment]
> Do you mean "header" in the sense of the masthead pattern? Or in the wider sense of what is the chief header of all the headers?

I think it would be the 'chief of all headers'. Or in that the `vf-masthead` classname should be attached to the <header> element along with any other classname needed.
```
<header class="vf-inlay__header | vf-masthead">
…
</header>
```
for example.

The component `vf-global-header` I wouldn't say is specifically a `<header>` as it's not as close to the w3c definition:

> …introductory content for its nearest ancestor sectioning content or sectioning root element. A header typically contains a group of introductory or navigational aids.

As the `vf-masthead` design is.

**Comment by sturobson** [comment]
🤔 perhaps this is more a 'look at where `<header>` is used across the components and make it simpler.

**Comment by sturobson** [comment]
We should close #258 I guess and move the conversation here.

**Comment by sturobson** [comment]
> I'm wondering if it's a better fit as a <span> or similar of vf-masthead__heading.

> Currently the markup is:
```
<div class="vf-masthead__title">
  <h1 class="vf-masthead__heading">Häring Group</h1>
  <p class="vf-masthead__sub-heading">Chromosome structure and dynamics</p>
</div>
```
> I think we could change that to:
```
<div class="vf-masthead__title">
  <h1 class="vf-masthead__heading">Häring Group<span class="vf-sr-only">:</span> <span class="vf-masthead__heading--additional">Chromosome structure and dynamics</span></h1>
</div>
```

**Comment by khawkins98** [comment]
With #313 committed are we largely done here, or is there more of this to take on?

**Comment by sturobson** [comment]
I think we can close this as #382 should cover most of issue
