### ISSUE TITLE
ENHANCEMENT - automate the release as much as possible

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#274]
The release is still quite a manual process with a few command lines etc etc.

It'd be neat to have something like `gulp release patch` or similar (I'm not sure you can add a variable like this to a gulp task) so that it would then go off and - 

- do the correct Lerna commands
- anything else
- pushing to the GH repo

**Comment by khawkins98** [comment]
Yeah, here's my little release to-do script:

```
# Release to-do script

1. [ ] Finish up outstanding ticket/tasks 
2. [ ] Do release notes
3. [ ] Push to npm (lerna)
   - `lerna publish --no-git-tag-version  --conventional-commits --no-push`
       - if you mess up, and need to run again without pushing to npm `--skip-npm`
    - verify no tags added: `git tag`
    - PR version changes
4. [ ] Sync changes to `vf-child-template`, `npm update` it
5. [ ] Merge to `master`
6. [ ] Tag release on `master`
```

3, 5,  and 6 could be pretty easily automated, but in reality I've been finding a lot of things when I do step 4: `npm install`ing the patterns, which means step 3 usually has to be done a couple of times.

**Comment by khawkins98** [comment]
Added to the backlog.
