### ISSUE TITLE
is it me or are `/docs/` a little 'broke' now.

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#277]
- I'm wondering if we need to rethink the layout of the home page
- Where are the docs now
- the url for 'developing a pattern' - `/docs/guidelines` is broken - but there's no `.md` so it could be that. 
- Going back to the top one - I'm wondering if we're outgrowing what fractal can do for documentation? Carbon (IBM's) uses fractal for the patterns and they're pulled into a separate 'documentation' site. - https://www.carbondesignsystem.com/components/code-snippet/code

**Comment by khawkins98** [comment]
I do think the homepage needs work, we need to ask ourselves "what are the user needs we're addressing on it? how does the github page relate/not relate?

Also agree on the docs. With how we can access each pattern's data, we should be able to loop through all the `README.md`s and do something.

We also still need to address the JS (and sass) "API style docs"... that might be related (or not) to the `README.md`s.

**Comment by sturobson** [comment]
I wonder if this is a start to making the documentation more the 'design system' incorporating lots of things as well as the visual framework components separate to the fractal install -- leaving the VF Fractal install to be the 'bare bones'

**Comment by khawkins98** [comment]
I've had an itch that perhaps the patterns should have a different relationship to the fractal theme.

Currently:

```
├── build_config (gulp, linting, etc.)
├── components 
│   └──  (all the components)
│        └── README.md (static)
├── docs (though this may become redundant)
│   └── markdown_files
└── tools 
    ├── component-generator
    ├── css-generator
    └── frctl-theme (pattern library layout, homepage)
```

I wonder if instead:

```
├── build_config (gulp, linting, etc.)
├── components 
│   |──  `vf-pattern-library-layout` (the fractal theme, as this is replaceable and versionable ... and in principle not required to use patterns) 
│   └──  (all the components)
│        └── README.md (dynamically built from comments/docs in scss+js)
├── pages (for any special needs, the formerly "docs" directory)
│   └── markdown_files
└── tools 
    ├── component-generator
    └── css-generator
```

☝️ I think we can make our code more understandable by "writing the readme" in the Sass and building the README.md dynamically, using something like KSS. That also allows the VF to become less fractal dependent.

**Comment by khawkins98** [comment]
Added to the backlog. This may get addressed by some other changes ... at a minimum we won't have a clear picture on this issue until we've done some other things.
