### ISSUE TITLE
ENHANCEMENT - Design Tokens (Colour)

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#279]
At the moment the design tokens transformation from .yml files only creates `.scss` versions of them.

`vf-design-tokens` needs to potentially 

- support Sketch
- support Adobe products
- required a documented page (#278)
- other

We are currently using Theo, from Salesforce for creating the Sass variables - and I've spotted this repo - https://github.com/kaelig/tokens2palettes-example - that might help us create the required sketch and adobe product palette.

As well as being able to do this we also need to look at:

- announcements for updates
- ease of updating for non-developers

**Comment by khawkins98** [comment]
Adding to the backlog.

See also #315
