### ISSUE TITLE
QUESTION - Do we publish patterns independently or as part of one big release?

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#28]
We will be [making use of Lerna](https://github.com/lerna/lerna) to help publish the components of the visual framework to NPM.

One decision that needs making...

Do we allow each component to be published independently? 
ie: if we update the buttons we can push the new version of that package up with it's version bump

Or do we publish the component library as a whole(fixed)?
ie: if we update the buttons we push a version bump to all packages.

A part from 'hot fixes', would it be better for our audience to 'schedule' releases (in time) which means a 'publishing as a whole' would work better?

Another idea is we could start with indepentently (as we're in alpha) and move to fixed when the VF is at Beta or live?

**Comment by khawkins98** [comment]
Adding a footnote that this versioning method could (should?) also apply the VF WP theme (`vf-wp`).

So `vf-wp:2.0.10` would expect atleast `vf-core:^2.0.0`. And the `vf-wp` for EMBL site would also require `vf-embl:^2.0.0`.

That's my take, anyways.

**Comment by sturobson** [comment]
I was talking about this w/ @dbushell yesterday. Unless it's a breaking change (v1.2.3 to v2.0.0) where we are breaking the HTML / class name convention (mainly, but there could be other reasons for the breaking change) ... David was thinking that a link to the CDN of the (versioned) .css file would be a easier / better solution.

(I guess that idea should really be it's own issue within the`vf-wp` repo)

**Comment by khawkins98** [comment]
Sounds about right to me. The generic `vf-wp` theme will be quite general in usage, so it probably makes sense to use the kitchen sink CSS+JS from the CDN.

That also makes it possible to have an admin field of "Want a different look? Link to your VF 2.0.X compatible CSS and JS here."

**Comment by sturobson** [comment]
@khawkins98 as part of the build process to put the new build the visual framework live - can we add a CHORE (new label needed) to make it spit out the CSS and JS to a CDN somewhere>

**Comment by khawkins98** [comment]
@dbushell Sounds great. I think that would make the devs at EBI (who are responsible for maintenance) really happy, too. 

@khawkins98 Do you mean the kitchen sink CSS/JS, or the individual component CSS/JS?  The former is already there at:
- https://dev.assets.emblstatic.net/vf/scripts/scripts.js
- https://dev.assets.emblstatic.net/vf/css/styles.css

@pwalter-ebi Just occurred to me we probably need to do a version number on those, a la: 
- https://dev.assets.emblstatic.net/vf/2.0.0/scripts/scripts.js
- https://dev.assets.emblstatic.net/vf/{tag}/scripts/scripts.js

**Comment by sturobson** [comment]
@khawkins98 @pwalter-ebi would keeping the version in the .css file with cache busting be better as it could/would require less effort for people to upgrade?

`https://dev.assets.emblstatic.net/vf/css/styles.css?v=2.0.1`

**Comment by pwalter-ebi** [comment]
Cloudfront ignores all querystring parameters, so this approach will not work.

**Comment by dbushell** [comment]
Would it be possible to do similar to https://unpkg.com whereby non-versioned URLs redirect to the latest version?

That way anyone developing with VF can effective opt-in to the latest assets without updating anything.

**Comment by khawkins98** [comment]
I think this has already been addressed in versioning notes elsewhere (patterns have their own version numbers) and is being further addressed in the two referenced issues above. 

Closing, please reopen if you think we should.
