### ISSUE TITLE
REFACTOR - The Links Mixin(s)

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#292]
I'm thinking that there should be two categories for 'links`. Both having sub-categories.

I think this should fix some issues, as well as making it more clearer in the Sass files as to what we're using rather than a long string of variables.:

vf-badge pattern, when it is use as, or part of, a link.

vf-summary--people (for example) that has lots of links in the content.

text links

content text links
primary call-to-action text links
secondary links
button links

for actual button links
outline buttons
normal buttons
for things that have their own design links (like vf-badge)

**Comment by khawkins98** [comment]
Sounds about right. 

There's things things where the link is on the text (`display: inline`), and things where the link is on the element (`display: inline-block, flex, etc`)

And then there's always `Category C: other`, like menu buttons, or random edge case. But there's no avoiding that.

**Comment by khawkins98** [comment]
Oh, and linked images, I'm think that goes under "`button links`"?

**Comment by khawkins98** [comment]
Added to backlog.
