### ISSUE TITLE
FEATURE: Update pattern library pattern layout

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#30]
Would be good if we can increase the width of the pattern library's pattern preview area to be [--- full width --] and escape the grid and pinch of the sidebar.

I'll work up a PR and some screenshots.

**Comment by khawkins98** [comment]
Ok, first off, this idea is still a WIP, but here's a before after where I think it shows good merit:

[Site header currently}(http://dev.beta.embl.org/guidelines/visual-framework/dev-docs/components/detail/vf-header.html):

![image](https://user-images.githubusercontent.com/928100/48369252-563bdc00-e6b6-11e8-8a0d-dc10be29c48b.png)

And in the branch https://github.com/visual-framework/vf-core/tree/features/update-pattern-library-layout 

![image](https://user-images.githubusercontent.com/928100/48369306-77043180-e6b6-11e8-8aa8-40ed0399e8fe.png)


One more before/after:

![image](https://user-images.githubusercontent.com/928100/48369348-913e0f80-e6b6-11e8-8f2e-20017df5c955.png)

![image](https://user-images.githubusercontent.com/928100/48369368-9bf8a480-e6b6-11e8-926b-f425690df04c.png)

So, @sturobson if you think I'm not making a mistake here, I'll work on this branch a bit more and polish off some rough edges + give it some more thought.

**Comment by sturobson** [comment]
I'm liking this -- taking the pattern out of the box and making it as wide as the `main` grid item saves things looking a little 'small' :)

One question that I've been thinking about and one that popped up in conversation w/ David yesterday -- is having the navigation on the right a good solution, or is it just because that's what the EMBL-grid offers?

**Comment by khawkins98** [comment]
Nice, I'll carry on then. 

I agree on the sidebar; couple thoughts:

- The right navigation feels a bit odd, but it's also a convention in the "science world". It's a pattern we shouldn't forget to make. 
- I wonder if we should even sidebar (left or right)...
    - It will squeeze content
    - Should we use the container system and put it at the bottom? Or just link back to the landing page to "view more patterns"? Containers allow us space to describe the patterns.
    - And/or should we have a type-ahead hot-jump navigation as our search box?

Maybe that's a seperate ticket.

**Comment by sturobson** [comment]
aside: We would also need to work out what to do with CSS that is specific for the component library (if we end up with any). Currently I'm putting it into the `shame.scss` file.

**Comment by khawkins98** [comment]
+1 for `shame.scss`

---

Have pushed some more edits here, dropping the sidebar nav to further use a container layout/nav approach. 

![image](https://user-images.githubusercontent.com/928100/48621835-1e2de500-e9a5-11e8-9405-19c9050858a4.png)

I'm sure there's a lot more to be done here, but from my end I think it's a lot of progress -- what do you think @sturobson should we adopt this branch and then push on from there?

**Comment by sturobson** [comment]
We're getting there 👍 

This throws up things like 'how we write documentation' (when we (or I mostly) get around to it. 

So that it fits this layout better.

It would be _really_ neat if we move those 'tags' tabs to use the tabs pattern too? Maybe?

**Comment by khawkins98** [comment]
Think we've largely achieved the goals here. More to do on this theme, but closing this one.
