### ISSUE TITLE
REFACTOR - move to nunjucks

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#301]
As discussed in person (14/03/19).

We should move the templating engine used for the Visual Framework component library from handlebars to Nunjucks.

Things to do:

- [x] swap out the fractal engine to use Nunjucks (https://github.com/frctl/nunjucks) for components and docks.
- [x] change the handlebars helpers to Nunjucks as needed.
- [x] update the components to use Nunjucks syntax where needed.
- [ ] bring in #1 to make use of .yml so we're including components within components.

**Comment by sturobson** [comment]
@khawkins98 any considerations I've missed here? Feel free to edit.

**Comment by khawkins98** [comment]
Related to #302 

I think we're mostly done here?

**Comment by sturobson** [comment]
Yep - I've pretty much duplicated #1 as #316
