### ISSUE TITLE
CHORE - add Visual Regression Testing

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#31]
We need to make sure we start adding visual regression tests so that we confidently update patch, minor, and breaking changes.

As we will also be hosting a CDN version of the `styles.css` and `scripts.js` file that will depend on the file path altering when we make a major version change we need to include VRTs as part of the develop and/or build step(s).

There are several resources for this, both paid and completely open-source. I have used [BackstopJS[(https://garris.github.io/BackstopJS/) previously.

Is this something that can be part of the CI build?

**Comment by khawkins98** [comment]
Just leaving a note, in addition to BackstopJS there's also Percy — I think you've previously mentioned it?

**Comment by khawkins98** [comment]
Another option: [ReleaseIt](https://github.com/webpro/release-it)

**Comment by sturobson** [comment]
Closing because of #376
