### ISSUE TITLE
Documentation - Design Tokens

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#315]
The Design Tokens (typographic scales, colours, spacings, etc) are their own npm dependency `vf-design-tokens`.

We need to document these in several ways, including:

1.  [ ] what they are
2.  [ ] how they can be used
3.  [ ] how they can be updated
4.  [ ] what to do when they need updating
5.  [ ] what they look like

---

1. I imagine this being the 'home page' for the design tokens
2. I imagine this being the 'home page' for the design tokens 
3. I imagine this being part of the `vf-design-tokens` `.md` file pulled into a broader page
4. I imagine this being part of the `vf-design-tokens` `.md` file pulled into a broader page
5. Pages showing the colours, spacing, sizes of type.

---

5. What they look like:
  - something that's auto-updated when we update the tokens.
  - should show the colours with the `#hexcode`, `rgb`, `Sass variable`, `css custom property`.
  - a 'contrast checks' we can get inline via the client side.
  - shows the various font sizes used and their relative mixin needed to display them
  - shows the spacing options

Other:

We should think about, investigate, and include anything else that's in design tokens or _should be in design tokens (z-index, breakpoints, animations).

**Comment by khawkins98** [comment]
I think there's more to be done, but a good bit of this has now been done? https://visual-framework.github.io/vf-core/components/detail/vf-design-tokens.html

@sturobson Could you clarify what still needs doing, or maybe it's a new ticket that's needed?

**Comment by sturobson** [comment]
I think this is mostly done. The documentation needs a little TLC and adding too - but not a priority right now with the move to the next chunk of work.

**Comment by khawkins98** [comment]
Cool. moving to backlog.
