### ISSUE TITLE
Documentation / Chore - npm guidelines and learn improvements

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#317]
We need to document (and put somewhere (in the documentation site(?))) -

- how we're making the component library via npm
- what we're using to do this
- how they can be installed (in part this is also - TASK Integration examples)
- how we update them (with lerna)
- what steps are needed for this

We need to carve out an `npm script` or `gulp task` that would create the and process the updates of all the packages.

**Comment by khawkins98** [comment]
Added to backlog.
