### ISSUE TITLE
BUILDS  - premade bundles

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#323]
A sub-issue for #321

https://github.com/visual-framework/vf-core/issues/321#issuecomment-476550440_

> re: *a few builds of the VF as premade bundles*
> 
> Should 'we' be doing this? My thinking is that `vf-core` is something that is consumed by 'others'. So those 'others' would need to include it however they wish.

**Comment by khawkins98** [comment]
I'm thinking less a CDN of the CSS+JS, and more that we'll want to publish the pattern library as a static site, which would need to have the compiled CSS and JS to be made.

**Comment by sturobson** [comment]
Ah, ok. 

So having a separate 'EMBL pattern library' that's either live or installable?

If so, there could be some confusion as to where a pattern is, why it's 'specific' to EMBL, why can't I use it for uniprot etc?

I think we could go better in separating the various 'team' patterns than how we do on the main page at the moment. 

If you're thinking something different, and I'm not 'getting it', apologies :)

**Comment by khawkins98** [comment]
Maybe i shouldn't have made child tickets, I think a lot of these things will point to similar root things....  

I would expect that anything `embl-*` should be fairly obvious why it's specific to EMBL (breadcrumb lookup uses the EMBL taxonomy structure, EMBL logo is the EMBL logo, etc) 

Having a seperate pattern library per design system should also help us with that front page layout; as:

- the EMBL design system wouldn't need to categorise if it's a vf- or embl- pattern as they'd all be relevant to EMBL sites (and vf- patterns that aren't relevant could be turned off, like `vf-logo`)
- the VF Core "sample"  wouldn't show anything that isn't intended for global use (so no embl-* patterns)

**Comment by khawkins98** [comment]
Much like #322:

>  I've set this one to on hold, I don't think we can proceed with improving the CI builds until we:

1. [ ] Get alpha.4 published as a snapshot; and
2. [ ] Make some decisions and changes as to what's in and not-in vf-core; see https://github.com/visual-framework/vf-core/issues/321#issuecomment-476572646

**Comment by khawkins98** [comment]
This has been eclipsed/outdated.
