### ISSUE TITLE
BUILDS - split out gulp tasks

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#324]
This is a sub-issue of #321 

> The gulp build is global.

(probably not the best sentence to quote, but heh)

If we're looking at building more functionality with the gulp tasks - it is probably time we look at splitting these out as separate 'things' in a `gulpfilejs` folder.

This might make it easier in the overall `gulpfile.js` file to see what is doing what, where and why - and we can easily hunt down the separate tasks when any editing is needed.

**Comment by khawkins98** [comment]
Breaking up the gulpfile would probably be a necessary and helpful step in any situation.
