### ISSUE TITLE
CHORE - Track all component files for npm

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#333]
As discussed (briefly) at https://github.com/visual-framework/vf-core/pull/331#issuecomment-477588045, it would simplify component maintenance and increase reliability if we simply tracked all component files for npm.

The easiest (best?) way to do this would be to remove the `files { }` section, https://alligator.io/nodejs/package-json/:

> files: This optional key expects an array of files that are included when the project is added a dependency to another project. File names/paths can use a glob pattern and when the files key is not provided a default value of ["*"] is used, which means that all the files will be included. Not to worry though, certain files/folders such as .git and nome_modules are always ignored.

If that, suits we'd need to:

- [x] Update the component builder template
- [ ] Update all the components
- [x] Consider adding [`.npmignore`](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) to the template

**Comment by sturobson** [comment]
Hmmm, my original thinking is that people don't necessarily need to install the `.md` files etc for a project (adding that 'bloat' people complain about with Node and NPM). 

In saying that, I think removing `files { }` will definitely improve us shipping things without the extra checks to make sure we've included any additional files added to the folder.

I'm happy with this move forward.

**Comment by khawkins98** [comment]
Addressed by #388
