### ISSUE TITLE
CHORE - Cleanup, remove, deprecate components

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#336]
Shipping already dead/outdated things in beta.1 will only increase code maintenance while offering features that shouldn't be used to new users. 

So, I think:
- [x] for the vast majority of deprecated component we should `npm-unpublish`
- [x] have one sample `vf-deprecated` example component and `npm-deprecate` it
- [x] have a look through the list of stuff of https://www.npmjs.com/org/visual-framework and `npm-unplublish` and dead ends; for example all these will be dead as they have been renamed:
    - https://www.npmjs.com/package/@visual-framework/vf-simple-search
    - https://www.npmjs.com/package/@visual-framework/vf-plex-sans-font
    - https://www.npmjs.com/package/@visual-framework/vf-plex-mono-font
    - might be others
- [x] anything we unpublish, we should double check we're not referencing as a peer dependency in our components
- [x] remove any deprecated/unused things from the mono-repo

Once we go beta/rc, I know we won't want to npm-unpublish, but as right now the only users are maintainers, it's a good chance to do some cleaning.

**Comment by sturobson** [comment]
I've found `npm-unpublish` rarely works and I've had to `nom-deprecate` in the past. We might be able to ask NPM to delete them entirely (I've asked before (for several packages, and they've managed to).


But yes, we shouldn't be bringing things into beta which we don't want. 

I've also noticed some 'old ways' of doing things #337. So we definitely need to make sure we're not referencing anything old.

I'd also like to see this one done sooner rather than later.

**Comment by sturobson** [comment]
Happy to pick this issue up tomorrow.

**Comment by khawkins98** [comment]
👍 Being bold and assigning.

**Comment by khawkins98** [comment]
Probably obv, but have also added a bullet: "- remove any deprecated/unused things from the mono-repo"

**Comment by khawkins98** [comment]
Deprecated a few components which were no longer in the code/renamed/moved:

```
npm deprecate @visual-framework/vf-simple-search "no longer supported use the @visual-framework/vf-search instead"
npm deprecate @visual-framework/vf-plex-sans-font "no longer supported use the @visual-framework/vf-font-plex-sans instead"
npm deprecate @visual-framework/vf-plex-mono-font "no longer supported use the @visual-framework/vf-font-plex-mono instead"
npm deprecate @visual-framework/visual-framework "no longer supported use the @visual-framework/vf-core instead"
```

**Comment by khawkins98** [comment]
And, yeah, no love on unpublishing ... only possible within 24 hours of publishing, otherwise you have to email.
