### ISSUE TITLE
COMPONENT - vf-snippet and variants

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#345]
Add a one sentence summary of what it is you need it to do.
[An image gallery that shows one large image+caption, and thumbnails of more images. Clicking any image starts a slideshow]

## Standard questions

- In a few words, what does this component look like?
  In some places (for now it's just the sidebar) there's the need for a 'snippet' of content that is styled (currently) differently to what we have already (smaller, tighter)

- In a few words, what does this component do?
  Display a smaller amount of content

- Would a rebrand change the structure or layout of this component?
  Non

- Can other websites use this component? Or is it only useful in your organisation or website?
  Yes

- Do you have any designs or concepts?
  Only what is currently in use as `vf-news-item--snippet` (deprecated)

- Have you done any user testing already?
  No

**Comment by sturobson** [comment]
from reading this and not having an idea on what I am on about -- I think we need to look at how we can improve issues in the future :D

**Comment by khawkins98** [comment]
I think this one has been lost to time in memoriam? 

Closing. Shout if it shouldn't be ...

**Comment by sturobson** [comment]
kinda done in `vf-u-et-al` so no worries in closing :)
