### ISSUE TITLE
BUG: vf-link mixin spits out disabled by default. I don't think it should

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#355]
With the mixin `@mixin inline-link{}` we are creating the `hover`, `active`, and `visited` states.

We are also bundling in the `disabled` state. 

I'm not sure this is a good idea. 

Unlike the `hover`, `active`, and `visited` states `disabled` is something that I feel shouldn't be shipped with the code and rather an additional separate 'class' that are either added in the markup or by something controlling state (JS).

I'm sure disabled 'text' won't change in colour between various uses - so I think a simple mixin to create the disabled state class should be written and added to the components partial as a separate block of code to the `inline-link` mixin.

I think shipping it on every link 'just in case' is something that I failed to see as a problem when I originally wrote the mixin - and we should clear that up with a specific 'state mixin' for `disabled`.

Thoughts?

**Comment by sturobson** [comment]
This would also stop the doubling up of CSS for when we have `vf-link vf-link--secondary`.

**Comment by sturobson** [comment]
`vf-link vf-link--secondary` has me thinking that we shouldn't do too much to `vf-link` and style it with `vf-link--primary` -- but we're probably too late to do that now - but it could be something we retroactively sort?

**Comment by sturobson** [comment]
… although - if a component is using `vf-link` - it should be using `vf-componentName-link`?

**Comment by sturobson** [comment]
to update - I've got something working.

- a single 'vf-disabled' mixin
- requires an additional Sass file in the component which is included after all the other variants to combat the cascade or is it inherency ¯\_(ツ)_/¯.

currently the Sass partial is called `vf-componentName--disabled.scss` I'm wondering if explicitness is better here than having something like `vf-componentName--state.scss`

I guess 'state' could get tricky as `:hover`, `:active`, `:visited` are states but it feels icky moving them.

I guess `disabled` is more an 'add on' to a component rather than something inherent.

**Comment by khawkins98** [comment]
+1 for an `@mixin vf-disabled` -- agree that it could be all sorts of things that may or may not need a disabled state, so it's good to almost "utilitise" it. 

---

On using `vf-link` in another component, I think in some cases this has been done (`.vf-summary__link`), but we've not been consistent about it. 

I wonder if `.vf-link` should be `.vf-u-link` to make it a bit clearer.

**Comment by sturobson** [comment]
I think, if you're happy with the suggestions in #356 we don't necessarily need to create `vf-u-link` right now. So I've not added this into #354 - which I'd say is 'ready'.

**Comment by sturobson** [comment]
With #354 merged - I think we're good to close this one.

re-open if required.
