### ISSUE TITLE
QUESTION - Should all 'element' components be prefixed with `vf-u-` 

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#356]
From Ken's comment in #355 - https://github.com/visual-framework/vf-core/issues/355#issuecomment-483547875 

As the idea around the 'element' components is more for show and testing rather than utilisation within a component would it be better that all `element` components have the prefix of `vf-u-`

**Comment by sturobson** [comment]
this could be a problem with buttons and form elements - as it would mean that there'd be a lot of repeated CSS

**Comment by sturobson** [comment]
actually -- now that the codebase designs have stabilised - should we go back to including `vf-u-heading--xl` into larger components?

**Comment by khawkins98** [comment]
I can see the logic in the above but it makes my head hurt with the number of other moving bits of code we have going on. Do you think we should settle this first or we could save for beta.2?

**Comment by sturobson** [comment]
I think things should be authored like this …

- element: `vf-button` - this has the basic colour, typography, and some spacing.

- block: `vf-summary` which has a child component of `vf-summary__button | vf-button`. A block lays out the element components but doesn't change any styling. It can effect the spacing of elements.

- container: shouldn't do anything to change the child component of `vf-summary`. A container is more about the vertical 'slice' layout. It can effect the spacing of blocks.

This way:

We have the 'base' components that (from now on) rarely change that much, or not a big sweeping naming change at least.
if we remove or change a block - we don't have to change any 'element'  CSS.

Currently, as you've mentioned (somewhere), there's a lack of consistency in the use of components. 

I think we should try and get this into `beta.1` as if we waited there could be a large 'refactor' for several codebases.

**Comment by khawkins98** [comment]
If I follow on the above, only `elements` would have styles?  Would something like the links in [vf-navigation](https://dev.beta.embl.org/guidelines/visual-framework/dev-docs/components/detail/vf-navigation.html) still be "compliant" with this approach? Or would it necesitate a lot of extra complexity in the elements?

**Comment by sturobson** [comment]
hmm, I guess it falls down there a little - perhaps vf-link is for things 'inline' lie we've got in `vf-summary`.

I've been thinking about this - and I've still got some things to work out - I'm sure there's a good codifiable compromise in 

- not duplicating too much CSS
- not having HTML full of classnames

it'll probably be a tightrope :D

**Comment by khawkins98** [comment]
In wonder if there's some kind of _clever_ opt-in CSS concatenation that could be done as a post processor

**Comment by sturobson** [comment]
well, I think CSS Modules solves this, from what I've read about it. I almost suggested it last year too :sob: 

Sass + CSS Modules could work - not sure how much of a CSS re-write it would need though:

as far as I understood it:

- keeps CSS modular
- can make BEM-style classnames 'per component'

(amongst other things)

**Comment by sturobson** [comment]
I know there's more pressing things - but perhaps I should spend a little bit of time today/tomorrow investigating 

(i've just found all my "gulp + css modules + Sass" bookmarks from last year too

**Comment by khawkins98** [comment]
Added to backlog.
