### ISSUE TITLE
Using frctl `path` with njk templates

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#364]
Now that we're passing data in from the Yaml files, it presents an issue with file assets.

Issue: from the Yaml we can't pass `  imageUrl: "{{ '/assets/vf-figure/assets/figure-example.png' | path }}"` without affecting the Njk template. 

So we're passing fixed paths in #363, that works fine on local but won't work once deployed. 

One way around is to utilise the "real" template in some other way, like the README.md:

```
{% render "@vf-figure", {
  text: "Version, 1982, Adenovirus with 217 dots",
  alttext: "hello alt text",
  imageUrl: '/assets/vf-figure/assets/figure-example.png' | path
} %}
```
However the `| path` filter doesn't properly work there :cry: 

As a temporary work around we could pass in assets deployed on remote URLs, but we'll eventually need to sort this.

**Comment by sturobson** [comment]
> As a temporary work around we could pass in assets deployed on remote URLs, but we'll eventually need to sort this.

I always thought it would be nice to use 'real content' from Bynder for the component library

I knew I'd break things with this

**Comment by khawkins98** [comment]
#365 has addressed usage within the component's `.njk` files, however we still have issues in the README.md. 

For example doing:`{% render '@vf-figure'  %}` fails to link the image, returning a path of `assets/vf-figure/assets/figure-example.png`. 

That's because the request context isn't correctly bubbling up to the Fractal NJK plugin. 

Doing `{{ '/assets/vf-figure/assets/figure-example.png' | path}}` in the README.md also has the same issue. 

I dropped a PR (https://github.com/frctl/nunjucks/pull/13) that would resolve the later of the two problems, but the request context is still getting lost when we `{% render '@vf-figure'  %}`, however a workaround would be to pass the path at the README.md level:

- `{% render '@vf-figure', {imageUrl: '/assets/vf-figure/assets/figure-example.png' | path } %}`

But that would only work if the PR gets merged in.

**Comment by sturobson** [comment]
is `{% render %} supposed to work in README.md files?

I know this - https://fractal.build/guide/documentation/dynamic-docs.html#using-bundled-helpers - is handlebars but I'd've expected the same limited availability.

**Comment by khawkins98** [comment]
When you set the docs to use nunjucks it uses the same for the notes (README.md); 

```
    fractal.docs.set('ext', '.njk');
    fractal.docs.engine(nunj); 
```

**Comment by sturobson** [comment]
> `fractal.docs.set('ext', '.njk');`

Do we need to change this `.md` to `.njk`?

**Comment by sturobson** [comment]
> Do we need to change this .md to .njk?

No - because then there are no docs

**Comment by khawkins98** [comment]
Not sure I follow, we do have docs in `./docs` and we'd lose support for nunjucks in README.md files. Am I missing something?

**Comment by sturobson** [comment]
I was assuming `'ext', '.njk'` meant it would only work within a .njk doc file - but it doesn't matter

So - there's a few things going on around this. I've got it working in the .md but not the actual .njk - so I'm investigating.

**Comment by khawkins98** [comment]
Another option could be to move our dovs into the 11ty boilerplate. But it'd still be really useful to show "real" demos in the README.md ... But maybe hand coded demos make sense. If we get stuck on the technical side, we could have a think about what we actually need.

**Comment by sturobson** [comment]
So, Fractal pulls out `assets` to a separate folder on build (is this something we've added?) 

So in the `README.md` writing:

```
{% render '@vf-figure', {imageUrl: '../../assets/vf-figure/assets/figure-example.png' | path } %}
```

works when running `gulp dev` and it works for the static build of the component library too.

In the component template nunjucks file you would write:

```
<img class="vf-figure__image" src="{{ imageUrl | path }}" alt="{{alttext}}">
```

In the Components YAML you would still write:

```
imageUrl: "/assets/vf-figure/assets/figure-example.png"
```

note: `| path` does nothing in the `README.md` so we can either use it or lose it. It is needed in the component template for it to work in the component live view though

**Comment by sturobson** [comment]
actually we have a gulp task that pulls out all of the assets to the assets folder - it's not a fractal thing

**Comment by sturobson** [comment]
tbh - we could even write `'../../assets/vf-figure/assets/figure-example.png'` in the component .yml file - as the blackbox will fix the paths for us

**Comment by khawkins98** [comment]
> tbh - we could even write '../../assets/vf-figure/assets/figure-example.png' in the component .yml file - as the blackbox will fix the paths for us

Maybe that's the approach to take … "When linking local files in the component's `assets` directory, prefix it with `../../`" 

And we could also add a sample asset to the component boilerplate. 

---

> note: | path does nothing in the README.md so we can either use it or lose it. It is needed in the component template for it to work in the component live view though

If they decide to merge in that PR to `frctl/nunjucks`, that would work.
