### ISSUE TITLE
REFACTOR - vf-summary components(s) need a little nunjucks/yaml optimisation

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#383]
It looks like when #372 missed the opportunity to refactor the `vf-summary` pattern to make it more robust and usable. 

Although the `vf-summary--profile` pattern got the most ❤️ we/I should look at making the rest of the summary variants: `--news`,`--has-image`,`--job`,`--article` more malleable. Perhaps even unifying the template so it's a "one-size catch all" where adding relevant 'types' decide what classnames to use etc.

This would help in the larger picture of updating `vf-containers` so they're using data and not rendering components 'as is' from `vf-blocks`.

**Comment by khawkins98** [comment]
Tossing this one in the backlog
