### ISSUE TITLE
A demonstration site using vf-core components

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#394]
how is this different to #392

**Comment by khawkins98** [comment]
I think this is:
- A bit about showing how to "consume" the components (using vf-eleventy, for example)
- also covers onboarding/hello/welcome to the VF

With that in mind I've made https://github.com/visual-framework/vf-welcome

Might could use a "real" url for the VF in the coming weeks -- seems like visualframework.org is available.

#watchThisSpace

**Comment by khawkins98** [comment]
vf-eleventy should have this covered.
