### ISSUE TITLE
CHORE - Add a bunch of fundamental components (tables, cards, etc.)

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#395]

**Comment by khawkins98** [comment]
Just adding a note for later reference; List of patterns from audit is at: https://docs.google.com/spreadsheets/d/1unIfejFmxAS1ZpVE3pPN5PrGH4kdtCe-4d7iqwQggqE/edit#gid=0

**Comment by khawkins98** [comment]
Spotted [this in Abstract](https://share.goabstract.com/7db0f437-aaf1-46fb-a6ad-d02e6f1d3245), where Mark had done some designs for me any of these:

![More patterns](https://user-images.githubusercontent.com/928100/77881740-e05ef300-725f-11ea-90fd-de052e512e93.png)

**Comment by khawkins98** [comment]
I think most of these have been implemented or are in the backlog
