### ISSUE TITLE
vf-summary -- with image has inline spacing issue

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#409]

**Comment by sturobson** [comment]
@khawkins98 I think you fixed this?

**Comment by khawkins98** [comment]
Looks alright at https://dev.beta.embl.org/guidelines/visual-framework/dev-docs/components/detail/vf-summary--has-image.html ... so i guess someone did. 

closing. 

![clueless](https://media.tenor.co/images/e1cf80e109e488de85b922e6c6cd19b1/tenor.gif)
