### ISSUE TITLE
Colour tokens are broken

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#417]
Following #398 many (most?) of the colour tokens are busted; for example the [`vf-divider`](https://visual-framework.github.io/vf-core/components/preview/vf-divider.html) has no background.

https://github.com/visual-framework/vf-core/blob/d65c37340bbddf7b031d0dc5a2cd1efadf7c6389/components/vf-sass-config/mixins/_divider.scss#L4

When the token is:

https://github.com/visual-framework/vf-core/blob/d65c37340bbddf7b031d0dc5a2cd1efadf7c6389/components/vf-design-tokens/src/core.palette.alias.yml#L62

I'm not sure which way is right -- with one hyphen or two?

**Comment by sturobson** [comment]
I’ll tackle this in the morning.
