### ISSUE TITLE
BUG - hover issue with buttons or links that look like buttons

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#436]

**Comment by pwalter-ebi** [comment]
[Screen Recording 2019-06-26 at 09.52.23.mov.zip](https://github.com/visual-framework/vf-core/files/3329303/Screen.Recording.2019-06-26.at.09.52.23.mov.zip)

**Comment by khawkins98** [comment]
Should be sorted by#450 in the next alpha release
