### ISSUE TITLE
Refactor: Drop t-shirt sizing for typography design tokens

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#445]
We continue to see that t-shirt-style sizing names (`vf-heading--l`,  `vf-heading--r`, ...)  aren't flexible enough for the VF (latest example: #443).

There are few thoughts around this:

- Option 1. do something like `text-preset--1` so we’re not defining that ‘these are heading sizes only’
- Option 2:  `button-preset--n`, `heading-preset--n`, `test-preset--n` so we have some explicit ‘design decisions’
- Option 3: some other magic way of getting better alignment between sketch and design tokens

Also; some more thoughts from @sturobson via slack:

> Add in something like `fluid typography` as some sizes look silly-ly big on my phone. could also be a good opportunity to try out the Plex variable font — but we’d need to host that on our CDN
>
> We should also try and do something similar for the colours as `--100`, `--400`...

**Comment by khawkins98** [comment]
An observation: in sketch typography presets have component-like names, but they aren’t tied specifically to components.

![image](https://user-images.githubusercontent.com/928100/60422602-a38c9f80-9bec-11e9-9fab-5f95f5d9414d.png)

So we should also make sure our token naming is aligned with sketch, and sketch with the VF tokens.

**Comment by khawkins98** [comment]
Probably related: "REFACTOR - The Links Mixin(s) #292"

**Comment by sturobson** [comment]
Working through this with #466

**Comment by sturobson** [comment]
we kept the t-shirt sizing for spacing and breakpoints as they made more sense there.

This can be closed, with documentation for it moving to beta2

**Comment by khawkins98** [comment]
👍
