### ISSUE TITLE
CHORE - Move "misc" docs from `vf-core` to `vf-welcome`

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#447]
With https://github.com/visual-framework/vf-welcome we now have a "general information" landing page for the visual framework where we can start to house general onboarding information, and that will allow the `vf-core` site to specialise in being a component library.

So, we need to move (many/most) of the docs from vf-core over.

**Comment by sturobson** [comment]
hmmmm. I think the whole set of various 'design system' pages needs a look at, at some point. The 'single source of truth' of a design system needs somehow be all together in one site (made of many). At the moment, to me, there seems some disconnect.

**Comment by khawkins98** [comment]
This is wrapped up in #339; closing this one.
