### ISSUE TITLE
CHORE - Swap npm for yarn

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#455]
As discussed somewhere on Slack, it would be good to switch from using `npm install` to `yarn install` for `vf-core`. This is mainly for consistency in documentation when a developer goes from using `vf-eleventy` to looking at `vf-core` docs. 

And it's likely yarn would be a good bit faster for vf-core, as it is considerably faster for vf-eleventy. 

Things we'd need to do:

- [x] Delete `npm-shrinkwrap.json`
- [x] Add yarn.lock
- [x] Update docks to reference `yarn add` and installing yarn
- [x] Update components to say `yarn add <component-name>`
- [x] Update component generator

**Comment by khawkins98** [comment]
Quick speed comparison between the two:

- yarn: `42.98s` `679MB`
- npm  `91.641s` `728MB`

This is after removing the lock files and `rm -rf node_modules`

**Comment by sturobson** [comment]
ok, I'm sold - good to see there's a storage space saving as well as a massive jump in download speed.

I want to sneak in removing `style lint` when running `gulp vf-dev` - which will bring development changes up to speed too. I'll raise that PR
