### ISSUE TITLE
vf-code-example, and vf-font-plex-mono

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#467]
With the changes to the design tokens #466 there's only a real need for one monospace font-size and weight. 

Currently as part of #466 we have reduced the amount of options there are in the Sass map to use this font.

I think we need to make some changes and below lists them out as a checklist.

- [x] change `text-body--5` to `text-code--1` (currently this is breaking the map, therefore:)
- [ ] change how this token is generated to make a Sass variable rather than a map.
- [ ] look at how to incorporate the specific font file as part of `vf-code-example`.

**Comment by khawkins98** [comment]
Pretty sure we've done this, largely in #511. Being bold and closing.

@sturobson If i'm off, just re-open.
