### ISSUE TITLE
BUG - vf-card margins / padding issue

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#480]
https://dev.beta.embl.org/explore/

🐞 bugs

- text in the card moves to the left on hover
- images resize if they're initial too small(?)
- if wrapped in a link the text is changed to link colours

---

🔥 enhancement

- needs a container to allow for title and additional text

**Comment by sturobson** [comment]
- should the card align with the heading so that they fill the 'grid' to start with then expand out of the grid on hover?

Currently the cards start 16px further towards the centre than the title and the containers above and below.

**Comment by khawkins98** [comment]
This one closable?

**Comment by sturobson** [comment]
fixed in #495
