### ISSUE TITLE
ENHANCEMENT - move Autoprefixer, minification to build only

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#483]
Currently Autoprefixer adds:

- about 250ms to build times
- 50kb to the file size of CSS

Most of this is (probably) down to `2 last versions` as that includes Blackberry OS 7.

We should look to either

a) move it to build time only
b) remove it completely and wait for the bug reports

**Comment by sturobson** [comment]
this might be easier now we've got split out gulp tasks?

We'd probably need to pass an `ENV` variable so that if we're in build it pulls in the autoprefixer task

**Comment by khawkins98** [comment]
As per conversation on #481; we can use the same logic to also run the minification on deploy only. 

From #481:
- [ ] Disable minification on local builds (~600ms)
- [ ] Investigate need for/optimising prefixing (~210ms)
