### ISSUE TITLE
FEATURE/IDEA - Partial component overrides

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#485]
It will be incredibly useful to have partial component overrides (hooks); that is:

> I'm developing "Some Site" and I'm using `vf-button` but I only want to change one part of the `njk` template or `sass`

Currently you'd have to fork the pattern: 

- `yarn remove @visual-framework/vf-button` 
-  copy `vf-button` to your local components and edit

That's a bit tedious for small changes and makes a complete fork for what would often be only a small tweak.

It would be useful to be able to (illustrative):

- `yarn add @visual-framework/vf-button` (the usual install into `./src/components/vf-core-components`)
- create `src/components/_vf-button`
- there you can add `vf-buttons.scss` or `vf-button.njk` which would be used in preference of the version in `node_modules`

Feels like a beta.2 thing.

**Comment by sturobson** [comment]
¯\_(ツ)_/¯ feels like the start to an 'anti design system' thing ;)

**Comment by khawkins98** [comment]
Think of it like this: if uniprot.org is using the VF for their design system, it will be better if they can use `vf-box` with a couple of additions in a local `_vf-box/vf-box.scss` rather than forking `vf-box` and never getting any updates.

**Comment by sturobson** [comment]
So, what I did for my previous client was to make anything that is _allowed_ to be changed a (scoped to the component) Sass variable.

This means that if they are doing the dirty work and including the Sass partials they can

```
@import 'variables';

$button-color--red: blue;

@import 'vf-button';
```

If they're not doing that and relying on something we provide we should look to ship a 'brand overrides' Sass partial:
```
@import 'variables';

@import 'project-overrides';

@import 'vf-button';
```

If it's more than colours, typography, spacing tokens that need changing then I'd suggest that it's either:

- a potential variant that could help all projects
- an update to the existing default
- their own little pattern that they can maintain

**Comment by sturobson** [comment]
of course, if it's 'carte blanche' changes of the design tokens - then `beta2` should look at working through this:

![design tokens](https://user-images.githubusercontent.com/925197/61210575-ce9ae700-a6f4-11e9-8bf2-e3206f672f8f.png)

**Comment by khawkins98** [comment]
A lot of what it might come down to (and often has so far in my time consuming vf 2 components) is a need to update the njk templates, something like:

Needing to add `data-vf-custom-hook-need class="vf-box__text"` or an additional class in `vf-button.njk`
```
<div

{# Here is where we are adding the vf-text--body modifier #}
class="vf-box
{%- if class %} {{class}}{% endif -%}

{# You want a snowflake of a classname for something, here you  #}
{%- if override_class %} | {{override_class}}{% endif -%}

">
  <h3 class="vf-box__heading">{{- heading -}}</h3>
  <p data-vf-custom-hook-need class="vf-box__text">{{- text -}}</p>
</div>
```

As it stands now you either have to:

- forever for vf-box
- make your own `mysite-box`, but that doesn't help if you have up/downstream templates that use `vf-box`


The CSS use case is probably secondary. 

To be honest, in the case of CSS changes, most devs are just going to do a `.vf-box { color: green !important }` in their `local.css`

**Comment by khawkins98** [comment]
Enabling hooks for njk templates and sass will require distinct development work, so maybe the is a case of just focusing on the njk side.

There might be other places where a hook would be helpful (JS or Yaml) but as the VF doesn't do much JS, I can't really see that at the moment, and I can't yet imagine needing to override the Yaml.

**Comment by khawkins98** [comment]
A lot of that njk stuff might already exist in template inheritance (https://mozilla.github.io/nunjucks/templating.html#template-inheritance), but I've yet to explore.

**Comment by khawkins98** [comment]
Moving to the backlog.
