### ISSUE TITLE
IDEA - Allow per-component vf-utility and vf-content rules

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#494]
Currently `vf-content` and `vf-utility` are optional components, which is good.

What's less good is how we deal with component specific `-content` and `-utility` things; they can either:

- go in the `-utility/-content` component, and you'll get the class irregardless if you use the the related component — this also means you can't add `vf-u-component-specific-thing` without modify `vf-utility` too
- go in the component, which means you get utility/content classes even if you don't want them 

Instead what we could do is add a pattern of files like:

- `vf-component.utility.scss`
- `vf-component.content.scss`

And then, if you enable `vf-content` or `vf-utlity`, those components would aggregate all the `**/*.utility.scss` via a `vf-utility.rollup.scss`

Probably a backlog or beta.2 thing.

**Comment by sturobson** [comment]
does this align with #485 a bit?

**Comment by khawkins98** [comment]
Spiritually I think it aligns but I suspect it would needs its own architecting -- either way there's loads of other things to do and this isn't breaking anything yet. Backloging this one.
