### ISSUE TITLE
COMPONENT - Use polyfill for all browsers in embl-content-hub-loader

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#508]
In [`embl-content-hub-loader`](https://visual-framework.github.io/vf-core//components/detail/embl-content-hub-loader.html) we only use the polyfill if the  native html imports fail ... so, native for chrome and elsewhere polyfill.

That's fine but as @esanzgar points out, even Chrome will soon deprecate and it makes an annoying warning: 

> You probably know this: `[Deprecation] HTML Imports is deprecated and will be removed in M80, around February 2020. Please use ES modules instead. See https://www.chromestatus.com/features/5144752345317376 and https://developers.google.com/web/updates/2019/07/web-components-time-to-upgrade for more details.`

As Chrome will soon end support, it probably makes more sense to just polyfill everywher.

**Comment by sturobson** [comment]
Cool - I'm wondering if this is a 'component' (as it currently is) or an implementation detail that would be better 'somewhere else' (tools, probably(?)) - but that's part of a larger story.
