### ISSUE TITLE
PATTERNS/FEATURE - Navigation and breadcrumbs driven by meta properties

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#51]
For EMBL, we have a who-what-where concept that we can use to template the logic for the navigation in the masthead and breadcrumbs, and enable cross-silo exploration.

A lot of this is still in my head and has been explored with many in the Comms team in separate conversations ... so a task for me to put together some functional code to explore this. 

In bullets:

1. Use meta-properties to describe pages
    - the `embl-content-meta-properties` pattern
2. Meta properties come from our taxonomies
    - done(ish)
3. Those taxonomies are linked in a who-what-where ontology
    - done(ish)
4. On pages specify the primary taxonomy in use 
    - a PR coming for the `embl-content-meta-properties` pattern
5. Derive primary navigation ancestors (breadcrumbs)
    - a new `embl-meta-breadcrumbs`(?) pattern
    - this would also apply to the `vf-masthead`, but that could wait for the next alpha of the pattern
6. Derive secondary navigation paths
     - part of the `embl-meta-breadcrumbs` pattern

**Comment by sturobson** [comment]
Is this additive?

Does it need to be baked into navigation patterns that won’t be using this or can it be something layered (as part of a variant)

I’m slightly on edge that we might be baking stuff in that’s more for specific (regardless of how much it’s used) use cases rather than more portable components

**Comment by khawkins98** [comment]
Well, everything is specific ;)

But I get your point.

I think it is/will be layered in two parts:
1. A breadcrumb variant to add in secondary nav paths; that I'm thinking is part of `vf-core`
2. A way that queries the contentHub for menu items themselves; that's pretty embl specific, so `vf-embl` 

I think that's what you're getting at? Some if it might be clearer once we actually break out the embl stuff into `vf-embl`...

**Comment by khawkins98** [comment]
This one is largely done, clossing. Further work to be done and is/will be visible in other tickets.
