### ISSUE TITLE
IDEA — Add sass functions to component boilerplate 

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#514]
While reviewing #512 and thinking that we have a healthy number of maps+functions (colours, z-index, type, etc), it often requires poking into other patterns to see how to set things — would be helpful if samples were added to `tools/component-generator/templates/_component.scss`

**Comment by sturobson** [comment]
I think we should look at documentation first – #284, or similar. 

With documented pages 'live' on a server somewhere - we could put 'links' into the `_component.scss` file so people know where to look though

**Comment by khawkins98** [comment]
Think this has been eclipsed by more recent documentation efforts.
