### ISSUE TITLE
Different look for input fields in Firefox vs. Chrome

### ISSUE THREAD

**Issue by esanzgar** [visual-framework/vf-core#519]
I noticed that input fields look quite different in firefox vs chrome for version 2.0: https://codepen.io/esanzgar/pen/NQgQpJ

It would be great if the look would look similar.

1. I suggest adding a background colour for disabled input fields:

```
.vf-form__input:disabled {
    background:  #e6e2e2;
} 
```

2. The other issue is the colour of the placeholder text. Although it is the same colour in both browser it looks lighter in firefox.

**Comment by esanzgar** [comment]
For the second issue:

```
.vf-form__input::placeholder {
    opacity: 1;
}
```

**Comment by esanzgar** [comment]
Solved: https://codepen.io/esanzgar/pen/LwjPLX

**Comment by sturobson** [comment]
you'll probably notice _all_ colours look different in Firefox and Chrome …

https://twitter.com/marcedwards/status/1154980879023800320

**Comment by sturobson** [comment]
to quote the tweet:

> "Safari and Chrome are colour managed. CSS colours are considered sRGB and converted to the display’s colour profile. This is good.
Firefox doesn’t do that. It just uses the values as is, showing them in the display’s profile. On wide gamut displays it means they’re too vivid."

**Comment by sturobson** [comment]
@esanzgar thanks for bringing this up. As commented above Firefox is another beast with colours. As someone that's been using the nightly browser for development - this has slipped by. 

In fact, this probably opens up a larger discussion in regards to colour contrast of all text as I'm sure, if we took a deeper look the greys are not going to be _that great_. 

---

@khawkins98 perhaps we should look at colour contrast for the next beta release? I know some people have managed to include something like [pa11y](http://pa11y.org) into fractal.

Of course your colour contrast codepen could be looked at / included too.

This is also something that I want to address in the design tokens pages.

**Comment by khawkins98** [comment]
Do we want to normalise the firefox opacity of placeholder text? This pops up in a few places, but is probably most concise at https://css-tricks.com/almanac/selectors/p/placeholder/#firefox-placeholder-color: 

> #Firefox placeholder color
> You might notice how in Firefox the color of the placeholder looks faded when compared to other browsers. 
> The Chrome version is ideally the style that we’d like to see everywhere.
> This is because, by default, all placeholders in Firefox have an opacity value applied to them, so in order to fix this we need to reset that value:

Under our usual methodology we would only target `vf-form__input::placeholder`, but we might need to repeat this for other placeholder elements.

**Comment by sturobson** [comment]
`:placeholder` should be prefixed for production on `gulp vf-build` because it should be using autoprefixer?

**Comment by khawkins98** [comment]
I mean if we have a `vf-some-other-thing` that also has a `:placeholder` but doesn't get `vf-form__input`

**Comment by khawkins98** [comment]
The FF behaviour is stuck in bug debate hell: https://bugzilla.mozilla.org/show_bug.cgi?id=556145#c23

**Comment by khawkins98** [comment]
And now Chrome is going to somewhat align by using `rgba(0,0,0,.54)` but FF will still have an opacity value, meaning the default will be similar, but still borked if you use a colour-only value in FF 

https://www.chromestatus.com/feature/5415963870625792
