### ISSUE TITLE
COMPONENT - Remove warning when no breadcrumbs

### ISSUE THREAD

**Issue by esanzgar** [visual-framework/vf-core#522]
I would suggest to remove the warning when no breadcrumbs are included. In my case, I have custom breadcrumbs and it is a bit annoying the warning.

In function `scripts.js`
```
  if (emblBreadcrumbTarget.length === 0) {
    console.warn('There is no `[data-embl-js-breadcrumbs-lookup]` in which to insert the breadcrumbs; exiting');
    return false;
  }
```

**Comment by khawkins98** [comment]
+1 

I need to do some refactoring on the contentHub imports (like #508), will plan to get this one in too.
