### ISSUE TITLE
vf-block :last-child more specific

### ISSUE THREAD

**Issue by esanzgar** [visual-framework/vf-core#523]
![AwesomeScreenshot-localhost-change-password-2019-08-06_9_25](https://user-images.githubusercontent.com/8555781/62523992-c7b35000-b82c-11e9-9e7f-fbbf83eaa176.png)

I am using vf-block for displaying form errors:
```
<div class="vf-box vf-box--error">
    <i class="icon icon-common icon-exclamation-triangle vf-u-margin__right--xs"></i>Password is required
</div>
```
`vf-u-margin__right--xs` is not having any effect because of this rule:

```
.vf-box :last-child {
    margin: 0;
}
```

I suggest that rule should be more specific so it doesn't affect other margins (left, right, upper) except the bottom one:

```
.vf-box :last-child {
    margin-bottom: 0;
}
```

**Comment by khawkins98** [comment]
I think it's probably worth making this target `margin-bottom`, conceivably we could have a series a side-by-side thumbnails in a vf-box where we might get a similar unexpected spacing issue.

It would also make things line up with the perceived intent:

https://github.com/visual-framework/vf-core/blob/93d39f734418d6a6d4dcf02002a351995689e653/components/vf-box/vf-box.scss#L23

--- 

@esanzgar as an aside, while you've probably already moved past this, two workarounds:

```html
<div class="vf-box vf-box--error">
    <i class="icon icon-common icon-exclamation-triangle vf-u-margin__right--xs"></i>
    <span>Password is required</span>
</div>
```

```html
<div class="vf-box vf-box--error">
    <span>
    <i class="icon icon-common icon-exclamation-triangle vf-u-margin__right--xs"></i>Password is required
    </span>
</div>
```
