### ISSUE TITLE
Suggestion: highlight current item in navigation component 

### ISSUE THREAD

**Issue by esanzgar** [visual-framework/vf-core#526]
![AwesomeScreenshot-localhost-change-password-2019-08-07_11_49](https://user-images.githubusercontent.com/8555781/62617397-a6746180-b909-11e9-9d47-ea4ffdcb1605.png)

What do you think about adding a `vf-navigation__item-active` or `vf-navigation__link-active` classes to highlight the current navigation? Similar to `.vf-navigation__item:hover` but slightly different colour so you can differentiate between hover and active states.

**Comment by sturobson** [comment]
Hey Eduardo, thanks for raising the issue. 

We have [this]https://github.com/visual-framework/vf-core/blob/develop/components/vf-navigation/vf-navigation--main.scss#L36) which would need `.is-active` adding to the HTML when it's on the current item. 

The implementation hasn't been finalised in `.njk` or in WordPress land yet.

@khawkins98 w/ 11ty / nunjucks is this easy (and cleanly) to implement? I'm assuming we would need to wait until September for David to (cleanly) implement in WP?

**Comment by khawkins98** [comment]
I think there are some fairly simple WP methods, will also have a gander at Njk. 

Also thinking this should be `.vf-is-active`, or similar.

**Comment by khawkins98** [comment]
Totally missed @esanzgar 's suggestion(`vf-navigation__item-active`), which sounds about right

**Comment by esanzgar** [comment]
That's what I needed, thanks!

 Maybe it can be added to the code example [here](https://visual-framework.github.io/vf-core/components/detail/vf-navigation--main.html).

P.S.: For your information, most of the JavaScript frameworks (React and Angular, at least) add the active class at the anchor level.

**Comment by sturobson** [comment]
Hey,

> P.S.: For your information, most of the JavaScript frameworks (React and Angular, at least) add the active class at the anchor level.

We would have to see if moving the background colour swap on hover from `vf-navigation__item` to `vf-navigation__link` would effect the other two `vf-navigation` options and look to see how much of a refactor of the code would be needed. 

If we scheduled time for this - we could also look at:

- changing the [SMACSS](http://smacss.com/book/type-state)–essie 'is-active` to be more specific to the component.
- adding the documentation on the availability of the `active` class and anything else to make it better.

**Comment by sturobson** [comment]
I'm closing this as the `vf-navigation` component has been redesign and recoded to match and there is no active state - I think the expectation is for the use of `vf-breadcrumbs` to guide the user as to where they are on the site.
