### ISSUE TITLE
DOCUMENTATION: Sass Utilities & Mixins & Variables

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#546]
Now that we have exposed the Sass Utilities in the component library (under Containers) and after sitting in on the preview of the workshop yesterday (04/09/19) I think we need do document the all the Sass things so that developers using `vf-core` to create things can see what options there are available.

For example, exposing the global Sass variables for spacing could show developers that we have a spacing system and aren't really keen on deviating from that. This could also apply for when a developer attempts to create a new component and can see that there is a mixin available to create the typography.

**Comment by khawkins98** [comment]
Further addressed in #638 — is it worth keeping this open, or are we pretty aware that we need to keep on with the documentation effort?

**Comment by sturobson** [comment]
let's close it. We know we (me) need to do it
