### ISSUE TITLE
DOCUMENTATION: Utility Classes

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#547]
Now that these are exposed in the `container` section. Like the Sass utilities I think we need to look at how we can document them in a more holistic place.

**Comment by khawkins98** [comment]
As discussed offline, we can just add a "utility" level of component for now to improve this.

**Comment by khawkins98** [comment]
Being bold and closing this one as I think it's sorted; and I really want to get the issue down to 25, so there's only one page ... cause that's like super important.
