### ISSUE TITLE
ENHANCEMENT: generate Sass source maps in local development only

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#549]
Currently we're shipping ~300kb of Sass sourcemap data in our compiled `.css` file. 

We could either

- move the sourcemap data to a separate file
- remove it from compiled CSS, and having it so gulp only creates it when we're running things locally.

I think the latter is probably the better option.

**Comment by sturobson** [comment]
investigating this:

It seems we have a `vf-css:producution` gulp task that takes the compiled CSS and generates a `.min` file that is:
a) minified
b) adds autoprefixer

This is not currently used in production (which means certain things could look rubbish (`select` being one as it needs `appearance: none` and it's `-moz` prefix)).

So, we don't actually need to create a differing gulp task that does the same as `vf-css` but remove the source map - we just need to make live sites use the `.min` css file.

@khawkins98 what would be the easiest way to resolve this for any current live sites to use `.min`. I'm assuming it would be a small change in the `vf-wp` and `vf-eleventy` repos somewhere?

**Comment by khawkins98** [comment]
Yeah, or should we only ship the minified CSS? 

That is: 

- drop `styles.min.css`
- make `styles.css` minified and prefixed in production

In either case, we should ensure the production styles.css has prefixes

**Comment by sturobson** [comment]
I can go with that, seeing as the `css:production` task duplicates the non-minified version to then minify and add autoprefixer. 

Changing a few lines in that gulp task would mean that in local development we have Sass maps still. I'll raise a PR for this
