### ISSUE TITLE
Shouldn't `.vf-link` have `cursor: pointer`?

### ISSUE THREAD

**Issue by esanzgar** [visual-framework/vf-core#558]

**Comment by khawkins98** [comment]
What's the use case for it? When `vf-link` is on something that isn't an `<a>` element?

**Comment by esanzgar** [comment]
There is eslint rule that discourage to have anchor elements without href attributes. What I often do is to replace the `a` element for a `span`  with the same look and feel as a `a` element.
`vf-link` would be great for that.

**Comment by esanzgar** [comment]
This is the [rule](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md)

**Comment by sturobson** [comment]
if you're not linking to something (semantically using an `a` tag) what are you needing the style for?

**Comment by esanzgar** [comment]
I wanted to style a `Sign Out` as an anchor, because although it does perform a small operation (like `button`), then it navigates away to another page (like `a`).

See 'Sign In/Sign Out' on the top-right corner here: https://wwwint.ebi.ac.uk/my-account

**Comment by khawkins98** [comment]
This one, I think, is in a tricky space:

- pro: I get the use case and why you're using a `span` for what is more a link/button
- con: With the VF we're trying to support use cases AND best semantic practice

Could you just do `<a href="javascript:void(0);" class="vf-link">Sign out</a>`?

**Comment by esanzgar** [comment]
I could, but I will get still these warnings:

* The href attribute requires a valid value to be accessible. Provide a valid, navigable address as the href value. If you cannot provide a valid href, but still need the element to resemble a link, use a button and change it with appropriate styles. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md  jsx-a11y/anchor-is-valid
* Script URL is a form of eval


That's OK. I can deal with that... nothing to worry.

I close the ticket.
