### ISSUE TITLE
Expose Nunjucks environment options and extensions

### ISSUE THREAD

**Issue by dbushell** [visual-framework/vf-core#576]
## Issue

To make best use of the component **Nunjucks templates** in other projects a little bit of configuration is required to match `vf-core`.

Namely the `env` options (defined in [fractal.js](https://github.com/visual-framework/vf-core/blob/develop/fractal.js#L24)):

```js
env: {
  lstripBlocks: true,
  trimBlocks: true,
  autoescape: false
}
```

And more importantly, any [Nunjucks extensions](https://github.com/visual-framework/vf-core/tree/develop/tools/vf-frctl-extensions) used by the templates. Of those, at present only `{% spaceless %}` is used by components I think.

## Idea

It would be nice if the `vf-core` package had these functions available independently with minimal dependencies (they're currently wrapped with a `fractal` function).

My current solution is to copy the extension into [my own module](https://github.com/visual-framework/vf-wp/blob/feature/vf-gutenberg/wp-content/plugins/vf-gutenberg/blocks/utils/nunjucks-spaceless.js):

```js
function SpacelessExtension() {
  /* ... extension code ... */
}
module.exports = SpacelessExtension;
```

and I'm [initialising Nunjucks here](https://github.com/visual-framework/vf-wp/blob/feature/vf-gutenberg/wp-content/plugins/vf-gutenberg/blocks/hooks/use-nunjucks.js).

Ideally I would require the `env` options and extensions from the `vf-core` package rather than manually duplicating the code.

**Comment by dbushell** [comment]
Documenting each component with a list of Nunjucks extensions it uses would be helpful. Perhaps within `package.json` so it can be read programmatically.

**Comment by khawkins98** [comment]
Good point.

Two thoughts:

1. We really do need to document using the Nunj templates better
2. _perhaps_ of some use to you is https://github.com/visual-framework/vf-eleventy--extensions 

That was made with 11ty in mind, but it is a collection of those nunj tags/extenstions/filters. They're slightly different from the Fractal ones because _versions_. Mostly because Fractal treats the Nunjucks as trusted, and with 11ty they need to be rendered as "safeStrings".

I'll probably loop back tomorrow with some documentation, but maybe that linked npm package is of help?

**Comment by dbushell** [comment]
yep eleventy package looks useful thanks. That's basically what I had in mind.

In a world where there are many more extensions and projects using them, I can imagine a high-level package that can is used by `vf-core`, `vf-eleventy` and `vf-wp` (in the browser) and future projects. That could be difficult with differences you've noted. On solution is to write a generic wrapper function and an option to provide a custom callback.

Anyway, probably out of scope for the time being!

**Comment by khawkins98** [comment]
Adding this one to the backlog.
