### ISSUE TITLE
Add precompiled Nunjucks templates to component packages?

### ISSUE THREAD

**Issue by dbushell** [visual-framework/vf-core#577]
I'm using the slimmed down version of **Nunjucks** (`nunjucks-slim.js`) to render component templates in the browser.

It only supports precompiled templates, which are intermediate JavaScript functions, but basically work the same just more performant.

I've written a [gulp task](https://github.com/visual-framework/vf-wp/blob/feature/vf-gutenberg/gulp-tasks/vf-nunjucks.js) to generate precompiled templates and [save them](https://github.com/visual-framework/vf-wp/tree/feature/vf-gutenberg/wp-content/plugins/vf-gutenberg/blocks/templates) to my repo.

Ideally I would just require the template from the packages if each component had something like `vf-component.precompiled.js` alongside the `vf-component.njk`.

It would save me a build step.

**Comment by khawkins98** [comment]
I've not yet tried to use precompiled templates, but this seems pretty reasonable and doable. 

Your approach looks pretty straightforward and portable to vf-core. 

I'll give it a go this week.

**Comment by sturobson** [comment]
Can this be explained simply? 

Is this creating nunjucks templates out of the initial template with all possible variants or doing something else?

Did we go too far in making a ‘catch all’ template rather than individual files to start with?

**Comment by dbushell** [comment]
@sturobson this is just saving a version of each template after Nunjucks parses the `.njk` file.

It's useful because it skips a step, and in my use case allows me to bundle less code in the browser (nunjucks-slim excludes the parser).

In most use cases the original `.njk` templates are better because they're actually readable.
