### ISSUE TITLE
CHORE - (Nunjucks) conditional template variables for more robustness

### ISSUE THREAD

**Issue by dbushell** [visual-framework/vf-core#589]
I'm adding blocks to WordPress for components like `vf-activity-list`.

The Gutenberg editor experience looks like this:

<img width="744" alt="activity-list-editor" src="https://user-images.githubusercontent.com/998922/66061983-0e24e280-e530-11e9-85b5-f28cd1392dd6.png">

Default/placeholder content is set for items but the user can leave the field empty.

Once rendered with Nunjucks the result is:

<img width="735" alt="activity-list-render" src="https://user-images.githubusercontent.com/998922/66062051-30b6fb80-e530-11e9-89ed-00335b303b4a.png">

The empty item is obivously undesirable.

I should probably add validation and filtering to improve this but I think the Nunjucks templates would benefit from a few tweaks.

Using `vf-activity-list` as an example:

Existing template:
```nunjucks
{% for item in list %}
  <li class="vf-activity__item">
    {{ item }}
  </li>
{% endfor %}
```

possible improvement (assuming my code is correct):
```nunjucks
{% for item in list %}
  {% if item|length %}
    <li class="vf-activity__item">
      {{ item }}
    </li>
  {% endif %}
{% endfor %}
```

The rationale here is a more robust and "unbreakable" template without having to assume the user (me) has read the manual.

**Comment by dbushell** [comment]
Since I tagged this as "Question"; thoughts?

**Comment by sturobson** [comment]
> "a more robust and "unbreakable" template"

sounds like a super good thing to do.

**Comment by khawkins98** [comment]
I think we all agree this is good. Two tasks I see:

1. [ ] Update some existing templates to use `  {% if item|length %}`
2. [ ] Add the approach to the njk boilerplate in the component generator

**Comment by khawkins98** [comment]
Do we still need this ticket, or is all this part of our working practice now?

**Comment by khawkins98** [comment]
Hi @nitinja this one might be good for you to look at it. It relates to the nunjucks templating and conditional output.

Some of our component templates are very up-to-date and use best practices, bust some of the older ones are more simplistic and prone to breaking.

- good templates: 
  - [vf-card](https://github.com/visual-framework/vf-core/blob/develop/components/vf-card/vf-card.njk) 
  - [vf-button](https://github.com/visual-framework/vf-core/blob/develop/components/vf-button/vf-button.njk)
- older templates: 
  - [vf-list](https://github.com/visual-framework/vf-core/blob/develop/components/vf-list/vf-list.njk) (which would benefit from an `{% if item|length %}`
  - [vf-video](https://github.com/visual-framework/vf-core/blob/develop/components/vf-video/vf-video.njk)

This might be a good area for you to have a first try at, going through some of these NJK templates and making them more robust.

Related VF docs:

- https://latest.visual-framework.dev/guidance/components-and-patterns/
- https://latest.visual-framework.dev/developing/getting-started/pull-requests/
- https://github.com/visual-framework/vf-core/blob/develop/tools/vf-component-generator/templates/_component.njk

**Comment by sturobson** [comment]
a quick note on `whitepsace`. 

For some reason, Eleventy doesn't treat whitespace in the `.njk` component like Fractal does. Fractal is a lot less 'strict' and you can get away with more whitespace for clarity of the component. 

In Eleventy it doesn't like 'over indentation'. 

Normally the fix is as easy as adding `-` to the Nunjucks code:

Where we have `{% include thing %}` in Fractal, Eleventy might need `{% - include thing -%}`. The good thing is that Fractal will work either way.

Hope that makes sense.
