### ISSUE TITLE
DOCUMENTATION - Add a "Working with VF code/syntax" guide

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#592]
The VF syntax isn't unusual, but it isn't like everything else (but what is?).

Some less-CSS experienced developers may find some principles/methods/syntax unusual or not expect certain VF behaviours; that is:

- VF CSS doesn't target IDs or HTML elements
- How to deal with WYSIWYG generated html (`vf-content`)
- When to use premade CSS and when to build your own CSS from components
- When to use the NJK templates
- Use of pipes inside the HTML class attribute
- How CSS Grid works and how we use it
- Our compatibility approach with other CSS frameworks
- Use BEM syntax, including explaining what BEM is
- JS data attributes
- I'm sure other things

This is probably a tutorial with lots of examples and section. Almost FAQ like.

**Comment by sturobson** [comment]
some of this was addressed? Although I cannot see it in this repo? Did you move it to `vf-welcome`?

**Comment by sturobson** [comment]
hmm, some of it is -- I'm ready with my edit finger when you make a PR :D

**Comment by khawkins98** [comment]
Yeah, that stuff is at https://visual-framework.github.io/vf-welcome/developing/guidelines/css/

But I think the audience there is for component makers, and what I had in mind here was for those using VF component/rollup CSS ... basically, addressing the pains that the EBI team has had.

There's probably a refactor of the above URL, or maybe they can be the same page. Or maybe they cross link. I've yet to get my head into really ... I think so far it's mostly: "we need something for people who are used to copy-pasting code snippets"

**Comment by sturobson** [comment]
> "addressing the pains that the EBI team has had." 
👍
> "we need something for people who are used to copy-pasting code snippets"
👍

**Comment by khawkins98** [comment]
Maybe rather than getting tangled up in a documentation refactor, it would be better to start as a blog post ... simpler to do and we could get some feedback from EBI on what's helpful/what more is needed.

**Comment by sturobson** [comment]
similarly - I was thinking that one on 'creating your own snowflakes' would be good - as it's what I've done for training this last sprint in a couple of places.

**Comment by khawkins98** [comment]
A lot of this is now covered in https://work.allaboutken.com/posts/20191118-first-page-with-the-visual-framework.html

There are a few follow on things to do:

- moving these VF posts I've made onto a VF blog, which still needs to be made
- guide on "creating your own snowflakes"
- lots of other documentation 

But those are pretty distinct things and I think mostly covered in other issues. Being bold and closing this one.
