### ISSUE TITLE
Automate Lerna/Publishing using Github Actions

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#603]
Now that `vf-core` components are being used in production and by teams creating new sites it would be beneficial if we could automate the lerna process of updating and releasing packages.

It would be great if we could set `lerna` to publish new packages of any changed components when we merge into `develop` (for now, maybe `master` at some point).

I think we should try to get it so that it [follows the publishing documentation](https://github.com/visual-framework/vf-core/blob/develop/PUBLISHING.md) as closely as possible so there's little to no 'human interaction' involved when we merge to `develop` (or `master`).

This might also involved use looking at 'release notes generators' as posted in #15.

**Comment by khawkins98** [comment]
Moving to the backlog.

**Comment by khawkins98** [comment]
See also #274
