### ISSUE TITLE
CHORE - Add Slack to the README

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#604]
Now that we are publicising (internally) that there is a slack group for `vf-core` and, I guess, fundamentally the EMBL Design System as an entire eco-system. 

We should add the link to a signup page or similar for the Slack Group

**Comment by khawkins98** [comment]
Some of this is in https://github.com/visual-framework/vf-core/pull/601/files 

But we might do more to promote it.

**Comment by sturobson** [comment]
Gah! I didn't see #601 when I quickly added this.

I think we can delete this issue and I'll look to merge that PR in now.

**Comment by khawkins98** [comment]
:)
