### ISSUE TITLE
CHORE - update any existing SVG icons with newer streamline icons

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#605]
Now that EMBL has purchased the licence to use the [streamline icons](http://streamlineicons.com) we should look to move any existing SVGs to what is available in this massive set.

This is in lieu of any systemising of the icons so they're either 'their own thing' or part of `vf`core`.

I think they should be a separate package - as that could be something used elsewhere

**Comment by khawkins98** [comment]
Should we put this one on the hold/backlog list?

**Comment by sturobson** [comment]
backlog sounds good! Looking at the News pages Szymon has been doing we might get some icons in the next tranche of work

**Comment by khawkins98** [comment]
Moved to backlog.
