### ISSUE TITLE
REFACTOR / QUESTION -- component and content typography

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#607]
Currently the Sass `mixin` for typography sets an appropriate `margin-bottom` defined in `vf-design-tokens`.

If we take a look at something like the `vf-summary` component we are often removing this margin or setting component and variant specific bottom margins.

Should we look to have a difference in how the typography that is used with na component is defined compared to a block of `vf-content`.

This could probably also look at `line-height` too.

This would a large-fish refactor of the Sass mixin and addition to the component CSS for adding any required margin.

TL;DR

for content `@include vf-content-typography(body--1);` which would spit out the relevant `font-size`, `line-height`, and `margin-bottom` for the element.

for components `@include vf-content-typography` which would only spit out the `font-size` leaving us to determine the `margin-bottom` and `line-heigh` for the component.

We _could_ let `line-height` be set, as it's probably a good default -- but we could be looking at adding padding to make it 'work' because of the line-height.

Perhaps for some components we could use a `line-height` crop tool / Sass mixin - like https://codyhouse.co/blog/post/line-height-crop

**Comment by khawkins98** [comment]
Any chance of getting to this one, or should we backlog?

**Comment by sturobson** [comment]
This has been started in #865

**Comment by khawkins98** [comment]
Still worth keeping open? 

If yes, should we link to https://github.com/visual-framework/vf-core/milestone/25 ?

**Comment by khawkins98** [comment]
My 6-month check on this, worth keeping open?

**Comment by sturobson** [comment]
I think it's still worthwhile to look at this -- but not in the current time frame, and adding `$custom-margin-bottom: 0` as needed "works".
