### ISSUE TITLE
vf-fractal:build Gulp task error

### ISSUE THREAD

**Issue by dbushell** [visual-framework/vf-core#613]
The `vf-fractal:build` gulp task assumes Fractal config exists:
https://github.com/visual-framework/vf-core/blob/develop/tools/gulp-tasks/vf-fractal.js#L14

In cases like `vf-wp` where Fractal isn't used it errors:

```
UnhandledPromiseRejectionWarning: Error: Cannot find module '[...]/vf-wp/fractal.js'
```

Solution: do a file exists on `fractalConfig` path and resolve the task early? I suppose `vf-wp` could also avoid using `vf-build` and add its own grouped task.

**Comment by khawkins98** [comment]
Yeah, this should be fairly easy to sort, will have a look.

**Comment by khawkins98** [comment]
As noted in #614, I think that will half fix this issue. 

I think what we now need to do is:

> - Option B: We support client projects using `vf-build`, but we need to add some parameter so that the correct Fractal build mode is invoked (or not at all, when it's not needed)

I think to do that it would probably mean adding another config option in the client (in this case `vf-wp`) `package.json` file:

```js
  "vfConfig": {
    "vfName": "VF WordPress",
    "vfNamespace": "vfwp-",
    ...
    "vfFractalMode": "normal|dataObject|none"
  },
```

Where:

- **default** `normal`: standard full build of all static html for components, `gulp.task('vf-fractal:build', `
- `dataObject`: just render the objects to memory for further use, `gulp.task('vf-fractal:dataobject',`
- `none`: don't invoke fractal at all

**Comment by sturobson** [comment]
@khawkins98 can this be closed now?

**Comment by khawkins98** [comment]
Think so.
