### ISSUE TITLE
ebi-vf1-integration component additions

### ISSUE THREAD

**Issue by dbushell** [visual-framework/vf-core#615]
In the `vf-wp` WordPress theme I'm seeing CSS specificity issues with `ebi-global.css` overriding the friendlier `vf-core` styles.

Logging those as I notice them in this issue below.

**Comment by dbushell** [comment]
### Blockquotes

```css
// ebi-global
blockquote, blockquote p {
  color: #8a8a8a;
}
```
`.vf-blockquote` is getting re-colored.

**Comment by dbushell** [comment]
### Selects
`.vf-form__select` is getting various conflicts with a raw `select` style - primarily a defined `height` is the biggest visual effect. Visible in `vf-wp` `/blog/` sidebar widgets.

**Comment by khawkins98** [comment]
I made a quick codepen to see how some of these conflict with ebi-global and Bootstrap 3, 4, and raw Foundation: https://codepen.io/khawkins98/pen/eYYWJNO

In short, it's mostly Foundation (and therefore also EBI 1.x) that makes issues.

I think that means that over time some fixes are going to be:

- only for `ebi-vf1-integration`
- some will be wider fixes that we could either:  
    - better "insulate" VF components from inheritance issues
    - make per-framework fix files (this way lies madness?)

**Comment by dbushell** [comment]
`.vf-form__textarea` border on focus get changes, unlike text inputs.

**Comment by dbushell** [comment]
### Dividers

`.vf-divider` is affected by:

```css
hr {
  clear: both;
  max-width: 80rem;
}
```

**Comment by sturobson** [comment]
![Screenshot 2019-10-30 at 14 36 09](https://user-images.githubusercontent.com/925197/67875411-34896e00-fb2e-11e9-8c81-5ac99eefface.png)

`vf1.x` has a `:visited` state that makes links override `vf2.x`

**Comment by khawkins98** [comment]
This still active? Or can we close an tackle new things as they come?

**Comment by khawkins98** [comment]
Going to close this one until someone shouts 

![closing](https://media.tenor.co/images/018d84b27578ff0b8368578ebcddec69/tenor.gif)
