### ISSUE TITLE
PATTERN - vf-banner

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#62]
A slot is a full-width component that:

- can either be at the top or bottom of a page. 
- can be permanent or removable.
- can include text, a link, an inline link (a link within text), and buttons.
- content is centred within the grid system.
- text is left aligned with buttons right aligned.

## Standard questions

- In a few words, what does this pattern look like?
    A coloured bar with text, link, buttons at the top or bottom of the page.

- In a few words, what does this pattern do?
    It relays information regarding the page and/or website. This message can either be permanent or dismissible. 

- Can other websites use this pattern? Or is it only useful in your organisation or website? 
    Yes

- Do you have any designs or concepts?
    We already have this in place as the data protection banner

- Have you done any user testing already? 
    no

- How often do you expect to make use of this pattern?
    This will be used for the data protection banner (as it is now) but also for permanent messages - like 'this page is an alpha'

- Can you list out major elements in this pattern?
    text,
    link,
    button

- Will all elements of this pattern be used every time?
    the buttons would only be used if it's a dismissible component.

- Does this pattern contain other patterns?
    vf-data-protection-banner,

**Comment by sturobson** [comment]
The data protection banner contains some [specific code](https://github.com/visual-framework/vf-core/blob/develop/components/blocks/vf-data-protection-banner/vf-data-protection-banner.hbs#L1) required for it's usage across sites.

This would need to be a variant.

**Comment by sturobson** [comment]
On some research to see what 'others do' and also thinking about what these types of patterns I am thinking that 'vf-banner' would be better.

This gives us the option to have variants:

- `vf-banner--fixed` or `vf-banner--inline`
- `vf-banner--top` or `vf-banner--bottom` to position the `vf-banner-fixed` pattern
- `vf-banner--gdpr` for the data protection banner as it needs extra HTML
- `vf-banner--phase` to for alpha/beta notifications
- `vf-banner--dark` or `vf--banner--light` to determine the two colour variants (as primary/secondary could be confusing) … we could, of course, leave this to the `--phase` or `--gdpr` variant.

**Comment by khawkins98** [comment]
There are some things/features/ideas in here that we should revisit after alpha.2, where we'll have the first iterations on an improved `vf-banner`.

**Comment by khawkins98** [comment]
Think this [is also sorted](https://github.com/visual-framework/vf-core/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+banner), we still need to add some options/colours, but I think we can address those as they arise?

Being bold and closing, but please reopen if you think we should.
