### ISSUE TITLE
BUG - vf-button :hover/:focus interaction bug

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#626]
![button](https://user-images.githubusercontent.com/925197/67851729-f32f9900-fb02-11e9-8eba-7c718f102257.gif)

I'm not sure how this regression has crept in. Spotted in Safari on Catalina.

**Comment by khawkins98** [comment]
Also weird in Safari in 10.14.

It looks like adding:

```css
.vf-button {
  transform: translate(0,0);
}
```

sorts it.

Probably some sort of issue around using the gpu for resizing and a stutter+antialias thing, will whip up a quick PR.

**Comment by sturobson** [comment]
hmm, it's commented out in the source file. It doesn't fix it in Catalina for me :-/

**Comment by khawkins98** [comment]
I think this might be a Safari issue as it jitters on small movements of box shadows: https://codepen.io/khawkins98/pen/ZEEaBME

**Comment by khawkins98** [comment]
I think we've done the best we can for now? (pending an upstream safari fix)

Being bold and closing, reopen if it's worth keeping open.
