### ISSUE TITLE
BUG - Design tokens are freaking Renovate Bot out

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#636]
There's probably a setting we can pass to Reonvate to stop:

> https://github.com/visual-framework/vf-core/pull/634#issuecomment-548831768

> lerna notice cli v3.18.3
> lerna info versioning independent
> lerna info Bootstrapping 74 packages
> lerna info Installing external dependencies
> lerna ERR! npm install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879 exited 1 in '@visual-framework/vf-design-tokens'
> lerna ERR! npm install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879 stderr:
> npm ERR! code EUNSUPPORTEDPROTOCOL
> npm ERR! Unsupported URL Type "network:": network:31879
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /tmp/renovate-cache/others/npm/_logs/2019-11-01T15_39_01_296Z-debug.log
> 
> lerna ERR! npm install --ignore-scripts --ignore-engines --ignore-platform --mutex network:31879 exited 1 in '@visual-framework/vf-design-tokens'
>

**Comment by sturobson** [comment]
I'm guessing because `vf-design-tokens` has it's own little `npm`–y and `gulp`–y stuff going on?

**Comment by khawkins98** [comment]
That should be fine. I think there's a dependency the package uses that
Renovate doesn't play nice with

**Comment by sturobson** [comment]
this should be fixed with the recent merge of #644 - let's keep this issue alive until we see that it's fixed?

**Comment by khawkins98** [comment]
This seems to have been resolved by adding `  "npmClient": "yarn",` to `lerna.json` https://github.com/visual-framework/vf-core/commit/5ac5e41d1dbadab708e7f1aac0adee22f707610d
