### ISSUE TITLE
ENHANCEMENT - vf-figure--float

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#637]
We need something like a `vf-figure--float`  that can be used for your classic bit of image+caption to:

1. [x] have it float right or left within a block of text
2. [x] Default width should be image width (now works with ` vf-u-float__right` and  ` vf-u-float__left`)
3. [ ] Some way to control sizing 1/3, 1/4, 1/5, etc
4. [ ] stack inline (centred?) on smaller screens

Useful things:

- [existing vf-figure component](https://visual-framework.github.io/vf-core/components/detail/vf-figure.html)
- [bare bones codepen of a situation where we'd like to use it](https://codepen.io/khawkins98/pen/WNNzoEO?editors=1100)

**Comment by khawkins98** [comment]
And we could probably do with some utility `vf-u-float--right` classes for ad hoc stuff.

**Comment by sturobson** [comment]
ideally these would need to be hooked into WordPress' defaults somehow - as I think they're not working when set in the WYSIYG.

Also - does it need to be tied to `figure` or do we need some abstracted utility classes for this - so that they can be used be a.n.other platform as needed?

**Comment by sturobson** [comment]
I'm happy to grab this one and expand on it with 'other' utility classes we could do with.

I have some other thoughts on utility classes which would be best to go into the documentation somewhere too.

**Comment by khawkins98** [comment]
All good thoughts ... i kinda tried to go with the most narrow/actionable approach by focusing on vf-figure (as that's the squeaky wheel at the moment) but, yeah, agree. 

If you're up for taking this one, go for it. I won't have much time this week anyways.

**Comment by khawkins98** [comment]
We've probably done enough here for the current needs.
