### ISSUE TITLE
BUG - fractal 'hidden: true' no longer adhered to

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#65]
Fractal allows you to pick and choose if you want to hide folders and things that have a `.config.yml` file by having a `hidden: true/false` in the frontend matter of the .yml

Since changing templates - this is no longer working.

**Comment by sturobson** [comment]
I was thinking something to do with `{% if variants.filter('isHidden', false) %}` in the preview.nunj would work - but after a quick five minutes it's something else / loose related I guess

**Comment by khawkins98** [comment]
Sorted by #113 /closing
