### ISSUE TITLE
.vf-sr-only displays content

### ISSUE THREAD

**Issue by esanzgar** [visual-framework/vf-core#665]
Example:
https://visual-framework.github.io/vf-core/components/detail/vf-pagination.html

The 'page' here is displayed:
<span class="vf-sr-only"> page</span>

**Comment by sturobson** [comment]
Hey, 

can you elaborate more? I've done a quick run through using Voiceover and I've spotted other issues that we need to address. Unless they're the same? 

For this example - https://visual-framework.github.io/vf-core/components/preview/vf-pagination.html - we are getting "page" + number being announced (which could do with some improvement)

**Comment by khawkins98** [comment]
This is sorted by https://github.com/visual-framework/vf-core/pull/663

I've just merged and it should be reflected shortly.

Related: `.vf-sr-only` will work but has now been deprecated and replaced with `.vf-u-sr-only`

**Comment by sturobson** [comment]
Ah, thanks @khawkins98 - my bad in misunderstanding the issue from the example. 

We still need to look at how the screenreader is reading things out here. As I'm not convinced the current way 'make sense':

"-10 Page" could be better as "go back 10 pages"

I'll raise another issue to discuss this

**Comment by esanzgar** [comment]
Thanks.

**Comment by esanzgar** [comment]
I believe `vf-u-sr-only` should work either if html class is `vf-js` or `vf-no-js`.

I don't see a compelling reason for `vf-u-sr-only` to only work in association with `vf-js`.
