### ISSUE TITLE
DOCUMENTATION - Global/local layout and theme classes

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#673]
PR #671 added concepts around a global layout and theme as parent CSS classes. 

I'm not sure where that would best live, perhaps as both:

- Narrative docs in: https://github.com/visual-framework/vf-welcome/blob/master/src/site/developing/guidelines/css.njk
- Boilerplate quick start code in: https://github.com/visual-framework/vf-core/blob/develop/tools/component-generator/templates/_component.scss

**Comment by khawkins98** [comment]
Can be closed?

**Comment by sturobson** [comment]
Getting ahead of the game and closing this.

Since moving away from the ‘mortal kombat’ levels of fanciness to a more maintainable and defined set of components there isn’t really (currently) any ‘global’ / ‘local’ theming options to make use of.

**Comment by khawkins98** [comment]
Nice. 

I won't think too much about all the thought on the global themes that has turned out to be redundant 😭 

But it really was a bridge too far given all the fundamentals that then (and still do) need to be done.
