### ISSUE TITLE
REFACTOR - grids

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#69]
@markboulton has reworked the grid system (specifically the `embl-grid`) so that it has:

- a small initial column
- larger grid-gaps
- the first grid-gap is larger than others
- a smaller sidebar column
- adds (potentially) another `embl-grid--variant` that has the initial column and three equally sized columns.

I've worked on a [quick demo in codepen](https://s.codepen.io/sturobson/debug/2073aeb15ca16be145a0860faaecf744).

Some questions, thoughts around this:

As found with the initial Cancer landing page I believe the `embl-grid` also needs to denote the columns with their own naming convention. We have discussed this in #13 

Because the grid could also be used for long form article content - the `vf-container__heading' doesn't make sense as a name because the column contains meta information regarding the article (author, date, categories, etc).

I think we're also potentially 'limiting' the `vf-container__sidebar` with the term too - especially as on smaller devices there is not 'sidebar'.

I propose the column naming convention inside the embl-grid should therefore be:

- `vf-container__prime`
- `vf-container__main`
- `vf-container__extra`

Other things to consider:

We will need to amend the vf-grid and vf-page-grid to use the same generic grid gutter spacing.

**Comment by khawkins98** [comment]
Was thinking about the naming aspect a little... it's always going to be hard for the framework to anticipate exactly the type of content -- but maybe that's just life.

So otherwise two thoughts:
- "prime" vs "main" might be confusing, maybe "capital" or "keystone"?
- alternatively, could just give up and do `__first` `__second` `__nth`

**Comment by sturobson** [comment]
primary, secondary, tertiary? 

I guess we're not naming 'the content' but the container position

**Comment by khawkins98** [comment]
Seems fine to me

(Sent from my mobile.)

**Comment by sturobson** [comment]
closing this - I'll update documentation for the grids and their usage this afternoon.

In short:

- Use `embl-grid` on your container. 
- Make your container decide how the content should be laid out.
- If your content is to be 'centred' use `embl-grid--has-centered-content`.

This means we do not have to make people mark up the content in their containers with something like `vf-container__primary` etc.
