### ISSUE TITLE
normalise the use of --page-grid-gap inside embl-grid

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#695]
As in #694

We have changed a value of `left: -18px;` to `left: calc(var(--page-grid-gap) / -2);` 

This should really be a design token (in Sass) and we should use one that's existing and close (rather than create a specific 18px token for this use case.

**Comment by khawkins98** [comment]
Do you mean [`--page-grid-gap`](https://github.com/visual-framework/vf-core/blob/develop/components/vf-sass-config/variables/vf-global-custom-properties.scss) should be a design token? Or to create a new design token for the "column gutter" on embl-grid?

**Comment by sturobson** [comment]
We should use a `vf-spacing--` Sass variable and normalise the value (currently 16px) to either:

`vf-spacing--md` - 16px or `vf-spacing--lg` - 20px

This would need a quick design review. As I think `--page-grid-gap` is used for some container spacing (don't hold me to that
