### ISSUE TITLE
STRATEGIC - Don't use master

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#698]
In #335 we revived the `master` branch, but following a recent component release (#697), I'm thinking we don't need a `master` branch; as:

1. It adds extra housekeeping tasks (and opportunities for mistakes/a more convoluted automation scenario) to both `vf-core` and component releases
1. For us "master" (stable) is when and how we push to npm, we don't encourage or support "installing" from git for production use

If there's agreement:

- [x] Replace `master` with a stub branch that only has a readme.md
- [x] Document this at https://visual-framework.github.io/vf-welcome/developing/guidelines/versioning/ (which needs an update anyways)
- [x] Update PUBLISHING.md

**Comment by sturobson** [comment]
How do we go about teams that are/would/could make use of 'just' using the link to the compiled `develop` branch of the CSS. I guess, realistically - no-one should be using that

**Comment by khawkins98** [comment]
I think that's it, no one should be using the `develop` branch (or any of the direct git repo) in production code, everything should come through npm.

**Comment by khawkins98** [comment]
Have also had the thought: we keep `master` but it is only a README.md that explains why we don't use a `master` branch and `npm` is canonical.

**Comment by khawkins98** [comment]
Working off that last comment:

1. I've updated the checklist in the original issue
2. I've prepared some draft text for a `README.md` to use in a stub `master` branch (it reuses some text from our existing readme)

```markdown

# Where's `master`?

This project does not use a `master` branch, why? 

- Development takes place on `develop`
- Stable release of `vf-core` and components is pushed to npm. [Here's a usage guide](https://visual-framework.github.io/vf-welcome/building)
    - n.b. Stable code is also available in [tagged releases](https://github.com/visual-framework/vf-core/releases) but we _do not_ recommend using those in production

## You likely won't need to download or clone this repo

Most won't need to clone this repo. Do so if you only wish to [develop the architecture](https://visual-framework.github.io/vf-welcome/developing/) of the Visual Framework core or contribute a global component, otherwise [use one of the boilerplates or install a component directly from npm](https://visual-framework.github.io/vf-welcome/building/). 
```

**Comment by khawkins98** [comment]
This one should be wrapped now.
