### ISSUE TITLE
STRATEGIC - Register a domain

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#699]
As discussed on Slack:

> Friday, 22 Nov

> Stu Robson 12:21
> Dropping this here
> visual-framework.com is available 
> visual-framework.design is available
> visual-framework.dev is available
> 
> Ken Hawkins 12:43
> .dev is alluring, but maybe .com is just the simplest?
> Stu Robson 12:44
> Yeah. I originally looked at .design because “design systems” but then thought of .dev … and then it was well why not just .com
> Although I’ve put the order differently here

So with that in mind, we should register the domain and do it before any leadership changes. — It will also help with education efforts.

**Comment by khawkins98** [comment]
Adding a note.

On Slack we've agreed to use `visual-framework.com` and I've pinged our EBI colleagues for help registering the domain and setting up the server.

**Comment by khawkins98** [comment]
`visual-framework.dev` has now been registered for 2 years with EBI Purchasing team.

**Comment by khawkins98** [comment]
Here's the wishlist I'll ask Web Dev to configure (as discussed in Slack):

Existing deployments of the following a "remapped" to the gitlab deployment:

- `visual-framework.github.io/vf-welcome`  to the root of `visual-framework.dev`
- `visual-framework.github.io/vf-core`  to `visual-framework.dev/vf-core`
- `visual-framework.github.io/vf-eleventy`  to `visual-framework.dev/vf-eleventy`
- and: have 301 redirects from `/eleventy/*` to `/vf-eleventy/*` (and for `vf-core/*`)

And we'll skip a `dev.visual-framework.dev` as the added complexity of configuration and maintenance is likely not justified — also as it's weird looking 🙃

**Comment by sturobson** [comment]
`latest.visual-framework.dev`?

**Comment by khawkins98** [comment]
The main part of this ticket is done, have made a new ticket #720 (Deploy documentation sites to visual-framework.com)
