### ISSUE TITLE
FEATURE - Create Github Issue and Pull Request templates.

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#7]
To make it a little easier and consistent we should look at adopting some templates for issues and pull requests. 

- [here's the GitHub blogpost about them](https://blog.github.com/2016-02-17-issue-and-pull-request-templates/)
- [here's a repo with some examples](https://github.com/stevemao/github-issue-templates)

**Comment by khawkins98** [comment]
I think we have the basics in place here -- should we close and revisit as/when we have more specific needs?
