### ISSUE TITLE
CHORE - Deploy documentation sites to visual-framework.dev

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#720]
We now have the `visual-framework.dev` domain registered (#699) but we need to make use of it; here's the wishlist I've ask Web Dev to configure (as discussed in Slack):

Existing deployments of the following a "remapped" to the gitlab deployment:

- [x] `visual-framework.github.io/vf-core`  to the root of `stable.visual-framework.dev`
- [x] last tagged release goes to the live URL (`stable.visual-framework.dev`)
- [x] head (`develop` branch) goes to `latest.visual-framework.dev`
- [x] https://visual-framework.dev and https://www.visual-framework.dev redirect to stable.visual-framework.dev

### Possibly in the future
- [ ] `visual-framework.github.io/vf-eleventy`  to `visual-framework.dev/vf-eleventy`

**Comment by khawkins98** [comment]
@sandykadam Have assigned this one to you -- could you work on it as you have time? And do let us know where we can assist.

**Comment by sandykadam** [comment]
Hi @khawkins98 
I stumbled upon this ticket and I remembered we had some discussion but went completely off radar. 
Who owns this domain now EBI or EMBL IT? based on the discussions we had I think we will have to register `latest` and `stable` subdomain with SSL certs on all of them.

**Comment by khawkins98** [comment]
Hey Sandeep, also tardy in this. 

The domain is registered with EBI -- we should have an option for subdomains, I'll forward a couple of emails from around 8 Jan.

**Comment by sandykadam** [comment]
Deployment done and domains are in place now.
https://latest.visual-framework.dev/

https://stable.visual-framework.dev/

**Comment by khawkins98** [comment]
This one is now done.
