### ISSUE TITLE
proposal -  make `vf-links--summary` linkable

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#727]

**Comment by khawkins98** [comment]
Footnote: there was some related thinking about summary images at #759 (The one where we refactor the summary component)

**Comment by khawkins98** [comment]
Resurrecting this one which is a follow up to the EMBL.org homepage launch: 

![image](https://user-images.githubusercontent.com/928100/81543073-e4f5eb80-9375-11ea-9371-0495dddd31d0.png)

https://stable.visual-framework.dev/components/vf-summary/#vf-summary--news-has-image

**Comment by sturobson** [comment]
similar to #910 … which I'm working on/

**Comment by sturobson** [comment]
looking at this, along with a similar change to `vf-card`.

notes and further questions
- there will be a need for a breaking change
- would there ever be a link in the text that might link somewhere else that needs to work
- are we only wanting the image and text to be an url, rather than 'the whole thing'
- are dates linkable to see search results of other things with that date?

**Comment by khawkins98** [comment]
> - would there ever be a link in the text that might link somewhere else that needs to work

Quite possibly.

> - are we only wanting the image and text to be an url, rather than 'the whole thing'

Yeah, I think that's best/most expected/leaves open other links inside the teaser text.

> - are dates linkable to see search results of other things with that date?

As long as we're refactoring, would be good to consider this ... this could also be an area for an author byline or category.

**Comment by sturobson** [comment]
These changes along with the changes to #910 would create breaking changes for both.

Do you want them in before or after the vf2.0.1 release?

**Comment by khawkins98** [comment]
I suppose this is now redundant with the wider vf-summary refactor?
