### ISSUE TITLE
proposal vf-footer background or vf-banner for gdpr banner

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#728]
for the new landing page of embl.org - they use the same grey and are a little visually confusing because of this

**Comment by khawkins98** [comment]
Would be good if we can pick this "easy win" back up as it would help us close https://gitlab.ebi.ac.uk/emblorg/backlog/issues/284

Screencap of the current issue:

![image](https://user-images.githubusercontent.com/928100/78705411-b6679980-790d-11ea-8047-7f8a1f696266.png)

**Comment by sturobson** [comment]
Yes! As the footer is going to be the grey - I wonder if the GDPR banner could be a lighter shade. To really separate it.
