### ISSUE TITLE
Enhancement: insert svg icons via JS

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#751]
For `vf-section-header--link` why not use an actual SVG file via CSS? 

Would make updates easier if/when the graphic changes.

https://github.com/visual-framework/vf-core/blob/cc8ac4a153af2f492515e7dd0ccdc6f523455853/components/vf-section-header/vf-section-header.njk#L15

**Comment by sturobson** [comment]
So, there's the HTTP request for one icon (or even the small set of icons we currently use if made into a sprite) that kinda swayed the decision here. 

There's also the few requirements, like it needs to be easily controlled via CSS.

I'd expect, more often than not, that the nunjucks/WP template should be used (as a best practice), rather than copying and pasting. Which means inlining is fine.

**Comment by khawkins98** [comment]
Keep in mind that 11ty/WP will largely be used only for the corporate portion EMBL.org/EBI.ac.uk sites. Service teams will be using _other_ solutions, so it will make changes to the icons hard to manage/enforce without inspecting source code.

**Comment by khawkins98** [comment]
What sort of CSS control do you mean? Positioning effects/transitions?

**Comment by khawkins98** [comment]
Thinking ~aloud~ typing: depending on the needs of that CSS control, we could make the inline an option when using the NJK template. So if you use the template you get the inline, if not you get the HTML fetch.

**Comment by khawkins98** [comment]
Picking up on https://github.com/visual-framework/vf-core/pull/785#discussion_r387543577

> The 'on this page' list needs an SVG icon -- We need to work out if inline is the best approach, or if we should be creating a sprite. We'd need to be able to style the SVG w/ CSS (at least)

Another option would be to use JS, where we need SVGs we could:

1. Add `data-vf-add-this-icon-here`
2. Component `vf-icons-whatevername` picks up on that data attribute
3. Injects the SVG inline

This would:

1. keep the HTML clean
2. not result in extra HTTP requests (the SVG inline code could be in the minified JS)
3. still allow CSS cascade styling
4. no faffing about with sprites

I think it would be a fair use of JS, as if/when it fails you don't get icons, which shouldn't be critical to your content. (right?)

**Comment by khawkins98** [comment]
We don't have the capacity to action this, it is being moved to the backlog #446
