### ISSUE TITLE
DOCUMENTATION - Breakpoints missing from design token docs

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#756]
The [vf-breakpoints.yml](https://github.com/visual-framework/vf-core/blob/develop/components/vf-design-tokens/src/variables/vf-breakpoints.yml) design tokens aren't in the component docs.

https://visual-framework.github.io/vf-core/components/detail/vf-design-tokens--spacing.html

Use case: need a way to see what the breakpoints are without consulting the source.

**Comment by sturobson** [comment]
Yep, I think this was one of those "can you stop that and do this instead" scenarios that left these languishing with no form of documentation.
