### ISSUE TITLE
BUG - vf-masthead colour options are partly broken

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#758]
With the changes to the vf-wp-group themes the options to change the masthead colours was, i suppose, deprecated (#672).

However we still have some code around using the colour keying and it's still possible to partly colourise the `vf-masthead--default`: https://codepen.io/khawkins98/pen/abOOZdq?editors=1100

In the above, the coloured background still works but text colour does not. 

Confusingly the docs still say this is supported: https://visual-framework.github.io/vf-core/components/detail/vf-masthead--default.html

I think there will still be a need to colourise the backgrounds, however the requirements to do so aren't clear at the moment.

So I think we have three options:

1. Remove all the legacy documentation and code around colourising the masthead
2. Reimplement the colour options as best we can 
3. Make some sort of vf-masthead--colourised variant

My inclination would be to do Option 1 and add a footnote in the README.md that we plan to implement a colourised masthead, and point back to this issue.

---

(This may have been discussed before, but [I didn't find any issues](https://github.com/visual-framework/vf-core/issues?utf8=%E2%9C%93&q=is%3Aissue+vf-masthead+))

**Comment by sturobson** [comment]
If there is a need to "need to colourise the backgrounds". It should probably move towards how we are theming both globally and locally.

(a fast and loose, rough example)
```
// Browsers that don't support custom properties get a black and white experience. 
.vf-masthead {
  background-color: #000;
  background-color: var(--local-theme-bg-color, var(--global-theme-bg-color, #000));
  color: #FFF;
  color: var(--local-theme-fg-color, var(--global-theme-ft-color, #FFF));
}

// to be a class added to the component, this overrides the fallback and the global theme rule
.vf-masthead-theme--primary {
  --local-theme-bg-color: green;
  --local-theme-fg-color: white;
}

// to be put on a parent somewhere (body or html would be ideal)
// this overrides the fallback and can be override by a localised theming class
.vf-theme--primary {
  --global-theme-bg-color: orange;
  --global-theme-fg-color: black;
}
```

**Comment by khawkins98** [comment]
Cool, in that case I'd say we should remove the old code remnants and clean up the docs.
