### ISSUE TITLE
DOCUMENTATION - Make the changelog easier to find/review

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#761]
Now that we're a bit better about our changelogs, we should make sure the changes are easy to review. 

You can install and view the CHANGELOG.md, but that's not very seamless, and npm doesn't offer a way to get to the changelog online: https://www.npmjs.com/package/@visual-framework/vf-footer

I think the best we can do is to update the homepage url in the components' package.json to point to the folder: 
    - ⛔️`homepage` https://visual-framework.github.io/vf-core/
    - ✅ https://visual-framework.github.io/vf-core/components/detail/vf-footer.html (where the changelog is shown)

We might also add something to the component generator to add  a link:

- `[View the changelog](https://github.com/visual-framework/vf-core/blob/develop/components/vf-footer/CHANGELOG.md)`

**Comment by sturobson** [comment]
We can close this - as I think the current implementation of changelogs matches or improves what is suggested.
