### ISSUE TITLE
DOCUMENTATION - vf-body, vf-grid, and embl-grid

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#779]
We need to thrash out the documentation of the grid layouts to avoid incorrect and accidental misuse. 

This issue is a 'loose start'.

`vf-core` comes with several grid layouts but they only work when used in certain ways.

`vf-body` should only be used once, and on the `<body>` element. 

`vf-grid` needs to be a direct child of `vf-body` for it to 'fit' in the page giving it left and right padding automatically at smaller viewports

`embl-grid` is similar to `vf-grid` in that it needs to be a direct child of `vf-body` to work correctly.

To make use of `vf-grid` and `embl-grid` several components rely on being direct children of the grid to work.

**Comment by khawkins98** [comment]
We can't assume or enforce `body.vf-body` as:

- The VF will be used in many "solutions" and not all of them use the `body` element the same. React, for example, doesn't like to work directly off `body`
- Not all sites will use the VF "everywhere". Some may only use it for the header/footer and a sidebar widget

It's come up before, I think mainly on slack.

In some of those cases we could assume that there would be only one `element.vf-body`, but there will be cases that need multiple `vf-body`s, either as a strategic decision or quite possibly technical issues. 

--- 

On `vf-grid` padding, it doesn't seem to be working for smaller viewports even as a direct child: https://visual-framework.github.io/vf-core/components/preview/vf-grid.html 

Looking at that, this might be a bug/oversight: seems small screens override the default use of `main`:

```css
.vf-grid {
    display: grid;
    grid-column: main;
    grid-column-gap: var(--page-grid-gap);
}
```

And over setting with:

```css
media (max-width: 1299px)
.vf-grid {
    grid-column: 1/-1;
}
```

I'm not sure what the original intent was of that media query and why smaller screens didn't use `main`. Might be the small-screen css wasn't updated when `main-start / main-end` was removed: https://github.com/visual-framework/vf-core/commit/126071dfa82e617c8281e2b1db7c21dd265b32ef
