### ISSUE TITLE
vf-wp-news: vf-inlay grid issue at 1024px

### ISSUE THREAD

**Issue by kasprzyk-sz** [visual-framework/vf-core#782]
As on attached screenshot.

![Screenshot 2020-02-26 at 14 37 43](https://user-images.githubusercontent.com/54020899/75452329-67276400-5972-11ea-92a4-91cba0439da1.png)

Solution by @khawkins98:

`.vf-inlay__content--additional {
  grid-column: 2 / -2; }
  @media (min-width: 600px) {
    .vf-inlay__content--additional {
      grid-template-columns: repeat(2, 1fr);
      display: grid;
      grid-column-gap: var(--page-grid-gap); } }
  @media (min-width: 1024px) {
    .vf-inlay__content--additional {
      display: block;
      grid-column: 3 / 4; } }`

**Comment by sturobson** [comment]
Some thoughts…

I think this is more an issue of trying to bend vf-grid to do something it wasn’t initially designed to do

Is this a layout purely for the news page or has this got designs for several other pages. 

As with the sidebar that’s used in the training pages — there’s nothing wrong in having components/layouts that are of the design system but not part of the component library code base. 

Looking at the image each grid item (column) is a different size. What grid are you setting on the parent? Is it just `vf-grid`?

**Comment by sturobson** [comment]
So, we don't need to use `vf-inlay` for this grid at all - we have the primitives available with `vf-grid` … and it could give better spacing/sizing consistency too. 

I'll try and raise a PR in `vf-wp` that will change this.

**Comment by sturobson** [comment]
![Screenshot 2020-04-29 at 16 22 33](https://user-images.githubusercontent.com/925197/80613839-ab4be900-8a35-11ea-9a8f-cbc9d02b9a7c.png)


- less mark up
- less `vf-wp` context specific requirements in CSS
- same amount of utility classes (🤦)

**Comment by khawkins98** [comment]
Nice. As discussed in Slack: would be good (on first thinking) if we could phase out vf-inlay

**Comment by sturobson** [comment]
We can close this as `vf-inlay` is now deprecated entirely.
