### ISSUE TITLE
Design tokens: Grey is lighter than grey light?

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#788]
`ui-color--grey` is lighter than `ui-color--grey--light` This seems off and I'm guessing unintended?

https://github.com/visual-framework/vf-core/blob/6759c69b88706eb55bed405dd5799f57fa60fef3/components/vf-design-tokens/src/core.palette.alias.yml#L64-L65

**Comment by sturobson** [comment]
Ah, for UI colours - yes - this is more than likely an unintended error.
