### ISSUE TITLE
UI colours missing from Design token documentation

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#789]
Spotted when looking in #788, the vf-ui-* colours are missing from the docs at https://visual-framework.github.io/vf-core/components/detail/vf-design-tokens--colours.html

**Comment by sturobson** [comment]
I've been wanting to take a look a the docs for design tokens and utility classes for some time.

We're missing border radius (and links potentially) for the design tokens, and we should probably look to start adding more things now - like animation and elevation (z-index) too.

I've always thought it would be nice to some how hide the 'code example' and other parts of the document page for things like tokens too - but not sure how we would easily go about that (I guess something added to the frontMatter)
