### ISSUE TITLE
Bug/enhancement: Be more portable with NJK templates

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#804]
When using the Nunjucks templates, different environments handle `context` differently.

So far we've seen difference between Eleventy and WP's Gutenberg (React):

https://github.com/visual-framework/vf-core/blob/2ab60bb0e5abbf7c2b8e1d1c52ac9128864bce60/components/vf-box/vf-box.njk#L3-L6

This causes issues in WP as there's no easy way to set `context` or pass `field: { box: field_name }` 

An improvement could be to "flatten" the context object in the above code:

```njk
 {# if we're being passed "context" from a parent template, use it as "box" #} 
 {%- if context %} 
   {% set box_title = context.box_title %} 
   {% set box_body = context.box_body %} 
   ...
 {% endif %} 
```

In theory this would then suit Eleventy and Gutenberg.

**Comment by sturobson** [comment]
```
 {# if we're being passed "context" from a parent template, use it as "box" #} 
 {%- if context %} 
   {% set box_title = context.box_title %} 
   {% set box_body = context.box_body %} 
   ...
 {% endif %} 
```

Might be a good stop-gap to get into `vf-core` now and update?

**Comment by khawkins98** [comment]
I can't see much of a downside to it.

**Comment by sturobson** [comment]
I'll switch gears and get this into `vf-box` and any other components I started adding this too.
