### ISSUE TITLE
bug: embl-content-hub-loader results in errors in some conditions

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#809]
If components like vf-tabs and embl-notifications aren't present, `embl-content-hub-loader` results in JS errors:

![image](https://user-images.githubusercontent.com/928100/77226011-00fabf00-6b75-11ea-85bb-a005d6b51683.png)

The `typeof` isn't cutting it:

https://github.com/visual-framework/vf-core/blob/ddbc2c97026c4e38b8cc7f373690c4167241950e/components/embl-content-hub-loader/embl-content-hub-loader__fetch.js#L65-L73

**Comment by khawkins98** [comment]
Perhaps this is as it needs `()`s:

https://github.com/visual-framework/vf-core/blob/ddbc2c97026c4e38b8cc7f373690c4167241950e/components/embl-content-hub-loader/embl-content-hub-loader__fetch.js#L174-L176

**Comment by sturobson** [comment]
@khawkins98 How is this issue now?
