### ISSUE TITLE
INVESTIGATE: Sass Versioning

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#810]
We are already versioning components using Lerna but this might be a good addition for revealing potential bugs from version mistmatches, or missing packages and exposing them in the cli which would/could mitigate potential issues being raised.

With Lerna, it should be a case that this is not needed as the components should make sure they’re pulling in any other required packages as a matter of course.

**Comment by sturobson** [comment]
A handy link would help to the Sass framework for versioning 

https://github.com/dominikwilkowski/sass-versioning

**Comment by khawkins98** [comment]
This is a good idea, but not one we'll get to soon. moving to the backlog.
