### ISSUE TITLE
Enhancement: add alignment options for vf-figure

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#813]
We need the ability to left/right float figures in text. 

Something like `vf-figure__left`

Would also need:

- Some spacing around the image. ([perhaps similar to WP](https://codex.wordpress.org/CSS#WordPress_Generated_Classes))
- Probably responsive compatibility (no need to float beneath a certain size)

For the moment we can skate past with utility classes but that won't be very consistent or perhaps responsive: https://github.com/visual-framework/vf-wp/pull/197

Like so:

![image](https://user-images.githubusercontent.com/928100/77318643-b2345d00-6d0d-11ea-8da3-fecf4bf3ba4d.png)

FYI: @kasprzyk-sz

**Comment by sturobson** [comment]
I recall discussing this with @dbushell - I cannot see an issue raised for it though. I think the idea was to replicate what floating options WP gives but with classnames (as outlined in the above opening comment).

**Comment by khawkins98** [comment]
Yeah, i thought there was an issue too, but couldn't find it

**Comment by sturobson** [comment]
We can close this as it's PR'd in #890
