### ISSUE TITLE
Component: auto anchor links + table of contents

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#818]
[As discussed on Slack]

Building off the [`vf-links-list` "On this page" navigation](https://visual-framework.github.io/vf-core/components/detail/vf-link-list--easy.html#is-active) we'd like to:

- automatically generate anchor links
- put those into a table of content

Won't look like anything, mostly JS. Perhaps it could live inside the vf-links-list component.

There is some code we can use:

- generate anchor links: https://remysharp.com/2014/08/08/automatic-permalinks-for-blog-posts
- generate table of contents: https://www.ebi.ac.uk/style-lab/websites/patterns/lists-table-of-contents.html

The rub might be when we don't want a particular heading to show, or we want to show different text. We could probably address that through data attributes, or classes, in the case of WordPress:
- `data-vf-link-list-auto-dont-show`
- `data-vf-link-list-auto-title="Manual title"`
- `class="vf-link-lista--auto-dont-show"`

Would be useful in content like: https://www.embl.org/news/lab-matters/corona-updates/ (which has some formatting issues in general)

**Comment by sturobson** [comment]
This would also 

- rely on good content structure, which can be aided by guidelines/documentation.
- do absolutely nothing if the JavaScript doesn't load.

**Comment by sturobson** [comment]
We should also seek guidance from content editors as to where this is best placed which, again would rely on content structure. Of course, this could potentially be a `vf-wp` block that's added into the page content? So the authors can decide where it should go.

**Comment by khawkins98** [comment]
This could integrate with the vf-link-list's [easy](https://stable.visual-framework.dev/components/vf-link-list/#vf-link-list--easy) and [very-easy](https://stable.visual-framework.dev/components/vf-link-list/#vf-link-list--very-easy) variants.

**Comment by khawkins98** [comment]
We don't have the capacity to action this, it is being moved to the backlog #446
