### ISSUE TITLE
ENHANCEMENT - vf-table

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#852]
The below is not exhaustive and is taken from #830 so that we can at least ship some basic `vf-table` structure and styles.

- [ ]  documentation
- [ ]  what to do with numerical data styling
- [x]  sort fixed header styles
- [x]  vf-table__footer element
- [ ]  better example data in the .yml file.

**Comment by sturobson** [comment]
@gabsie I did a quick prototype in code of what some of the interactive things could look like… here's a screenshot

![Screenshot 2020-04-15 at 15 31 53](https://user-images.githubusercontent.com/925197/79349727-81230300-7f2e-11ea-8ec0-7261a05fc7a6.png)

**Comment by gabsie** [comment]
@sturobson and @khawkins98  - can we have the design for checked boxes be a bit more familiar? ()
I don't know how established the filled checkboxes are already... :) but I think Ken also suggested once the more common check (similar to gov uk ones etc)
:) Sorry!

And Stu - the selections should drive some additional bulk action... which I have been wondering where to place..

Gabs

**Comment by sturobson** [comment]
The first iteration of this is now in `vf-core` as it's own usable table as well as a paired down version that can be used in `vf-content` that doesn't require additional HTML classes to be added.
