### ISSUE TITLE
CHORE: Bullet wrapping should be "outside" on Links List: Very Easy

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#854]
Noticed on https://wwwdev.embl.org/partnerships/ the [Links List: Very Easy](https://visual-framework.github.io/vf-core/components/detail/vf-link-list--very-easy.html) bullets wrap under:

![image](https://user-images.githubusercontent.com/928100/79225735-777d9a80-7e5d-11ea-8669-d31311a6a9c2.png)

Would be better as:

![image](https://user-images.githubusercontent.com/928100/79226305-6f722a80-7e5e-11ea-9e4f-2e2fd49ebb62.png)

Achieved in the above as:

```
.vf-links__list--s .vf-list__item {
  list-style-position: outside;
  margin-left: 14px;
}
```

**Comment by sturobson** [comment]
good catch!
