### ISSUE TITLE
COMPONENT - blogpost 'tags'

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#875]
The article pages on www.embl.org/news have a section for relevant article tags to help people springboard to different related content. As this is quite a standard component I think it is ripe for creating in `vf-core`. 

This could be a riff off of `vf-links-list` as it's essentially a list of links. 

The current markup is also a little `<div>` heavy so this will help clear that up, and as it's part of `vf-content` it gets the `:visited` state which isn't necessarily the best for what is more a 'ui component'.

**Comment by khawkins98** [comment]
@cindyebi we recently discussed with Stu about if we should use vf-badge for tags.

Here's an example of use of tags: https://www.embl.org/news/science/artificial-intelligence-makes-great-microscopes-better-than-ever/

![image](https://user-images.githubusercontent.com/928100/120309994-2dac7980-c2d6-11eb-9156-78e3fe888322.png)

My only worry might be that vf-badge would be too visually loud — thoughts?
