### ISSUE TITLE
investigate inline text elements and their styling

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#877]
Discussed in Slack. 

There are several inline text elements that we have not looked at to see if they need any additional styling over what they inherit from the element they're inside of and what the browser defaults give us for free.

I do not think we need to give each inline text element it's own component class, `vf-sup` for example. 

We could probably get away with using the class attribute selectors to target many if not all `vf-` components and apply the same styling (if required) for each inline text element.

Here is [MDN's list of inline text elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element#Inline_text_semantics) which we should reference.

**Comment by sturobson** [comment]
Some of the inline text elements are used because they are dictated from the content style guide.

Perhaps we need a 'typography' documentation page to explain why this/that/the other inline text element is doing something or not _as well as_ having the content style guide as part of a larger 'design systems' documentation site.

**Comment by khawkins98** [comment]
Closing this one. We've already made some progress here, and we'll hopefully make more as we become more consistent with integrating the design tokens and design guidance.
