### ISSUE TITLE
COMPONENT - A Search Results Page

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#878]
With the launch of the [Covid 19 Portal](https://www.covid19dataportal.org) and with the [jobs page](https://www.embl.org/jobs/) live too - we should think to standardise the search results pages so they have, at least, they're name spacing. 

The Covid 19 Portal results have some fun things that could be addressed and standardised to meet the system.

**Comment by khawkins98** [comment]
Picking back up on this today.

There's a placeholder at https://latest.visual-framework.dev/patterns/search-results/

We may find ourselves needing two (or perhaps more) variants of a search page, but let's see how far we get with one.

Some use cases to incorporate: 

### embl.org/jobs
![image](https://user-images.githubusercontent.com/928100/98657019-b0251a00-2341-11eb-886a-4fd14b9ee14e.png)

### [COVID19DataPortal](https://www.covid19dataportal.org/sequences?db=embl-covid19)

![image](https://user-images.githubusercontent.com/928100/98657059-bdda9f80-2341-11eb-9f34-44f87adb6766.png)

### [EBI Training](https://wwwdev.ebi.ac.uk/training-beta/search-results?query=dna&domain=ebiweb_training_events&page=1&facets=)

![image](https://user-images.githubusercontent.com/928100/98657157-d6e35080-2341-11eb-9116-85bbccf8b229.png)

### www.embl.org/search

![image](https://user-images.githubusercontent.com/928100/98657242-eebad480-2341-11eb-8015-ffb33b804f0e.png)

### www.embl.org/documents

![image](https://user-images.githubusercontent.com/928100/98657949-bff12e00-2342-11eb-8ab3-a7ed5bd2409f.png)


There are probably more examples already, but this is plenty to chew on.

**Comment by khawkins98** [comment]
A very much work in progress for tomorrow's clinic 

![image](https://user-images.githubusercontent.com/928100/98689185-f7280500-236b-11eb-9f8c-3ec242413244.png)

**Comment by khawkins98** [comment]
Copying some comments from slack in as while I think they've been previously raised, they're not captured here.

![image](https://user-images.githubusercontent.com/928100/101161811-b0a78c80-3631-11eb-9624-6d435a79a6e5.png)


> yeah, would be nice to either push/pull the filters to show at the bottom (and add a “view filters”) or use the vf-details/vf-show-more to hide some by default
> but that’s part of the wider search discussion
> 
> yeah a vf-facet pattern or something. I don’t think it really fits the details/summary semantics ¯\_(ツ)_/¯
> 
> similarly I think we’ve also hijacked the left column in the embl-grid in a way that’s not correct

**Comment by sturobson** [comment]
regarding facets -- I've mentioned this - but documenting it here.

I worked with UCL on their search system in 2014/5 and the result is still live. This was based off of exterior UX for the rough design and user journeys. Essentially on smaller viewports the facets become hidden by default:

https://search2.ucl.ac.uk/s/search.html?query=science&collection=website-meta&profile=_directory&tab=directory

![Screen Shot 2020-12-08 at 10 33 18](https://user-images.githubusercontent.com/925197/101472717-d938ca80-3940-11eb-9a0b-79d8d588bdd7.png)
![Screen Shot 2020-12-08 at 10 33 14](https://user-images.githubusercontent.com/925197/101472719-da69f780-3940-11eb-96bc-829070bd9c68.png)
![Screen Shot 2020-12-08 at 10 33 11](https://user-images.githubusercontent.com/925197/101472720-db028e00-3940-11eb-891b-c8e0f68c3a2f.png)
![Screen Shot 2020-12-08 at 10 32 59](https://user-images.githubusercontent.com/925197/101472722-db028e00-3940-11eb-981d-82919844dd56.png)

**Comment by khawkins98** [comment]
We don't have the capacity to action this, it is being moved to the backlog #446
