### ISSUE TITLE
ENHANCEMENT - Add vf-table support to vf-content

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#887]
This came up last week, capturing it here too. 

- [ ] We need a table default when using `.vf-content table`, probably the striped look a that's best for "general-purpose text"
- [ ] That look should be overridable; example: "I have a table inside vf-content I want to be compact" `.vf-content .vf-table.vf-table--compact`

Random notes/thoughts:

-  I think the above pretty consistent with the `.vf-content table:not([class*='vf-'])` approach ... but, you know, tables are always hiding surprises
- This need will probably come up during the WP group site sprint
- Should the code `.vf-content table` code live in `vf-content` or `vf-table`? For bigger components where is it more sustainable to support vf-content? That might belong in a bigger issue.

**Comment by sturobson** [comment]
> I think the above pretty consistent with the .vf-content table:not([class*='vf-']) approach ... but, you know, tables are always hiding surprises

We should be able to get around some of the design things that classes bring to tables by using good ol' specificity in HTML elements `tr > th { /* make the heading in a row bolder */ }` 

I think there could be a need for a `vf-table` block for some things though -- perhaps a little bit of research into existing articles with tables to see what's going on would help

**Comment by sturobson** [comment]
> We need a table default when using .vf-content table, probably the striped look a that's best for "general-purpose text"

I think it should be the striped variant at least - as it could be an easier reading experience
