### ISSUE TITLE
vf-navigation improvements

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#895]
the new 'levels of fanciness' for navigation mean that several levels do not have `:hover` or `:focus` states. We should introduce these, probably with `text-decoration: underline`.

We could then include the `is-active` class state too that was reference in #526

**Comment by khawkins98** [comment]
This will revisit if we do `.vf-navigation__link.is-active` or `.vf-navigation__link.vf-navigation__link__is-active` (like `vf-form__is-active`)
 
The purist in me still wants the later, but it's a bit mad. 

Either way, I don't think we have a documented policy on these standard modifiers and why they get exempted from the "everything must be prefixed".

**Comment by khawkins98** [comment]
Resurrecting this one as the group sites progress, this is becoming a bit more needed: https://wwwdev.embl.org/groups/gross/

**Comment by sturobson** [comment]
aside: do we need a `'home` link - or should that be the group name? 

I guess 'visually' it would be a nice to have - but it would be clearer to have the `home` link

I think I've both 'opened' and 'closed' the initial question now. Moving on. :sob:

**Comment by khawkins98** [comment]
Yeah, we've gone around on using `Home` or `Name of Group`. I think the better choice varies by the relative humidity.
