### ISSUE TITLE
'foreround' is misspelled

### ISSUE THREAD

**Issue by esanzgar** [visual-framework/vf-core#911]
It should probably be 'foreground' 😉 

https://github.com/visual-framework/vf-core/blob/b58bf4f9afadc75247e292168846420593b06ebb/components/vf-masthead/vf-masthead.scss#L16-L103

**Comment by sturobson** [comment]
Thanks @esanzgar! 

At least it was a find–and–replace so the custom property is consistent inside the `vf-masthead`.

I'll fix this up now.
