### ISSUE TITLE
remove horizontal padding on vf-breadcrumbs

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#918]
As we are moving away from using CSS grid for centering of content in a viewport that is wide enough there's a little bit of padding left and right that needs removing

**Comment by khawkins98** [comment]
+1 for this

**Comment by sturobson** [comment]
I noticed a couple more instances where it just looks awkward now with the latest decisions made after the last design exploration.

**Comment by sturobson** [comment]
this is linked to #933

**Comment by sturobson** [comment]
This has been fixed in #937. Closing.
