### ISSUE TITLE
vf-hero enhancements 

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#919]
there's a branch that updates `vf-hero` to include the parallax version that's available on embl.org … this needs to be checked and a PR raised to merge it into `develop`

**Comment by khawkins98** [comment]
I think that's an artefact from #715. 

As it's not something we want people to be using outside of the EMBL.org landing pages, it's best to not put it in the npm version of vf-hero.

**Comment by sturobson** [comment]
> As it's not something we want people to be using outside of the EMBL.org landing pages, it's best to not put it in the npm version of vf-hero.

I'm thinking it does need to be a part of the nam package but with clear use/don't use documentation.

My worry is, if the component changes, without having `--extreme` version available to test at a component library, it could quite easily blow up on a site - which would lead to questions and investigations that could just be saved with a simple **"This is EMBL landing pages only"**

We could include it in the npm package but hide it from the component library site?

**Comment by sturobson** [comment]
We've pulled in `--extreme` into `vf-core` now so we can close this.
