### ISSUE TITLE
vf-navigation isn't responsive

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#922]
The [vf-navigation--main](https://visual-framework.github.io/vf-core/components/detail/vf-navigation--main.html) (and similar) don't respond to the viewport size, causing screen smaller than the nav width to horizontal scroll.

![image](https://user-images.githubusercontent.com/928100/82026729-707fbd00-9693-11ea-946a-b7f8dd4522a9.png)

Visible on:

- https://visual-framework.github.io/vf-core/components/detail/vf-navigation--main.html
- https://wwwdev.embl.org/groups/communications/

This is partly solvable by:

```css
.vf-navigation--main .vf-navigation__list {
    flex-wrap: wrap;
}
```

But then the component needs some space massaging.

![image](https://user-images.githubusercontent.com/928100/82026683-6362ce00-9693-11ea-8b4d-834f6b3440e8.png)

It's the start of a wider thread about how to handle nav on mobile, but if the navigation can "gracefully" stack we can defer a conversation on burgers and tacos. 

Priority set to high as we're getting close to launching some of these sites with the vf-wp--group-site theme.

**Comment by sturobson** [comment]
We never got around to formalising what would happen on mobile (small viewports) with navigation - I recall it being discussed - I think the move to the new design exploration layouts removed some of the original CSS I had in place to 'make up' for the lack of design in older versions.

I'll dig it out and see what we can do.


(that's a lot of navigation)

**Comment by sturobson** [comment]
I think that this would be a better experience? 

https://iamsteve.me/blog/entry/horizontal-scrolling-responsive-menu

rather than - taking up all that whitespace with a blocked list or throwing it behind a 'hamburger' menu.

**Comment by khawkins98** [comment]
+1 for trying the horiz scrolling for the site nav; good for a few reasons in my view:

- as you point out: doesn't eat up all of the screen
- simplifies questions around spacing when stacked
- encourages content owners to minimise number of links as the "extra" go off-screen

It might raise questions/concerns, but I feel like it's a more sustainable path. I've also seen some other implementations that "hint" that you can side scroll -- but we can look into those if/when we need to, especially as that would need JS.

**Comment by sturobson** [comment]
> It might raise questions/concerns

One concern I have for things like this is  – "do you need that much top level navigation?"

**Comment by khawkins98** [comment]
They don't need it, but it has to be there. :/

**Comment by sturobson** [comment]
for example - is home not better placed as making "EMBL Communications" linkable to the 'home'?

on mobile it might be confusing too - is that home to the top level or home to the embl comms level

**Comment by khawkins98** [comment]
> is home not better placed as making "EMBL Communications" linkable to the 'home'?

Yeah, good point. I can't recall why Mark advocated for "home" there. Perhaps the nav structure has changed in the interim.

**Comment by sturobson** [comment]
I think this one can be closed?

**Comment by khawkins98** [comment]
Should we prioritise a "priority" nav like https://gijsroge.github.io/priority-nav.js/

Also similar to what we did for EBI, and the community was happy with it http://www.ebi.ac.uk/style-lab/websites/patterns/menu-local-nav.html

Or have we done enough for now and make a new backlog issue?

**Comment by sturobson** [comment]
I think we can close this one and make a new backlog issue as suggested

**Comment by sturobson** [comment]
I'm closing this as we now use `vf-cluster` to help with the layout of `--main` which this issue was mainly about.

@khawkins98 feel free to re-open - or start a fresh issue if there's some loose threads here that warrant further discussion.

**Comment by khawkins98** [comment]
We might want to re-open this one. In any case, copying a conversation with @sturobson  from Slack so it isn't lost. 

> currently things like navigation flow (using the vf-cluster):

<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/928100/99141907-14045700-2650-11eb-9f6e-63a121721da0.png"><img src="https://user-images.githubusercontent.com/928100/99141907-14045700-2650-11eb-9f6e-63a121721da0.png" alt="Screen Shot 2020-11-13 at 14 53 38" style="height: 400px;"></a>

> but what about something like this, so this only happens if the viewport is narrower than the content:

<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/928100/99141944-6ba2c280-2650-11eb-9d8c-ccfdb34413b2.gif"><img src="https://user-images.githubusercontent.com/928100/99141944-6ba2c280-2650-11eb-9d8c-ccfdb34413b2.gif" alt="reel" style="height: 400px;"></a>
I sometimes think we could do similar for our news summaries and cards, in certain contexts. But that's a wide discussion

<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/928100/99141953-85440a00-2650-11eb-94d0-3428c6c6229a.gif"><img src="https://user-images.githubusercontent.com/928100/99141953-85440a00-2650-11eb-94d0-3428c6c6229a.gif" alt="side scroll content" style="height: 400px;"></a>


> With one overarching ‘simple’ layout component (like we’ve done with stack and cluster) we should be able to ‘just’ drop it in as needed.
>
> Although - for the navigation — I don’t think we want to show the ‘scrolling’ on larger screens where we have stupidly long navigation so perhaps we’d also need to introduce ‘breakpoint overrides’
> `<div class="vf-component | vf-reel vf-cluster--md">…</div>`

>
