### ISSUE TITLE
vf-summary--profile avatar image size difference irl

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#926]
note how Mathias' avatar is larger than the default icon

https://wwwdev.embl.org/press/

**Comment by khawkins98** [comment]
Might also be a chance to sneak in a fix to the long emails breaking layout.

https://wwwdev.embl.org/groups/dummy-embl-group/members/

![image](https://user-images.githubusercontent.com/928100/82053015-eea48980-96bc-11ea-9a09-ba47421b72f7.png)

We previously discussed `word-break: break-word;` being the best of mediocre solutions.

**Comment by khawkins98** [comment]
Bumping this as it will likely be the only blocker to the new Press page live; https://wwwdev.embl.org/press/

![image](https://user-images.githubusercontent.com/928100/83996889-751b5680-a95d-11ea-9c6c-fb7252e38ad0.png)

**Comment by khawkins98** [comment]
Ah, that's the same link in the original issue summary. Also good for testing https://wwwdev.embl.org/groups/dummy-embl-group/members/

(particularly at ~1000px)

![image](https://user-images.githubusercontent.com/928100/83997111-efe47180-a95d-11ea-9143-b23e81258e65.png)
