### ISSUE TITLE
COMPONENT - `embl-topic-listing`

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#936]
This will use the contentHub, EMBL.org profiles, `embl-breadcrumbs-lookup` and `vf-link-list--easy` to provide topic-based navigation rendered client-side. 

This is mainly to support navigation around EMBL.org

What we want to do:

- Give a topic by name or UUID: 
  - `Structural and Computational Biology` || `83a1abe4-a2a1-4527-9165-85cf5812c664`

What we get:

- A list of links for navigation: Beck, Bork, Duss groups, etc.

Notes:

- this should be abstracted into two parts:
  1. loading a list of terms to be shown
  2. render it as a pattern
    - it would be good if we could use the [`.precompiled.js` njk templates](https://mozilla.github.io/nunjucks/api.html#precompiling), but the additional JS may not be worth it
- should we just do this on the contentHub server side. It will be a slower process but will free JS dependencies
- the taxonomy loading may need to be extracted from `embl-breadcrumbs-lookup` (`embl-ontology-loader`?)
- we'll want to support this as a Gutenberg block (a vf-wp container, likely)

Future features:
- do we only support `vf-link-list--easy`? should we also be able to show them as cards?
- support `and` / `or` terms 
  - give me all things that are `Structural and Computational Biology` and in `Heidelberg`
  - give me all things that are `Structural and Computational Biology` or `Developmental Biology` and `Heidelberg`
- should we support sorting, if so how?
  - alphabetical (default)
  - weighting? would need a new setting in EMBL.org Profiles
  - custom?
- limit?
- filter out a result?
- add a custom addition?

**Comment by khawkins98** [comment]
The [contentHub HTML API](https://docs.google.com/spreadsheets/d/1ThNJn7TSQ1nlmjRONhyHU4orXx2cC97XGejoOphP5QI/edit#gid=0) can support a similar method already by:

- UUID: https://content.embl.org/api/v1/pattern.html?pattern=node-display-title&filter-content-type=profiles&filter-field-value[field_embl_org_term_what.entity.uuid]=f2024f52-ae49-453d-8ef9-abbce2aa79d4
- Text: https://content.embl.org/api/v1/pattern.html?pattern=node-display-title&filter-content-type=profiles&filter-field-value[field_embl_org_term_what.entity.title]=Developmental%20Biology

It also supports `and`/`or` *within* a field:
- `,` = or: https://content.embl.org/api/v1/pattern.html?pattern=node-display-title&filter-content-type=profiles&filter-field-value[field_embl_org_term_what.entity.title]=Communications,Developmental%20Biology
- `*` = and: https://content.embl.org/api/v1/pattern.html?pattern=node-display-title&filter-content-type=profiles&filter-field-value[field_embl_org_term_what.entity.title]=Communications*Developmental%20Biology

We can also `AND` for multiple fields:
- `Developmental Biology` AND `EMBL Heidelberg` https://content.embl.org/api/v1/pattern.html?pattern=node-display-title&filter-content-type=profiles&filter-field-value%5Bfield_embl_org_term_what.entity.title%5D=Developmental%20Biology&filter-field-value%5Bfield_embl_org_term_where.entity.title%5D=EMBL%20Heidelberg

To use this:

1. Need to add the `vf-link-list--easy` pattern as a Twig template
2. Consider how we can lookup parent terms (I want to query by "research" which is a parent of `Developmental Biology`

**Comment by khawkins98** [comment]
This came up today on Slack in a conversation with @filipe-dias. 

The contentHub can already do the types of queries needed, the biggest request would be to add vf-summary or vf-list pattern support to the profile contentType. Maybe something to flag for the next sprint as we’ll need a lot of help from Maged.

Ultimately we'll still want this ticket in the VF issue queue as there would be follow on work for embl-breadcrumbs and embl-ContentHub-Loader, however there's a big pillar of work in the contentHub.

**Comment by sturobson** [comment]
With things like `vf-box`, `vf-stack`, `vf-card`, `vf-cluster` etc. 

I'd like to try and push further away from the 'content specific' naming of components If at all possible.

**Comment by khawkins98** [comment]
Yeah, I think in this case there won't be be an embl-topic-listing component, rather it might be a function as part of embl-conenthub-loader (`function emblTopicListing () {}`) and that would read the breadcrumbs to construct the contentHub query.

**Comment by khawkins98** [comment]
We don't have the capacity to action this, it is being moved to the backlog #446
