### ISSUE TITLE
BUG - vf-footer green border needs a z-index

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#950]
![image](https://user-images.githubusercontent.com/928100/83629566-9f09fd00-a59a-11ea-8431-a72c5f623e38.png)

The green strip now shows at the top of the stack and over the data protection banner. Visible on wwwdev.embl.org

Believe this is as `.vf-footer` is now `position: relative;`

Adding a `z-index:1` stops it, but not sure if some other value or approach is better.

**Comment by sturobson** [comment]
I think as the GDPR banner is the one that should always win - it needs the `z-index` so it is always on top
