### ISSUE TITLE
COMPONENT - image gallery

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#953]
Before developing a new image gallery component (or set of components, potentially). 

We should:

- explore what is already in use across EMBL products.
- investigate what works / does not work for site users.
- work on some prototypes based off the above.

Here is an example of something from recent design explorations.

![Screenshot 2020-06-04 at 09 24 26](https://user-images.githubusercontent.com/925197/83733464-7985fd80-a645-11ea-89d3-096256833f11.png)

Does this work? Does this fit every need?

**Comment by sturobson** [comment]
via @filipe-dias on https://wwwdev.embl.org/sites/heidelberg/accommodation/guest-houses/suedstadt/

![Screenshot 2020-06-04 at 16 01 46](https://user-images.githubusercontent.com/925197/83773684-c20cdd80-a67c-11ea-9e9c-b97d0ac52361.png)

**Comment by khawkins98** [comment]
Copying in Stu's comment from #976:

> After a quick Slack discussion with @spivass81 there could be a need for the `vf-figure` component to take more than one image.
> 
> We should investigate this. See how it works with the various alignment `--modifiers` available and adjust CSS accordingly. We would also need to adjust the `.njk` template to allow for multiple images too.
> 
> Looking at the specification and HTML5 Doctor we can still only use on `figcaption`: http://html5doctor.com/the-figure-figcaption-elements/

**Comment by khawkins98** [comment]
@sturobson think it's worthwhile to go the route of a `figcaption` with multiple images (which could be the simplest?) or something else? 


https://www.w3.org/TR/2011/WD-html5-author-20110809/the-figure-element.html

```html
<figure>
 <img src="castle1423.jpeg" title="Etching. Anonymous, ca. 1423."
      alt="The castle has one tower, and a tall wall around it.">
 <img src="castle1858.jpeg" title="Oil-based paint on canvas. Maria Towle, 1858."
      alt="The castle now has two towers and two walls.">
 <img src="castle1999.jpeg" title="Film photograph. Peter Jankle, 1999."
      alt="The castle lies in ruins, the original tower all that remains in one piece.">
 <figcaption>The castle through the ages: 1423, 1858, and 1999 respectively.</figcaption>
</figure>
```

**Comment by khawkins98** [comment]
We don't have the capacity to action this, it is being moved to the backlog #446
