### ISSUE TITLE
BUG - vf-author__name spacing is strange?

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#961]
Noticed this while reading a news post on my phone: https://www.embl.org/news/science/new-insights-into-epigenetic-modifications/

![image](https://user-images.githubusercontent.com/928100/84362852-2a544580-abce-11ea-9aaf-123a3b9790aa.png)

And disabling:

```css
.vf-article-meta-info__author .vf-author__name {
  word-spacing: 100vw;
}
```

Looks better:

![image](https://user-images.githubusercontent.com/928100/84362907-3f30d900-abce-11ea-8c45-8c9e16e10698.png)

Might be a bug or maybe I don't understand the intent. Looking at 
https://visual-framework.github.io/vf-core/components/detail/vf-article-meta-information.html I'm guessing perhaps this works well for cases of just a First + Surname, but less so for Latin-style names.

**Comment by sturobson** [comment]
Ah, the original use case for `word-spacing: 100vw` was because the design wanted the first name and surname on separate lines.

But, that's clearly not workable with 'actual content'.

👍 to remove it and let the content simply 'flow'.
