### ISSUE TITLE
QUESTION - should we let `vf-figure` take multiple images

### ISSUE THREAD

**Issue by sturobson** [visual-framework/vf-core#976]
After a quick Slack discussion with @spivass81 there could be a need for the `vf-figure` component to take more than one image. 

We should investigate this. See how it works with the various alignment `--modifiers` available and adjust CSS accordingly. We would also need to adjust the `.njk` template to allow for multiple images too. 

Looking at the specification and HTML5 Doctor we can still only use on `figcaption`: http://html5doctor.com/the-figure-figcaption-elements/

**Comment by khawkins98** [comment]
I think this is #953 by another name, or at least a variant of 953. 

Crossling and being bold: closing. 

Stu please reopen if you see fit.
