### ISSUE TITLE
BUG? vf-hero text line height

### ISSUE THREAD

**Issue by khawkins98** [visual-framework/vf-core#997]
The `vf-hero__text` line height seems to ha-ha-high:

https://visual-framework.github.io/vf-core/components/detail/vf-hero--normal.html

![image](https://user-images.githubusercontent.com/928100/85955574-bcef3580-b97f-11ea-84d8-05b15e220cab.png)

As seen on embl.org

Old: https://www.embl.org/research/
![image](https://user-images.githubusercontent.com/928100/85955586-d7c1aa00-b97f-11ea-8eec-2538721956c6.png)

New:  https://wwwdev.embl.org/research/
![image](https://user-images.githubusercontent.com/928100/85955582-cd9fab80-b97f-11ea-8de1-1c66ebdd836b.png)

**Comment by sturobson** [comment]
Yeah, I set it to `2` - https://github.com/visual-framework/vf-core/blob/develop/components/vf-hero/vf-hero.scss#L100 - From designs and reasoning behind I’d always thought that a hero would be short on text as you’ve got the rest of the page for text :-D and less text read better with more height (imho)

Let’s revert back to what comes with the mixin and try not to write War and Peace in the paragraph text :)
